## Deprecated SDK imports removed

This project no longer depends on `bigdata-client` or `bigdata-research-tools`. See **MIGRATION_NOTES.md** / **README.md** and [Thematic_Screener_CLI](../Thematic_Screener_CLI/) for the REST + `bigdata-smart-batching` + OpenAI pattern. Pass company CSVs (`RP_ENTITY_ID`, `COMPANY_NAME`) instead of watchlists.

  # US Tariffs: Risks & Strategies - Report Generator

  ## Automated Analysis of Trade Tariff Risks and Corporate Mitigation Strategies

  ## Why It Matters







  In an era of increasing trade tensions and evolving geopolitical landscapes, companies face unprecedented uncertainty around import tariffs and trade barriers. Understanding corporate exposure to tariff risks across global supply chains is critical for investment decisions, risk management, and strategic planning. Manual tracking of tariff impacts across multiple companies and markets is time-intensive and often incomplete.

  ## What It Does



  This workflow combines an OpenAI-generated risk taxonomy, Bigdata.com REST + `bigdata-smart-batching` search, and the `GenerateReport` class to systematically analyze corporate exposure to US import tariff risks. Designed for portfolio managers, risk analysts, and trade compliance professionals, it transforms scattered information from news, filings, and earnings calls into a detailed research report covering risk intelligence and mitigation strategies.

  ## How It Works



  The workflow integrates **hybrid semantic search**, **AI-powered risk taxonomies**, and **multi-source content analysis** to deliver:



  - **Automated Risk Taxonomy Creation**: Uses OpenAI to generate hierarchical risk categories specific to tariff impacts

  - **Cross-Source Intelligence Gathering**: Searches news articles, SEC filings, and earnings transcripts for relevant discussions

  - **AI-Powered Risk Classification**: Categorizes content into specific risk scenarios

  - **Corporate Response Extraction**: Identifies and summarizes company mitigation plans from official communications

  - **Customizable Report Generation**: Produces professional HTML reports ranked by Media Attention, Financial Impact, and Uncertainty

  ## A Real-World Use Case







 This cookbook demonstrates the complete end-to-end workflow through analyzing how US import tariffs impact major American companies. You'll see how the system transforms scattered tariff discussions across news, SEC filings, and earnings transcripts into structured risk assessments, complete with corporate response strategies and quantified exposure metrics for investment and risk management decisions.

  ## Setup and Imports

  ## Async Compatibility Setup



  **Run this cell first** - Required for Google Colab, Jupyter Notebooks, and VS Code with Jupyter extension:



  ### Why is this needed?



  Interactive environments (Colab, Jupyter) already have an asyncio event loop running. Several helpers in this notebook's `src/` package (labeling, summarization, response extraction) make async calls to OpenAI, and without `nest_asyncio` you'll get this error:



  ```

  RuntimeError: asyncio.run() cannot be called from a running event loop

  ```



  The `nest_asyncio.apply()` command patches this to allow nested event loops.



  💡 **Tip**: If you're unsure which environment you're in, just run the cell below - it won't hurt in any environment!

In [1]:
import datetime
start = datetime.datetime.now()

try:
    import asyncio
    asyncio.get_running_loop()
    import nest_asyncio; nest_asyncio.apply()
    print("✅ nest_asyncio applied")
except (RuntimeError, ImportError):
    print("✅ nest_asyncio not needed or not available")

✅ nest_asyncio applied

  ## Environment Setup







  The following cell configures the necessary path for the analysis

In [2]:
import os
import sys


current_dir = os.getcwd()
if current_dir not in sys.path:
    sys.path.append(current_dir)
print(f"✅ Local environment setup complete")

✅ Local environment setup complete

  ## Optional: Plotly Display Configuration







  For better visualization rendering, you can also set the Plotly renderer:

In [3]:
import plotly.io as pio

# Try to detect the environment and set appropriate renderer
try:
    # Check if we're in JupyterLab
    import os
    if 'JUPYTERHUB_SERVICE_PREFIX' in os.environ or 'JPY_SESSION_NAME' in os.environ:
        pio.renderers.default = 'jupyterlab'
        print("✅ Plotly configured for JupyterLab")
    else:
        # Default for VS Code, Jupyter Notebook, etc.
        pio.renderers.default = 'plotly_mimetype+notebook'
        print("✅ Plotly configured for Jupyter/VS Code")
except:
    # Fallback to a more universal renderer
    pio.renderers.default = 'notebook'
    print("✅ Plotly configured with fallback renderer")

✅ Plotly configured for Jupyter/VS Code

  ## Configure Output Directories







  Set up the directory structure where analysis results and reports will be saved.

In [4]:
# Define output file paths for our report
output_dir = "output"
os.makedirs(output_dir, exist_ok=True)

  ## Load Credentials

In [5]:
from dotenv import load_dotenv
from pathlib import Path

script_dir = Path(__file__).parent if '__file__' in globals() else Path.cwd()
load_dotenv(script_dir / '.env')

BIGDATA_API_KEY = os.getenv('BIGDATA_API_KEY')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

if not all([BIGDATA_API_KEY, OPENAI_API_KEY]):
    print("❌ Missing required environment variables")
    raise ValueError("Missing required environment variables. Check your .env file.")
else:
    print("✅ Credentials loaded from .env file")

✅ Credentials loaded from .env file

  ## Connecting to Bigdata







  Create a Bigdata object with your credentials.

In [6]:
# Bigdata.com access is now REST + bigdata-smart-batching, both authenticated
# directly with BIGDATA_API_KEY from the environment (loaded in the previous
# cell) -- there is no persistent SDK client object to construct anymore.
# See MIGRATION_PATTERNS.md / Thematic_Screener_CLI for the reference pattern.
os.environ.setdefault("BIGDATA_API_KEY", BIGDATA_API_KEY)
print("✅ Bigdata.com REST access ready (BIGDATA_API_KEY set)")

✅ Bigdata.com REST access ready (BIGDATA_API_KEY set)

  ## Import Required Libraries







  Import the core libraries needed for tariff risk analysis

In [7]:
from types import SimpleNamespace

from IPython.display import display, HTML
import pandas as pd

from src.bigdata_rest import load_universe, company_ids_from_universe
from src.mindmap.generate_trees import generate_themes_tree_dict, get_most_granular_elements
from src.mindmap.themes import print_tree
from src.search.content_retrieval import DataRetriever
from src.label.label_process import LabelProcessor
from src.report_generator import GenerateReport

print("✅ Core libraries imported (REST + bigdata-smart-batching + OpenAI pattern)")

✅ Core libraries imported (REST + bigdata-smart-batching + OpenAI pattern)

  ## Defining the Analysis Parameters



  - **Main Theme** (`main_theme`): The central risk scenario to analyze across companies

  - **Focus** (`focus`): Expert perspective for generating targeted risk taxonomies

  - **Company Universe** (`universe_df`): The set of companies to analyze, loaded from a CSV with `RP_ENTITY_ID` + `COMPANY_NAME` columns

  - **Model Selection** (`llm_model`): The AI model used for risk classification and summarization

  - **Time Period** (`start_date` and `end_date`): The date range for the analysis

  - **Frequency** (`freq`): The frequency of the date ranges to search over. Supported values:

     - `Y`: Yearly intervals.

     - `M`: Monthly intervals.

     - `W`: Weekly intervals.

     - `D`: Daily intervals. Defaults to `3M`.

  - **Document Limit** (`document_limit`): The maximum number of documents to return per query to Bigdata API.

  - **Batch Size** (`batch_size`): The number of entities to include in a single batched query.

  - **Rerank Threshold** (`rerank_threshold`): By setting this value, you’re enabling the cross-encoder which reranks the results and selects those whose relevance is above the percentile you specify (0.7 being the 70th percentile). More information on the re-ranker can be found [here](https://docs.bigdata.com/how-to-guides/rerank_search).

  - **Response From News** (`response_from_news`): Controls the `news_search_fallback` parameter. If `True`, when no response is found in transcripts/filings, the system uses News as fallback. In reports, fallback responses are annotated with `[From News]`. If `False`, missing responses show "No evidence of discussions found in Transcripts/Filings.". Default: `True`.

In [8]:
# ===== Customizable Parameters =====

from datetime import datetime, timedelta

# Company Universe: small slice (~5 companies) of the NASDAQ universe CSV
# bundled with Thematic_Screener_CLI (RP_ENTITY_ID + COMPANY_NAME), instead of
# a bigdata-client watchlist. Kept small to control API/LLM cost.
universe_path = "../Thematic_Screener_CLI/40_companies.csv"
universe_df = load_universe(universe_path).head(5).reset_index(drop=True)
company_ids = company_ids_from_universe(universe_df)
print(f"✅ Company universe loaded: {len(universe_df)} companies")
display(universe_df)

# Main Analysis Theme
main_theme = 'US Import Tariffs Corporate Risk Impact Analysis'
focus = "Provide a detailed taxonomy of risks describing how new American import tariffs will impact worldwide companies, their operations and strategy."

# LLM Model Configuration (plain OpenAI model id, passed straight to the OpenAI client)
llm_model = "gpt-4o-mini"

# Time Range Configuration -- kept to a ~30 day window to control API/LLM cost
end_date = datetime.now().strftime("%Y-%m-%d")
start_date = (datetime.now() - timedelta(days=30)).strftime("%Y-%m-%d")
freq = 'M'  # Monthly search frequency

# Enable/Disable Reranker
rerank_threshold = None

# Document Retrieval Limits (kept small to control OpenAI labeling/summary cost)
document_limit_news = 10
document_limit_filings = 5
batch_size = 1

# Toggle fallback to News for company responses
response_from_news = True

✅ Company universe loaded: 5 companies

  RP_ENTITY_ID     COMPANY_NAME
0       E09E2B     NVIDIA Corp.
1       D8442A       Apple Inc.
2       228D42  Microsoft Corp.
3       0157B1  Amazon.com Inc.
4       4A6F00    Alphabet Inc.

  ## Risk Analysis



  The first phase builds the risk taxonomy and retrieves/labels the News content that feeds the report generation phase (this replaces the deprecated `bigdata-research-tools` `RiskAnalyzer` class with local `src/` helpers built on REST + `bigdata-smart-batching` + OpenAI). This phase includes three critical steps that prepare the data for the report generation phase.

  ### Initialize Company Universe



  Sets up the company objects used for the risk discovery and taxonomy-driven search below:

  - **Automated Taxonomy Generation**: Creates a hierarchical structure of tariff-related risks

  - **Semantic Content Retrieval**: Searches news articles using the taxonomy's leaf summaries as queries

  - **Intelligent Content Labeling**: Categorizes found content into specific risk scenarios

In [9]:
# Build the company objects used for the News retrieval + labeling steps below.
# (GenerateReport builds these internally too, but we need the same objects
# here since retrieval/labeling for News happens before GenerateReport exists --
# this replaces RiskAnalyzer's internal entity resolution.)
id_to_name = dict(zip(universe_df["RP_ENTITY_ID"], universe_df["COMPANY_NAME"]))
list_entities = [SimpleNamespace(id=eid, name=name) for eid, name in id_to_name.items()]

print(f"✅ {len(list_entities)} companies ready for taxonomy-driven search: "
      f"{', '.join(e.name for e in list_entities)}")

✅ 5 companies ready for taxonomy-driven search: NVIDIA Corp., Apple Inc., Microsoft Corp., Amazon.com Inc., Alphabet Inc.

  ### Generate Risk Taxonomy







  Create a comprehensive taxonomy that breaks down tariff risks into specific, analyzable categories such as supply chain disruption, pricing impacts, and market access challenges.

In [10]:
# Generate a compact risk taxonomy for the theme/focus via OpenAI
# (replaces RiskAnalyzer.create_taxonomy())
themes_tree_dict = generate_themes_tree_dict(main_theme, focus)
risk_tree = themes_tree_dict[main_theme]
terminal_labels = get_most_granular_elements(risk_tree, 'Label')
risk_summaries = get_most_granular_elements(risk_tree, 'Summary')

print(f"✅ Taxonomy generated with {len(terminal_labels)} leaf risk categories")
print_tree(risk_tree)

2026-08-14 09:19:44,345 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

✅ Taxonomy generated with 6 leaf risk categories
US Import Tariffs Corporate Risk Impact Analysis
├── │   Operational Risks
│   ├── │   │   Supply Chain Disruptions
│   ├── │   │   Increased Costs
│   └── │       Compliance Challenges
└──     Strategic Risks
    ├──     │   Market Access Limitations
    ├──     │   Investment Decisions
    └──         Reputation Risks

  The taxonomy tree shows how tariff risks branch into specific sub-scenarios. Each terminal node represents a distinct risk category that will be used to classify and analyze news content.

  ### Retrieve Relevant Content







  Search news articles using the generated taxonomy to find discussions about tariff impacts across our company universe.

In [11]:
# Search news articles across the company universe using the taxonomy's leaf
# summaries as queries (replaces RiskAnalyzer.retrieve_results()).
data_retriever_news = DataRetriever(
    company_ids=company_ids,
    id_to_name=id_to_name,
    document_limit=document_limit_news,
    sortby="relevance",
    search_freq=freq,
    start_date_query=start_date,
    end_date_query=end_date,
)

df_sentences_semantic = data_retriever_news.retrieve(
    themes_tree_dict=themes_tree_dict,
    list_specific_themes=[main_theme],
    document_type="news",
)

if df_sentences_semantic is None:
    df_sentences_semantic = pd.DataFrame()

# Cost control: cap the number of chunks sent to OpenAI for labeling
df_sentences_semantic = df_sentences_semantic.head(document_limit_news)
print(f"✅ Retrieved {len(df_sentences_semantic)} news chunks (capped at {document_limit_news})")
df_sentences_semantic.head()

2026-08-14 09:19:44,373 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:19:44,373 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:19:44,374 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:19:44,375 - INFO - Loaded 1 companies from universe

2026-08-14 09:19:44,377 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:19:44,378 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 213 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:19:45,711 - INFO - Planning complete: 213 expected chunks in 1 baskets

2026-08-14 09:19:45,712 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:19:45,712 - INFO - Total maximum expected chunks: 4

2026-08-14 09:19:45,712 - INFO - Searching 1 baskets

2026-08-14 09:19:46,961 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 4 documents with 4 chunks

2026-08-14 09:19:46,962 - INFO - First pass complete: 4 documents with 4 chunks

2026-08-14 09:19:46,962 - INFO - Search complete: 4 documents with 4 chunks retrieved in 1.25s

2026-08-14 09:19:46,963 - INFO - Deduplicated: 4 unique documents from 4 total (chunks merged)

2026-08-14 09:19:46,963 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:19:46,963 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:19:46,964 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:19:46,964 - INFO - Loaded 1 companies from universe

2026-08-14 09:19:46,964 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:19:46,965 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 48 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:19:48,154 - INFO - Planning complete: 48 expected chunks in 1 baskets

2026-08-14 09:19:48,154 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:19:48,154 - INFO - Total maximum expected chunks: 0

2026-08-14 09:19:48,155 - INFO - Searching 1 baskets

2026-08-14 09:19:49,341 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:19:49,344 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:19:49,344 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.19s

2026-08-14 09:19:49,344 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:19:49,344 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:19:49,345 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:19:49,345 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:19:49,345 - INFO - Loaded 1 companies from universe

2026-08-14 09:19:49,346 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:19:49,346 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:19:50,331 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:19:50,332 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:19:50,332 - INFO - Total maximum expected chunks: 0

2026-08-14 09:19:50,332 - INFO - Searching 1 baskets

2026-08-14 09:19:51,449 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:19:51,450 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:19:51,451 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.12s

2026-08-14 09:19:51,451 - WARNING - Failed baskets: 1

2026-08-14 09:19:51,451 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:19:51,451 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:19:51,452 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:19:51,452 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:19:51,452 - INFO - Loaded 1 companies from universe

2026-08-14 09:19:51,452 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:19:51,452 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 14 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:19:52,761 - INFO - Planning complete: 14 expected chunks in 1 baskets

2026-08-14 09:19:52,762 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:19:52,762 - INFO - Total maximum expected chunks: 0

2026-08-14 09:19:52,763 - INFO - Searching 1 baskets

2026-08-14 09:19:54,000 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:19:54,000 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:19:54,001 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.24s

2026-08-14 09:19:54,001 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:19:54,001 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:19:54,001 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:19:54,002 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:19:54,002 - INFO - Loaded 1 companies from universe

2026-08-14 09:19:54,002 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:19:54,002 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 173 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:19:55,011 - INFO - Planning complete: 173 expected chunks in 1 baskets

2026-08-14 09:19:55,011 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:19:55,012 - INFO - Total maximum expected chunks: 3

2026-08-14 09:19:55,012 - INFO - Searching 1 baskets

2026-08-14 09:19:56,258 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 3 documents with 3 chunks

2026-08-14 09:19:56,260 - INFO - First pass complete: 3 documents with 3 chunks

2026-08-14 09:19:56,260 - INFO - Search complete: 3 documents with 3 chunks retrieved in 1.25s

2026-08-14 09:19:56,261 - INFO - Deduplicated: 3 unique documents from 3 total (chunks merged)

2026-08-14 09:19:56,261 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:19:56,261 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:19:56,262 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:19:56,262 - INFO - Loaded 1 companies from universe

2026-08-14 09:19:56,262 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:19:56,263 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 429 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:19:57,265 - INFO - Planning complete: 429 expected chunks in 1 baskets

2026-08-14 09:19:57,266 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:19:57,266 - INFO - Total maximum expected chunks: 8

2026-08-14 09:19:57,266 - INFO - Searching 1 baskets

2026-08-14 09:19:58,530 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 8 documents with 8 chunks

2026-08-14 09:19:58,531 - INFO - First pass complete: 8 documents with 8 chunks

2026-08-14 09:19:58,531 - INFO - Search complete: 8 documents with 8 chunks retrieved in 1.27s

2026-08-14 09:19:58,531 - INFO - Deduplicated: 8 unique documents from 8 total (chunks merged)

2026-08-14 09:19:58,534 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:19:58,534 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:19:58,535 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:19:58,535 - INFO - Loaded 1 companies from universe

2026-08-14 09:19:58,535 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:19:58,535 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 630 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:19:59,759 - INFO - Planning complete: 630 expected chunks in 1 baskets

2026-08-14 09:19:59,759 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:19:59,759 - INFO - Total maximum expected chunks: 12

2026-08-14 09:19:59,759 - INFO - Searching 1 baskets

2026-08-14 09:20:00,835 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 12 documents with 12 chunks

2026-08-14 09:20:00,836 - INFO - First pass complete: 12 documents with 12 chunks

2026-08-14 09:20:00,836 - INFO - Search complete: 12 documents with 12 chunks retrieved in 1.08s

2026-08-14 09:20:00,836 - INFO - Deduplicated: 12 unique documents from 12 total (chunks merged)

2026-08-14 09:20:00,836 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:20:00,837 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:00,837 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:00,837 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:00,837 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:00,837 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 31 data points, 2270 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2270 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 2 period(s) (split_3_volume), 2 basket(s)
2026-08-14 09:20:03,255 - INFO - Planning complete: 2,270 expected chunks in 2 baskets

2026-08-14 09:20:03,255 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:03,256 - INFO - Total maximum expected chunks: 45

2026-08-14 09:20:03,260 - INFO - Searching 2 baskets

2026-08-14 09:20:04,498 - INFO - Basket basket_1_high_20260815_20260815: Retrieved 0 documents with 0 chunks

2026-08-14 09:20:05,500 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 44 documents with 45 chunks

2026-08-14 09:20:05,501 - INFO - First pass complete: 44 documents with 45 chunks

2026-08-14 09:20:05,501 - INFO - Search complete: 44 documents with 45 chunks retrieved in 2.24s

2026-08-14 09:20:05,501 - WARNING - Failed baskets: 1

2026-08-14 09:20:05,502 - INFO - Deduplicated: 44 unique documents from 44 total (chunks merged)

2026-08-14 09:20:05,502 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:20:05,502 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:05,502 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:05,502 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:05,502 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:05,503 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 61 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:06,520 - INFO - Planning complete: 61 expected chunks in 1 baskets

2026-08-14 09:20:06,520 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:06,520 - INFO - Total maximum expected chunks: 1

2026-08-14 09:20:06,520 - INFO - Searching 1 baskets

2026-08-14 09:20:07,501 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:20:07,502 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:20:07,502 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.98s

2026-08-14 09:20:07,502 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:20:07,502 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:20:07,502 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:07,503 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:07,503 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:07,503 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:07,503 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 135 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:08,459 - INFO - Planning complete: 135 expected chunks in 1 baskets

2026-08-14 09:20:08,460 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:08,460 - INFO - Total maximum expected chunks: 2

2026-08-14 09:20:08,460 - INFO - Searching 1 baskets

2026-08-14 09:20:09,571 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 2 documents with 2 chunks

2026-08-14 09:20:09,571 - INFO - First pass complete: 2 documents with 2 chunks

2026-08-14 09:20:09,571 - INFO - Search complete: 2 documents with 2 chunks retrieved in 1.11s

2026-08-14 09:20:09,572 - INFO - Deduplicated: 2 unique documents from 2 total (chunks merged)

2026-08-14 09:20:09,572 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:20:09,572 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:09,572 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:09,572 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:09,572 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:09,572 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 31 data points, 1176 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1176 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 2 period(s) (split_2_volume), 2 basket(s)
2026-08-14 09:20:11,593 - INFO - Planning complete: 1,176 expected chunks in 2 baskets

2026-08-14 09:20:11,594 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:11,594 - INFO - Total maximum expected chunks: 23

2026-08-14 09:20:11,594 - INFO - Searching 2 baskets

2026-08-14 09:20:12,530 - INFO - Basket basket_1_high_20260815_20260815: Retrieved 0 documents with 0 chunks

2026-08-14 09:20:12,652 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 19 documents with 23 chunks

2026-08-14 09:20:12,653 - INFO - First pass complete: 19 documents with 23 chunks

2026-08-14 09:20:12,653 - INFO - Search complete: 19 documents with 23 chunks retrieved in 1.06s

2026-08-14 09:20:12,653 - WARNING - Failed baskets: 1

2026-08-14 09:20:12,654 - INFO - Deduplicated: 19 unique documents from 19 total (chunks merged)

2026-08-14 09:20:12,654 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:20:12,654 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:12,654 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:12,654 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:12,655 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:12,655 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 31 data points, 1056 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1056 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 2 period(s) (split_2_volume), 2 basket(s)
2026-08-14 09:20:14,784 - INFO - Planning complete: 1,056 expected chunks in 2 baskets

2026-08-14 09:20:14,784 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:14,784 - INFO - Total maximum expected chunks: 21

2026-08-14 09:20:14,785 - INFO - Searching 2 baskets

2026-08-14 09:20:15,677 - INFO - Basket basket_1_high_20260815_20260815: Retrieved 0 documents with 0 chunks

2026-08-14 09:20:16,410 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 21 documents with 21 chunks

2026-08-14 09:20:16,412 - INFO - First pass complete: 21 documents with 21 chunks

2026-08-14 09:20:16,413 - INFO - Search complete: 21 documents with 21 chunks retrieved in 1.63s

2026-08-14 09:20:16,413 - WARNING - Failed baskets: 1

2026-08-14 09:20:16,413 - INFO - Deduplicated: 21 unique documents from 21 total (chunks merged)

2026-08-14 09:20:16,416 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:20:16,416 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:16,417 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:16,417 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:16,417 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:16,417 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 224 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:17,519 - INFO - Planning complete: 224 expected chunks in 1 baskets

2026-08-14 09:20:17,520 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:17,520 - INFO - Total maximum expected chunks: 4

2026-08-14 09:20:17,520 - INFO - Searching 1 baskets

2026-08-14 09:20:18,680 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 4 documents with 4 chunks

2026-08-14 09:20:18,681 - INFO - First pass complete: 4 documents with 4 chunks

2026-08-14 09:20:18,682 - INFO - Search complete: 4 documents with 4 chunks retrieved in 1.16s

2026-08-14 09:20:18,682 - INFO - Deduplicated: 4 unique documents from 4 total (chunks merged)

2026-08-14 09:20:18,682 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:20:18,683 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:18,683 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:18,683 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:18,683 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:18,684 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 116 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:19,597 - INFO - Planning complete: 116 expected chunks in 1 baskets

2026-08-14 09:20:19,597 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:19,598 - INFO - Total maximum expected chunks: 2

2026-08-14 09:20:19,598 - INFO - Searching 1 baskets

2026-08-14 09:20:20,657 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 2 documents with 2 chunks

2026-08-14 09:20:20,659 - INFO - First pass complete: 2 documents with 2 chunks

2026-08-14 09:20:20,659 - INFO - Search complete: 2 documents with 2 chunks retrieved in 1.06s

2026-08-14 09:20:20,659 - INFO - Deduplicated: 2 unique documents from 2 total (chunks merged)

2026-08-14 09:20:20,660 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:20:20,660 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:20,660 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:20,660 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:20,660 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:20,660 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 16 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:21,773 - INFO - Planning complete: 16 expected chunks in 1 baskets

2026-08-14 09:20:21,774 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:21,774 - INFO - Total maximum expected chunks: 0

2026-08-14 09:20:21,775 - INFO - Searching 1 baskets

2026-08-14 09:20:23,174 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:20:23,174 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:20:23,175 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.40s

2026-08-14 09:20:23,175 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:20:23,176 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:20:23,176 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:23,176 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:23,176 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:23,177 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:23,177 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 12 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:24,144 - INFO - Planning complete: 12 expected chunks in 1 baskets

2026-08-14 09:20:24,145 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:24,145 - INFO - Total maximum expected chunks: 0

2026-08-14 09:20:24,145 - INFO - Searching 1 baskets

2026-08-14 09:20:25,089 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:20:25,090 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:20:25,090 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.94s

2026-08-14 09:20:25,091 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:20:25,091 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:20:25,091 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:25,092 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:25,092 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:25,092 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:25,093 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 153 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:26,229 - INFO - Planning complete: 153 expected chunks in 1 baskets

2026-08-14 09:20:26,230 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:26,230 - INFO - Total maximum expected chunks: 3

2026-08-14 09:20:26,230 - INFO - Searching 1 baskets

2026-08-14 09:20:27,315 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 3 documents with 3 chunks

2026-08-14 09:20:27,315 - INFO - First pass complete: 3 documents with 3 chunks

2026-08-14 09:20:27,316 - INFO - Search complete: 3 documents with 3 chunks retrieved in 1.09s

2026-08-14 09:20:27,316 - INFO - Deduplicated: 3 unique documents from 3 total (chunks merged)

2026-08-14 09:20:27,316 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:20:27,316 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:27,316 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:27,317 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:27,317 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:27,317 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 535 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:28,530 - INFO - Planning complete: 535 expected chunks in 1 baskets

2026-08-14 09:20:28,530 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:28,530 - INFO - Total maximum expected chunks: 10

2026-08-14 09:20:28,531 - INFO - Searching 1 baskets

2026-08-14 09:20:29,636 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 9 documents with 10 chunks

2026-08-14 09:20:29,637 - INFO - First pass complete: 9 documents with 10 chunks

2026-08-14 09:20:29,638 - INFO - Search complete: 9 documents with 10 chunks retrieved in 1.11s

2026-08-14 09:20:29,638 - INFO - Deduplicated: 9 unique documents from 9 total (chunks merged)

2026-08-14 09:20:29,640 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:20:29,640 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:29,641 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:29,641 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:29,641 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:29,642 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 118 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:30,604 - INFO - Planning complete: 118 expected chunks in 1 baskets

2026-08-14 09:20:30,604 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:30,604 - INFO - Total maximum expected chunks: 2

2026-08-14 09:20:30,604 - INFO - Searching 1 baskets

2026-08-14 09:20:31,714 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 2 documents with 2 chunks

2026-08-14 09:20:31,716 - INFO - First pass complete: 2 documents with 2 chunks

2026-08-14 09:20:31,717 - INFO - Search complete: 2 documents with 2 chunks retrieved in 1.11s

2026-08-14 09:20:31,717 - INFO - Deduplicated: 2 unique documents from 2 total (chunks merged)

2026-08-14 09:20:31,717 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:20:31,718 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:31,718 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:31,718 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:31,719 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:31,719 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 609 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:32,703 - INFO - Planning complete: 609 expected chunks in 1 baskets

2026-08-14 09:20:32,704 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:32,704 - INFO - Total maximum expected chunks: 12

2026-08-14 09:20:32,704 - INFO - Searching 1 baskets

2026-08-14 09:20:33,813 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 12 documents with 12 chunks

2026-08-14 09:20:33,813 - INFO - First pass complete: 12 documents with 12 chunks

2026-08-14 09:20:33,813 - INFO - Search complete: 12 documents with 12 chunks retrieved in 1.11s

2026-08-14 09:20:33,813 - INFO - Deduplicated: 12 unique documents from 12 total (chunks merged)

2026-08-14 09:20:33,814 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:20:33,814 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:33,814 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:33,814 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:33,814 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:33,814 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 11 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:34,721 - INFO - Planning complete: 11 expected chunks in 1 baskets

2026-08-14 09:20:34,721 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:34,721 - INFO - Total maximum expected chunks: 0

2026-08-14 09:20:34,721 - INFO - Searching 1 baskets

2026-08-14 09:20:35,870 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:20:35,871 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:20:35,871 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.15s

2026-08-14 09:20:35,871 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:20:35,871 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:20:35,872 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:35,872 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:35,872 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:35,872 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:35,872 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 18 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:37,187 - INFO - Planning complete: 18 expected chunks in 1 baskets

2026-08-14 09:20:37,187 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:37,188 - INFO - Total maximum expected chunks: 0

2026-08-14 09:20:37,188 - INFO - Searching 1 baskets

2026-08-14 09:20:38,174 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:20:38,175 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:20:38,176 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.99s

2026-08-14 09:20:38,176 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:20:38,177 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:20:38,177 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:38,177 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:38,177 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:38,178 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:38,178 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 439 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:39,313 - INFO - Planning complete: 439 expected chunks in 1 baskets

2026-08-14 09:20:39,313 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:39,314 - INFO - Total maximum expected chunks: 8

2026-08-14 09:20:39,314 - INFO - Searching 1 baskets

2026-08-14 09:20:40,457 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 8 documents with 8 chunks

2026-08-14 09:20:40,459 - INFO - First pass complete: 8 documents with 8 chunks

2026-08-14 09:20:40,459 - INFO - Search complete: 8 documents with 8 chunks retrieved in 1.14s

2026-08-14 09:20:40,459 - INFO - Deduplicated: 8 unique documents from 8 total (chunks merged)

2026-08-14 09:20:40,460 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:20:40,460 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:40,460 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:40,460 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:40,461 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:40,461 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 539 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:41,659 - INFO - Planning complete: 539 expected chunks in 1 baskets

2026-08-14 09:20:41,659 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:41,660 - INFO - Total maximum expected chunks: 10

2026-08-14 09:20:41,660 - INFO - Searching 1 baskets

2026-08-14 09:20:42,671 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 10 documents with 10 chunks

2026-08-14 09:20:42,672 - INFO - First pass complete: 10 documents with 10 chunks

2026-08-14 09:20:42,672 - INFO - Search complete: 10 documents with 10 chunks retrieved in 1.01s

2026-08-14 09:20:42,672 - INFO - Deduplicated: 10 unique documents from 10 total (chunks merged)

2026-08-14 09:20:42,673 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:20:42,674 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:42,674 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:42,674 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:42,674 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:42,675 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 233 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:43,635 - INFO - Planning complete: 233 expected chunks in 1 baskets

2026-08-14 09:20:43,635 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:43,635 - INFO - Total maximum expected chunks: 4

2026-08-14 09:20:43,636 - INFO - Searching 1 baskets

2026-08-14 09:20:44,655 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 4 documents with 4 chunks

2026-08-14 09:20:44,657 - INFO - First pass complete: 4 documents with 4 chunks

2026-08-14 09:20:44,657 - INFO - Search complete: 4 documents with 4 chunks retrieved in 1.02s

2026-08-14 09:20:44,658 - INFO - Deduplicated: 4 unique documents from 4 total (chunks merged)

2026-08-14 09:20:44,658 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:20:44,659 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:44,659 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:44,659 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:44,660 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:44,660 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 255 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:45,638 - INFO - Planning complete: 255 expected chunks in 1 baskets

2026-08-14 09:20:45,638 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:45,639 - INFO - Total maximum expected chunks: 5

2026-08-14 09:20:45,639 - INFO - Searching 1 baskets

2026-08-14 09:20:46,667 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 5 documents with 5 chunks

2026-08-14 09:20:46,668 - INFO - First pass complete: 5 documents with 5 chunks

2026-08-14 09:20:46,668 - INFO - Search complete: 5 documents with 5 chunks retrieved in 1.03s

2026-08-14 09:20:46,668 - INFO - Deduplicated: 5 unique documents from 5 total (chunks merged)

2026-08-14 09:20:46,669 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:20:46,669 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:46,669 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:46,669 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:46,669 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:46,670 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 137 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:47,840 - INFO - Planning complete: 137 expected chunks in 1 baskets

2026-08-14 09:20:47,841 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:47,841 - INFO - Total maximum expected chunks: 2

2026-08-14 09:20:47,842 - INFO - Searching 1 baskets

2026-08-14 09:20:48,927 - INFO - Basket basket_0_medium_20260715_20260814: Retrieved 2 documents with 2 chunks

2026-08-14 09:20:48,928 - INFO - First pass complete: 2 documents with 2 chunks

2026-08-14 09:20:48,928 - INFO - Search complete: 2 documents with 2 chunks retrieved in 1.09s

2026-08-14 09:20:48,928 - INFO - Deduplicated: 2 unique documents from 2 total (chunks merged)

2026-08-14 09:20:48,929 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:20:48,929 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:48,929 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:48,930 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:48,930 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:48,930 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 76 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:50,080 - INFO - Planning complete: 76 expected chunks in 1 baskets

2026-08-14 09:20:50,081 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:50,081 - INFO - Total maximum expected chunks: 1

2026-08-14 09:20:50,081 - INFO - Searching 1 baskets

2026-08-14 09:20:51,082 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:20:51,083 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:20:51,083 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.00s

2026-08-14 09:20:51,084 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:20:51,084 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:20:51,084 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:51,085 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:51,085 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:51,085 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:51,085 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 679 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:52,171 - INFO - Planning complete: 679 expected chunks in 1 baskets

2026-08-14 09:20:52,172 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:52,172 - INFO - Total maximum expected chunks: 13

2026-08-14 09:20:52,172 - INFO - Searching 1 baskets

2026-08-14 09:20:53,295 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 13 documents with 13 chunks

2026-08-14 09:20:53,296 - INFO - First pass complete: 13 documents with 13 chunks

2026-08-14 09:20:53,296 - INFO - Search complete: 13 documents with 13 chunks retrieved in 1.12s

2026-08-14 09:20:53,296 - INFO - Deduplicated: 13 unique documents from 13 total (chunks merged)

2026-08-14 09:20:53,296 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:20:53,297 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:20:53,297 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:20:53,297 - INFO - Loaded 1 companies from universe

2026-08-14 09:20:53,297 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:20:53,297 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 744 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:20:54,271 - INFO - Planning complete: 744 expected chunks in 1 baskets

2026-08-14 09:20:54,272 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:20:54,272 - INFO - Total maximum expected chunks: 14

2026-08-14 09:20:54,273 - INFO - Searching 1 baskets

2026-08-14 09:20:55,529 - INFO - Basket basket_0_high_20260715_20260814: Retrieved 14 documents with 14 chunks

2026-08-14 09:20:55,530 - INFO - First pass complete: 14 documents with 14 chunks

2026-08-14 09:20:55,530 - INFO - Search complete: 14 documents with 14 chunks retrieved in 1.26s

2026-08-14 09:20:55,531 - INFO - Deduplicated: 14 unique documents from 14 total (chunks merged)

✅ Retrieved 10 news chunks (capped at 10)

,document_id,headline,timestamp,url,source_id,source_name,chunk_text,text,masked_text,relevance,sentiment,entity_id,entity_ids,entity_name,query,document_type,theme,entity_searched_id,entity_searched_name
0,6BD4C558F99E2E4B6D30005261AB1EE9,Americans are rallying against data centers. S...,2026-08-12T01:17:54,https://us.cnn.com/2026/08/06/business/ai-data...,2435A4,CNN,What's behind the delays?\nMaterials shortages...,What's behind the delays?\nMaterials shortages...,What's behind the delays?\nMaterials shortages...,0.185838,-0.60,E09E2B,[E09E2B],NVIDIA Corp.,Impact on sourcing materials and components du...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.
1,A4F0293E4168D93FEE46B691BF3BF73F,IBM share plunge is a warning to the IT sector,2026-07-15T07:57:15,https://www.ft.com/content/83aa00c5-e773-47be-...,DA9FC6,Financial Times,The other risk is that rising prices will cons...,The other risk is that rising prices will cons...,The other risk is that rising prices will cons...,0.126713,-0.28,E09E2B,[E09E2B],NVIDIA Corp.,Impact on sourcing materials and components du...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.
2,F3B0763201F7324906237FE21EE578E3,Transcript: The weaponisation of trade,2026-07-30T04:00:31,https://www.ft.com/content/9be25b80-1882-4107-...,DA9FC6,Financial Times,So I think this is a very powerful weapon for ...,So I think this is a very powerful weapon for ...,So I think this is a very powerful weapon for ...,0.110417,-0.35,E09E2B,[E09E2B],NVIDIA Corp.,Impact on sourcing materials and components du...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.
3,900688489DBDF8BC9BC983DA7A32A448,"""Look to Taiwan's supply chain for a peak-out ...",2026-08-04T21:07:31,https://magazine.hankyung.com/money/article/20...,2F93EE,Hankyung,"""The contract method has changed to LTA. While...","""The contract method has changed to LTA. While...","""The contract method has changed to LTA. While...",0.103011,-0.40,E09E2B,[E09E2B],NVIDIA Corp.,Impact on sourcing materials and components du...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.
4,B6CE2458767C79494D80035A9D18ED92,Oil prices sink nearly 7% and world shares gai...,2026-07-27T11:51:50,https://kstp.com/ap-top-news/ap-top-news-busin...,5E53F3,KSTP-TV,Higher energy costs are taking up a bigger sha...,Higher energy costs are taking up a bigger sha...,Higher energy costs are taking up a bigger sha...,0.107008,-0.42,E09E2B,[E09E2B],NVIDIA Corp.,Higher expenses related to tariffs leading to ...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.

  ### Labeling



  Use AI to analyze each news excerpt and categorize it into the appropriate risk scenarios. This creates structured data from unstructured news content.

In [12]:
# Classify each retrieved news excerpt into a risk category using OpenAI
# (replaces RiskAnalyzer.label_search_results()).
label_processor = LabelProcessor(
    list_entities=list_entities,
    themes_tree_dict=themes_tree_dict,
    list_specific_themes=[main_theme],
    api_key=OPENAI_API_KEY,
)

if df_sentences_semantic.empty:
    df_labeled = pd.DataFrame()
    print("⚠️ No news content retrieved for this window; skipping labeling.")
else:
    df_labeled = label_processor.run_label_process(df_sentences=df_sentences_semantic)
    if df_labeled is None:
        df_labeled = pd.DataFrame()
    print(f"✅ Labeled {len(df_labeled)} news excerpts")

df_labeled.head()

2026-08-14 09:20:56,732 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:56,787 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:56,796 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:56,804 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:56,825 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:56,886 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:56,972 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:56,999 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:57,353 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:20:57,355 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 10 requests in 1.79 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
✅ Labeled 10 news excerpts

,document_id,headline,timestamp,url,source_id,source_name,chunk_text,text,masked_text,relevance,...,entity_id,entity_ids,entity_name,query,document_type,theme,entity_searched_id,entity_searched_name,motivation,label
0,6BD4C558F99E2E4B6D30005261AB1EE9,Americans are rallying against data centers. S...,2026-08-12T01:17:54,https://us.cnn.com/2026/08/06/business/ai-data...,2435A4,CNN,What's behind the delays?\nMaterials shortages...,What's behind the delays?\nMaterials shortages...,What's behind the delays?\nMaterials shortages...,0.185838,...,E09E2B,[E09E2B],NVIDIA Corp.,Impact on sourcing materials and components du...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company is not mentioned as being impac...,unclear
1,A4F0293E4168D93FEE46B691BF3BF73F,IBM share plunge is a warning to the IT sector,2026-07-15T07:57:15,https://www.ft.com/content/83aa00c5-e773-47be-...,DA9FC6,Financial Times,The other risk is that rising prices will cons...,The other risk is that rising prices will cons...,The other risk is that rising prices will cons...,0.126713,...,E09E2B,[E09E2B],NVIDIA Corp.,Impact on sourcing materials and components du...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company does not explicitly mention how...,unclear
2,F3B0763201F7324906237FE21EE578E3,Transcript: The weaponisation of trade,2026-07-30T04:00:31,https://www.ft.com/content/9be25b80-1882-4107-...,DA9FC6,Financial Times,So I think this is a very powerful weapon for ...,So I think this is a very powerful weapon for ...,So I think this is a very powerful weapon for ...,0.110417,...,E09E2B,[E09E2B],NVIDIA Corp.,Impact on sourcing materials and components du...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company does not explicitly mention any...,unclear
3,900688489DBDF8BC9BC983DA7A32A448,"""Look to Taiwan's supply chain for a peak-out ...",2026-08-04T21:07:31,https://magazine.hankyung.com/money/article/20...,2F93EE,Hankyung,"""The contract method has changed to LTA. While...","""The contract method has changed to LTA. While...","""The contract method has changed to LTA. While...",0.103011,...,E09E2B,[E09E2B],NVIDIA Corp.,Impact on sourcing materials and components du...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company is discussing long-term contrac...,unclear
4,B6CE2458767C79494D80035A9D18ED92,Oil prices sink nearly 7% and world shares gai...,2026-07-27T11:51:50,https://kstp.com/ap-top-news/ap-top-news-busin...,5E53F3,KSTP-TV,Higher energy costs are taking up a bigger sha...,Higher energy costs are taking up a bigger sha...,Higher energy costs are taking up a bigger sha...,0.107008,...,E09E2B,[E09E2B],NVIDIA Corp.,Higher expenses related to tariffs leading to ...,news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company is not discussed in the context...,unclear

  ## Report Generation



  The second phase uses `GenerateReport` and transforms the classified risk data into comprehensive reports with corporate mitigation strategies.

  ### Initialize GenerateReport







  The `GenerateReport` class will:



  - Create sector-wide risk summaries



  - Generate company-specific risk scores and summaries



  - Extract mitigation plans from SEC filings and earnings transcripts



  - Produce professional HTML reports with customizable ranking criteria

In [13]:
# Initialize the report generator with our analysis parameters
report_generator = GenerateReport(
        universe_df=universe_df,
        main_theme=main_theme,
        focus=focus,
        llm_model=llm_model,
        api_key=OPENAI_API_KEY,
        start_date=start_date,
        end_date=end_date,
        search_frequency=freq,
        document_limit_news=document_limit_news,
        document_limit_filings=document_limit_filings,
        batch_size=batch_size,
        themes_tree_dict=themes_tree_dict
)

  ### Generate Comprehensive Report







  Execute the complete report generation workflow including:



  1. **Sector-Level Summarization**: Create thematic summaries across risk categories



  2. **Company-Level Analysis**: Generate risk scores for Media Attention, Financial Impact, and Uncertainty



  3. **Mitigation Strategy Extraction**: Search filings and transcripts for corporate response plans (with News fallback when enabled via `news_search_fallback`)



  4. **Data Integration**: Combine all sources into structured report datasets

In [14]:
# Generate the risk report data
report = report_generator.generate_report(
    df_labeled=df_labeled,
    news_search_fallback = response_from_news, # Use response_from_news to enable/disable News fallback
    import_from_path=None,
    export_to_path=output_dir,
)

2026-08-14 09:20:59,451 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:21:01,036 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:21:01,115 - INFO - Exported summaries to pickle file.

2026-08-14 09:21:01,116 - INFO - Preparing topics from the labeled DataFrame

2026-08-14 09:21:01,119 - INFO - Starting processing for 2 tasks...

2026-08-14 09:21:01,120 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Market Access Limitations' for entity 'NVIDIA Corp.'

2026-08-14 09:21:01,122 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Increased Costs' for entity 'NVIDIA Corp.'

2026-08-14 09:21:02,388 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:21:02,452 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:21:03,425 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:21:03,482 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:21:04,636 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:21:04,749 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:21:04,751 - INFO - Exporting processed data to output/df_by_company

2026-08-14 09:21:04,752 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:21:04,752 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:04,753 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:04,753 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:04,753 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:04,753 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 10 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:05,650 - INFO - Planning complete: 10 expected chunks in 1 baskets

2026-08-14 09:21:05,651 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:05,651 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:05,652 - INFO - Searching 1 baskets

2026-08-14 09:21:06,676 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:06,677 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:06,677 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.02s

2026-08-14 09:21:06,677 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:06,678 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:21:06,678 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:06,678 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:06,678 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:06,678 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:06,679 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:07,799 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:07,800 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:07,800 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:07,800 - INFO - Searching 1 baskets

2026-08-14 09:21:08,723 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:21:08,723 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:21:08,724 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.92s

2026-08-14 09:21:08,724 - WARNING - Failed baskets: 1

2026-08-14 09:21:08,724 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:21:08,724 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:21:08,724 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:08,724 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:08,725 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:08,725 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:08,725 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:09,863 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:09,863 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:09,863 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:09,864 - INFO - Searching 1 baskets

2026-08-14 09:21:10,781 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:21:10,782 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:21:10,782 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.92s

2026-08-14 09:21:10,783 - WARNING - Failed baskets: 1

2026-08-14 09:21:10,783 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:21:10,783 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:21:10,783 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:10,783 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:10,783 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:10,784 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:10,784 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:11,691 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:11,692 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:11,692 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:11,693 - INFO - Searching 1 baskets

2026-08-14 09:21:12,693 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:21:12,694 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:21:12,694 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.00s

2026-08-14 09:21:12,695 - WARNING - Failed baskets: 1

2026-08-14 09:21:12,695 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:21:12,695 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:21:12,696 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:12,696 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:12,696 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:12,696 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:12,697 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:13,743 - INFO - Planning complete: 2 expected chunks in 1 baskets

2026-08-14 09:21:13,743 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:13,744 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:13,744 - INFO - Searching 1 baskets

2026-08-14 09:21:14,731 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:14,732 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:14,734 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.99s

2026-08-14 09:21:14,735 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:14,736 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:21:14,736 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:14,737 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:14,737 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:14,737 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:14,738 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 10 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:15,612 - INFO - Planning complete: 10 expected chunks in 1 baskets

2026-08-14 09:21:15,613 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:15,613 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:15,613 - INFO - Searching 1 baskets

2026-08-14 09:21:16,853 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:16,855 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:16,855 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.24s

2026-08-14 09:21:16,856 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:16,860 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:21:16,860 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:16,860 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:16,861 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:16,861 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:16,861 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:17,982 - INFO - Planning complete: 3 expected chunks in 1 baskets

2026-08-14 09:21:17,982 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:17,982 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:17,983 - INFO - Searching 1 baskets

2026-08-14 09:21:18,961 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:18,962 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:18,963 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.98s

2026-08-14 09:21:18,963 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:18,964 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:21:18,964 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:18,964 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:18,966 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:18,967 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:18,968 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:19,896 - INFO - Planning complete: 2 expected chunks in 1 baskets

2026-08-14 09:21:19,897 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:19,897 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:19,897 - INFO - Searching 1 baskets

2026-08-14 09:21:20,883 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:20,884 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:20,884 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.99s

2026-08-14 09:21:20,884 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:20,885 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:21:20,885 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:20,885 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:20,885 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:20,885 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:20,885 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:21,770 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:21,770 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:21,770 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:21,770 - INFO - Searching 1 baskets

2026-08-14 09:21:22,786 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:21:22,787 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:21:22,788 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.02s

2026-08-14 09:21:22,788 - WARNING - Failed baskets: 1

2026-08-14 09:21:22,788 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:21:22,789 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:21:22,789 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:22,789 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:22,789 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:22,790 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:22,790 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:23,751 - INFO - Planning complete: 2 expected chunks in 1 baskets

2026-08-14 09:21:23,753 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:23,754 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:23,754 - INFO - Searching 1 baskets

2026-08-14 09:21:24,726 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:24,727 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:24,727 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.97s

2026-08-14 09:21:24,727 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:24,728 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:21:24,728 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:24,728 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:24,728 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:24,729 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:24,729 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:25,630 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:25,630 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:25,630 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:25,631 - INFO - Searching 1 baskets

2026-08-14 09:21:26,604 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:21:26,605 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:21:26,605 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.97s

2026-08-14 09:21:26,606 - WARNING - Failed baskets: 1

2026-08-14 09:21:26,606 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:21:26,607 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:21:26,608 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:26,608 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:26,608 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:26,608 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:26,609 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 4 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:27,679 - INFO - Planning complete: 4 expected chunks in 1 baskets

2026-08-14 09:21:27,679 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:27,680 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:27,680 - INFO - Searching 1 baskets

2026-08-14 09:21:28,643 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:28,644 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:28,645 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.96s

2026-08-14 09:21:28,645 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:28,650 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:21:28,650 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:28,651 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:28,651 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:28,651 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:28,651 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:29,602 - INFO - Planning complete: 3 expected chunks in 1 baskets

2026-08-14 09:21:29,603 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:29,603 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:29,603 - INFO - Searching 1 baskets

2026-08-14 09:21:30,611 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:30,612 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:30,612 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.01s

2026-08-14 09:21:30,612 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:30,613 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:21:30,613 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:30,613 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:30,613 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:30,613 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:30,614 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:31,585 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:31,585 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:31,585 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:31,585 - INFO - Searching 1 baskets

2026-08-14 09:21:32,545 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:21:32,546 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:21:32,546 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.96s

2026-08-14 09:21:32,547 - WARNING - Failed baskets: 1

2026-08-14 09:21:32,547 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:21:32,547 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:21:32,547 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:32,548 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:32,548 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:32,548 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:32,548 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:33,517 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:33,517 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:33,518 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:33,518 - INFO - Searching 1 baskets

2026-08-14 09:21:34,551 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:21:34,551 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:21:34,552 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.03s

2026-08-14 09:21:34,552 - WARNING - Failed baskets: 1

2026-08-14 09:21:34,552 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:21:34,552 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:21:34,552 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:34,553 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:34,553 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:34,553 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:34,553 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:35,526 - INFO - Planning complete: 2 expected chunks in 1 baskets

2026-08-14 09:21:35,526 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:35,527 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:35,527 - INFO - Searching 1 baskets

2026-08-14 09:21:36,687 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:36,688 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:36,688 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.16s

2026-08-14 09:21:36,688 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:36,688 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:21:36,689 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:36,689 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:36,689 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:36,689 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:36,689 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:37,612 - INFO - Planning complete: 1 expected chunks in 1 baskets

2026-08-14 09:21:37,613 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:37,613 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:37,614 - INFO - Searching 1 baskets

2026-08-14 09:21:38,678 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:38,679 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:38,679 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.07s

2026-08-14 09:21:38,680 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:38,680 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:21:38,680 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:38,680 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:38,680 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:38,681 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:38,681 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 12 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:39,815 - INFO - Planning complete: 12 expected chunks in 1 baskets

2026-08-14 09:21:39,816 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:39,818 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:39,820 - INFO - Searching 1 baskets

2026-08-14 09:21:41,152 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:41,152 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:41,153 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.33s

2026-08-14 09:21:41,153 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:41,154 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:21:41,154 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:41,154 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:41,154 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:41,154 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:41,154 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 4 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:42,475 - INFO - Planning complete: 4 expected chunks in 1 baskets

2026-08-14 09:21:42,475 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:42,476 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:42,476 - INFO - Searching 1 baskets

2026-08-14 09:21:43,471 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:43,472 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:43,472 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.00s

2026-08-14 09:21:43,472 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:43,472 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:21:43,472 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:43,473 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:43,473 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:43,474 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:43,474 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:44,629 - INFO - Planning complete: 2 expected chunks in 1 baskets

2026-08-14 09:21:44,630 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:44,630 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:44,630 - INFO - Searching 1 baskets

2026-08-14 09:21:45,589 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:45,592 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:45,592 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.96s

2026-08-14 09:21:45,593 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:45,593 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:21:45,594 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:45,594 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:45,594 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:45,595 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:45,595 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:46,502 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:46,502 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:46,502 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:46,503 - INFO - Searching 1 baskets

2026-08-14 09:21:47,657 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:21:47,658 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:21:47,658 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.15s

2026-08-14 09:21:47,658 - WARNING - Failed baskets: 1

2026-08-14 09:21:47,658 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:21:47,659 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:21:47,659 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:47,659 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:47,659 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:47,660 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:47,660 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:48,761 - INFO - Planning complete: 2 expected chunks in 1 baskets

2026-08-14 09:21:48,762 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:48,762 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:48,763 - INFO - Searching 1 baskets

2026-08-14 09:21:49,952 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:49,953 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:49,954 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.19s

2026-08-14 09:21:49,955 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:49,955 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:21:49,956 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:49,956 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:49,956 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:49,957 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:49,957 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:50,884 - INFO - Planning complete: 3 expected chunks in 1 baskets

2026-08-14 09:21:50,885 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:50,885 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:50,885 - INFO - Searching 1 baskets

2026-08-14 09:21:51,881 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:51,882 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:51,882 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.00s

2026-08-14 09:21:51,882 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:51,882 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:21:51,882 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:51,882 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:51,883 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:51,883 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:51,883 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 17 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:53,092 - INFO - Planning complete: 17 expected chunks in 1 baskets

2026-08-14 09:21:53,092 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:53,092 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:53,092 - INFO - Searching 1 baskets

2026-08-14 09:21:54,105 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:54,106 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:54,107 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.01s

2026-08-14 09:21:54,108 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:54,111 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:21:54,111 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:54,112 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:54,112 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:54,112 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:54,112 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 8 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:55,275 - INFO - Planning complete: 8 expected chunks in 1 baskets

2026-08-14 09:21:55,275 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:55,276 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:55,276 - INFO - Searching 1 baskets

2026-08-14 09:21:56,237 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:56,238 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:56,238 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.96s

2026-08-14 09:21:56,239 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:56,239 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:21:56,239 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:56,240 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:56,240 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:56,240 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:56,242 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:21:57,155 - INFO - Planning complete: 3 expected chunks in 1 baskets

2026-08-14 09:21:57,156 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:57,156 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:57,156 - INFO - Searching 1 baskets

2026-08-14 09:21:58,186 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:21:58,187 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:21:58,188 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.03s

2026-08-14 09:21:58,188 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:21:58,189 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:21:58,189 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:21:58,190 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:21:58,190 - INFO - Loaded 1 companies from universe

2026-08-14 09:21:58,190 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:21:58,191 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:21:59,289 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:21:59,289 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:21:59,290 - INFO - Total maximum expected chunks: 0

2026-08-14 09:21:59,290 - INFO - Searching 1 baskets

2026-08-14 09:22:00,256 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:00,257 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:00,257 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.97s

2026-08-14 09:22:00,257 - WARNING - Failed baskets: 1

2026-08-14 09:22:00,258 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:00,258 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:22:00,258 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:00,258 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:00,258 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:00,258 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:00,259 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:01,534 - INFO - Planning complete: 1 expected chunks in 1 baskets

2026-08-14 09:22:01,534 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:01,535 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:01,535 - INFO - Searching 1 baskets

2026-08-14 09:22:02,502 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:02,502 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:02,503 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.97s

2026-08-14 09:22:02,503 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:02,503 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:22:02,503 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:02,503 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:02,504 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:02,504 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:02,504 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:03,669 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:03,669 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:03,669 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:03,670 - INFO - Searching 1 baskets

2026-08-14 09:22:04,800 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:04,801 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:04,802 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.13s

2026-08-14 09:22:04,802 - WARNING - Failed baskets: 1

2026-08-14 09:22:04,802 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:04,803 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:22:04,803 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:04,803 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:04,804 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:04,804 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:04,804 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 9 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:05,967 - INFO - Planning complete: 9 expected chunks in 1 baskets

2026-08-14 09:22:05,968 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:05,968 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:05,969 - INFO - Searching 1 baskets

2026-08-14 09:22:06,916 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:06,917 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:06,918 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.95s

2026-08-14 09:22:06,918 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:06,924 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:22:06,925 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:06,925 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:06,925 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:06,926 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:06,926 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 4 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:07,877 - INFO - Planning complete: 4 expected chunks in 1 baskets

2026-08-14 09:22:07,877 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:07,877 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:07,878 - INFO - Searching 1 baskets

2026-08-14 09:22:09,000 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:09,001 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:09,001 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.12s

2026-08-14 09:22:09,001 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:09,001 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:22:09,001 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:09,002 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:09,002 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:09,002 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:09,002 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:09,982 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:09,983 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:09,983 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:09,983 - INFO - Searching 1 baskets

2026-08-14 09:22:10,890 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:10,890 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:10,891 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.91s

2026-08-14 09:22:10,891 - WARNING - Failed baskets: 1

2026-08-14 09:22:10,891 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:10,891 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:22:10,891 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:10,891 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:10,892 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:10,892 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:10,892 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:11,800 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:11,801 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:11,801 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:11,801 - INFO - Searching 1 baskets

2026-08-14 09:22:12,821 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:12,823 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:12,824 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.02s

2026-08-14 09:22:12,824 - WARNING - Failed baskets: 1

2026-08-14 09:22:12,824 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:12,825 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:22:12,825 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:12,826 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:12,826 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:12,826 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:12,827 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:13,708 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:13,709 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:13,709 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:13,709 - INFO - Searching 1 baskets

2026-08-14 09:22:14,616 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:14,617 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:14,618 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.91s

2026-08-14 09:22:14,618 - WARNING - Failed baskets: 1

2026-08-14 09:22:14,618 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:14,618 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:22:14,619 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:14,619 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:14,619 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:14,619 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:14,619 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 4 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:15,527 - INFO - Planning complete: 4 expected chunks in 1 baskets

2026-08-14 09:22:15,527 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:15,528 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:15,528 - INFO - Searching 1 baskets

2026-08-14 09:22:16,491 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:16,492 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:16,493 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.96s

2026-08-14 09:22:16,493 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:16,493 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:22:16,494 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:16,494 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:16,494 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:16,494 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:16,495 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 9 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:17,644 - INFO - Planning complete: 9 expected chunks in 1 baskets

2026-08-14 09:22:17,645 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:17,645 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:17,645 - INFO - Searching 1 baskets

2026-08-14 09:22:18,604 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:18,604 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:18,605 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.96s

2026-08-14 09:22:18,605 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:18,606 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:22:18,606 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:18,606 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:18,607 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:18,607 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:18,607 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 8 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:19,561 - INFO - Planning complete: 8 expected chunks in 1 baskets

2026-08-14 09:22:19,561 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:19,561 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:19,562 - INFO - Searching 1 baskets

2026-08-14 09:22:20,564 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:20,566 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:20,566 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.00s

2026-08-14 09:22:20,566 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:20,566 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:22:20,566 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:20,567 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:20,567 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:20,567 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:20,567 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 5 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:21,472 - INFO - Planning complete: 5 expected chunks in 1 baskets

2026-08-14 09:22:21,472 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:21,473 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:21,473 - INFO - Searching 1 baskets

2026-08-14 09:22:22,589 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:22,590 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:22,591 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.12s

2026-08-14 09:22:22,591 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:22,592 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:22:22,592 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:22,592 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:22,592 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:22,593 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:22,593 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:23,477 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:23,477 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:23,478 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:23,478 - INFO - Searching 1 baskets

2026-08-14 09:22:24,588 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:24,590 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:24,591 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.11s

2026-08-14 09:22:24,591 - WARNING - Failed baskets: 1

2026-08-14 09:22:24,592 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:24,592 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:22:24,593 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:24,593 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:24,593 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:24,594 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:24,594 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:25,699 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:25,700 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:25,700 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:25,701 - INFO - Searching 1 baskets

2026-08-14 09:22:27,020 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:27,022 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:27,022 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.32s

2026-08-14 09:22:27,023 - WARNING - Failed baskets: 1

2026-08-14 09:22:27,023 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:27,024 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:22:27,025 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:27,025 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:27,026 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:27,027 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:27,027 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:27,963 - INFO - Planning complete: 3 expected chunks in 1 baskets

2026-08-14 09:22:27,963 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:27,963 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:27,963 - INFO - Searching 1 baskets

2026-08-14 09:22:28,903 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:28,904 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:28,904 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.94s

2026-08-14 09:22:28,904 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:28,905 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:22:28,905 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:28,905 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:28,905 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:28,905 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:28,905 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 7 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:30,026 - INFO - Planning complete: 7 expected chunks in 1 baskets

2026-08-14 09:22:30,027 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:30,027 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:30,027 - INFO - Searching 1 baskets

2026-08-14 09:22:31,148 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:31,148 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:31,148 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.12s

2026-08-14 09:22:31,149 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:31,150 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:22:31,150 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:31,150 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:31,150 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:31,151 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:31,151 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:32,038 - INFO - Planning complete: 3 expected chunks in 1 baskets

2026-08-14 09:22:32,038 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:32,039 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:32,039 - INFO - Searching 1 baskets

2026-08-14 09:22:33,109 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:33,110 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:33,110 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.07s

2026-08-14 09:22:33,110 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:33,110 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:22:33,111 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:33,111 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:33,111 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:33,111 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:33,111 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:34,046 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:34,046 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:34,046 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:34,047 - INFO - Searching 1 baskets

2026-08-14 09:22:35,163 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:35,164 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:35,165 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.12s

2026-08-14 09:22:35,165 - WARNING - Failed baskets: 1

2026-08-14 09:22:35,165 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:35,166 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:22:35,166 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:35,166 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:35,166 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:35,166 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:35,166 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:36,102 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:36,102 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:36,102 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:36,102 - INFO - Searching 1 baskets

2026-08-14 09:22:37,228 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:37,230 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:37,230 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.13s

2026-08-14 09:22:37,231 - WARNING - Failed baskets: 1

2026-08-14 09:22:37,231 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:37,232 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:22:37,232 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:37,232 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:37,233 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:37,233 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:37,234 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:38,320 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:38,320 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:38,321 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:38,321 - INFO - Searching 1 baskets

2026-08-14 09:22:39,363 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:39,364 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:39,364 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.04s

2026-08-14 09:22:39,365 - WARNING - Failed baskets: 1

2026-08-14 09:22:39,365 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:39,365 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:22:39,365 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:39,366 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:39,366 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:39,366 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:39,366 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:40,455 - INFO - Planning complete: 1 expected chunks in 1 baskets

2026-08-14 09:22:40,455 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:40,455 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:40,456 - INFO - Searching 1 baskets

2026-08-14 09:22:41,395 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:41,396 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:41,396 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.94s

2026-08-14 09:22:41,397 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:41,397 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:22:41,397 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:41,397 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:41,397 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:41,398 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:41,398 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 13 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:42,511 - INFO - Planning complete: 13 expected chunks in 1 baskets

2026-08-14 09:22:42,512 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:42,512 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:42,512 - INFO - Searching 1 baskets

2026-08-14 09:22:43,744 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:43,745 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:43,745 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.23s

2026-08-14 09:22:43,745 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:43,747 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:22:43,747 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:43,747 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:43,747 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:43,747 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:43,747 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:44,764 - INFO - Planning complete: 2 expected chunks in 1 baskets

2026-08-14 09:22:44,765 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:44,765 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:44,765 - INFO - Searching 1 baskets

2026-08-14 09:22:45,737 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:45,738 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:45,738 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.97s

2026-08-14 09:22:45,739 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:45,739 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:22:45,739 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:45,739 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:45,739 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:45,740 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:45,740 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:46,678 - INFO - Planning complete: 1 expected chunks in 1 baskets

2026-08-14 09:22:46,678 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:46,678 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:46,679 - INFO - Searching 1 baskets

2026-08-14 09:22:47,635 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:47,636 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:47,636 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.96s

2026-08-14 09:22:47,637 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:47,637 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:22:47,638 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:47,638 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:47,639 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:47,641 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:47,642 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:48,606 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:48,607 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:48,608 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:48,608 - INFO - Searching 1 baskets

2026-08-14 09:22:49,549 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:49,549 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:49,550 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.94s

2026-08-14 09:22:49,550 - WARNING - Failed baskets: 1

2026-08-14 09:22:49,550 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:49,550 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:22:49,550 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:49,551 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:49,551 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:49,551 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:49,552 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:50,526 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:50,527 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:50,529 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:50,530 - INFO - Searching 1 baskets

2026-08-14 09:22:51,448 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:51,451 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:51,451 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.92s

2026-08-14 09:22:51,453 - WARNING - Failed baskets: 1

2026-08-14 09:22:51,453 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:51,465 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:22:51,468 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:51,471 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:51,475 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:51,488 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:51,490 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 9 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:52,549 - INFO - Planning complete: 9 expected chunks in 1 baskets

2026-08-14 09:22:52,550 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:52,550 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:52,550 - INFO - Searching 1 baskets

2026-08-14 09:22:53,526 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:53,527 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:53,527 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.98s

2026-08-14 09:22:53,527 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:53,527 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:22:53,527 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:53,528 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:53,528 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:53,528 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:53,528 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 25 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:54,756 - INFO - Planning complete: 25 expected chunks in 1 baskets

2026-08-14 09:22:54,756 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:54,757 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:54,757 - INFO - Searching 1 baskets

2026-08-14 09:22:55,710 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:22:55,711 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:22:55,712 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.95s

2026-08-14 09:22:55,712 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:22:55,717 - INFO - Planning search for text: 'Impact on sourcing materials and components due to increased costs or availability issues.'

2026-08-14 09:22:55,717 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:55,717 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:55,717 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:55,717 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:55,718 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:22:56,671 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:22:56,671 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:56,671 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:56,672 - INFO - Searching 1 baskets

2026-08-14 09:22:57,815 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:22:57,816 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:22:57,817 - INFO - Search complete: 0 documents with 0 chunks retrieved in 1.14s

2026-08-14 09:22:57,817 - WARNING - Failed baskets: 1

2026-08-14 09:22:57,818 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:22:57,818 - INFO - Planning search for text: 'Higher expenses related to tariffs leading to potential price increases for consumers.'

2026-08-14 09:22:57,818 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:22:57,819 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:22:57,819 - INFO - Loaded 1 companies from universe

2026-08-14 09:22:57,819 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:57,819 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 4 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:58,935 - INFO - Planning complete: 4 expected chunks in 1 baskets

2026-08-14 09:22:58,936 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:58,936 - INFO - Total maximum expected chunks: 0

2026-08-14 09:22:58,936 - INFO - Searching 1 baskets

2026-08-14 09:23:00,104 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:23:00,105 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:23:00,106 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.17s

2026-08-14 09:23:00,107 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:23:00,108 - INFO - Planning search for text: 'Difficulties in adhering to new regulations and tariff classifications.'

2026-08-14 09:23:00,110 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:23:00,111 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:23:00,112 - INFO - Loaded 1 companies from universe

2026-08-14 09:23:00,113 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:23:00,113 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:23:01,358 - INFO - Planning complete: 1 expected chunks in 1 baskets

2026-08-14 09:23:01,358 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:23:01,358 - INFO - Total maximum expected chunks: 0

2026-08-14 09:23:01,358 - INFO - Searching 1 baskets

2026-08-14 09:23:02,599 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:23:02,621 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:23:02,623 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.26s

2026-08-14 09:23:02,624 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:23:02,626 - INFO - Planning search for text: 'Reduced ability to enter or compete in certain markets due to tariff barriers.'

2026-08-14 09:23:02,627 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:23:02,627 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:23:02,628 - INFO - Loaded 1 companies from universe

2026-08-14 09:23:02,631 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:23:02,634 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 0 new companies, 1 remaining
      Batch 1 complete: 0 found, 1 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 0 companies with chunks > 0, 1 very_low

Phase 1 complete: 1 comention queries
Found 0 companies with chunks > 0

Created 0 entity groups (min_entities_per_group=1)
  Zero chunks: 1 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
2026-08-14 09:23:03,609 - INFO - Planning complete: 0 expected chunks in 1 baskets

2026-08-14 09:23:03,609 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:23:03,609 - INFO - Total maximum expected chunks: 0

2026-08-14 09:23:03,610 - INFO - Searching 1 baskets

2026-08-14 09:23:04,585 - INFO - Basket basket_0_very_low_20260715_20260814: Retrieved 0 documents with 0 chunks

2026-08-14 09:23:04,586 - INFO - First pass complete: 0 documents with 0 chunks

2026-08-14 09:23:04,586 - INFO - Search complete: 0 documents with 0 chunks retrieved in 0.98s

2026-08-14 09:23:04,587 - WARNING - Failed baskets: 1

2026-08-14 09:23:04,588 - INFO - Deduplicated: 0 unique documents from 0 total (chunks merged)

2026-08-14 09:23:04,588 - INFO - Planning search for text: 'Changes in capital allocation and investment strategies in response to tariff impacts.'

2026-08-14 09:23:04,588 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:23:04,588 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:23:04,588 - INFO - Loaded 1 companies from universe

2026-08-14 09:23:04,589 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:23:04,589 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 4 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:23:05,507 - INFO - Planning complete: 4 expected chunks in 1 baskets

2026-08-14 09:23:05,507 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:23:05,507 - INFO - Total maximum expected chunks: 0

2026-08-14 09:23:05,507 - INFO - Searching 1 baskets

2026-08-14 09:23:06,650 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:23:06,651 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:23:06,651 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.14s

2026-08-14 09:23:06,651 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:23:06,651 - INFO - Planning search for text: 'Potential backlash from consumers and stakeholders regarding pricing and sourcing practices.'

2026-08-14 09:23:06,651 - INFO - Date range: 2026-07-15 to 2026-08-14

2026-08-14 09:23:06,652 - INFO - Using 1 entity IDs from inline list

2026-08-14 09:23:06,652 - INFO - Loaded 1 companies from universe

2026-08-14 09:23:06,652 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:23:06,652 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2026-07-15 to 2026-08-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 10 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:23:07,642 - INFO - Planning complete: 10 expected chunks in 1 baskets

2026-08-14 09:23:07,642 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:23:07,642 - INFO - Total maximum expected chunks: 0

2026-08-14 09:23:07,643 - INFO - Searching 1 baskets

2026-08-14 09:23:09,101 - INFO - Basket basket_0_low_20260715_20260814: Retrieved 1 documents with 1 chunks

2026-08-14 09:23:09,102 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-14 09:23:09,103 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.46s

2026-08-14 09:23:09,103 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-14 09:23:10,405 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:23:10,461 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:23:10,643 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 3 requests in 1.54 seconds.

2026-08-14 09:23:11,721 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:23:11,726 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 2 requests in 1.07 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
2026-08-14 09:23:11,736 - INFO - Exported labeled DataFrame to pickle file.

2026-08-14 09:23:12,951 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:23:12,996 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:23:13,424 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 3 requests in 1.69 seconds.

2026-08-14 09:23:14,570 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:23:14,716 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 2 requests in 1.30 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
2026-08-14 09:23:14,730 - INFO - Exported labeled DataFrame to pickle file.

2026-08-14 09:23:14,733 - INFO - Starting process_response_by_company with 1 tasks...

2026-08-14 09:23:14,733 - INFO - Processing response summary for entity 'NVIDIA Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Supply Chain Disruptions'

2026-08-14 09:23:14,735 - WARNING - No topic summary present for entity 'NVIDIA Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Supply Chain Disruptions'

2026-08-14 09:23:14,735 - WARNING - No response data generated; returning an empty DataFrame.

2026-08-14 09:23:14,738 - INFO - Starting process_response_by_company with 2 tasks...

2026-08-14 09:23:14,739 - INFO - Processing response summary for entity 'NVIDIA Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Market Access Limitations'

2026-08-14 09:23:14,741 - INFO - Processing response summary for entity 'NVIDIA Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Increased Costs'

2026-08-14 09:23:15,777 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-14 09:23:16,527 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  ## Final Output



  Transform the analysis results into professional, customizable reports. The system provides two distinct presentation styles, each optimized for different use cases and audiences.

  ### Report Customization Options







  Both report formats allow customization through multiple ranking criteria:







  **Sector-Wide Analysis**:



  - Identifies the most significant tariff risks across all companies



  - Ranks themes by media attention and document frequency



  - Provides executive summaries for each risk category







  **Company-Specific Analysis**:



  - **Most Reported Issue**: Highest media coverage and attention



  - **Biggest Risk**: Greatest potential financial impact



  - **Most Uncertain Issue**: Highest uncertainty scores and ambiguity







  Each company analysis includes extracted mitigation plans from official corporate communications, providing actionable intelligence for investment and risk management decisions.

  ### Report Format 1: Executive Summary Style







  This format prioritizes clarity and executive readability, focusing on the top risks per company across three key dimensions. Ideal for senior management briefings and board presentations.

In [15]:
from src.html_report import generate_html_report, prepare_data_report_0

# Extract report data for processing
df_by_theme = report.report_by_theme
df_by_company_with_responses = report.report_by_company

# Prepare data with executive summary formatting
top_by_theme, top_by_company = prepare_data_report_0(df_by_theme, df_by_company_with_responses)

# Generate executive-style HTML report
html_content = generate_html_report(top_by_theme, top_by_company, 'US Import Tariffs: Corporate Risk Impact Analysis')

# Save the executive report
report_filename = f'{output_dir}/tariffs_executive_report.html'
with open(report_filename, 'w') as file:
     file.write(html_content)

print(f"✅ Executive Report saved: {report_filename}")

✅ Executive Report saved: output/tariffs_executive_report.html

  #### Display Executive Report

In [16]:
display(HTML(html_content))

  ### Report Format 2: Detailed Analysis Version







  This format provides comprehensive risk analysis with extended company coverage and detailed risk breakdowns. Designed for analysts, portfolio managers, and risk management teams requiring in-depth insights.

In [17]:
from src.html_report import generate_html_report_v1, prepare_data_report_1

# Prepare data with detailed analysis formatting
top_by_theme, top_by_company = prepare_data_report_1(df_by_theme, df_by_company_with_responses)

# Generate detailed analysis HTML report
html_content_detailed = generate_html_report_v1(top_by_theme, top_by_company, 'US Import Tariffs: Comprehensive Risk Analysis')

# Save the detailed report
detailed_filename = f'{output_dir}/tariffs_detailed_analysis.html'
with open(detailed_filename, 'w') as file:
     file.write(html_content_detailed)

print(f"✅ Detailed Analysis Report saved: {detailed_filename}")

✅ Detailed Analysis Report saved: output/tariffs_detailed_analysis.html

  #### Display Detailed Analysis Report

In [18]:
display(HTML(html_content_detailed))

  ### Export Results for Further Analysis







  The generated data can be exported for integration with existing risk management systems, portfolio optimization tools, or compliance reporting workflows.

In [19]:
# Optional: Export structured data for external analysis
try:
    # Export the core datasets
    df_by_theme.to_csv(f'{output_dir}/tariffs_risks_by_theme.csv', index=False)
    df_by_company_with_responses.to_csv(f'{output_dir}/tariffs_risks_by_company.csv', index=False)
    
    print("✅ Data exported successfully:")
    print(f"   - Thematic analysis: {output_dir}/tariffs_risks_by_theme.csv")
    print(f"   - Company analysis: {output_dir}/tariffs_risks_by_company.csv")
    print(f"   - Executive report: {output_dir}/tariffs_executive_report.html")
    print(f"   - Detailed analysis: {output_dir}/tariffs_detailed_analysis.html")
    
except Exception as e:
    print(f"Warning: Export failed - {e}")

✅ Data exported successfully:
   - Thematic analysis: output/tariffs_risks_by_theme.csv
   - Company analysis: output/tariffs_risks_by_company.csv
   - Executive report: output/tariffs_executive_report.html
   - Detailed analysis: output/tariffs_detailed_analysis.html