## Deprecated SDK imports removed

This project no longer depends on `bigdata-client` or `bigdata-research-tools`. See **MIGRATION_NOTES.md** / **README.md** and [Thematic_Screener_CLI](../Thematic_Screener_CLI/) for the REST + `bigdata-smart-batching` + OpenAI pattern. Pass company CSVs (`RP_ENTITY_ID`, `COMPANY_NAME`) instead of watchlists.

  # US Tariffs: Risks & Strategies - Report Generator

  ## Automated Analysis of Trade Tariff Risks and Corporate Mitigation Strategies

  ## Why It Matters







  In an era of increasing trade tensions and evolving geopolitical landscapes, companies face unprecedented uncertainty around import tariffs and trade barriers. Understanding corporate exposure to tariff risks across global supply chains is critical for investment decisions, risk management, and strategic planning. Manual tracking of tariff impacts across multiple companies and markets is time-intensive and often incomplete.

  ## What It Does



  This workflow combines an OpenAI-generated risk taxonomy, Bigdata.com REST + `bigdata-smart-batching` search, and the `GenerateReport` class to systematically analyze corporate exposure to US import tariff risks. Designed for portfolio managers, risk analysts, and trade compliance professionals, it transforms scattered information from news, filings, and earnings calls into a detailed research report covering risk intelligence and mitigation strategies.

  ## How It Works



  The workflow integrates **hybrid semantic search**, **AI-powered risk taxonomies**, and **multi-source content analysis** to deliver:



  - **Automated Risk Taxonomy Creation**: Uses OpenAI to generate hierarchical risk categories specific to tariff impacts

  - **Cross-Source Intelligence Gathering**: Searches news articles, SEC filings, and earnings transcripts for relevant discussions

  - **AI-Powered Risk Classification**: Categorizes content into specific risk scenarios

  - **Corporate Response Extraction**: Identifies and summarizes company mitigation plans from official communications

  - **Customizable Report Generation**: Produces professional HTML reports ranked by Media Attention, Financial Impact, and Uncertainty

  ## A Real-World Use Case







 This cookbook demonstrates the complete end-to-end workflow through analyzing how US import tariffs impact major American companies. You'll see how the system transforms scattered tariff discussions across news, SEC filings, and earnings transcripts into structured risk assessments, complete with corporate response strategies and quantified exposure metrics for investment and risk management decisions.

  ## Setup and Imports

  ## Async Compatibility Setup



  **Run this cell first** - Required for Google Colab, Jupyter Notebooks, and VS Code with Jupyter extension:



  ### Why is this needed?



  Interactive environments (Colab, Jupyter) already have an asyncio event loop running. Several helpers in this notebook's `src/` package (labeling, summarization, response extraction) make async calls to OpenAI, and without `nest_asyncio` you'll get this error:



  ```

  RuntimeError: asyncio.run() cannot be called from a running event loop

  ```



  The `nest_asyncio.apply()` command patches this to allow nested event loops.



  💡 **Tip**: If you're unsure which environment you're in, just run the cell below - it won't hurt in any environment!

In [1]:
import datetime
start = datetime.datetime.now()

try:
    import asyncio
    asyncio.get_running_loop()
    import nest_asyncio; nest_asyncio.apply()
    print("✅ nest_asyncio applied")
except (RuntimeError, ImportError):
    print("✅ nest_asyncio not needed or not available")

✅ nest_asyncio applied

  ## Environment Setup







  The following cell configures the necessary path for the analysis

In [2]:
import os
import sys


current_dir = os.getcwd()
if current_dir not in sys.path:
    sys.path.append(current_dir)
print(f"✅ Local environment setup complete")

✅ Local environment setup complete

  ## Optional: Plotly Display Configuration







  For better visualization rendering, you can also set the Plotly renderer:

In [3]:
import plotly.io as pio

# Try to detect the environment and set appropriate renderer
try:
    # Check if we're in JupyterLab
    import os
    if 'JUPYTERHUB_SERVICE_PREFIX' in os.environ or 'JPY_SESSION_NAME' in os.environ:
        pio.renderers.default = 'jupyterlab'
        print("✅ Plotly configured for JupyterLab")
    else:
        # Default for VS Code, Jupyter Notebook, etc.
        pio.renderers.default = 'plotly_mimetype+notebook'
        print("✅ Plotly configured for Jupyter/VS Code")
except:
    # Fallback to a more universal renderer
    pio.renderers.default = 'notebook'
    print("✅ Plotly configured with fallback renderer")

✅ Plotly configured for Jupyter/VS Code

  ## Configure Output Directories







  Set up the directory structure where analysis results and reports will be saved.

In [4]:
# Define output file paths for our report
output_dir = "output"
os.makedirs(output_dir, exist_ok=True)

  ## Load Credentials

In [5]:
from dotenv import load_dotenv
from pathlib import Path

script_dir = Path(__file__).parent if '__file__' in globals() else Path.cwd()
load_dotenv(script_dir / '.env')

BIGDATA_API_KEY = os.getenv('BIGDATA_API_KEY')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

if not all([BIGDATA_API_KEY, OPENAI_API_KEY]):
    print("❌ Missing required environment variables")
    raise ValueError("Missing required environment variables. Check your .env file.")
else:
    print("✅ Credentials loaded from .env file")

✅ Credentials loaded from .env file

  ## Connecting to Bigdata







  Create a Bigdata object with your credentials.

In [6]:
# Bigdata.com access is now REST + bigdata-smart-batching, both authenticated
# directly with BIGDATA_API_KEY from the environment (loaded in the previous
# cell) -- there is no persistent SDK client object to construct anymore.
# See MIGRATION_PATTERNS.md / Thematic_Screener_CLI for the reference pattern.
os.environ.setdefault("BIGDATA_API_KEY", BIGDATA_API_KEY)
print("✅ Bigdata.com REST access ready (BIGDATA_API_KEY set)")

✅ Bigdata.com REST access ready (BIGDATA_API_KEY set)

  ## Import Required Libraries







  Import the core libraries needed for tariff risk analysis

In [7]:
from types import SimpleNamespace

from IPython.display import display, HTML
import pandas as pd

from src.bigdata_rest import load_universe, company_ids_from_universe
from src.mindmap.generate_trees import generate_themes_tree_dict, get_most_granular_elements
from src.mindmap.themes import print_tree
from src.search.content_retrieval import DataRetriever
from src.label.label_process import LabelProcessor
from src.report_generator import GenerateReport

print("✅ Core libraries imported (REST + bigdata-smart-batching + OpenAI pattern)")

✅ Core libraries imported (REST + bigdata-smart-batching + OpenAI pattern)

  ## Defining the Analysis Parameters



  - **Main Theme** (`main_theme`): The central risk scenario to analyze across companies

  - **Focus** (`focus`): Expert perspective for generating targeted risk taxonomies

  - **Company Universe** (`universe_df`): The set of companies to analyze, loaded from a CSV with `RP_ENTITY_ID` + `COMPANY_NAME` columns

  - **Model Selection** (`llm_model`): The AI model used for risk classification and summarization

  - **Time Period** (`start_date` and `end_date`): The date range for the analysis

  - **Frequency** (`freq`): The frequency of the date ranges to search over. Supported values:

     - `Y`: Yearly intervals.

     - `M`: Monthly intervals.

     - `W`: Weekly intervals.

     - `D`: Daily intervals. Defaults to `3M`.

  - **Document Limit** (`document_limit`): The maximum number of documents to return per query to Bigdata API.

  - **Batch Size** (`batch_size`): The number of entities to include in a single batched query.

  - **Rerank Threshold** (`rerank_threshold`): By setting this value, you’re enabling the cross-encoder which reranks the results and selects those whose relevance is above the percentile you specify (0.7 being the 70th percentile). More information on the re-ranker can be found [here](https://docs.bigdata.com/how-to-guides/rerank_search).

  - **Response From News** (`response_from_news`): Controls the `news_search_fallback` parameter. If `True`, when no response is found in transcripts/filings, the system uses News as fallback. In reports, fallback responses are annotated with `[From News]`. If `False`, missing responses show "No evidence of discussions found in Transcripts/Filings.". Default: `True`.

In [8]:
# ===== Customizable Parameters =====

from datetime import datetime, timedelta

# Company Universe: small slice (~5 companies) of the NASDAQ universe CSV
# bundled with Thematic_Screener_CLI (RP_ENTITY_ID + COMPANY_NAME), instead of
# a bigdata-client watchlist. Kept small to control API/LLM cost.
universe_path = "../Thematic_Screener_CLI/mag7.csv"
universe_df = load_universe(universe_path).reset_index(drop=True)
company_ids = company_ids_from_universe(universe_df)
print(f"✅ Company universe loaded: {len(universe_df)} companies")
display(universe_df)

# Main Analysis Theme
main_theme = 'US Import Tariffs Corporate Risk Impact Analysis'
focus = "Provide a detailed taxonomy of risks describing how new American import tariffs will impact worldwide companies, their operations and strategy."

# LLM Model Configuration (plain OpenAI model id, passed straight to the OpenAI client)
llm_model = "gpt-5.6-luna"

# Time Range Configuration -- kept to a ~30 day window to control API/LLM cost
end_date = "2025-08-13"
start_date = "2025-02-01"
freq = 'M'  # Monthly search frequency

# Enable/Disable Reranker
rerank_threshold = None

# Document Retrieval Limits (kept small to control OpenAI labeling/summary cost)
document_limit_news = 10
document_limit_filings = 5
batch_size = 1

# Toggle fallback to News for company responses
response_from_news = True

✅ Company universe loaded: 7 companies

  RP_ENTITY_ID         COMPANY_NAME
0       E09E2B         NVIDIA Corp.
1       D8442A           Apple Inc.
2       228D42      Microsoft Corp.
3       0157B1      Amazon.com Inc.
4       4A6F00        Alphabet Inc.
5       12E454  Meta Platforms Inc.
6       DD3BB1           Tesla Inc.

  ## Risk Analysis



  The first phase builds the risk taxonomy and retrieves/labels the News content that feeds the report generation phase (this replaces the deprecated `bigdata-research-tools` `RiskAnalyzer` class with local `src/` helpers built on REST + `bigdata-smart-batching` + OpenAI). This phase includes three critical steps that prepare the data for the report generation phase.

  ### Initialize Company Universe



  Sets up the company objects used for the risk discovery and taxonomy-driven search below:

  - **Automated Taxonomy Generation**: Creates a hierarchical structure of tariff-related risks

  - **Semantic Content Retrieval**: Searches news articles using the taxonomy's leaf summaries as queries

  - **Intelligent Content Labeling**: Categorizes found content into specific risk scenarios

In [9]:
# Build the company objects used for the News retrieval + labeling steps below.
# (GenerateReport builds these internally too, but we need the same objects
# here since retrieval/labeling for News happens before GenerateReport exists --
# this replaces RiskAnalyzer's internal entity resolution.)
id_to_name = dict(zip(universe_df["RP_ENTITY_ID"], universe_df["COMPANY_NAME"]))
list_entities = [SimpleNamespace(id=eid, name=name) for eid, name in id_to_name.items()]

print(f"✅ {len(list_entities)} companies ready for taxonomy-driven search: "
      f"{', '.join(e.name for e in list_entities)}")

✅ 7 companies ready for taxonomy-driven search: NVIDIA Corp., Apple Inc., Microsoft Corp., Amazon.com Inc., Alphabet Inc., Meta Platforms Inc., Tesla Inc.

  ### Generate Risk Taxonomy







  Create a comprehensive taxonomy that breaks down tariff risks into specific, analyzable categories such as supply chain disruption, pricing impacts, and market access challenges.

In [10]:
# Generate a compact risk taxonomy for the theme/focus via OpenAI
# (replaces RiskAnalyzer.create_taxonomy())
themes_tree_dict = generate_themes_tree_dict(main_theme, focus)
risk_tree = themes_tree_dict[main_theme]
terminal_labels = get_most_granular_elements(risk_tree, 'Label')
risk_summaries = get_most_granular_elements(risk_tree, 'Summary')

print(f"✅ Taxonomy generated with {len(terminal_labels)} leaf risk categories")
print_tree(risk_tree)

2026-08-27 14:30:49,270 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

✅ Taxonomy generated with 3 leaf risk categories
US Import Tariffs Corporate Risk Impact Analysis
├── │   Financial and Commercial Risks
├── │   Operational and Supply-Chain Risks
└──     Strategic, Legal, and Geopolitical Risks

  The taxonomy tree shows how tariff risks branch into specific sub-scenarios. Each terminal node represents a distinct risk category that will be used to classify and analyze news content.

  ### Retrieve Relevant Content







  Search news articles using the generated taxonomy to find discussions about tariff impacts across our company universe.

In [11]:
# Search news articles across the company universe using the taxonomy's leaf
# summaries as queries (replaces RiskAnalyzer.retrieve_results()).
data_retriever_news = DataRetriever(
    company_ids=company_ids,
    id_to_name=id_to_name,
    document_limit=document_limit_news,
    sortby="relevance",
    search_freq=freq,
    start_date_query=start_date,
    end_date_query=end_date,
)

df_sentences_semantic = data_retriever_news.retrieve(
    themes_tree_dict=themes_tree_dict,
    list_specific_themes=[main_theme],
    document_type="news",
)

if df_sentences_semantic is None:
    df_sentences_semantic = pd.DataFrame()

# Cost control: cap the number of chunks sent to OpenAI for labeling
df_sentences_semantic = df_sentences_semantic  # full retrieved set for labeling
print(f"✅ Retrieved {len(df_sentences_semantic)} news chunks (capped at {document_limit_news})")
df_sentences_semantic.head()

2026-08-27 14:30:49,291 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:30:49,291 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:30:49,291 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:30:49,292 - INFO - Loaded 1 companies from universe

2026-08-27 14:30:49,295 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:30:49,295 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 174 data points, 2482 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2482 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_3_volume), 3 basket(s)
2026-08-27 14:30:51,694 - INFO - Planning complete: 2,482 expected chunks in 3 baskets

2026-08-27 14:30:51,694 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:30:51,695 - INFO - Total maximum expected chunks: 49

2026-08-27 14:30:51,695 - INFO - Searching 3 baskets

2026-08-27 14:30:52,788 - INFO - Basket basket_1_high_20250404_20250502: Retrieved 18 documents with 18 chunks

2026-08-27 14:30:53,009 - INFO - Basket basket_2_high_20250503_20250813: Retrieved 14 documents with 14 chunks

2026-08-27 14:30:53,025 - INFO - Basket basket_0_high_20250201_20250403: Retrieved 16 documents with 16 chunks

2026-08-27 14:30:53,026 - INFO - First pass complete: 48 documents with 48 chunks

2026-08-27 14:30:53,026 - INFO - Search complete: 48 documents with 48 chunks retrieved in 1.33s

2026-08-27 14:30:53,027 - INFO - Deduplicated: 48 unique documents from 48 total (chunks merged)

2026-08-27 14:30:53,027 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:30:53,027 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:30:53,028 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:30:53,028 - INFO - Loaded 1 companies from universe

2026-08-27 14:30:53,028 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:30:53,029 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 177 data points, 2869 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2869 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_3_volume), 3 basket(s)
2026-08-27 14:30:55,083 - INFO - Planning complete: 2,869 expected chunks in 3 baskets

2026-08-27 14:30:55,084 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:30:55,084 - INFO - Total maximum expected chunks: 57

2026-08-27 14:30:55,085 - INFO - Searching 3 baskets

2026-08-27 14:30:56,054 - INFO - Basket basket_0_high_20250201_20250408: Retrieved 19 documents with 19 chunks

2026-08-27 14:30:56,288 - INFO - Basket basket_1_high_20250409_20250507: Retrieved 18 documents with 19 chunks

2026-08-27 14:30:56,422 - INFO - Basket basket_2_high_20250508_20250813: Retrieved 18 documents with 18 chunks

2026-08-27 14:30:56,422 - INFO - First pass complete: 55 documents with 56 chunks

2026-08-27 14:30:56,423 - INFO - Search complete: 55 documents with 56 chunks retrieved in 1.34s

2026-08-27 14:30:56,423 - INFO - Deduplicated: 55 unique documents from 55 total (chunks merged)

2026-08-27 14:30:56,423 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:30:56,423 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:30:56,423 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:30:56,423 - INFO - Loaded 1 companies from universe

2026-08-27 14:30:56,424 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:30:56,424 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 163 data points, 1200 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1169 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_2_volume), 3 basket(s)
2026-08-27 14:30:58,257 - INFO - Planning complete: 1,200 expected chunks in 3 baskets

2026-08-27 14:30:58,257 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:30:58,257 - INFO - Total maximum expected chunks: 24

2026-08-27 14:30:58,258 - INFO - Searching 3 baskets

2026-08-27 14:30:59,034 - INFO - Basket basket_2_high_20250814_20250814: Retrieved 5 documents with 5 chunks

2026-08-27 14:30:59,115 - INFO - Basket basket_1_high_20250414_20250813: Retrieved 10 documents with 11 chunks

2026-08-27 14:30:59,167 - INFO - Basket basket_0_high_20250201_20250413: Retrieved 12 documents with 12 chunks

2026-08-27 14:30:59,168 - INFO - First pass complete: 27 documents with 28 chunks

2026-08-27 14:30:59,168 - INFO - Search complete: 27 documents with 28 chunks retrieved in 0.91s

2026-08-27 14:30:59,168 - INFO - Deduplicated: 27 unique documents from 27 total (chunks merged)

2026-08-27 14:30:59,169 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:30:59,170 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:30:59,170 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:30:59,170 - INFO - Loaded 1 companies from universe

2026-08-27 14:30:59,170 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:30:59,170 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 190 data points, 6284 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 6884 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 5 period(s) (split_7_volume), 5 basket(s)
2026-08-27 14:31:00,753 - INFO - Planning complete: 6,284 expected chunks in 5 baskets

2026-08-27 14:31:00,753 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:00,754 - INFO - Total maximum expected chunks: 125

2026-08-27 14:31:00,754 - INFO - Searching 5 baskets

2026-08-27 14:31:01,626 - INFO - Basket basket_4_high_20250811_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:02,205 - INFO - Basket basket_0_high_20250201_20250403: Retrieved 19 documents with 20 chunks

2026-08-27 14:31:02,290 - INFO - Basket basket_3_high_20250601_20250810: Retrieved 16 documents with 17 chunks

2026-08-27 14:31:02,323 - INFO - Basket basket_2_high_20250503_20250531: Retrieved 27 documents with 28 chunks

2026-08-27 14:31:02,545 - INFO - Basket basket_1_high_20250404_20250502: Retrieved 55 documents with 57 chunks

2026-08-27 14:31:02,546 - INFO - First pass complete: 118 documents with 123 chunks

2026-08-27 14:31:02,546 - INFO - Search complete: 118 documents with 123 chunks retrieved in 1.79s

2026-08-27 14:31:02,547 - INFO - Deduplicated: 118 unique documents from 118 total (chunks merged)

2026-08-27 14:31:02,547 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:31:02,547 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:02,547 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:02,547 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:02,548 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:02,548 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 190 data points, 8900 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 8981 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 5 period(s) (split_9_volume), 5 basket(s)
2026-08-27 14:31:04,305 - INFO - Planning complete: 8,900 expected chunks in 5 baskets

2026-08-27 14:31:04,306 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:04,307 - INFO - Total maximum expected chunks: 178

2026-08-27 14:31:04,307 - INFO - Searching 5 baskets

2026-08-27 14:31:05,231 - INFO - Basket basket_4_high_20250730_20250813: Retrieved 12 documents with 12 chunks

2026-08-27 14:31:05,285 - INFO - Basket basket_0_high_20250201_20250403: Retrieved 22 documents with 24 chunks

2026-08-27 14:31:05,341 - INFO - Basket basket_3_high_20250601_20250729: Retrieved 19 documents with 19 chunks

2026-08-27 14:31:05,410 - INFO - Basket basket_2_high_20250503_20250531: Retrieved 31 documents with 36 chunks

2026-08-27 14:31:05,990 - INFO - Basket basket_1_high_20250404_20250502: Retrieved 71 documents with 84 chunks

2026-08-27 14:31:05,991 - INFO - First pass complete: 155 documents with 175 chunks

2026-08-27 14:31:05,991 - INFO - Search complete: 155 documents with 175 chunks retrieved in 1.68s

2026-08-27 14:31:05,991 - INFO - Deduplicated: 155 unique documents from 155 total (chunks merged)

2026-08-27 14:31:05,992 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:31:05,992 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:05,992 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:05,992 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:05,992 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:05,993 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 187 data points, 3716 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3716 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 4 period(s) (split_4_volume), 4 basket(s)
2026-08-27 14:31:07,565 - INFO - Planning complete: 3,716 expected chunks in 4 baskets

2026-08-27 14:31:07,565 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:07,565 - INFO - Total maximum expected chunks: 74

2026-08-27 14:31:07,565 - INFO - Searching 4 baskets

2026-08-27 14:31:08,436 - INFO - Basket basket_2_high_20250506_20250610: Retrieved 17 documents with 18 chunks

2026-08-27 14:31:08,489 - INFO - Basket basket_1_high_20250407_20250505: Retrieved 23 documents with 24 chunks

2026-08-27 14:31:08,592 - INFO - Basket basket_3_high_20250611_20250813: Retrieved 12 documents with 12 chunks

2026-08-27 14:31:08,732 - INFO - Basket basket_0_high_20250201_20250406: Retrieved 17 documents with 19 chunks

2026-08-27 14:31:08,733 - INFO - First pass complete: 69 documents with 73 chunks

2026-08-27 14:31:08,733 - INFO - Search complete: 69 documents with 73 chunks retrieved in 1.17s

2026-08-27 14:31:08,734 - INFO - Deduplicated: 69 unique documents from 69 total (chunks merged)

2026-08-27 14:31:08,735 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:31:08,735 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:08,735 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:08,735 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:08,735 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:08,735 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 166 data points, 1462 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1690 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_2_volume), 3 basket(s)
2026-08-27 14:31:10,209 - INFO - Planning complete: 1,462 expected chunks in 3 baskets

2026-08-27 14:31:10,209 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:10,210 - INFO - Total maximum expected chunks: 29

2026-08-27 14:31:10,210 - INFO - Searching 3 baskets

2026-08-27 14:31:10,964 - INFO - Basket basket_2_high_20250812_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:11,080 - INFO - Basket basket_0_high_20250201_20250422: Retrieved 13 documents with 14 chunks

2026-08-27 14:31:11,106 - INFO - Basket basket_1_high_20250423_20250811: Retrieved 14 documents with 14 chunks

2026-08-27 14:31:11,107 - INFO - First pass complete: 28 documents with 29 chunks

2026-08-27 14:31:11,107 - INFO - Search complete: 28 documents with 29 chunks retrieved in 0.90s

2026-08-27 14:31:11,107 - INFO - Deduplicated: 28 unique documents from 28 total (chunks merged)

2026-08-27 14:31:11,108 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:31:11,108 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:11,108 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:11,108 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:11,108 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:11,108 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 148 data points, 1162 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1162 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_2_volume), 3 basket(s)
2026-08-27 14:31:12,500 - INFO - Planning complete: 1,162 expected chunks in 3 baskets

2026-08-27 14:31:12,500 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:12,500 - INFO - Total maximum expected chunks: 23

2026-08-27 14:31:12,500 - INFO - Searching 3 baskets

2026-08-27 14:31:13,207 - INFO - Basket basket_2_high_20250809_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:13,321 - INFO - Basket basket_0_high_20250201_20250414: Retrieved 11 documents with 11 chunks

2026-08-27 14:31:13,663 - INFO - Basket basket_1_high_20250415_20250808: Retrieved 11 documents with 11 chunks

2026-08-27 14:31:13,664 - INFO - First pass complete: 23 documents with 23 chunks

2026-08-27 14:31:13,664 - INFO - Search complete: 23 documents with 23 chunks retrieved in 1.16s

2026-08-27 14:31:13,664 - INFO - Deduplicated: 23 unique documents from 23 total (chunks merged)

2026-08-27 14:31:13,665 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:31:13,665 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:13,665 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:13,665 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:13,665 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:13,666 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 178 data points, 1353 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1353 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_2_volume), 3 basket(s)
2026-08-27 14:31:15,922 - INFO - Planning complete: 1,353 expected chunks in 3 baskets

2026-08-27 14:31:15,923 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:15,924 - INFO - Total maximum expected chunks: 27

2026-08-27 14:31:15,924 - INFO - Searching 3 baskets

2026-08-27 14:31:16,709 - INFO - Basket basket_2_high_20250813_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:16,825 - INFO - Basket basket_0_high_20250201_20250424: Retrieved 12 documents with 13 chunks

2026-08-27 14:31:17,050 - INFO - Basket basket_1_high_20250425_20250812: Retrieved 13 documents with 13 chunks

2026-08-27 14:31:17,050 - INFO - First pass complete: 26 documents with 27 chunks

2026-08-27 14:31:17,050 - INFO - Search complete: 26 documents with 27 chunks retrieved in 1.13s

2026-08-27 14:31:17,051 - INFO - Deduplicated: 26 unique documents from 26 total (chunks merged)

2026-08-27 14:31:17,053 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:31:17,053 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:17,053 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:17,053 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:17,053 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:17,054 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 180 data points, 2490 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2717 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_3_volume), 3 basket(s)
2026-08-27 14:31:18,905 - INFO - Planning complete: 2,490 expected chunks in 3 baskets

2026-08-27 14:31:18,905 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:18,905 - INFO - Total maximum expected chunks: 49

2026-08-27 14:31:18,905 - INFO - Searching 3 baskets

2026-08-27 14:31:19,731 - INFO - Basket basket_1_high_20250411_20250509: Retrieved 15 documents with 16 chunks

2026-08-27 14:31:19,785 - INFO - Basket basket_0_high_20250201_20250410: Retrieved 16 documents with 17 chunks

2026-08-27 14:31:19,887 - INFO - Basket basket_2_high_20250510_20250813: Retrieved 15 documents with 15 chunks

2026-08-27 14:31:19,888 - INFO - First pass complete: 46 documents with 48 chunks

2026-08-27 14:31:19,888 - INFO - Search complete: 46 documents with 48 chunks retrieved in 0.98s

2026-08-27 14:31:19,889 - INFO - Deduplicated: 46 unique documents from 46 total (chunks merged)

2026-08-27 14:31:19,889 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:31:19,889 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:19,890 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:19,890 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:19,890 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:19,890 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 189 data points, 3784 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3811 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 4 period(s) (split_4_volume), 4 basket(s)
2026-08-27 14:31:21,506 - INFO - Planning complete: 3,784 expected chunks in 4 baskets

2026-08-27 14:31:21,507 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:21,507 - INFO - Total maximum expected chunks: 75

2026-08-27 14:31:21,507 - INFO - Searching 4 baskets

2026-08-27 14:31:22,486 - INFO - Basket basket_3_high_20250726_20250813: Retrieved 3 documents with 3 chunks

2026-08-27 14:31:22,502 - INFO - Basket basket_2_high_20250507_20250725: Retrieved 18 documents with 18 chunks

2026-08-27 14:31:22,541 - INFO - Basket basket_0_high_20250201_20250407: Retrieved 17 documents with 19 chunks

2026-08-27 14:31:22,678 - INFO - Basket basket_1_high_20250408_20250506: Retrieved 30 documents with 34 chunks

2026-08-27 14:31:22,678 - INFO - First pass complete: 68 documents with 74 chunks

2026-08-27 14:31:22,678 - INFO - Search complete: 68 documents with 74 chunks retrieved in 1.17s

2026-08-27 14:31:22,679 - INFO - Deduplicated: 68 unique documents from 68 total (chunks merged)

2026-08-27 14:31:22,679 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:31:22,679 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:22,679 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:22,679 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:22,680 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:22,680 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 186 data points, 1941 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1979 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_2_volume), 3 basket(s)
2026-08-27 14:31:24,209 - INFO - Planning complete: 1,941 expected chunks in 3 baskets

2026-08-27 14:31:24,209 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:24,209 - INFO - Total maximum expected chunks: 38

2026-08-27 14:31:24,209 - INFO - Searching 3 baskets

2026-08-27 14:31:24,902 - INFO - Basket basket_2_high_20250814_20250814: Retrieved 5 documents with 5 chunks

2026-08-27 14:31:25,147 - INFO - Basket basket_1_high_20250425_20250813: Retrieved 19 documents with 19 chunks

2026-08-27 14:31:25,148 - INFO - Basket basket_0_high_20250201_20250424: Retrieved 18 documents with 19 chunks

2026-08-27 14:31:25,149 - INFO - First pass complete: 42 documents with 43 chunks

2026-08-27 14:31:25,149 - INFO - Search complete: 42 documents with 43 chunks retrieved in 0.94s

2026-08-27 14:31:25,150 - INFO - Deduplicated: 42 unique documents from 42 total (chunks merged)

2026-08-27 14:31:25,151 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:31:25,151 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:25,151 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:25,151 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:25,151 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:25,151 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 186 data points, 2167 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2167 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 4 period(s) (split_3_volume), 4 basket(s)
2026-08-27 14:31:26,585 - INFO - Planning complete: 2,167 expected chunks in 4 baskets

2026-08-27 14:31:26,585 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:26,585 - INFO - Total maximum expected chunks: 43

2026-08-27 14:31:26,585 - INFO - Searching 4 baskets

2026-08-27 14:31:27,375 - INFO - Basket basket_3_high_20250813_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:27,464 - INFO - Basket basket_1_high_20250309_20250424: Retrieved 13 documents with 14 chunks

2026-08-27 14:31:27,525 - INFO - Basket basket_0_high_20250201_20250308: Retrieved 13 documents with 14 chunks

2026-08-27 14:31:27,548 - INFO - Basket basket_2_high_20250425_20250812: Retrieved 13 documents with 13 chunks

2026-08-27 14:31:27,549 - INFO - First pass complete: 40 documents with 42 chunks

2026-08-27 14:31:27,549 - INFO - Search complete: 40 documents with 42 chunks retrieved in 0.96s

2026-08-27 14:31:27,549 - INFO - Deduplicated: 40 unique documents from 40 total (chunks merged)

2026-08-27 14:31:27,549 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:31:27,550 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:27,550 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:27,550 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:27,550 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:27,550 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 179 data points, 2485 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2466 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_3_volume), 3 basket(s)
2026-08-27 14:31:28,971 - INFO - Planning complete: 2,485 expected chunks in 3 baskets

2026-08-27 14:31:28,972 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:28,972 - INFO - Total maximum expected chunks: 49

2026-08-27 14:31:28,972 - INFO - Searching 3 baskets

2026-08-27 14:31:29,850 - INFO - Basket basket_2_high_20250429_20250813: Retrieved 10 documents with 10 chunks

2026-08-27 14:31:29,866 - INFO - Basket basket_0_high_20250201_20250303: Retrieved 22 documents with 22 chunks

2026-08-27 14:31:29,893 - INFO - Basket basket_1_high_20250304_20250428: Retrieved 14 documents with 16 chunks

2026-08-27 14:31:29,893 - INFO - First pass complete: 46 documents with 48 chunks

2026-08-27 14:31:29,893 - INFO - Search complete: 46 documents with 48 chunks retrieved in 0.92s

2026-08-27 14:31:29,893 - INFO - Deduplicated: 46 unique documents from 46 total (chunks merged)

2026-08-27 14:31:29,894 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:31:29,894 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:29,894 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:29,894 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:29,894 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:29,894 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 192 data points, 2736 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2795 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 4 period(s) (split_3_volume), 4 basket(s)
2026-08-27 14:31:31,525 - INFO - Planning complete: 2,736 expected chunks in 4 baskets

2026-08-27 14:31:31,526 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:31,526 - INFO - Total maximum expected chunks: 54

2026-08-27 14:31:31,526 - INFO - Searching 4 baskets

2026-08-27 14:31:32,426 - INFO - Basket basket_0_high_20250201_20250306: Retrieved 18 documents with 18 chunks

2026-08-27 14:31:32,435 - INFO - Basket basket_1_high_20250307_20250430: Retrieved 15 documents with 17 chunks

2026-08-27 14:31:32,595 - INFO - Basket basket_3_high_20250812_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:32,687 - INFO - Basket basket_2_high_20250501_20250811: Retrieved 17 documents with 17 chunks

2026-08-27 14:31:32,687 - INFO - First pass complete: 51 documents with 53 chunks

2026-08-27 14:31:32,687 - INFO - Search complete: 51 documents with 53 chunks retrieved in 1.16s

2026-08-27 14:31:32,688 - INFO - Deduplicated: 51 unique documents from 51 total (chunks merged)

2026-08-27 14:31:32,689 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:31:32,689 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:32,689 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:32,689 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:32,689 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:32,690 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 170 data points, 1479 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1479 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_2_volume), 3 basket(s)
2026-08-27 14:31:34,306 - INFO - Planning complete: 1,479 expected chunks in 3 baskets

2026-08-27 14:31:34,306 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:34,306 - INFO - Total maximum expected chunks: 29

2026-08-27 14:31:34,306 - INFO - Searching 3 baskets

2026-08-27 14:31:35,006 - INFO - Basket basket_2_high_20250812_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:35,127 - INFO - Basket basket_0_high_20250201_20250420: Retrieved 13 documents with 14 chunks

2026-08-27 14:31:35,249 - INFO - Basket basket_1_high_20250421_20250811: Retrieved 14 documents with 14 chunks

2026-08-27 14:31:35,249 - INFO - First pass complete: 28 documents with 29 chunks

2026-08-27 14:31:35,249 - INFO - Search complete: 28 documents with 29 chunks retrieved in 0.94s

2026-08-27 14:31:35,249 - INFO - Deduplicated: 28 unique documents from 28 total (chunks merged)

2026-08-27 14:31:35,250 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:31:35,250 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:35,250 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:35,250 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:35,250 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:35,250 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 161 data points, 1251 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1268 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_2_volume), 3 basket(s)
2026-08-27 14:31:36,730 - INFO - Planning complete: 1,251 expected chunks in 3 baskets

2026-08-27 14:31:36,730 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:36,730 - INFO - Total maximum expected chunks: 25

2026-08-27 14:31:36,731 - INFO - Searching 3 baskets

2026-08-27 14:31:37,416 - INFO - Basket basket_2_high_20250808_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:37,507 - INFO - Basket basket_1_high_20250422_20250807: Retrieved 11 documents with 11 chunks

2026-08-27 14:31:37,594 - INFO - Basket basket_0_high_20250201_20250421: Retrieved 12 documents with 13 chunks

2026-08-27 14:31:37,595 - INFO - First pass complete: 24 documents with 25 chunks

2026-08-27 14:31:37,595 - INFO - Search complete: 24 documents with 25 chunks retrieved in 0.86s

2026-08-27 14:31:37,595 - INFO - Deduplicated: 24 unique documents from 24 total (chunks merged)

2026-08-27 14:31:37,595 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:31:37,595 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:37,596 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:37,596 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:37,596 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:37,596 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 186 data points, 1450 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 1489 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_2_volume), 3 basket(s)
2026-08-27 14:31:39,242 - INFO - Planning complete: 1,450 expected chunks in 3 baskets

2026-08-27 14:31:39,243 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:39,243 - INFO - Total maximum expected chunks: 29

2026-08-27 14:31:39,243 - INFO - Searching 3 baskets

2026-08-27 14:31:39,978 - INFO - Basket basket_2_high_20250807_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:31:40,082 - INFO - Basket basket_1_high_20250424_20250806: Retrieved 13 documents with 13 chunks

2026-08-27 14:31:40,183 - INFO - Basket basket_0_high_20250201_20250423: Retrieved 13 documents with 14 chunks

2026-08-27 14:31:40,184 - INFO - First pass complete: 27 documents with 28 chunks

2026-08-27 14:31:40,184 - INFO - Search complete: 27 documents with 28 chunks retrieved in 0.94s

2026-08-27 14:31:40,185 - INFO - Deduplicated: 27 unique documents from 27 total (chunks merged)

2026-08-27 14:31:40,186 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:31:40,186 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:40,187 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:40,187 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:40,187 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:40,187 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 188 data points, 4826 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 5207 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 5 period(s) (split_6_volume), 5 basket(s)
2026-08-27 14:31:41,703 - INFO - Planning complete: 4,826 expected chunks in 5 baskets

2026-08-27 14:31:41,703 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:41,703 - INFO - Total maximum expected chunks: 96

2026-08-27 14:31:41,703 - INFO - Searching 5 baskets

2026-08-27 14:31:42,712 - INFO - Basket basket_0_high_20250201_20250313: Retrieved 16 documents with 16 chunks

2026-08-27 14:31:42,770 - INFO - Basket basket_3_high_20250511_20250725: Retrieved 14 documents with 16 chunks

2026-08-27 14:31:42,919 - INFO - Basket basket_1_high_20250314_20250411: Retrieved 38 documents with 38 chunks

2026-08-27 14:31:43,038 - INFO - Basket basket_2_high_20250412_20250510: Retrieved 22 documents with 23 chunks

2026-08-27 14:31:43,490 - INFO - Basket basket_4_high_20250726_20250813: Retrieved 2 documents with 2 chunks

2026-08-27 14:31:43,491 - INFO - First pass complete: 92 documents with 95 chunks

2026-08-27 14:31:43,491 - INFO - Search complete: 92 documents with 95 chunks retrieved in 1.79s

2026-08-27 14:31:43,491 - INFO - Deduplicated: 92 unique documents from 92 total (chunks merged)

2026-08-27 14:31:43,491 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:31:43,491 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:43,491 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:43,492 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:43,492 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:43,492 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 191 data points, 5421 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 5421 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 5 period(s) (split_6_volume), 5 basket(s)
2026-08-27 14:31:44,997 - INFO - Planning complete: 5,421 expected chunks in 5 baskets

2026-08-27 14:31:44,997 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:44,997 - INFO - Total maximum expected chunks: 108

2026-08-27 14:31:44,997 - INFO - Searching 5 baskets

2026-08-27 14:31:45,931 - INFO - Basket basket_2_high_20250411_20250509: Retrieved 23 documents with 24 chunks

2026-08-27 14:31:46,008 - INFO - Basket basket_0_high_20250201_20250312: Retrieved 18 documents with 18 chunks

2026-08-27 14:31:46,067 - INFO - Basket basket_3_high_20250510_20250721: Retrieved 15 documents with 17 chunks

2026-08-27 14:31:46,183 - INFO - Basket basket_4_high_20250722_20250813: Retrieved 4 documents with 4 chunks

2026-08-27 14:31:46,292 - INFO - Basket basket_1_high_20250313_20250410: Retrieved 40 documents with 43 chunks

2026-08-27 14:31:46,292 - INFO - First pass complete: 100 documents with 106 chunks

2026-08-27 14:31:46,293 - INFO - Search complete: 100 documents with 106 chunks retrieved in 1.30s

2026-08-27 14:31:46,293 - INFO - Deduplicated: 100 unique documents from 100 total (chunks merged)

2026-08-27 14:31:46,293 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:31:46,293 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:31:46,294 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:31:46,294 - INFO - Loaded 1 companies from universe

2026-08-27 14:31:46,294 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:31:46,294 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0


Pre-computing volume time series for 1 groups exceeding 1000 chunks (outer pool_workers=1, shared rate limiter)...

    Group 0 (1 companies): 185 data points, 2574 total chunks
  Pre-computed volume for 1/1 groups

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 2574 total chunks, bucket=high
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
    Group 0: using pre-computed volume data
  Group 0: 3 period(s) (split_3_volume), 3 basket(s)
2026-08-27 14:31:47,721 - INFO - Planning complete: 2,574 expected chunks in 3 baskets

2026-08-27 14:31:47,721 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:31:47,721 - INFO - Total maximum expected chunks: 51

2026-08-27 14:31:47,721 - INFO - Searching 3 baskets

2026-08-27 14:31:48,502 - INFO - Basket basket_2_high_20250420_20250813: Retrieved 14 documents with 15 chunks

2026-08-27 14:31:48,623 - INFO - Basket basket_1_high_20250322_20250419: Retrieved 18 documents with 18 chunks

2026-08-27 14:31:49,084 - INFO - Basket basket_0_high_20250201_20250321: Retrieved 17 documents with 17 chunks

2026-08-27 14:31:49,085 - INFO - First pass complete: 49 documents with 50 chunks

2026-08-27 14:31:49,085 - INFO - Search complete: 49 documents with 50 chunks retrieved in 1.36s

2026-08-27 14:31:49,086 - INFO - Deduplicated: 49 unique documents from 49 total (chunks merged)

✅ Retrieved 1223 news chunks (capped at 10)

,document_id,headline,timestamp,url,source_id,source_name,chunk_text,text,masked_text,relevance,sentiment,entity_id,entity_ids,entity_name,query,document_type,theme,entity_searched_id,entity_searched_name
0,8AF5DC8E61FEC05F6246BFBCE1DB3BEE,'Dark Days' Likely Ahead For Tech Firms as Tar...,2025-04-04T15:19:17,,9D69F1,MT Newswires,"Earlier this year, Washington imposed tariffs ...","Earlier this year, Washington imposed tariffs ...","Earlier this year, Washington imposed tariffs ...",0.289953,-0.78,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.
1,BAD5EA33E54C61E9D0CDA15BF7304747,Huawei Moves Ratchet Up Nvidia's Stakes In The...,2025-05-01T15:58:56,https://www.forbes.com/sites/rscottraynovich/2...,22AC8B,Forbes.com,"Shifting Export Restrictions\nMeanwhile, U.S. ...","Shifting Export Restrictions\nMeanwhile, U.S. ...","Shifting Export Restrictions\nMeanwhile, U.S. ...",0.270230,-0.71,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.
2,A23CE52DA7BA1D93026FCB999657CCD4,Trump Tariff Strategy Creates 'Self-Inflicted ...,2025-04-08T18:16:34,https://www.benzinga.com/node/44698325?utm_cam...,5A5702,Benzinga,Also Read: Wall Street Soars As Trump Teases T...,Also Read: Wall Street Soars As Trump Teases T...,Also Read: Wall Street Soars As Trump Teases T...,0.240285,-0.37,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.
3,A161B914898BDE0A5862020D9EB650A7,Research Alert: Apple And Semis Not Directly E...,2025-04-04T15:25:08,,9D69F1,MT Newswires,"11:25 AM EDT, 04/04/2025 (MT Newswires) -- CFR...","11:25 AM EDT, 04/04/2025 (MT Newswires) -- CFR...","11:25 AM EDT, 04/04/2025 (MT Newswires) -- CFR...",0.230197,-0.56,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.
4,AEC4A47D33FBACC1F2F0C1178482C7E0,Trump-China trade war: Which US companies coul...,2025-04-15T15:37:15,https://www.aljazeera.com/news/2025/4/15/trump...,881677,Al Jazeera,"Tech companies, fashion firms and agribusiness...","Tech companies, fashion firms and agribusiness...","Tech companies, fashion firms and agribusiness...",0.223652,-0.60,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.

  ### Labeling



  Use AI to analyze each news excerpt and categorize it into the appropriate risk scenarios. This creates structured data from unstructured news content.

In [12]:
# Classify each retrieved news excerpt into a risk category using OpenAI
# (replaces RiskAnalyzer.label_search_results()).
label_processor = LabelProcessor(
    list_entities=list_entities,
    themes_tree_dict=themes_tree_dict,
    list_specific_themes=[main_theme],
    api_key=OPENAI_API_KEY,
)

if df_sentences_semantic.empty:
    df_labeled = pd.DataFrame()
    print("⚠️ No news content retrieved for this window; skipping labeling.")
else:
    df_labeled = label_processor.run_label_process(df_sentences=df_sentences_semantic)
    if df_labeled is None:
        df_labeled = pd.DataFrame()
    print(f"✅ Labeled {len(df_labeled)} news excerpts")

df_labeled.head()

2026-08-27 14:31:50,985 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,012 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,015 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,042 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,143 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,183 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,186 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,188 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,189 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,226 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,231 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,249 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,287 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,292 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,300 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,315 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,322 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,336 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,339 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,358 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,359 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,379 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,383 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,395 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,400 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,412 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,415 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,416 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,419 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,425 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,429 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,448 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,468 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,482 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,484 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,499 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,509 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,510 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,511 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,522 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,547 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,560 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,567 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,571 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,574 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,575 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,575 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,578 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,583 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,614 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,621 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,627 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,628 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,633 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,653 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,654 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,671 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,676 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,678 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,681 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,681 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,691 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,693 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,699 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,704 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,718 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,720 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,732 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,753 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,758 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,760 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,788 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,795 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,801 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,843 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,846 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,848 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,878 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,908 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,914 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,915 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,927 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,937 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,967 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:51,980 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,007 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,036 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,080 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,083 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,084 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,132 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,136 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,147 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,200 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,234 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,264 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,280 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,305 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,317 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,360 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,432 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,437 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,444 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,452 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,471 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,479 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,508 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,520 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,631 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,667 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,729 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,799 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,834 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,903 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,910 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:52,933 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,010 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,095 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,147 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,233 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,350 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,372 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,651 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,687 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,736 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,793 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,818 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,867 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,902 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:53,957 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:54,237 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:54,980 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 132 requests in 5.87 seconds.

2026-08-27 14:31:57,293 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,421 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,440 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,496 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,512 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,531 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,539 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,567 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,608 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,641 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,648 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,653 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,685 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,689 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,692 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,717 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,721 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,732 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,735 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,772 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,792 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,816 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,818 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,824 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,833 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,845 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,855 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,858 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,861 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,863 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,870 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,872 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,874 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,876 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,886 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,894 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,896 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,898 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,900 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,912 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,931 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,934 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,950 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,956 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,960 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,970 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:57,982 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,021 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,024 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,027 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,031 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,034 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,044 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,072 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,076 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,080 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,086 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,092 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,094 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,096 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,098 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,099 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,101 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,103 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,105 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,113 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,120 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,131 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,132 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,134 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,146 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,147 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,149 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,155 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,158 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,161 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,162 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,164 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,169 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,171 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,172 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,176 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,185 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,188 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,194 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,195 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,200 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,203 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,207 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,213 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,216 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,218 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,220 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,222 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,227 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,231 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,242 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,244 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,246 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,247 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,249 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,250 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,250 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,251 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,253 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,267 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,269 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,270 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,271 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,272 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,273 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,275 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,280 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,283 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,294 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,297 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,302 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,303 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,304 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,312 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,314 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,327 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,329 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,331 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,332 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,334 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,336 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,337 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,339 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,342 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,345 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,349 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,351 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,353 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,363 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,375 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,384 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,386 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,401 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,403 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,411 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,412 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,424 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,427 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,433 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,436 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,440 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,442 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,446 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,447 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,453 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,467 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,471 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,479 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,484 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,487 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,489 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,495 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,498 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,500 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,506 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,508 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,510 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,512 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,514 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,516 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,522 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,525 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,533 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,540 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,548 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,550 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,554 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,558 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,564 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,567 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,573 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,578 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,586 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,588 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,597 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,607 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,620 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,632 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,634 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,636 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,638 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,639 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,646 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,648 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,653 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,656 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,663 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,692 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,694 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,696 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,705 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,707 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,716 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,717 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,722 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,726 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,728 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,739 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,743 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,773 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,777 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,779 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,793 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,803 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,806 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,809 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,814 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,820 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,831 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,879 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,881 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,894 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,916 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,923 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,926 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,928 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,944 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,946 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,965 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,968 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,971 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,977 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,980 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,982 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:58,984 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,014 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,057 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,074 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,077 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,081 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,085 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,092 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,097 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,099 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,101 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,104 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,109 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,123 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,131 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,134 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,136 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,140 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,150 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,151 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,161 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,162 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,179 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,182 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,184 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,189 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,191 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,219 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,238 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,242 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,245 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,247 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,249 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,251 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,260 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,266 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,283 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,306 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,310 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,312 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,313 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,323 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,340 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,349 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,359 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,370 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,393 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,402 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,410 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,421 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,431 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,442 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,447 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,485 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,488 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,521 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,542 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,577 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,581 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,603 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,613 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,630 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,663 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,668 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,692 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,706 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,716 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,727 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,745 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,758 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,760 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,762 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,777 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,786 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,793 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,798 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,802 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,834 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,836 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,849 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,853 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,855 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,905 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,911 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,915 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,922 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,930 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:31:59,957 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,020 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,039 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,042 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,060 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,069 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,071 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,126 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,155 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,157 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,224 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,251 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,271 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,300 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,306 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,350 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,355 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,358 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,360 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,390 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,395 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,397 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,406 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,419 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,436 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,456 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,523 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,543 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,564 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,574 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,624 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,635 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,667 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,683 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,753 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,805 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,828 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,844 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,891 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,913 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,926 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:00,981 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:01,068 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:01,115 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:01,375 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:01,549 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:01,758 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:01,932 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:02,230 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:02,387 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:03,213 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:03,978 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:05,806 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:06,338 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 371 requests in 11.36 seconds.

2026-08-27 14:32:08,338 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,374 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,471 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,523 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,547 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,558 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,617 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,632 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,642 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,644 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,702 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,709 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,724 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,739 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,743 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,746 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,748 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,762 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,770 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,842 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,871 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,938 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,940 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,951 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,958 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:08,962 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,014 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,048 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,055 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,067 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,091 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,096 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,107 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,109 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,113 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,114 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,120 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,135 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,142 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,190 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,199 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,238 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,242 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,359 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,388 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,429 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,443 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,488 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,505 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,560 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,586 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,622 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,646 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,651 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,689 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,712 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,784 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,802 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,870 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:09,910 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,040 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,099 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,167 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,169 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,267 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,288 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,780 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,849 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:10,939 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:11,051 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:11,146 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:11,191 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:11,407 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:11,440 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:11,614 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:11,714 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:11,866 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:13,365 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:16,008 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 79 requests in 9.66 seconds.

2026-08-27 14:32:17,965 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,132 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,216 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,222 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,251 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,254 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,259 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,293 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,301 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,323 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,332 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,335 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,373 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,377 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,381 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,385 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,390 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,410 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,428 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,431 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,437 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,460 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,471 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,493 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,520 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,523 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,530 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,541 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,549 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,551 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,561 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,575 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,593 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,595 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,597 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,599 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,618 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,621 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,622 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,625 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,626 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,629 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,633 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,662 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,679 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,713 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,723 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,734 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,737 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,748 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,760 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,771 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,773 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,788 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,803 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,809 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,831 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,844 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,854 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,856 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,858 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,866 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,874 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,875 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,879 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,882 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,902 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,918 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,937 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,940 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,942 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,952 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,965 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,975 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,980 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:18,991 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,014 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,020 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,033 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,034 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,080 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,109 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,117 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,173 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,184 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,185 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,195 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,219 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,227 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,252 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,271 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,285 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,303 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,308 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,323 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,387 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,409 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,424 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,453 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,463 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,518 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,564 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,595 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,605 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,612 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,626 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,628 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,640 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,668 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,705 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,734 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,772 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,784 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,789 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,819 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,836 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,852 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,885 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,909 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,911 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,926 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:19,979 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,004 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,082 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,107 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,111 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,188 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,235 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,253 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,266 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,268 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,275 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,288 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,301 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,357 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,360 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,366 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,412 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,488 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,556 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,592 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,628 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,631 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,658 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,729 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,731 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,786 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,869 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,922 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:20,943 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,005 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,056 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,151 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,277 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,369 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,609 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,646 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,741 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,745 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,770 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,905 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:21,984 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:22,310 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:22,349 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:24,490 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 165 requests in 8.48 seconds.

2026-08-27 14:32:26,410 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,479 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,507 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,569 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,630 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,687 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,724 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,729 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,739 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,774 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,782 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,795 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,809 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,812 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,818 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,825 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,863 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,879 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,890 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,895 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,900 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,904 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,909 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,925 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,926 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,931 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,950 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,953 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,971 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,980 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,981 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,991 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:26,992 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,011 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,014 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,018 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,020 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,030 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,037 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,046 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,051 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,053 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,067 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,070 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,089 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,098 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,101 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,133 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,138 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,156 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,163 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,165 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,166 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,183 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,191 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,193 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,198 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,200 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,215 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,225 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,236 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,245 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,256 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,259 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,266 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,276 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,281 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,296 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,306 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,310 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,312 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,325 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,335 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,380 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,394 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,406 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,411 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,427 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,431 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,477 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,484 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,489 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,493 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,495 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,498 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,510 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,513 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,525 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,545 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,549 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,551 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,561 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,564 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,576 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,579 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,589 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,599 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,625 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,629 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,652 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,657 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,735 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,753 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,759 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,782 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,856 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,861 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,864 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,870 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,895 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,937 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,947 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,949 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,968 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,976 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:27,995 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,025 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,029 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,047 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,059 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,089 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,142 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,147 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,149 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,215 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,233 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,292 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,430 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,524 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,548 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,687 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,780 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:28,947 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:29,148 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:29,210 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:29,319 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:29,547 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:29,582 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:29,875 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:30,028 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:30,905 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:34,345 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:36,472 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 143 requests in 11.97 seconds.

2026-08-27 14:32:38,406 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,446 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,478 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,535 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,579 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,591 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,634 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,690 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,707 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,776 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,814 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,821 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,834 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,841 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,913 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:38,962 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,030 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,047 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,055 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,086 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,099 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,112 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,130 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,141 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,211 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,221 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,224 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,242 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,274 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,284 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,286 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,287 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,320 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,321 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,321 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,405 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,407 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,434 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,441 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,458 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,475 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,487 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,497 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,512 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,527 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,571 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,621 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,689 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,719 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,779 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,783 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,920 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,976 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,981 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:39,993 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,108 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,119 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,184 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,215 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,217 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,223 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,259 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,294 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,344 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,391 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,469 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,595 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,747 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:40,847 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,285 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,339 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,423 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,427 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,493 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,540 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,608 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,933 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:41,954 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:42,585 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:42,602 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:43,550 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:47,106 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 82 requests in 10.63 seconds.

2026-08-27 14:32:49,311 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,540 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,597 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,612 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,615 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,645 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,722 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,745 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,769 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,774 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,796 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,840 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,846 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,874 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,878 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,885 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,889 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,893 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,924 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,927 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,932 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,944 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,967 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,977 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,983 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,987 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:49,991 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,001 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,007 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,011 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,021 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,029 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,056 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,059 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,061 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,073 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,076 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,078 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,088 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,120 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,132 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,139 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,152 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,163 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,170 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,199 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,207 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,211 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,225 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,233 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,259 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,265 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,278 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,280 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,283 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,284 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,293 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,294 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,298 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,303 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,305 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,308 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,318 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,319 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,324 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,327 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,347 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,354 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,357 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,388 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,403 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,409 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,418 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,422 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,424 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,433 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,443 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,445 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,449 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,456 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,457 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,460 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,467 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,474 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,477 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,491 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,493 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,494 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,497 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,497 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,518 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,528 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,545 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,549 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,552 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,558 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,573 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,582 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,588 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,605 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,606 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,620 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,638 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,653 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,659 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,660 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,671 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,675 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,689 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,695 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,696 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,704 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,707 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,709 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,719 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,720 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,728 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,731 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,745 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,759 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,768 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,795 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,814 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,827 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,830 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,837 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,838 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,843 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,850 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,866 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,891 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,894 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,914 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,918 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,925 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,941 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,948 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,977 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:50,998 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,010 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,022 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,034 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,111 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,116 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,139 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,143 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,168 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,174 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,196 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,204 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,212 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,237 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,242 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,292 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,302 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,331 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,333 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,380 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,383 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,386 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,391 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,395 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,397 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,400 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,404 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,427 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,453 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,460 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,468 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,473 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,520 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,553 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,574 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,586 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,590 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,639 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,651 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,652 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,689 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,691 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,693 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,695 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,721 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,729 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,731 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,743 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,782 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,804 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,812 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,816 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,842 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,904 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,926 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,952 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:51,970 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,015 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,024 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,044 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,070 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,093 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,105 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,116 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,133 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,149 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,180 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,210 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,221 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,229 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,235 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,268 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,274 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,287 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,338 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,345 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,347 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,386 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,475 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,528 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,532 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,535 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,548 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,632 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,646 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,687 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,711 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,901 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,905 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,919 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,982 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:52,994 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,031 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,149 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,249 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,270 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,279 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,550 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,583 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,655 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,686 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,704 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,726 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:53,844 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:54,051 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:54,433 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:54,547 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:55,030 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:55,205 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:55,382 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:57,810 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:58,320 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:32:59,110 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 251 requests in 12.00 seconds.
✅ Labeled 1223 news excerpts

,document_id,headline,timestamp,url,source_id,source_name,chunk_text,text,masked_text,relevance,...,entity_id,entity_ids,entity_name,query,document_type,theme,entity_searched_id,entity_searched_name,motivation,label
0,8AF5DC8E61FEC05F6246BFBCE1DB3BEE,'Dark Days' Likely Ahead For Tech Firms as Tar...,2025-04-04T15:19:17,,9D69F1,MT Newswires,"Earlier this year, Washington imposed tariffs ...","Earlier this year, Washington imposed tariffs ...","Earlier this year, Washington imposed tariffs ...",0.289953,...,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company is not explicitly identified in...,unclear
1,BAD5EA33E54C61E9D0CDA15BF7304747,Huawei Moves Ratchet Up Nvidia's Stakes In The...,2025-05-01T15:58:56,https://www.forbes.com/sites/rscottraynovich/2...,22AC8B,Forbes.com,"Shifting Export Restrictions\nMeanwhile, U.S. ...","Shifting Export Restrictions\nMeanwhile, U.S. ...","Shifting Export Restrictions\nMeanwhile, U.S. ...",0.270230,...,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company is not explicitly identified in...,unclear
2,A23CE52DA7BA1D93026FCB999657CCD4,Trump Tariff Strategy Creates 'Self-Inflicted ...,2025-04-08T18:16:34,https://www.benzinga.com/node/44698325?utm_cam...,5A5702,Benzinga,Also Read: Wall Street Soars As Trump Teases T...,Also Read: Wall Street Soars As Trump Teases T...,Also Read: Wall Street Soars As Trump Teases T...,0.240285,...,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company is not explicitly identified in...,unclear
3,A161B914898BDE0A5862020D9EB650A7,Research Alert: Apple And Semis Not Directly E...,2025-04-04T15:25:08,,9D69F1,MT Newswires,"11:25 AM EDT, 04/04/2025 (MT Newswires) -- CFR...","11:25 AM EDT, 04/04/2025 (MT Newswires) -- CFR...","11:25 AM EDT, 04/04/2025 (MT Newswires) -- CFR...",0.230197,...,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company is not explicitly identified in...,unclear
4,AEC4A47D33FBACC1F2F0C1178482C7E0,Trump-China trade war: Which US companies coul...,2025-04-15T15:37:15,https://www.aljazeera.com/news/2025/4/15/trump...,881677,Al Jazeera,"Tech companies, fashion firms and agribusiness...","Tech companies, fashion firms and agribusiness...","Tech companies, fashion firms and agribusiness...",0.223652,...,E09E2B,[E09E2B],NVIDIA Corp.,"Higher landed costs, margin compression, prici...",news,US Import Tariffs Corporate Risk Impact Analysis,E09E2B,NVIDIA Corp.,Target Company is exposed to US import tariffs...,Financial and Commercial Risks

  ## Report Generation



  The second phase uses `GenerateReport` and transforms the classified risk data into comprehensive reports with corporate mitigation strategies.

  ### Initialize GenerateReport







  The `GenerateReport` class will:



  - Create sector-wide risk summaries



  - Generate company-specific risk scores and summaries



  - Extract mitigation plans from SEC filings and earnings transcripts



  - Produce professional HTML reports with customizable ranking criteria

In [13]:
# Initialize the report generator with our analysis parameters
report_generator = GenerateReport(
        universe_df=universe_df,
        main_theme=main_theme,
        focus=focus,
        llm_model=llm_model,
        api_key=OPENAI_API_KEY,
        start_date=start_date,
        end_date=end_date,
        search_frequency=freq,
        document_limit_news=document_limit_news,
        document_limit_filings=document_limit_filings,
        batch_size=batch_size,
        themes_tree_dict=themes_tree_dict
)

  ### Generate Comprehensive Report







  Execute the complete report generation workflow including:



  1. **Sector-Level Summarization**: Create thematic summaries across risk categories



  2. **Company-Level Analysis**: Generate risk scores for Media Attention, Financial Impact, and Uncertainty



  3. **Mitigation Strategy Extraction**: Search filings and transcripts for corporate response plans (with News fallback when enabled via `news_search_fallback`)



  4. **Data Integration**: Combine all sources into structured report datasets

In [14]:
# Generate the risk report data
report = report_generator.generate_report(
    df_labeled=df_labeled,
    news_search_fallback = response_from_news, # Use response_from_news to enable/disable News fallback
    import_from_path=None,
    export_to_path=output_dir,
)

2026-08-27 14:33:02,385 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:05,228 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:07,982 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:07,991 - INFO - Exported summaries to pickle file.

2026-08-27 14:33:07,992 - INFO - Preparing topics from the labeled DataFrame

2026-08-27 14:33:08,006 - INFO - Starting processing for 20 tasks...

2026-08-27 14:33:08,007 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks' for entity 'NVIDIA Corp.'

2026-08-27 14:33:08,012 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks' for entity 'NVIDIA Corp.'

2026-08-27 14:33:08,018 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks' for entity 'NVIDIA Corp.'

2026-08-27 14:33:08,022 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks' for entity 'Apple Inc.'

2026-08-27 14:33:08,035 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks' for entity 'Apple Inc.'

2026-08-27 14:33:08,043 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks' for entity 'Apple Inc.'

2026-08-27 14:33:08,047 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks' for entity 'Microsoft Corp.'

2026-08-27 14:33:08,055 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks' for entity 'Microsoft Corp.'

2026-08-27 14:33:08,057 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks' for entity 'Amazon.com Inc.'

2026-08-27 14:33:08,062 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks' for entity 'Amazon.com Inc.'

2026-08-27 14:33:08,071 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks' for entity 'Amazon.com Inc.'

2026-08-27 14:33:08,072 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks' for entity 'Alphabet Inc.'

2026-08-27 14:33:08,080 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks' for entity 'Alphabet Inc.'

2026-08-27 14:33:08,083 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks' for entity 'Alphabet Inc.'

2026-08-27 14:33:08,084 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks' for entity 'Meta Platforms Inc.'

2026-08-27 14:33:08,087 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks' for entity 'Meta Platforms Inc.'

2026-08-27 14:33:08,089 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks' for entity 'Meta Platforms Inc.'

2026-08-27 14:33:08,090 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks' for entity 'Tesla Inc.'

2026-08-27 14:33:08,097 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks' for entity 'Tesla Inc.'

2026-08-27 14:33:08,099 - INFO - Processing topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks' for entity 'Tesla Inc.'

2026-08-27 14:33:10,041 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:10,436 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:10,804 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:11,088 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:11,327 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:11,365 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:11,390 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:11,395 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:11,680 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:12,096 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:12,414 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:12,418 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:13,129 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:14,010 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:14,201 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:14,237 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:14,432 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:14,463 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:14,568 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:14,713 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:14,841 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:15,757 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,019 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,039 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,100 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,276 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,311 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,322 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,507 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,529 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,679 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:17,825 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:18,321 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:19,013 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:19,432 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:19,700 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:19,701 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:19,991 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:20,060 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:20,289 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:20,596 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:20,664 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:20,874 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:21,477 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:21,803 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:22,452 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:22,825 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:22,882 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:23,133 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:23,483 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:23,530 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:23,538 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:24,074 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:24,139 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:24,755 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:24,940 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:25,086 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:25,100 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:25,691 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:26,998 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:33:27,002 - INFO - Exporting processed data to output/df_by_company

2026-08-27 14:33:27,004 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:33:27,004 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:27,004 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:27,004 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:27,005 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:27,005 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 5 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:27,826 - INFO - Planning complete: 5 expected chunks in 1 baskets

2026-08-27 14:33:27,826 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:27,826 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:27,827 - INFO - Searching 1 baskets

2026-08-27 14:33:28,716 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:28,718 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:28,718 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.89s

2026-08-27 14:33:28,719 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:28,719 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:33:28,720 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:28,720 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:28,720 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:28,721 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:28,721 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 13 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:29,370 - INFO - Planning complete: 13 expected chunks in 1 baskets

2026-08-27 14:33:29,371 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:29,371 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:29,371 - INFO - Searching 1 baskets

2026-08-27 14:33:30,045 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:30,046 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:30,046 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.67s

2026-08-27 14:33:30,046 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:30,047 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:33:30,047 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:30,047 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:30,047 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:30,047 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:30,048 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 14 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:30,872 - INFO - Planning complete: 14 expected chunks in 1 baskets

2026-08-27 14:33:30,873 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:30,873 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:30,874 - INFO - Searching 1 baskets

2026-08-27 14:33:31,577 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:31,579 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:31,579 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.71s

2026-08-27 14:33:31,580 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:31,582 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:33:31,583 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:31,584 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:31,584 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:31,584 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:31,585 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 73 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:32,402 - INFO - Planning complete: 73 expected chunks in 1 baskets

2026-08-27 14:33:32,403 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:32,403 - INFO - Total maximum expected chunks: 1

2026-08-27 14:33:32,403 - INFO - Searching 1 baskets

2026-08-27 14:33:33,466 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:33,467 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:33,468 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.06s

2026-08-27 14:33:33,468 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:33,469 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:33:33,469 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:33,470 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:33,470 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:33,470 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:33,471 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 59 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:34,106 - INFO - Planning complete: 59 expected chunks in 1 baskets

2026-08-27 14:33:34,107 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:34,107 - INFO - Total maximum expected chunks: 1

2026-08-27 14:33:34,108 - INFO - Searching 1 baskets

2026-08-27 14:33:34,821 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:34,823 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:34,823 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.72s

2026-08-27 14:33:34,824 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:34,824 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:33:34,825 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:34,825 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:34,826 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:34,826 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:34,827 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 177 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:35,488 - INFO - Planning complete: 177 expected chunks in 1 baskets

2026-08-27 14:33:35,489 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:35,489 - INFO - Total maximum expected chunks: 3

2026-08-27 14:33:35,489 - INFO - Searching 1 baskets

2026-08-27 14:33:36,368 - INFO - Basket basket_0_medium_20250201_20250813: Retrieved 3 documents with 3 chunks

2026-08-27 14:33:36,371 - INFO - First pass complete: 3 documents with 3 chunks

2026-08-27 14:33:36,371 - INFO - Search complete: 3 documents with 3 chunks retrieved in 0.88s

2026-08-27 14:33:36,372 - INFO - Deduplicated: 3 unique documents from 3 total (chunks merged)

2026-08-27 14:33:36,375 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:33:36,375 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:36,376 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:36,376 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:36,377 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:36,377 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 32 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:37,108 - INFO - Planning complete: 32 expected chunks in 1 baskets

2026-08-27 14:33:37,109 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:37,110 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:37,110 - INFO - Searching 1 baskets

2026-08-27 14:33:37,879 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:37,880 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:37,881 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.77s

2026-08-27 14:33:37,881 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:37,881 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:33:37,882 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:37,882 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:37,882 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:37,882 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:37,883 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 23 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:38,706 - INFO - Planning complete: 23 expected chunks in 1 baskets

2026-08-27 14:33:38,707 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:38,708 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:38,708 - INFO - Searching 1 baskets

2026-08-27 14:33:39,424 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:39,426 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:39,427 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.72s

2026-08-27 14:33:39,427 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:39,428 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:33:39,428 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:39,428 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:39,429 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:39,429 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:39,430 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 195 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:40,255 - INFO - Planning complete: 195 expected chunks in 1 baskets

2026-08-27 14:33:40,256 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:40,256 - INFO - Total maximum expected chunks: 3

2026-08-27 14:33:40,257 - INFO - Searching 1 baskets

2026-08-27 14:33:41,137 - INFO - Basket basket_0_medium_20250201_20250813: Retrieved 3 documents with 3 chunks

2026-08-27 14:33:41,139 - INFO - First pass complete: 3 documents with 3 chunks

2026-08-27 14:33:41,140 - INFO - Search complete: 3 documents with 3 chunks retrieved in 0.88s

2026-08-27 14:33:41,141 - INFO - Deduplicated: 3 unique documents from 3 total (chunks merged)

2026-08-27 14:33:41,143 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:33:41,144 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:41,144 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:41,145 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:41,145 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:41,146 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 47 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:41,871 - INFO - Planning complete: 47 expected chunks in 1 baskets

2026-08-27 14:33:41,871 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:41,872 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:41,873 - INFO - Searching 1 baskets

2026-08-27 14:33:42,835 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:42,837 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:42,838 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.96s

2026-08-27 14:33:42,838 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:42,839 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:33:42,839 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:42,840 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:42,840 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:42,841 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:42,841 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 59 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:43,494 - INFO - Planning complete: 59 expected chunks in 1 baskets

2026-08-27 14:33:43,494 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:43,495 - INFO - Total maximum expected chunks: 1

2026-08-27 14:33:43,496 - INFO - Searching 1 baskets

2026-08-27 14:33:44,232 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:44,233 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:44,233 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.74s

2026-08-27 14:33:44,233 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:44,234 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:33:44,234 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:44,234 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:44,235 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:44,235 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:44,235 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 165 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:44,933 - INFO - Planning complete: 165 expected chunks in 1 baskets

2026-08-27 14:33:44,934 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:44,935 - INFO - Total maximum expected chunks: 3

2026-08-27 14:33:44,935 - INFO - Searching 1 baskets

2026-08-27 14:33:45,741 - INFO - Basket basket_0_medium_20250201_20250813: Retrieved 3 documents with 3 chunks

2026-08-27 14:33:45,743 - INFO - First pass complete: 3 documents with 3 chunks

2026-08-27 14:33:45,743 - INFO - Search complete: 3 documents with 3 chunks retrieved in 0.81s

2026-08-27 14:33:45,744 - INFO - Deduplicated: 3 unique documents from 3 total (chunks merged)

2026-08-27 14:33:45,746 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:33:45,746 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:45,747 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:45,747 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:45,747 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:45,748 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 121 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:46,408 - INFO - Planning complete: 121 expected chunks in 1 baskets

2026-08-27 14:33:46,408 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:46,409 - INFO - Total maximum expected chunks: 2

2026-08-27 14:33:46,409 - INFO - Searching 1 baskets

2026-08-27 14:33:47,221 - INFO - Basket basket_0_medium_20250201_20250813: Retrieved 2 documents with 2 chunks

2026-08-27 14:33:47,224 - INFO - First pass complete: 2 documents with 2 chunks

2026-08-27 14:33:47,225 - INFO - Search complete: 2 documents with 2 chunks retrieved in 0.82s

2026-08-27 14:33:47,227 - INFO - Deduplicated: 2 unique documents from 2 total (chunks merged)

2026-08-27 14:33:47,228 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:33:47,228 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:47,229 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:47,229 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:47,230 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:47,230 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 43 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:48,081 - INFO - Planning complete: 43 expected chunks in 1 baskets

2026-08-27 14:33:48,082 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:48,082 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:48,083 - INFO - Searching 1 baskets

2026-08-27 14:33:48,803 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:48,805 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:48,806 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.72s

2026-08-27 14:33:48,806 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:48,807 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:33:48,807 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:48,808 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:48,808 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:48,809 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:48,809 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 320 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:49,510 - INFO - Planning complete: 320 expected chunks in 1 baskets

2026-08-27 14:33:49,510 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:49,511 - INFO - Total maximum expected chunks: 6

2026-08-27 14:33:49,511 - INFO - Searching 1 baskets

2026-08-27 14:33:50,312 - INFO - Basket basket_0_medium_20250201_20250813: Retrieved 6 documents with 6 chunks

2026-08-27 14:33:50,314 - INFO - First pass complete: 6 documents with 6 chunks

2026-08-27 14:33:50,314 - INFO - Search complete: 6 documents with 6 chunks retrieved in 0.80s

2026-08-27 14:33:50,315 - INFO - Deduplicated: 6 unique documents from 6 total (chunks merged)

2026-08-27 14:33:50,318 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:33:50,318 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:50,319 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:50,319 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:50,319 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:50,320 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 35 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:51,309 - INFO - Planning complete: 35 expected chunks in 1 baskets

2026-08-27 14:33:51,310 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:51,311 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:51,311 - INFO - Searching 1 baskets

2026-08-27 14:33:52,245 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:52,245 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:52,246 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.93s

2026-08-27 14:33:52,246 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:52,246 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:33:52,246 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:52,246 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:52,247 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:52,247 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:52,247 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 15 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:52,926 - INFO - Planning complete: 15 expected chunks in 1 baskets

2026-08-27 14:33:52,926 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:52,927 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:52,927 - INFO - Searching 1 baskets

2026-08-27 14:33:53,611 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:53,613 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:53,613 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.69s

2026-08-27 14:33:53,614 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:53,614 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:33:53,615 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:53,615 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:53,616 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:53,616 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:53,617 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 111 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:54,309 - INFO - Planning complete: 111 expected chunks in 1 baskets

2026-08-27 14:33:54,310 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:54,310 - INFO - Total maximum expected chunks: 2

2026-08-27 14:33:54,311 - INFO - Searching 1 baskets

2026-08-27 14:33:55,385 - INFO - Basket basket_0_medium_20250201_20250813: Retrieved 2 documents with 2 chunks

2026-08-27 14:33:55,387 - INFO - First pass complete: 2 documents with 2 chunks

2026-08-27 14:33:55,387 - INFO - Search complete: 2 documents with 2 chunks retrieved in 1.08s

2026-08-27 14:33:55,388 - INFO - Deduplicated: 2 unique documents from 2 total (chunks merged)

2026-08-27 14:33:55,391 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:33:55,391 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:55,392 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:55,392 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:55,392 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:55,393 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 44 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:56,209 - INFO - Planning complete: 44 expected chunks in 1 baskets

2026-08-27 14:33:56,210 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:56,210 - INFO - Total maximum expected chunks: 0

2026-08-27 14:33:56,210 - INFO - Searching 1 baskets

2026-08-27 14:33:56,910 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:56,912 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:56,913 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.70s

2026-08-27 14:33:56,913 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:56,914 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:33:56,915 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:56,915 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:56,916 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:56,916 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:56,916 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 64 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:57,590 - INFO - Planning complete: 64 expected chunks in 1 baskets

2026-08-27 14:33:57,590 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:57,591 - INFO - Total maximum expected chunks: 1

2026-08-27 14:33:57,591 - INFO - Searching 1 baskets

2026-08-27 14:33:58,491 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:33:58,492 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:33:58,493 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.90s

2026-08-27 14:33:58,493 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:33:58,494 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:33:58,494 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:33:58,494 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:33:58,495 - INFO - Loaded 1 companies from universe

2026-08-27 14:33:58,495 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:33:58,496 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 69 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:33:59,211 - INFO - Planning complete: 69 expected chunks in 1 baskets

2026-08-27 14:33:59,211 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:33:59,212 - INFO - Total maximum expected chunks: 1

2026-08-27 14:33:59,212 - INFO - Searching 1 baskets

2026-08-27 14:34:00,019 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:00,020 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:00,021 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.81s

2026-08-27 14:34:00,021 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:00,025 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:34:00,025 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:00,025 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:00,025 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:00,025 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:00,026 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 18 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:00,895 - INFO - Planning complete: 18 expected chunks in 1 baskets

2026-08-27 14:34:00,896 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:00,896 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:00,897 - INFO - Searching 1 baskets

2026-08-27 14:34:01,768 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:01,770 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:01,771 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.87s

2026-08-27 14:34:01,771 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:01,772 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:34:01,772 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:01,773 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:01,773 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:01,774 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:01,775 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 8 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:02,535 - INFO - Planning complete: 8 expected chunks in 1 baskets

2026-08-27 14:34:02,536 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:02,536 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:02,537 - INFO - Searching 1 baskets

2026-08-27 14:34:03,394 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:03,396 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:03,396 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.86s

2026-08-27 14:34:03,397 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:03,397 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:34:03,398 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:03,398 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:03,399 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:03,399 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:03,400 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 18 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:04,025 - INFO - Planning complete: 18 expected chunks in 1 baskets

2026-08-27 14:34:04,026 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:04,026 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:04,026 - INFO - Searching 1 baskets

2026-08-27 14:34:04,757 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:04,758 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:04,759 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.73s

2026-08-27 14:34:04,759 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:04,761 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:34:04,762 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:04,762 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:04,762 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:04,763 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:04,763 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 39 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:05,594 - INFO - Planning complete: 39 expected chunks in 1 baskets

2026-08-27 14:34:05,594 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:05,595 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:05,595 - INFO - Searching 1 baskets

2026-08-27 14:34:06,525 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:06,527 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:06,528 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.93s

2026-08-27 14:34:06,528 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:06,529 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:34:06,529 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:06,529 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:06,530 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:06,530 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:06,531 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 33 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:07,334 - INFO - Planning complete: 33 expected chunks in 1 baskets

2026-08-27 14:34:07,335 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:07,335 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:07,336 - INFO - Searching 1 baskets

2026-08-27 14:34:08,284 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:08,285 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:08,285 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.95s

2026-08-27 14:34:08,286 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:08,286 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:34:08,286 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:08,287 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:08,287 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:08,287 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:08,287 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 50 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:09,080 - INFO - Planning complete: 50 expected chunks in 1 baskets

2026-08-27 14:34:09,081 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:09,082 - INFO - Total maximum expected chunks: 1

2026-08-27 14:34:09,082 - INFO - Searching 1 baskets

2026-08-27 14:34:09,868 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:09,869 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:09,870 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.79s

2026-08-27 14:34:09,870 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:09,873 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:34:09,873 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:09,874 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:09,874 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:09,874 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:09,875 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 35 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:10,539 - INFO - Planning complete: 35 expected chunks in 1 baskets

2026-08-27 14:34:10,540 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:10,540 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:10,540 - INFO - Searching 1 baskets

2026-08-27 14:34:11,238 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:11,240 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:11,241 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.70s

2026-08-27 14:34:11,241 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:11,242 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:34:11,242 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:11,242 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:11,243 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:11,243 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:11,244 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 8 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:11,898 - INFO - Planning complete: 8 expected chunks in 1 baskets

2026-08-27 14:34:11,898 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:11,899 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:11,899 - INFO - Searching 1 baskets

2026-08-27 14:34:12,819 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:12,821 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:12,821 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.92s

2026-08-27 14:34:12,822 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:12,822 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:34:12,823 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:12,823 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:12,823 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:12,824 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:12,824 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 92 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:13,489 - INFO - Planning complete: 92 expected chunks in 1 baskets

2026-08-27 14:34:13,489 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:13,490 - INFO - Total maximum expected chunks: 1

2026-08-27 14:34:13,490 - INFO - Searching 1 baskets

2026-08-27 14:34:14,469 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:14,471 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:14,471 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.98s

2026-08-27 14:34:14,472 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:14,474 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:34:14,475 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:14,475 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:14,475 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:14,476 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:14,476 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 37 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:15,088 - INFO - Planning complete: 37 expected chunks in 1 baskets

2026-08-27 14:34:15,089 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:15,089 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:15,090 - INFO - Searching 1 baskets

2026-08-27 14:34:15,826 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:15,828 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:15,829 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.74s

2026-08-27 14:34:15,829 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:15,830 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:34:15,830 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:15,830 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:15,831 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:15,831 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:15,832 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 36 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:16,639 - INFO - Planning complete: 36 expected chunks in 1 baskets

2026-08-27 14:34:16,640 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:16,640 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:16,641 - INFO - Searching 1 baskets

2026-08-27 14:34:17,363 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:17,365 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:17,366 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.72s

2026-08-27 14:34:17,366 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:17,367 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:34:17,367 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:17,368 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:17,368 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:17,369 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:17,369 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 94 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:18,048 - INFO - Planning complete: 94 expected chunks in 1 baskets

2026-08-27 14:34:18,048 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:18,048 - INFO - Total maximum expected chunks: 1

2026-08-27 14:34:18,049 - INFO - Searching 1 baskets

2026-08-27 14:34:18,826 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:18,827 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:18,827 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.78s

2026-08-27 14:34:18,828 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:18,829 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:34:18,830 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:18,830 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:18,830 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:18,831 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:18,831 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 56 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:19,515 - INFO - Planning complete: 56 expected chunks in 1 baskets

2026-08-27 14:34:19,515 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:19,516 - INFO - Total maximum expected chunks: 1

2026-08-27 14:34:19,516 - INFO - Searching 1 baskets

2026-08-27 14:34:20,244 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:20,245 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:20,245 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.73s

2026-08-27 14:34:20,245 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:20,246 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:34:20,246 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:20,246 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:20,247 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:20,247 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:20,247 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 27 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:20,862 - INFO - Planning complete: 27 expected chunks in 1 baskets

2026-08-27 14:34:20,862 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:20,863 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:20,863 - INFO - Searching 1 baskets

2026-08-27 14:34:21,559 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:21,560 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:21,560 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.70s

2026-08-27 14:34:21,560 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:21,560 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:34:21,560 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:21,561 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:21,561 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:21,561 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:21,561 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 155 total chunks, bucket=medium
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:22,251 - INFO - Planning complete: 155 expected chunks in 1 baskets

2026-08-27 14:34:22,251 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:22,251 - INFO - Total maximum expected chunks: 3

2026-08-27 14:34:22,252 - INFO - Searching 1 baskets

2026-08-27 14:34:23,434 - INFO - Basket basket_0_medium_20250201_20250813: Retrieved 3 documents with 3 chunks

2026-08-27 14:34:23,435 - INFO - First pass complete: 3 documents with 3 chunks

2026-08-27 14:34:23,436 - INFO - Search complete: 3 documents with 3 chunks retrieved in 1.18s

2026-08-27 14:34:23,437 - INFO - Deduplicated: 3 unique documents from 3 total (chunks merged)

2026-08-27 14:34:23,440 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:34:23,441 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:23,441 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:23,441 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:23,442 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:23,442 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 13 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:24,177 - INFO - Planning complete: 13 expected chunks in 1 baskets

2026-08-27 14:34:24,178 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:24,178 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:24,178 - INFO - Searching 1 baskets

2026-08-27 14:34:25,163 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:25,164 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:25,164 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.99s

2026-08-27 14:34:25,165 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:25,165 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:34:25,165 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:25,166 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:25,166 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:25,166 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:25,167 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 3 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:25,843 - INFO - Planning complete: 3 expected chunks in 1 baskets

2026-08-27 14:34:25,843 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:25,844 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:25,844 - INFO - Searching 1 baskets

2026-08-27 14:34:26,536 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:26,537 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:26,538 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.69s

2026-08-27 14:34:26,538 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:26,539 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:34:26,539 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:26,540 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:26,540 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:26,540 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:26,541 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 62 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:27,410 - INFO - Planning complete: 62 expected chunks in 1 baskets

2026-08-27 14:34:27,410 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:27,411 - INFO - Total maximum expected chunks: 1

2026-08-27 14:34:27,411 - INFO - Searching 1 baskets

2026-08-27 14:34:28,143 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:28,144 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:28,144 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.73s

2026-08-27 14:34:28,145 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:28,146 - INFO - Planning search for text: 'Higher landed costs, margin compression, pricing pressure, demand destruction, exchange-rate effects, and potential retaliation can weaken profitability and competitiveness. Companies may face contract disputes, reduced sales in tariff-sensitive markets, working-capital strain, and impairment of tariff-exposed assets or business units.'

2026-08-27 14:34:28,146 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:28,147 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:28,147 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:28,147 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:28,147 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 43 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:28,800 - INFO - Planning complete: 43 expected chunks in 1 baskets

2026-08-27 14:34:28,801 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:28,801 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:28,801 - INFO - Searching 1 baskets

2026-08-27 14:34:30,103 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:30,105 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:30,105 - INFO - Search complete: 1 documents with 1 chunks retrieved in 1.30s

2026-08-27 14:34:30,106 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:30,106 - INFO - Planning search for text: 'Tariffs can disrupt sourcing, production footprints, logistics flows, inventory planning, customs compliance, and supplier relationships. Firms may experience border delays, classification or origin disputes, capacity shortages in alternative locations, increased compliance costs, and reduced resilience when rapidly relocating production or suppliers.'

2026-08-27 14:34:30,107 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:30,107 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:30,107 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:30,108 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:30,108 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 43 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:30,773 - INFO - Planning complete: 43 expected chunks in 1 baskets

2026-08-27 14:34:30,773 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:30,774 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:30,774 - INFO - Searching 1 baskets

2026-08-27 14:34:31,519 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:31,521 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:31,521 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.75s

2026-08-27 14:34:31,522 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:31,522 - INFO - Planning search for text: 'Companies may need to redesign global manufacturing, market-entry, procurement, and investment strategies. Risks include retaliatory tariffs, regulatory uncertainty, trade-policy escalation, sanctions or export-control interactions, litigation and customs penalties, reputational exposure, and forced choices among reshoring, regionalization, price pass-through, product redesign, or market withdrawal.'

2026-08-27 14:34:31,523 - INFO - Date range: 2025-02-01 to 2025-08-13

2026-08-27 14:34:31,523 - INFO - Using 1 entity IDs from inline list

2026-08-27 14:34:31,524 - INFO - Loaded 1 companies from universe

2026-08-27 14:34:31,524 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-27 14:34:31,524 - INFO - Using 1 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-02-01 to 2025-08-13)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 1 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 1 new companies, 0 remaining
      Batch 1 complete: 1 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 1 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 1 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 1 companies, 19 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-27 14:34:32,245 - INFO - Planning complete: 19 expected chunks in 1 baskets

2026-08-27 14:34:32,245 - INFO - Executing search with 2.0% of chunks

2026-08-27 14:34:32,246 - INFO - Total maximum expected chunks: 0

2026-08-27 14:34:32,246 - INFO - Searching 1 baskets

2026-08-27 14:34:33,127 - INFO - Basket basket_0_low_20250201_20250813: Retrieved 1 documents with 1 chunks

2026-08-27 14:34:33,129 - INFO - First pass complete: 1 documents with 1 chunks

2026-08-27 14:34:33,130 - INFO - Search complete: 1 documents with 1 chunks retrieved in 0.88s

2026-08-27 14:34:33,131 - INFO - Deduplicated: 1 unique documents from 1 total (chunks merged)

2026-08-27 14:34:35,464 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:35,525 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:35,546 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 3 requests in 2.41 seconds.

2026-08-27 14:34:38,604 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:39,920 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 2 requests in 4.37 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
2026-08-27 14:34:39,943 - INFO - Exported labeled DataFrame to pickle file.

2026-08-27 14:34:42,614 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:43,489 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:44,093 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 3 requests in 4.15 seconds.

2026-08-27 14:34:47,371 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:47,613 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Completed 2 requests in 3.52 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
Completed 0 requests in 0.00 seconds.
2026-08-27 14:34:47,632 - INFO - Exported labeled DataFrame to pickle file.

2026-08-27 14:34:47,639 - INFO - Starting process_response_by_company with 3 tasks...

2026-08-27 14:34:47,639 - INFO - Processing response summary for entity 'NVIDIA Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:47,643 - INFO - Processing response summary for entity 'Apple Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:47,646 - INFO - Processing response summary for entity 'Apple Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks'

2026-08-27 14:34:49,615 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:49,695 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:53,247 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:53,250 - INFO - Exporting response summary to output/df_response_by_company

2026-08-27 14:34:53,266 - INFO - Starting process_response_by_company with 20 tasks...

2026-08-27 14:34:53,266 - INFO - Processing response summary for entity 'NVIDIA Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:53,270 - INFO - Processing response summary for entity 'NVIDIA Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks'

2026-08-27 14:34:53,276 - INFO - Processing response summary for entity 'NVIDIA Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks'

2026-08-27 14:34:53,283 - INFO - Processing response summary for entity 'Apple Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:53,293 - INFO - Processing response summary for entity 'Apple Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks'

2026-08-27 14:34:53,301 - INFO - Processing response summary for entity 'Apple Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks'

2026-08-27 14:34:53,304 - INFO - Processing response summary for entity 'Microsoft Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:53,312 - INFO - Processing response summary for entity 'Microsoft Corp.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks'

2026-08-27 14:34:53,315 - INFO - Processing response summary for entity 'Amazon.com Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks'

2026-08-27 14:34:53,319 - INFO - Processing response summary for entity 'Amazon.com Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:53,329 - INFO - Processing response summary for entity 'Amazon.com Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks'

2026-08-27 14:34:53,331 - INFO - Processing response summary for entity 'Alphabet Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:53,338 - INFO - Processing response summary for entity 'Alphabet Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks'

2026-08-27 14:34:53,341 - INFO - Processing response summary for entity 'Alphabet Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks'

2026-08-27 14:34:53,343 - INFO - Processing response summary for entity 'Meta Platforms Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:53,345 - INFO - Processing response summary for entity 'Meta Platforms Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks'

2026-08-27 14:34:53,348 - INFO - Processing response summary for entity 'Meta Platforms Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks'

2026-08-27 14:34:53,349 - INFO - Processing response summary for entity 'Tesla Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Financial and Commercial Risks'

2026-08-27 14:34:53,356 - INFO - Processing response summary for entity 'Tesla Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Strategic, Legal, and Geopolitical Risks'

2026-08-27 14:34:53,358 - INFO - Processing response summary for entity 'Tesla Inc.' and topic 'US Import Tariffs Corporate Risk Impact Analysis - Operational and Supply-Chain Risks'

2026-08-27 14:34:55,286 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:55,713 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:55,725 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:55,827 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:56,163 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:56,285 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:56,398 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:56,786 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:57,507 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:57,779 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:57,784 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:58,392 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:58,713 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:58,995 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:59,055 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:59,496 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:59,736 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:34:59,831 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:35:00,712 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-08-27 14:35:01,134 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

  ## Final Output



  Transform the analysis results into professional, customizable reports. The system provides two distinct presentation styles, each optimized for different use cases and audiences.

  ### Report Customization Options







  Both report formats allow customization through multiple ranking criteria:







  **Sector-Wide Analysis**:



  - Identifies the most significant tariff risks across all companies



  - Ranks themes by media attention and document frequency



  - Provides executive summaries for each risk category







  **Company-Specific Analysis**:



  - **Most Reported Issue**: Highest media coverage and attention



  - **Biggest Risk**: Greatest potential financial impact



  - **Most Uncertain Issue**: Highest uncertainty scores and ambiguity







  Each company analysis includes extracted mitigation plans from official corporate communications, providing actionable intelligence for investment and risk management decisions.

  ### Report Format 1: Executive Summary Style







  This format prioritizes clarity and executive readability, focusing on the top risks per company across three key dimensions. Ideal for senior management briefings and board presentations.

In [15]:
from src.html_report import generate_html_report, prepare_data_report_0

# Extract report data for processing
df_by_theme = report.report_by_theme
df_by_company_with_responses = report.report_by_company

# Prepare data with executive summary formatting
top_by_theme, top_by_company = prepare_data_report_0(df_by_theme, df_by_company_with_responses)

# Generate executive-style HTML report
html_content = generate_html_report(top_by_theme, top_by_company, 'US Import Tariffs: Corporate Risk Impact Analysis')

# Save the executive report
report_filename = f'{output_dir}/tariffs_executive_report.html'
with open(report_filename, 'w') as file:
     file.write(html_content)

print(f"✅ Executive Report saved: {report_filename}")

✅ Executive Report saved: output/tariffs_executive_report.html

  #### Display Executive Report

In [16]:
display(HTML(html_content))

  ### Report Format 2: Detailed Analysis Version







  This format provides comprehensive risk analysis with extended company coverage and detailed risk breakdowns. Designed for analysts, portfolio managers, and risk management teams requiring in-depth insights.

In [17]:
from src.html_report import generate_html_report_v1, prepare_data_report_1

# Prepare data with detailed analysis formatting
top_by_theme, top_by_company = prepare_data_report_1(df_by_theme, df_by_company_with_responses)

# Generate detailed analysis HTML report
html_content_detailed = generate_html_report_v1(top_by_theme, top_by_company, 'US Import Tariffs: Comprehensive Risk Analysis')

# Save the detailed report
detailed_filename = f'{output_dir}/tariffs_detailed_analysis.html'
with open(detailed_filename, 'w') as file:
     file.write(html_content_detailed)

print(f"✅ Detailed Analysis Report saved: {detailed_filename}")

✅ Detailed Analysis Report saved: output/tariffs_detailed_analysis.html

  #### Display Detailed Analysis Report

In [18]:
display(HTML(html_content_detailed))

  ### Export Results for Further Analysis







  The generated data can be exported for integration with existing risk management systems, portfolio optimization tools, or compliance reporting workflows.

In [19]:
# Optional: Export structured data for external analysis
try:
    # Export the core datasets
    df_by_theme.to_csv(f'{output_dir}/tariffs_risks_by_theme.csv', index=False)
    df_by_company_with_responses.to_csv(f'{output_dir}/tariffs_risks_by_company.csv', index=False)
    
    print("✅ Data exported successfully:")
    print(f"   - Thematic analysis: {output_dir}/tariffs_risks_by_theme.csv")
    print(f"   - Company analysis: {output_dir}/tariffs_risks_by_company.csv")
    print(f"   - Executive report: {output_dir}/tariffs_executive_report.html")
    print(f"   - Detailed analysis: {output_dir}/tariffs_detailed_analysis.html")
    
except Exception as e:
    print(f"Warning: Export failed - {e}")

✅ Data exported successfully:
   - Thematic analysis: output/tariffs_risks_by_theme.csv
   - Company analysis: output/tariffs_risks_by_company.csv
   - Executive report: output/tariffs_executive_report.html
   - Detailed analysis: output/tariffs_detailed_analysis.html