## SDK migration

`bigdata-client` and `bigdata-research-tools` are removed. Use REST (`BIGDATA_API_KEY`) / `bigdata-smart-batching` / OpenAI. Pass company CSVs (`RP_ENTITY_ID`, `COMPANY_NAME`) instead of watchlists. See [Thematic_Screener_CLI](../Thematic_Screener_CLI/) and [MIGRATION_PATTERNS.md](../MIGRATION_PATTERNS.md).

# ⚠️ SDK Migration Notice

**This notebook has been migrated off `bigdata-client` and `bigdata-research-tools`.**

- Use `src/bigdata_rest.py` and `src/search_helper.py` for API access
- Company universes are now CSV files with `RP_ENTITY_ID` and `COMPANY_NAME` columns (no more SDK watchlists)
- See `README.md` for updated setup instructions
- Refer to `Thematic_Screener_CLI` for modern patterns

# AI Cost Cutting Market Analysis

## Automated Analysis of AI Cost Cutting Providers and Users


## Why It Matters

Companies across industries are increasingly implementing AI solutions to optimize operations and reduce costs, creating opportunities for both technology providers and early adopters to gain competitive advantages. Tracking these developments across fragmented industry coverage is challenging for investment decisions and market intelligence.

## What It Does

Using the functions available in the `bigdata-research-tools` package, you can create a comprehensive AI cost cutting ecosystem analysis tool that identifies technology providers, tracks customer adoption patterns, and maps provider-customer relationships using unstructured data from news sources. These functions are suitable for technology analysts, investors, and industry professionals to create tools that transform scattered AI signals into quantified market intelligence and identify investment opportunities in the AI cost cutting value chain.

## How It Works

This workflow combines **dual-role classification**, **network analysis**, and **temporal tracking** to deliver:

- **Provider vs. User identification** distinguishing companies developing AI cost cutting solutions from those implementing them
- **Technology ecosystem mapping** revealing relationships between solution providers and corporate users
- **Adoption timeline tracking** showing how AI cost cutting implementation evolves across different companies
- **Market positioning analysis** quantifying each company's role and exposure in the AI cost cutting ecosystem

## A Real-World Use Case

This cookbook demonstrates the complete workflow through analyzing AI cost cutting technology dynamics across various industries using news data, showing how the system automatically identifies technology leaders, tracks customer adoption patterns, and reveals provider-customer networks through automated relationship analysis.

## Setup and Imports

## Async Compatibility Setup

**Run this cell first** - Required for Google Colab, Jupyter Notebooks, and VS Code with Jupyter extension:

### Why is this needed?

Interactive environments (Colab, Jupyter) already have an asyncio event loop running. `src/labeling.py`'s
OpenAI calls run in a dedicated worker thread with its own fresh event loop instead of relying on
`nest_asyncio`, because on this environment `nest_asyncio`'s loop patch breaks `asyncio.current_task()`
tracking, which the async OpenAI client's `httpx`/`anyio` internals depend on. This cell just confirms
whether a loop is already running; no patching is required either way.

💡 **Tip**: If you're unsure which environment you're in, just run the cell below - it won't hurt in any environment!

In [1]:
import datetime
start = datetime.datetime.now()

In [2]:
try:
    import asyncio
    asyncio.get_running_loop()
    print("running inside an existing event loop (Jupyter/Colab) -- OpenAI labeling calls will run in a dedicated worker thread, see below")
except RuntimeError:
    print("no event loop running -- OpenAI labeling calls will run directly")

running inside an existing event loop (Jupyter/Colab) -- OpenAI labeling calls will run in a dedicated worker thread, see below

## Environment Setup

The following cell configures the necessary path for the analysis

In [3]:
import os
import sys

current_dir = os.getcwd()
if current_dir not in sys.path:
    sys.path.append(current_dir)
print(f"✅ Local environment setup complete")

✅ Local environment setup complete

## Load Credentials

In [4]:
from dotenv import load_dotenv
from pathlib import Path

script_dir = Path(__file__).parent if '__file__' in globals() else Path.cwd()
load_dotenv(script_dir / '.env')

BIGDATA_API_KEY = os.getenv('BIGDATA_API_KEY')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

if not all([BIGDATA_API_KEY, OPENAI_API_KEY]):
    print("❌ Missing required environment variables")
    raise ValueError("Missing required environment variables. Check your .env file.")
else:
    print("✅ Credentials loaded from .env file")

✅ Credentials loaded from .env file

## Import Required Libraries

Below is the Python code required for setting up our environment and importing necessary libraries.

In [5]:
import pandas as pd

from src.bigdata_rest import BigdataRestClient, load_universe, company_ids_from_universe
from src.search import search_by_any
from src.labeling import run_ai_cost_cutting_prompt
from src.tool import (
    plot_top_companies_by_sector,
    identify_basket_and_plot_confidence,
    transform_to_reference_format,
    top_companies_time,
)
from src.network_analysis import provider_adopter_net

print("✅ Imports complete (REST client + smart-batching search + OpenAI labeling)")

✅ Imports complete (REST client + smart-batching search + OpenAI labeling)

## Optional: Plotly Display Configuration

For better visualization rendering, you can also set the Plotly renderer:

In [6]:
import plotly.io as pio
import plotly.graph_objects as go

# Try to detect the environment and set appropriate renderer
try:
    # Check if we're in JupyterLab
    import os
    if 'JUPYTERHUB_SERVICE_PREFIX' in os.environ or 'JPY_SESSION_NAME' in os.environ:
        pio.renderers.default = 'jupyterlab'
        print("✅ Plotly configured for JupyterLab")
    else:
        # Default for VS Code, Jupyter Notebook, etc.
        pio.renderers.default = 'plotly_mimetype+notebook'
        print("✅ Plotly configured for Jupyter/VS Code")
except:
    # Fallback to a more universal renderer
    pio.renderers.default = 'notebook'
    print("✅ Plotly configured with fallback renderer")

interactive_plots = True  # Set to False to generate static plots

✅ Plotly configured for Jupyter/VS Code

## Define Output Paths

We define the output paths for our AI cost cutting analysis results.

In [7]:
# Define output file paths for our results
output_dir = "output"
os.makedirs(output_dir, exist_ok=True)

export_path = f"{output_dir}/ai_cost_cutting_analysis_results.xlsx"

## Connecting to Bigdata

Create a Bigdata object with your credentials.

In [8]:
# No SDK client object needed. REST calls go through src/bigdata_rest.py,
# authenticated with BIGDATA_API_KEY sent as the X-API-KEY header.
bigdata_rest_client = BigdataRestClient(api_key=BIGDATA_API_KEY)
print("✅ REST client ready")

✅ REST client ready

## Defining your AI Cost Cutting Analysis Parameters


### Fixed Parameters
-  **Provider Theme** (`provider_theme`): The central concept to explore for AI cost cutting technology providers
-  **User Theme** (`user_theme`): The concept to explore for companies using AI for cost cutting in their operations
- **Provider Sentences** (`provider_sentences_list`): Sentences used to identify companies providing AI cost cutting solutions
- **User Sentences** (`user_sentences_list`): Sentences used to identify companies using AI cost cutting technology
-  **Document Type** (`document_type`): Specify which documents to search over
   (transcripts, filings, news)


### Customizable Parameters
-  **Watchlist** (`my_watchlist_id`): The set of companies to analyze. This is the ID of your watchlist on https://app.bigdata.com/watchlists. If set to `None`, each company referenced in the retrieved chunks will be analyzed.
-  **Model Selection** (`llm_model`): The LLM model used to label search result document chunks and generate summaries
-  **Frequency** (`freq`): The frequency of the date ranges to search over.
   Supported values:

   -  `Y`: Yearly intervals.
   -  `M`: Monthly intervals.
   -  `W`: Weekly intervals.
   -  `D`: Daily intervals. Defaults to `M`.

-   **Time Period** (`start_date` and `end_date`): The date range over which to
   run the analysis

-  **Document Sources** (`sources`): Specify set of sources within a document type, for
   example which news outlets (available via Bigdata API) you wish to
   search over

-  **Rerank Threshold** (`rerank_threshold`): By setting this value, you're
   enabling the cross-encoder which reranks the results and selects
   those whose relevance is above the percentile you specify (0.7 being
   the 70th percentile). More information on the re-ranker can be found
   [here](https://docs.bigdata.com/how-to-guides/rerank_search).

-  **Model Selection** (`llm_model`): The LLM model used to label the search result chunks

-  **Document Limit** (`document_limit`): The maximum number of documents to
   return per query to Bigdata API

-  **Batch Size** (`batch_size`): The number of entities to include in a
   single batched query

In [9]:
# ===== Fixed Parameters =====

# AI Cost Cutting Provider Theme
provider_theme = "Companies providing AI solutions for operational cost reduction"

# AI Cost Cutting User Theme  
user_theme = "Companies using AI to reduce their own operational costs"

# Sentences expressing AI cost cutting provider narratives
provider_sentences_list = [  # trimmed to 3 for cost control

    'Company develops AI solutions for operational cost reduction',
    'Firm provides AI-powered cost cutting tools',
    'Organization offers AI automation for cost savings',
    'Corporation supplies AI-driven efficiency solutions',
    'Company creates AI platforms for expense reduction',
    'Business develops artificial intelligence cost optimization',
    'Enterprise manufactures AI cost management systems',
    'Firm provides AI-powered process automation for cost reduction',
    'Company offers AI solutions for operational efficiency',
    'Organization develops AI tools for cost control',
    'Corporation creates AI software for expense management',
    'Business supplies AI automation for cost reduction',
    'Enterprise offers AI-driven operational optimization',
    'Company develops AI platforms for cost savings',
    'Firm creates artificial intelligence efficiency tools',
    'Organization provides AI solutions for process optimization',
    'Corporation develops AI systems for cost management',
    'Business offers AI automation for operational efficiency',
    'Enterprise creates AI tools for expense optimization',
    'Company supplies AI-powered cost reduction solutions'
]

# Sentences expressing AI cost cutting user narratives
user_sentences_list = [
    'Company implements AI for operational cost reduction',
    'Firm adopts AI automation to cut expenses',
    'Organization uses AI to reduce operational costs',
    'Corporation deploys AI for cost savings',
    'Company leverages AI to optimize expenses',
    'Business implements artificial intelligence for cost cutting',
    'Enterprise adopts AI to improve operational efficiency',
    'Firm uses AI automation for expense reduction',
    'Company deploys AI solutions to lower costs',
    'Organization implements AI for process optimization',
    'Corporation uses AI to streamline operations and reduce costs',
    'Business adopts AI for operational cost management',
    'Enterprise leverages AI to reduce expenses',
    'Company implements AI automation for efficiency',
    'Firm deploys artificial intelligence for cost control',
    'Organization uses AI to optimize operational processes for cost savings',
    'Corporation adopts AI for expense management',
    'Business implements AI to reduce operational overhead',
    'Enterprise uses AI automation for cost optimization',
    'Company leverages AI for operational cost savings'
]

# Document Configuration
document_type = "all"  # scope key understood by src/search_helper.py (news/filings/transcripts/all)

In [10]:
# ===== Customizable Parameters =====

# Company Universe (CSV instead of an SDK watchlist)
universe_path = "../Thematic_Screener_CLI/40_companies.csv"
universe_df = load_universe(universe_path).head(5)  # small smoke-test universe to control API cost
company_ids = company_ids_from_universe(universe_df)
id_to_name = dict(zip(universe_df["RP_ENTITY_ID"], universe_df["COMPANY_NAME"]))

# LLM Specification
llm_model = "gpt-4o-mini-2024-07-18"

# Search Frequency
search_frequency = 'M'

# Enable/Disable Reranker
rerank_threshold = None

# Specify Time Range (narrow window to control real API billing)
start_date = "2025-01-01"
end_date = "2025-01-14"

# Document Limits
document_limit = 100

# Others
batch_size = 10

print(f"✅ Universe loaded: {len(company_ids)} companies")
universe_df

✅ Universe loaded: 5 companies

  RP_ENTITY_ID     COMPANY_NAME
0       E09E2B     NVIDIA Corp.
1       D8442A       Apple Inc.
2       228D42  Microsoft Corp.
3       0157B1  Amazon.com Inc.
4       4A6F00    Alphabet Inc.

## Retrieve Content using Bigdata's Search Capabilities

With the AI cost cutting narratives and analysis parameters, you can leverage the
Bigdata API to run a search on company news for both provider and user indicators.

In [11]:
df_sentences_provider = search_by_any(
    sentences=provider_sentences_list[:3],  # cost control: fewer narrative queries
    start_date=start_date,
    end_date=end_date,
    company_ids=company_ids,
    id_to_name=id_to_name,
    scope=document_type,
    chunk_percentage=0.02,
    requests_per_minute=350,
)
df_sentences_provider["role_hint"] = "provider"

df_sentences_user = search_by_any(
    sentences=user_sentences_list[:3],  # cost control: fewer narrative queries
    start_date=start_date,
    end_date=end_date,
    company_ids=company_ids,
    id_to_name=id_to_name,
    scope=document_type,
    chunk_percentage=0.02,
    requests_per_minute=350,
)
df_sentences_user["role_hint"] = "user"

df_all = pd.concat([df_sentences_provider, df_sentences_user], ignore_index=True)
if not df_all.empty:
    df_all = df_all.drop_duplicates(subset=['document_id', 'headline', 'entity_id', 'entity_name', 'text'])
    df_all = df_all.reset_index(drop=True)
    df_all['sentence_id'] = df_all.index.astype(str)

print(f"✅ Retrieved {len(df_all)} chunk-level rows")

2026-08-14 09:22:34,295 - INFO - Planning search for text: 'Company develops AI solutions for operational cost reduction'

2026-08-14 09:22:34,295 - INFO - Date range: 2025-01-01 to 2025-01-14

2026-08-14 09:22:34,295 - INFO - Using 5 entity IDs from inline list

2026-08-14 09:22:34,296 - INFO - Loaded 5 companies from universe

2026-08-14 09:22:34,297 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:34,297 - INFO - Using 5 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-01-01 to 2025-01-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 5 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 5 new companies, 0 remaining
      Batch 1 complete: 5 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 5 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 5 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 5 companies, 500 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:35,610 - INFO - Planning complete: 500 expected chunks in 1 baskets

2026-08-14 09:22:35,610 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:35,610 - INFO - Total maximum expected chunks: 10

2026-08-14 09:22:35,611 - INFO - Searching 1 baskets

2026-08-14 09:22:37,037 - INFO - Basket basket_0_low_20250101_20250114: Retrieved 8 documents with 10 chunks

2026-08-14 09:22:37,039 - INFO - First pass complete: 8 documents with 10 chunks

2026-08-14 09:22:37,039 - INFO - Search complete: 8 documents with 10 chunks retrieved in 1.43s

2026-08-14 09:22:37,040 - INFO - Deduplicated: 8 unique documents from 8 total (chunks merged)

2026-08-14 09:22:37,040 - INFO - Planning search for text: 'Firm provides AI-powered cost cutting tools'

2026-08-14 09:22:37,041 - INFO - Date range: 2025-01-01 to 2025-01-14

2026-08-14 09:22:37,041 - INFO - Using 5 entity IDs from inline list

2026-08-14 09:22:37,041 - INFO - Loaded 5 companies from universe

2026-08-14 09:22:37,042 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:37,042 - INFO - Using 5 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-01-01 to 2025-01-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 5 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 5 new companies, 0 remaining
      Batch 1 complete: 5 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 5 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 5 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 5 companies, 336 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:38,404 - INFO - Planning complete: 336 expected chunks in 1 baskets

2026-08-14 09:22:38,405 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:38,405 - INFO - Total maximum expected chunks: 6

2026-08-14 09:22:38,406 - INFO - Searching 1 baskets

2026-08-14 09:22:39,767 - INFO - Basket basket_0_low_20250101_20250114: Retrieved 4 documents with 6 chunks

2026-08-14 09:22:39,768 - INFO - First pass complete: 4 documents with 6 chunks

2026-08-14 09:22:39,769 - INFO - Search complete: 4 documents with 6 chunks retrieved in 1.36s

2026-08-14 09:22:39,769 - INFO - Deduplicated: 4 unique documents from 4 total (chunks merged)

2026-08-14 09:22:39,769 - INFO - Planning search for text: 'Organization offers AI automation for cost savings'

2026-08-14 09:22:39,770 - INFO - Date range: 2025-01-01 to 2025-01-14

2026-08-14 09:22:39,770 - INFO - Using 5 entity IDs from inline list

2026-08-14 09:22:39,770 - INFO - Loaded 5 companies from universe

2026-08-14 09:22:39,770 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:39,770 - INFO - Using 5 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-01-01 to 2025-01-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 5 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 5 new companies, 0 remaining
      Batch 1 complete: 5 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 5 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 5 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 5 companies, 214 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:40,727 - INFO - Planning complete: 214 expected chunks in 1 baskets

2026-08-14 09:22:40,728 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:40,728 - INFO - Total maximum expected chunks: 4

2026-08-14 09:22:40,728 - INFO - Searching 1 baskets

2026-08-14 09:22:41,992 - INFO - Basket basket_0_low_20250101_20250114: Retrieved 3 documents with 4 chunks

2026-08-14 09:22:41,994 - INFO - First pass complete: 3 documents with 4 chunks

2026-08-14 09:22:41,995 - INFO - Search complete: 3 documents with 4 chunks retrieved in 1.27s

2026-08-14 09:22:41,995 - INFO - Deduplicated: 3 unique documents from 3 total (chunks merged)

2026-08-14 09:22:41,999 - INFO - Planning search for text: 'Company implements AI for operational cost reduction'

2026-08-14 09:22:41,999 - INFO - Date range: 2025-01-01 to 2025-01-14

2026-08-14 09:22:42,000 - INFO - Using 5 entity IDs from inline list

2026-08-14 09:22:42,000 - INFO - Loaded 5 companies from universe

2026-08-14 09:22:42,001 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:42,001 - INFO - Using 5 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-01-01 to 2025-01-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 5 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 5 new companies, 0 remaining
      Batch 1 complete: 5 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 5 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 5 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 5 companies, 250 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:44,472 - INFO - Planning complete: 250 expected chunks in 1 baskets

2026-08-14 09:22:44,473 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:44,473 - INFO - Total maximum expected chunks: 5

2026-08-14 09:22:44,473 - INFO - Searching 1 baskets

2026-08-14 09:22:45,580 - INFO - Basket basket_0_low_20250101_20250114: Retrieved 5 documents with 5 chunks

2026-08-14 09:22:45,581 - INFO - First pass complete: 5 documents with 5 chunks

2026-08-14 09:22:45,582 - INFO - Search complete: 5 documents with 5 chunks retrieved in 1.11s

2026-08-14 09:22:45,582 - INFO - Deduplicated: 5 unique documents from 5 total (chunks merged)

2026-08-14 09:22:45,584 - INFO - Planning search for text: 'Firm adopts AI automation to cut expenses'

2026-08-14 09:22:45,585 - INFO - Date range: 2025-01-01 to 2025-01-14

2026-08-14 09:22:45,585 - INFO - Using 5 entity IDs from inline list

2026-08-14 09:22:45,585 - INFO - Loaded 5 companies from universe

2026-08-14 09:22:45,586 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:45,586 - INFO - Using 5 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-01-01 to 2025-01-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 5 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 5 new companies, 0 remaining
      Batch 1 complete: 5 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 5 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 5 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 5 companies, 386 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:46,719 - INFO - Planning complete: 386 expected chunks in 1 baskets

2026-08-14 09:22:46,720 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:46,720 - INFO - Total maximum expected chunks: 7

2026-08-14 09:22:46,720 - INFO - Searching 1 baskets

2026-08-14 09:22:48,070 - INFO - Basket basket_0_low_20250101_20250114: Retrieved 7 documents with 7 chunks

2026-08-14 09:22:48,077 - INFO - First pass complete: 7 documents with 7 chunks

2026-08-14 09:22:48,079 - INFO - Search complete: 7 documents with 7 chunks retrieved in 1.36s

2026-08-14 09:22:48,079 - INFO - Deduplicated: 7 unique documents from 7 total (chunks merged)

2026-08-14 09:22:48,082 - INFO - Planning search for text: 'Organization uses AI to reduce operational costs'

2026-08-14 09:22:48,083 - INFO - Date range: 2025-01-01 to 2025-01-14

2026-08-14 09:22:48,083 - INFO - Using 5 entity IDs from inline list

2026-08-14 09:22:48,084 - INFO - Loaded 5 companies from universe

2026-08-14 09:22:48,085 - INFO - Using SmartBatchingPlanner with adaptive time-window splitting

2026-08-14 09:22:48,085 - INFO - Using 5 entity IDs from inline list

================================================================================
PHASE 1: Querying full period for all companies (2025-01-01 to 2025-01-14)
         Mode: iterative
================================================================================
    [ITERATIVE MODE] Querying 5 companies in 1 batches of 500 across 1 date sub-range(s) (1 work items, max_workers=1)
    Each batch iterates until no new companies are found (max 10 iterations)

      Batch 1/1, Iter 1: Found 5 new companies, 0 remaining
      Batch 1 complete: 5 found, 0 very_low, 1 iterations
    Completed 1 queries across 1 date sub-range(s). Found 5 companies with chunks > 0, 0 very_low

Phase 1 complete: 1 comention queries
Found 5 companies with chunks > 0

Created 1 entity groups (min_entities_per_group=1)
  Group 0: 5 companies, 146 total chunks, bucket=low
  Zero chunks: 0 companies

================================================================================
PHASE 2: Planning SMART configuration (per-group time splits)
================================================================================
  Group 0: 1 period (full_range), 1 basket
2026-08-14 09:22:49,194 - INFO - Planning complete: 146 expected chunks in 1 baskets

2026-08-14 09:22:49,194 - INFO - Executing search with 2.0% of chunks

2026-08-14 09:22:49,194 - INFO - Total maximum expected chunks: 2

2026-08-14 09:22:49,194 - INFO - Searching 1 baskets

2026-08-14 09:22:50,475 - INFO - Basket basket_0_low_20250101_20250114: Retrieved 2 documents with 2 chunks

2026-08-14 09:22:50,527 - INFO - First pass complete: 2 documents with 2 chunks

2026-08-14 09:22:50,530 - INFO - Search complete: 2 documents with 2 chunks retrieved in 1.34s

2026-08-14 09:22:50,531 - INFO - Deduplicated: 2 unique documents from 2 total (chunks merged)

✅ Retrieved 27 chunk-level rows

In [12]:
# Enrich chunk rows with entity sector/industry/country metadata.
# transform_to_reference_format() expects entity_sector/entity_industry/entity_country/entity_ticker.
unique_entity_ids = df_all['entity_id'].dropna().unique().tolist() if not df_all.empty else []
entities_meta = bigdata_rest_client.get_entities_by_id(unique_entity_ids) if unique_entity_ids else []


def _primary_ticker(entity):
    for listing in entity.get('listing_values') or []:
        if ':' in listing:
            return listing.split(':')[-1]
    return None


meta_df = pd.DataFrame([
    {
        'entity_id': e.get('id'),
        'entity_sector': e.get('sector'),
        'entity_industry': e.get('industry'),
        'entity_country': e.get('country'),
        'entity_ticker': _primary_ticker(e),
    }
    for e in entities_meta
])

if not df_all.empty:
    if not meta_df.empty:
        df_all = df_all.merge(meta_df, on='entity_id', how='left')
    else:
        for col in ['entity_sector', 'entity_industry', 'entity_country', 'entity_ticker']:
            df_all[col] = None

print(f"✅ Enriched with metadata for {len(meta_df)} entities")

✅ Enriched with metadata for 5 entities

In [13]:
from concurrent.futures import ThreadPoolExecutor

df_all = df_all.rename(columns={
            'entity_id': 'rp_entity_id',
            'document_id': 'rp_document_id',
            'timestamp': 'timestamp_utc',
        })

# Cost control: cap the OpenAI labeling call to ~10 rows total, balanced across
# provider- and user-narrative search hits so the small sample can plausibly
# contain both roles.
if not df_all.empty:
    df_all_for_labeling = pd.concat([
        df_all[df_all['role_hint'] == 'provider'].head(5),
        df_all[df_all['role_hint'] == 'user'].head(5),
    ]).drop_duplicates(subset=['sentence_id']).reset_index(drop=True)
else:
    df_all_for_labeling = df_all


def _run_labeling(sentences):
    # Run in a dedicated thread with its own fresh event loop -- avoids nest_asyncio
    # (see setup cell above) so the async OpenAI client's httpx/anyio internals work
    # correctly even though the notebook kernel already has a running event loop.
    with ThreadPoolExecutor(max_workers=1) as executor:
        future = executor.submit(
            run_ai_cost_cutting_prompt,
            sentences=sentences,
            masked_2=True,
            batch_size=10,
            open_ai_credentials=OPENAI_API_KEY,
        )
        return future.result()


if not df_all_for_labeling.empty:
    df_all_labeled = _run_labeling(df_all_for_labeling)
else:
    df_all_labeled = df_all_for_labeling.assign(label=[], motivation=[])

print(f"✅ Labeled {len(df_all_labeled)} rows")

  0%|          | 0/1 [00:00<?, ?it/s]

2026-08-14 09:23:04,247 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

100%|██████████| 1/1 [00:12<00:00, 12.74s/it]

100%|██████████| 1/1 [00:12<00:00, 12.74s/it]

✅ Labeled 10 rows

In [14]:
if not df_all_labeled.empty:
    df_all_labeled_transform = transform_to_reference_format(df_all_labeled)
    df_providers = df_all_labeled_transform[df_all_labeled_transform["label"] == "P"].copy()
    df_providers.reset_index(drop=True, inplace=True)
    df_users = df_all_labeled_transform[df_all_labeled_transform["label"] == "A"].copy()
    df_users.reset_index(drop=True, inplace=True)
else:
    df_all_labeled_transform = df_all_labeled
    df_providers = df_all_labeled.copy()
    df_users = df_all_labeled.copy()

print(f"✅ Providers: {len(df_providers)} rows | Users: {len(df_users)} rows")

✅ Providers: 0 rows | Users: 0 rows

## Visualizations

## Sector-Based AI Cost Cutting Technology Visualization

The following visualizations provide a sector-by-sector breakdown of companies involved in AI cost cutting technology. These charts help identify:

- **Industry Patterns**: Which sectors show more AI cost cutting activity
- **Technology Leaders**: Companies most frequently mentioned in AI cost cutting contexts within each sector  

Each bar represents the frequency of AI cost cutting mentions, with hover details providing the underlying news narrative that shaped each company's role in the AI cost cutting ecosystem.

### Companies Providing AI Cost Cutting Solutions

This chart displays companies that have been most frequently mentioned as providers of AI cost cutting technology, organized by sector and ranked by total mention volume. The visualization reveals which companies and industries are leading the development and supply of AI solutions for operational cost reduction.

In [15]:
if not df_providers.empty:
    plot_top_companies_by_sector(df_providers, min_companies=1, title_suffix="(AI Cost Cutting Providers)", top_sectors=4, interactive=interactive_plots)
else:
    print("No provider-labeled rows in this cost-controlled sample -- skipping providers-by-sector chart")

No provider-labeled rows in this cost-controlled sample -- skipping providers-by-sector chart

### Companies Using AI for Cost Cutting

This complementary chart shows companies most frequently mentioned as users of AI cost cutting technology in their operations, organized by sector and ranked by total mention volume. It identifies firms investing in AI automation, implementing cost reduction systems, or optimizing their operations through AI-driven efficiency improvements.

In [16]:
if not df_users.empty:
    plot_top_companies_by_sector(df_users, min_companies=1, title_suffix="(AI Cost Cutting Users)", top_sectors=4, interactive=interactive_plots)
else:
    print("No user-labeled rows in this cost-controlled sample -- skipping users-by-sector chart")

No user-labeled rows in this cost-controlled sample -- skipping users-by-sector chart

## AI Cost Cutting Ecosystem Analysis

This comprehensive assessment combines both provider and user signals to create a complete picture of the AI cost cutting ecosystem. The analysis provides:

- **Total Exposure**: Overall volume of AI cost cutting related news coverage for each company
- **Role Classification**: Relative proportion of provider versus user mentions  
- **Market Positioning**: How companies rank in terms of their involvement in the AI cost cutting market

The stacked bar chart shows the percentage breakdown of provider (green) versus user (red) mentions for the top 40 most-mentioned companies. Companies with predominantly blue bars are primarily technology providers, while those with green bars are mainly end-users implementing AI cost cutting solutions.

In [17]:
if not df_providers.empty or not df_users.empty:
    companies_basket = identify_basket_and_plot_confidence(df_providers, df_users, basket_size=40, theme_name='AI Cost Cutting', positive_label='Providers', negative_label='Users', interactive=interactive_plots)
else:
    print("No provider- or user-labeled rows in this cost-controlled sample -- skipping ecosystem basket chart")
    companies_basket = pd.DataFrame(columns=['Company', 'positive_exp', 'negative_exp', 'total_exposure'])

No provider- or user-labeled rows in this cost-controlled sample -- skipping ecosystem basket chart

In [18]:
companies_basket.head()

Empty DataFrame
Columns: [Company, positive_exp, negative_exp, total_exposure]
Index: []

## Top Companies Time Tracking

This visualization tracks the newsflow arrival across time for the top 4 companies most mentioned as users in AI cost cutting contexts, providing transparency about news content and media attention over time.

In [19]:
if not df_users.empty:
    top_companies_time(df_users, interactive=interactive_plots)
else:
    print("No user-labeled rows in this cost-controlled sample -- skipping top companies time chart")

No user-labeled rows in this cost-controlled sample -- skipping top companies time chart

## Provider-User Network Analysis

This network visualization reveals relationships between AI cost cutting technology providers and users through co-mentions in news articles. The analysis identifies:

- **Technology Partnerships**: Companies that frequently appear together in AI cost cutting contexts
- **Customer-Supplier Relationships**: Connections between solution providers and implementing organizations
- **Market Clusters**: Groups of companies operating in similar segments of the AI cost cutting ecosystem

Notable partnerships that may emerge include relationships between AI platform providers and enterprise users, automation vendors and operational teams, and technology developers working with early adopters to refine their cost cutting solutions.

In [20]:
if not df_users.empty and not df_providers.empty:
    fig = provider_adopter_net(
        df_filtered_adopters=df_users,
        df_filtered_providers=df_providers,
        bigdata_cred=None,
        min_occurrences=1, # Change this if you want to see fewer companies in the network
        dash=False,
        interactive=interactive_plots
    )
else:
    print("Need at least one provider- and one user-labeled row in this cost-controlled sample -- skipping provider-adopter network")
    fig = None

Need at least one provider- and one user-labeled row in this cost-controlled sample -- skipping provider-adopter network

## Key Insights and Technology Stories

The AI cost cutting analysis reveals distinct sector-specific adoption patterns and technology leadership dynamics:

**Financial Services AI Implementation**: Morgan Stanley Co. emerges as the dominant user in the Financials sector, demonstrating how traditional financial institutions are rapidly adopting AI cost cutting solutions to streamline operations, automate processes, and enhance operational efficiency in an increasingly competitive landscape.

**Cross-Sector Technology Versatility**: Amazon.com Inc. stands out in the Consumer sector as a unique dual-role player, simultaneously serving as both a leading provider of AI cost cutting solutions and a major implementer of these technologies in its own operations, showcasing the company's comprehensive AI ecosystem strategy.

**Technology Sector Innovation Hub**: The Technology sector reveals a clear hierarchy with NVIDIA leading as the primary provider of AI cost cutting infrastructure, while Microsoft and Alphabet dominate the broader provider landscape, reflecting their strategic positioning in enterprise AI solutions and cloud-based cost optimization platforms.

**Industrial Sector Digital Transformation**: Klarna Bank AB's prominence in the Industrials sector highlights the broader trend of fintech and digital-first companies driving AI adoption within traditionally industrial classifications, indicating how sector boundaries are evolving with digital transformation.

## Export the Results

Export the data as Excel files for further analysis or to share with the team.

In [21]:
try:
    with pd.ExcelWriter(export_path) as writer:
        df_providers.to_excel(writer, sheet_name="AI Cost Cutting Providers", index=False)
        df_users.to_excel(writer, sheet_name="AI Cost Cutting Users", index=False)
        companies_basket.to_excel(writer, sheet_name="Technology Ecosystem Basket", index=False)

    print(f"✅ Results exported to {export_path}")

except Exception as e:
    print(f"Warning while exporting to excel: {e}")

✅ Results exported to output/ai_cost_cutting_analysis_results.xlsx

In [22]:
print("Runtime:", datetime.datetime.now() - start)

Runtime: 0:00:31.890030