# Narrative Miners: Uncover the Stories That Drive Markets

## Automated Analysis of Market Narratives Across Multiple Document Sources

## Why It Matters

Understanding how market narratives emerge and evolve across different information sources is crucial for investment decision-making, but manually tracking narrative development across scattered news coverage, earnings calls, and regulatory filings is time consuming. Investment decisions need systematic analysis of narrative progression to identify emerging trends and timing patterns.

## What It Does

The `NarrativeMiner` class in the bigdata-research-tools package systematically tracks narrative evolution across multiple document types using unstructured data from news, transcripts, and filings. Built for analysts, portfolio managers, and investment professionals, it transforms scattered narrative signals into quantified trend intelligence and identifies timing patterns across different information sources.

## How It Works

The `NarrativeMiner` combines **multi-source content retrieval**, **temporal narrative tracking**, and **cross-source comparative analysis** to deliver:

- **Cross-document narrative mapping** across news media, earnings calls, and SEC filings
- **Temporal evolution tracking** showing how narratives develop and change over time across sources
- **Intensity measurement** quantifying narrative prevalence and significance across document types

## A Real-World Use Case

This cookbook demonstrates the complete workflow through analyzing "AI Bubble Concerns" narrative as it emerges and evolves across news, earnings calls, and regulatory filings, highlighting the difference between public discourse and corporate communications.

## Setup and Imports

## Async Compatibility Setup

**Run this cell first** - Required for Google Colab, Jupyter Notebooks, and VS Code with Jupyter extension:

### Why is this needed?

Interactive environments (Colab, Jupyter) already have an asyncio event loop running. When bigdata-research-tools makes async API calls (like to OpenAI), you'll get this error without nest_asyncio:

```
RuntimeError: asyncio.run() cannot be called from a running event loop
```

The `nest_asyncio.apply()` command patches this to allow nested event loops.

💡 **Tip**: If you're unsure which environment you're in, just run the cell below - it won't hurt in any environment!

In [1]:
import datetime
start = datetime.datetime.now()

try:
    import asyncio
    asyncio.get_running_loop()
    import nest_asyncio; nest_asyncio.apply()
    print("✅ nest_asyncio applied")
except (RuntimeError, ImportError):
    print("✅ nest_asyncio not needed or not available")

✅ nest_asyncio applied

## Environment Setup

The following cell configures the necessary path for the analysis

In [2]:
import os
import sys

current_dir = os.getcwd()
if current_dir not in sys.path:
    sys.path.append(current_dir)
print(f"✅ Local environment setup complete")

✅ Local environment setup complete

## Import Required Libraries

Import the core libraries needed for narrative mining analysis, including the custom visualization and analysis tools.

In [3]:
from IPython.display import display, HTML, IFrame
import pandas as pd
from pandas import merge

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from datetime import datetime
import warnings

from src.tool import (
    load_results, 
    extract_narrative_insights,
    create_source_summary,
    display_sample_data,
    visualize_cross_source_narratives, 
    visualize_news_narrative_breakdown
)

from bigdata_research_tools.workflows.narrative_miner import NarrativeMiner
from bigdata_research_tools.excel import ExcelManager
from bigdata_client import Bigdata
from bigdata_client.daterange import RollingDateRange
from bigdata_client.models.sources import Source
from bigdata_client.models.search import DocumentType

## Optional: Plotly Display Configuration

For better visualization rendering, you can also set the Plotly renderer:

In [4]:
import plotly
import plotly.graph_objects as go
import plotly.io as pio

# Try to detect the environment and set appropriate renderer
try:
    # Check if we're in JupyterLab
    import os
    if 'JUPYTERHUB_SERVICE_PREFIX' in os.environ or 'JPY_SESSION_NAME' in os.environ:
        pio.renderers.default = 'jupyterlab'
        print("✅ Plotly configured for JupyterLab")
    else:
        # Default for VS Code, Jupyter Notebook, etc.
        pio.renderers.default = 'plotly_mimetype+notebook'
        print("✅ Plotly configured for Jupyter/VS Code")
except:
    # Fallback to a more universal renderer
    pio.renderers.default = 'notebook'
    print("✅ Plotly configured with fallback renderer")

✅ Plotly configured for Jupyter/VS Code

/opt/anaconda/envs/pricing_power/lib/python3.11/site-packages/kaleido/__init__.py:14: UserWarning:



Warning: You have Plotly version 5.24.1, which is not compatible with this version of Kaleido (1.0.0).

This means that static image generation (e.g. `fig.write_image()`) will not work.

Please upgrade Plotly to version 6.1.1 or greater, or downgrade Kaleido to version 0.2.1.

## Define Output Paths

We define the output paths for our narrative mining results.

In [5]:
# Define output file paths for our results
output_dir = "output"
os.makedirs(output_dir, exist_ok=True)

news_results_path = f"{output_dir}/ai_bubble_news.xlsx"
visualization_path = f"{output_dir}/ai_bubble_narratives.html"

## Load Credentials

In [6]:
from dotenv import load_dotenv
from pathlib import Path

script_dir = Path(__file__).parent if '__file__' in globals() else Path.cwd()
load_dotenv(script_dir / '.env')

BIGDATA_USERNAME = os.getenv('BIGDATA_USERNAME')
BIGDATA_PASSWORD = os.getenv('BIGDATA_PASSWORD')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

if not all([BIGDATA_USERNAME, BIGDATA_PASSWORD, OPENAI_API_KEY]):
    print("❌ Missing required environment variables")
    raise ValueError("Missing required environment variables. Check your .env file.")
else:
    print("✅ Credentials loaded from .env file")

✅ Credentials loaded from .env file

## Connecting to Bigdata

Create a Bigdata object with your credentials.

In [7]:
bigdata = Bigdata(BIGDATA_USERNAME, BIGDATA_PASSWORD)

## Defining the Narrative Analysis Parameters

### Fixed Parameters
- **AI Bubble Narratives** (`main_narratives`): Specific narrative sentences related to AI bubble concerns
- **Common Parameters** (`common_params`): Shared configuration across all narrative miners
- **Model Selection** (`llm_model`): The LLM model used for narrative labeling and analysis
- **Time Period** (`start_date` and `end_date`): The date range over which to run the analysis
- **Rerank Threshold** (`rerank_threshold`): Cross-encoder threshold for result relevance filtering
- **Document Limits** (`document_limit`): Maximum number of documents to retrieve per query
- **Search Frequency** (`freq`): Frequency of date ranges for search operations

In [9]:
# AI Bubble Narratives
main_narratives = ['A proposed tax impacting companies employing H-1B visa holders.',
 'New tax may hinder recruitment of skilled H-1B visa workers.',
 'Higher costs may deter companies from hiring H-1B visa candidates.',
 'Companies may prioritize domestic candidates over H-1B visa applicants.',
 'Tax may exacerbate shortages in specialized skills from H-1B visa workers.',
 'Companies may alter recruitment strategies to minimize H-1B visa reliance.',
 'Tax increases operational costs for companies employing H-1B visa workers.',
 'Companies may need to allocate budgets for new H-1B visa taxes.',
 'Increased costs from H-1B visa taxes may reduce profit margins.',
 'Companies may reassess the financial viability of hiring H-1B visa workers.',
 'Companies may restructure operations to offset H-1B visa tax costs.',
 "Tax may affect companies' competitiveness in the global market.",
 'Higher costs may weaken competitiveness against international firms not facing H-1B visa taxes.',
 'Companies may need to adjust pricing due to increased H-1B visa costs.',
 'Competitors may attract H-1B visa talent by offering better conditions.',
 'Companies may need to rethink global strategies to attract H-1B visa talent.',
 'Tax influences long-term workforce planning regarding H-1B visa employees.',
 'Companies may struggle to develop a robust talent pipeline for H-1B visa roles.',
 'Tax may influence decisions to onshore or offshore roles typically filled by H-1B visa workers.',
 'Tax may limit diversity by reducing H-1B visa hiring.',
 'Companies may need to reassess skill requirements due to H-1B visa tax.',
 'Tax may impact innovation driven by H-1B visa talent.',
 'Reduced H-1B visa hiring may limit research and development initiatives.',
 'Tax may disrupt the flow of innovative ideas from H-1B visa workers.',
 'Tax may hinder collaboration with international H-1B visa talent.',
 'Reduced H-1B visa workforce may slow technological advancements.']
 
# LLM Specification
llm_model = "openai::gpt-4o-mini"


# Specify Time Range
start_date = "2025-09-19"
end_date = "2025-10-06"

# Rerank Threshold
rerank_threshold = 0.7

# Search Frequency
freq = 'D'

# Fiscal Year
fiscal_year = 2025

# Document Limits
document_limit = 100

# Commen Params
common_params = {
    "narrative_sentences": main_narratives,
    "llm_model": llm_model,
    "start_date": start_date,
    "end_date": end_date,
    "rerank_threshold": rerank_threshold}

## Configure the Narrative Miners

Create narrative miners for each document type. In this example, we select MT Newswires as the news source.

In [10]:
# Common Params
common_params = {
    "narrative_sentences": main_narratives,
    "llm_model": llm_model,
    "start_date": start_date,
    "end_date": end_date,
    "rerank_threshold": rerank_threshold}
    

# Create the specialized miners for each document type
news_miner = NarrativeMiner(
    document_type=DocumentType.NEWS,
    fiscal_year=None,
    **common_params
)

## Run Narrative Mining

Execute the narrative mining processes for news:

In [11]:
# Mine news narratives
print("Mining news narratives...")
try:
    news_results = news_miner.mine_narratives(
        document_limit=document_limit,
        freq=freq,
        export_path=news_results_path
    )
    print("✅ News mining completed successfully!")
except Exception as e:
    print(f"Warning during news mining: {e}")


df = news_results["df_labeled"]
#df.to_csv("news_results_labeled_oct.csv", index=False)

Mining news narratives...

Querying Bigdata...: 100%|██████████| 468/468 [06:34<00:00,  1.19it/s]
Processing screening results...: 100%|██████████| 9682/9682 [00:02<00:00, 4746.90it/s]
Querying OpenAI...: 100%|██████████| 12158/12158 [11:57<00:00, 16.94it/s]

✅ News mining completed successfully!

In [13]:
df = pd.read_csv("news_results_labeled_oct.csv")

df_narrative_search = df.copy()
#df_narrative_search = news_results["df_labeled"]

In [14]:
df_sentence_unique = df_narrative_search.drop_duplicates(subset=["Sentence ID"]).reset_index(drop=True)
print(len(df_narrative_search))
print(len(df_sentence_unique))

118587
5369

## Theme Match Labeling

This labeling is to filter out the retrieved chunks that are not about the main_theme

In [12]:
from src.labeler.narrative_labeler import NarrativeLabeler
labeler = NarrativeLabeler(llm_model=llm_model)

In [ ]:
df_sentence_unique_labeled = labeler.get_labels(
    main_theme="Introduction of a high fee on H-1B visas",
    texts=df_sentence_unique["Chunk Text"].tolist(),
    titles=df_sentence_unique["Headline"].tolist(),
    mode="theme_matching",
)

In [18]:
df_sentence_unique_labeled.rename(columns={"label": "Theme Matching Label", "motivation": "Theme Matching Motivation"}, inplace=True)
df_sentence_unique_labeled_merged = merge(df_sentence_unique, df_sentence_unique_labeled, left_index=True, right_index=True)

# Select columns from df_sentence_unique_labeled_filtered
columns_to_merge = df_sentence_unique_labeled_merged[['Sentence ID', 'Theme Matching Label', 'Theme Matching Motivation']]

# Merge with df on Sentence ID
df_sentences_merged = df.merge(columns_to_merge, on='Sentence ID', how='left')
df_sentences_related = df_sentences_merged[df_sentences_merged["Theme Matching Label"] != "unclear"]

df_sentences_related.to_csv("news_results_labeled.csv", index=False)

In [ ]:
#df_sentences_related = pd.read_csv("news_results_labeled.csv")

# Creating the DF

In [14]:
df = df_sentences_related.copy()
df_company = df[df["Entity Type"] == "COMP"]

In [15]:
# Donald Trump Dataframe
df_DonaldTrump = df[df["Entity"] == "Donald Trump"]

# US Dataframe
df_US = df[df["Country Code"] == "United States"]

In [16]:
#Top three People Entities after Donald Trump
counts = df[df["Entity Type"] == "PEOP"]["Entity"].value_counts()
top_3 = counts[counts.index != "Donald Trump"].head(3).index.tolist()

top_3_dict_entities = {}
for name in top_3:
    top_3_dict_entities[name] = df[df["Entity"] == name]

print(top_3_dict_entities.keys())

dict_keys(['Howard Lutnick', 'Jamie Dimon', 'Elon Musk'])

In [17]:
# Get top 3 companies from United States
counts = df_US[df_US["Entity Type"] == "COMP"]["Entity"].value_counts()
top_3_companies_US = counts.head(3).index.tolist()

# Create dictionary with dataframes for each top 5 company
top_3_companies_US_dict = {}
for company in top_3_companies_US:
    top_3_companies_US_dict[company] = df_US[df_US["Entity"] == company]

print(top_3_companies_US_dict.keys())

dict_keys(['Amazon.com Inc.', 'Microsoft Corp.', 'Alphabet Inc.'])

In [18]:
# Get value counts for places excluding India and United States
counts = df[df["Entity Type"] == "PLCE"]["Country Code"].value_counts()
top_3_places = counts[~counts.index.isin(["United States", "India"])].head(3).index.tolist()

# Create dictionary with dataframes for each top 3 place using Country Code
top_3_places_dict = {}
for place in top_3_places:
    top_3_places_dict[place] = df[df["Country Code"] == place]

print(top_3_places_dict.keys())

dict_keys(['China', 'Canada', 'United Kingdom'])

In [19]:
# Create dictionary of dictionaries with top 3 companies for each place
top_3_places_companies = {}

for place in top_3_places:
    df_place = top_3_places_dict[place]
    counts = df_place[df_place["Entity Type"] == "COMP"]["Entity"].value_counts()
    top_3_companies = counts.head(3).index.tolist()
    print(top_3_companies)
    companies_dict = {}
    for company in top_3_companies:
        companies_dict[company] = df_place[df_place["Entity"] == company]
    
    top_3_places_companies[place] = companies_dict

print(top_3_places_companies.keys())

['IBM Corp. Pty. Ltd.', 'Dewang', 'Metaview']
['Thomson Reuters Corp.', 'DBRS Ltd.', 'Talent Fund']
['The Financial Times Ltd.', 'Crossbridge Capital LLP', 'AJ Bell PLC']
dict_keys(['China', 'Canada', 'United Kingdom'])

# LABELING

In [20]:
from src.labeler.screener_labeler import ScreenerLabelerFlex
from src.labeler.narrative_labeler import NarrativeSummarizerFlex

## Trump Position

In [21]:
# Convert Date column to datetime for proper sorting
df_DonaldTrump_refined = df_DonaldTrump.copy()
df_DonaldTrump_refined['Date'] = pd.to_datetime(df_DonaldTrump_refined['Date'])

# Sort by Date (oldest first)
df_DonaldTrump_refined = df_DonaldTrump_refined.sort_values('Date')

# Remove duplicates keeping the first occurrence (oldest)
df_DonaldTrump_refined = df_DonaldTrump_refined.drop_duplicates(subset='Chunk Text', keep='first')

# Reset index
df_DonaldTrump_refined = df_DonaldTrump_refined.reset_index(drop=True)

print(len(df_DonaldTrump_refined))
print(len(df_DonaldTrump))

542
1781

In [22]:
import importlib
import sys

# Remove the module from cache if it exists
if 'src.labeler.narrative_labeler' in sys.modules:
    del sys.modules['src.labeler.narrative_labeler']

# Force reimport
from src.labeler.narrative_labeler import NarrativeLabeler
importlib.reload(sys.modules['src.labeler.narrative_labeler'])

import importlib
from src.prompts import labeler
importlib.reload(labeler)
from src.prompts.labeler import get_narrative_system_prompt
from src.prompts import labeler

## Extract Donald Trump direct references

In [28]:
labeler = NarrativeLabeler(llm_model=llm_model)
df_DT_citation = labeler.get_labels(
    main_theme="Introduction of a high fee on H-1B visas",
    texts=df_DonaldTrump_refined["Chunk Text"].tolist(),
    titles=df_DonaldTrump_refined["Headline"].tolist(),
    mode="entity_reference",
    entity_track="Donald Trump"
)

Querying OpenAI...:   0%|          | 0/542 [00:00<?, ?it/s]

Querying OpenAI...: 100%|██████████| 542/542 [00:22<00:00, 24.10it/s]

In [29]:
df_DT_theme_matching = merge(df_DonaldTrump_refined, df_DT_citation, left_index=True, right_index=True)
df_DT_theme_matching.loc[df_DT_theme_matching["label"] == "unclear", "label"] = "narrative"
df_DT_theme_matching_citation = df_DT_theme_matching[df_DT_theme_matching["label"] == "quote"]
df_DT_theme_matching_citation.replace(to_replace="unclear", value="narrative", inplace=True)

df_DT_theme_matching_narrative = df_DT_theme_matching[df_DT_theme_matching["label"] == "narrative"]

df_DT_theme_matching_citation.to_csv("news_results_labeled_citation.csv", index=False)
df_DT_theme_matching_narrative.to_csv("news_results_labeled_narrative.csv", index=False)

/tmp/ipykernel_26210/2741400982.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
#df_DT_theme_matching_citation = pd.read_csv("news_results_labeled_citation.csv")
#df_DT_theme_matching_narrative = pd.read_csv("news_results_labeled_narrative.csv")

In [24]:
import importlib
import sys

# Remove the module from cache if it exists
if 'src.labeler.narrative_labeler' in sys.modules:
    del sys.modules['src.labeler.narrative_labeler']

# Force reimport
from src.labeler.narrative_labeler import NarrativeLabeler, NarrativeSummarizerFlex
importlib.reload(sys.modules['src.labeler.narrative_labeler'])

import importlib
from src.prompts import labeler
importlib.reload(labeler)
from src.prompts.labeler import get_narrative_system_prompt
from src.prompts import labeler
from src.labeler.narrative_labeler import NarrativeLabeler, NarrativeSummarizerFlex

In [25]:
narrative_summarizer = NarrativeSummarizerFlex(llm_model="openai::gpt-4o")

# Sort and initialize columns once
df_DT_theme_matching_citation = df_DT_theme_matching_citation.sort_values('Date')
df_DT_theme_matching_citation["daily summary"] = None
df_DT_theme_matching_citation["daily bullet points"] = None

# Initialize cumulative dictionary
previous_narrative_dict = {}

narrative_dates = df_DT_theme_matching_citation["Date"].unique()

In [47]:


for date in narrative_dates:
    df_temp = df_DT_theme_matching_citation[df_DT_theme_matching_citation["Date"] == date]
    
    # Get daily recap
    daily_recap = narrative_summarizer.get_summaries(
        main_theme="Introduction of a high fee on H-1B visas",
        df=df_temp,
        mode="temporal_narrative", 
        entity_track="Donald Trump",
        previous_narrative=previous_narrative_dict
    )
    
    # Extract results
    summary = daily_recap["summary"].iloc[0]
    key_points = daily_recap["key_points"].iloc[0]
    
    # Convert key_points list to string with newlines
    if isinstance(key_points, list):
        key_points_str = "\n".join(key_points)
    else:
        key_points_str = str(key_points) if key_points is not None else ""
    
    print("Summary:", summary)
    print("Key points:", key_points_str)
    
    # Update dataframe - now using the string version
    mask = df_DT_theme_matching_citation["Date"] == date
    df_DT_theme_matching_citation.loc[mask, "daily summary"] = summary
    df_DT_theme_matching_citation.loc[mask, "daily bullet points"] = key_points_str
    
    # Add to cumulative dictionary for next iteration - CONVERT DATE TO STRING
    date_str = str(date)  # Convert Timestamp to string
    if isinstance(key_points, list):
        previous_narrative_dict[date_str] = summary + "\n" + "\n".join(key_points)
    else:
        previous_narrative_dict[date_str] = summary + "\n" + str(key_points)

df_DT_theme_matching_citation.to_csv("news_results_labeled_citation_summarized.csv", index=False)

================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries with bullet points based on some daily quotes about 'Donald Trump' coming from news articles.
The content of the summaries and the bullet points must only be related to the theme 'Introduction of a high fee on H-1B visas'. If some part of the information does not relate to 'Introduction of a high fee on H-1B visas', do not include it in the summary or in the bullet points.

You will receive:
    - Multiple sentences from news articles

Please adhere strictly to the following guidelines:

1. **Task**:
    - Your task is to analyze today's quotes about 'Donald Trump'

2. **Create an updated summary that**:
    - Primarily focuses on the quotes from 'Donald Trump'
    - Create a summary of the quotes from 'Donald Trump'

3. **Generate bullet points that**:
    - Contain the actual quotes (direct citations) from today's articles
    - Each bullet should include the verbatim text fro
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Quote_1": "\"I think they're going to be very happy,\n\" Trump said, anticipating the tech industry's response to the changes.\nAdditionally, White House staff secretary Will Scharf said,\n\"One of the most abused visa systems is the H1-B non-immigrant visa programme. This is supposed to allow highly skilled labourers who work in fields that Americans don't work in to come into the United States of America. What this proclamation will do is raise the fee that companies pay to sponsor H-1B applicants to $100,000. This will ensure that the people they're bringing in are actually very highly skilled and that they're not replaceable by American workers.\\\"It is noteworthy that Melania Trump, formerly Melania Knauss, received an H-1B visa in October 1996 for modelling work; she hails from Slovenia.", "Quote_2": "\"We need workers, we need great workers and this pretty much ensure that that's going to happen,\" Trump said.\nCommerce Secretary Howard Lutnick said that the new fee will prev
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.04s/it]

Summary: Donald Trump expressed optimism about the tech industry's reaction to the introduction of a high fee on H-1B visas, which is aimed at ensuring that only highly skilled workers are brought into the U.S. The new fee of $100,000 is intended to discourage the replacement of American workers and promote the hiring of domestic talent.
Key points: "I think they're going to be very happy," Trump said, anticipating the tech industry's response to the changes.
"One of the most abused visa systems is the H1-B non-immigrant visa programme. This is supposed to allow highly skilled labourers who work in fields that Americans don't work in to come into the United States of America. What this proclamation will do is raise the fee that companies pay to sponsor H-1B applicants to $100,000."
"We need workers, we need great workers and this pretty much ensure that that's going to happen," Trump said.
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries with bullet points based on some daily quotes about 'Donald Trump' coming from news articles.
You are also given cumulative narrative summaries from recent past days about 'Donald Trump'. These summaries were generated by previous iterations of this same prompt and represent the historical context.
The content of the summaries and the bullet points must only be related to the theme 'Introduction of a high fee on H-1B visas'. If some part of the information does not relate to 'Introduction of a high fee on H-1B visas', do not include it in the summary or in the bullet points.

You will receive:
    - Historical narrative summaries from recent past days about 'Donald Trump'
    - Multiple sentences from news articles

Please adhere strictly to the following guidelines:

1. **Task**:
    - Your task is to analyze today's quotes about 'Donald Trump' against the historical narrative t
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Narrative day 1": "Donald Trump expressed optimism about the tech industry's reaction to the introduction of a high fee on H-1B visas, which is aimed at ensuring that only highly skilled workers are brought into the U.S. The new fee of $100,000 is intended to discourage the replacement of American workers and promote the hiring of domestic talent.\n\"I think they're going to be very happy,\" Trump said, anticipating the tech industry's response to the changes.\n\"One of the most abused visa systems is the H1-B non-immigrant visa programme. This is supposed to allow highly skilled labourers who work in fields that Americans don't work in to come into the United States of America. What this proclamation will do is raise the fee that companies pay to sponsor H-1B applicants to $100,000.\"\n\"We need workers, we need great workers and this pretty much ensure that that's going to happen,\" Trump said.", "Quote_1": "Major technology companies and foreign governments are rushing to respond
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.14s/it]

Summary: Donald Trump has reiterated his administration's commitment to imposing a high fee on H-1B visas, raising it from $215 to $100,000 annually. This significant increase is aimed at discouraging the hiring of foreign workers in favor of American talent. Trump believes that this move will ensure that companies prioritize hiring skilled American workers. He has claimed that the new fee will be beneficial for the U.S. workforce, despite concerns from tech companies about the potential negative impact on their operations. The administration has framed this fee increase as a response to what they describe as systemic abuse of the H-1B program.
Key points: President Donald Trump announced plans to impose a $100,000 annual fee on H-1B visas, threatening to upend the program that underpins America's technology workforce.
Trump argued that America needs 'great workers' and that the newly imposed fee 'pretty much ensures that that's what's going to happen.'
The move is expected to significantly impact Indian technology workers who are hired by tech companies and others on H-1B visas.
Trump stated, 'The company needs to decide... is the person valuable enough to have $100,000 a year payment to the government? Or they should head home and they should go hire an American.'
The Donald Trump administration's decision to sharply hike H-1B visa fees has resulted in top companies like Meta and Microsoft recalling their H-1B visa holders to the US.
Trump accused IT outsourcing firms of 'systemic abuse' of the H-1B programme and branded it a 'national security threat.'
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries with bullet points based on some daily quotes about 'Donald Trump' coming from news articles.
You are also given cumulative narrative summaries from recent past days about 'Donald Trump'. These summaries were generated by previous iterations of this same prompt and represent the historical context.
The content of the summaries and the bullet points must only be related to the theme 'Introduction of a high fee on H-1B visas'. If some part of the information does not relate to 'Introduction of a high fee on H-1B visas', do not include it in the summary or in the bullet points.

You will receive:
    - Historical narrative summaries from recent past days about 'Donald Trump'
    - Multiple sentences from news articles

Please adhere strictly to the following guidelines:

1. **Task**:
    - Your task is to analyze today's quotes about 'Donald Trump' against the historical narrative t
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Narrative day 1": "Donald Trump expressed optimism about the tech industry's reaction to the introduction of a high fee on H-1B visas, which is aimed at ensuring that only highly skilled workers are brought into the U.S. The new fee of $100,000 is intended to discourage the replacement of American workers and promote the hiring of domestic talent.\n\"I think they're going to be very happy,\" Trump said, anticipating the tech industry's response to the changes.\n\"One of the most abused visa systems is the H1-B non-immigrant visa programme. This is supposed to allow highly skilled labourers who work in fields that Americans don't work in to come into the United States of America. What this proclamation will do is raise the fee that companies pay to sponsor H-1B applicants to $100,000.\"\n\"We need workers, we need great workers and this pretty much ensure that that's going to happen,\" Trump said.", "Narrative day 2": "Donald Trump has reiterated his administration's commitment to imp
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:09<00:00,  9.85s/it]

Summary: Donald Trump has officially signed a proclamation imposing a $100,000 fee on H-1B visa applications, a significant increase aimed at curbing program abuse and protecting American jobs. This move is framed as a response to the perceived systemic abuse of the H-1B program, which Trump claims has led to the replacement of American workers with lower-paid foreign labor. The administration argues that the new fee will incentivize companies to hire American workers instead. This announcement has raised concerns among tech companies that rely on H-1B visa holders, as they are now advising their employees to avoid international travel or return to the U.S. before the policy takes effect. The White House has reiterated that this fee increase is part of a broader strategy to address national security threats and the undercutting of wages in the U.S. workforce.
Key points: U.S. President Donald Trump on Friday signed a proclamation raising the fee that companies pay to sponsor H-1B applicants to 100,000 dollars, saying the move is intended to ensure that the United States brings in highly skilled talent whom American workers cannot replace.
Following the announcement, companies such as Microsoft and Amazon have advised H-1B employees to avoid international travel or return to the United States before the policy takes effect.
Trump said that companies would rather not pay the new fee, and hiring Americans would serve that purpose. 'So there's an incentive to hire American,' he said.
The White House claims companies are replacing U.S. workers with lower-paid foreign labor, citing instances of layoffs alongside H-1B approvals.
Trump's $100,000 H-1B fee is economic suicide for America. It will force Indian talent to go home, taking with them skills, savings, and global experience.
The administration warned that continued misuse of the H-1B program could discourage future American workers from pursuing STEM careers, posing potential risks to national security.
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries with bullet points based on some daily quotes about 'Donald Trump' coming from news articles.
You are also given cumulative narrative summaries from recent past days about 'Donald Trump'. These summaries were generated by previous iterations of this same prompt and represent the historical context.
The content of the summaries and the bullet points must only be related to the theme 'Introduction of a high fee on H-1B visas'. If some part of the information does not relate to 'Introduction of a high fee on H-1B visas', do not include it in the summary or in the bullet points.

You will receive:
    - Historical narrative summaries from recent past days about 'Donald Trump'
    - Multiple sentences from news articles

Please adhere strictly to the following guidelines:

1. **Task**:
    - Your task is to analyze today's quotes about 'Donald Trump' against the historical narrative t
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Narrative day 1": "Donald Trump expressed optimism about the tech industry's reaction to the introduction of a high fee on H-1B visas, which is aimed at ensuring that only highly skilled workers are brought into the U.S. The new fee of $100,000 is intended to discourage the replacement of American workers and promote the hiring of domestic talent.\n\"I think they're going to be very happy,\" Trump said, anticipating the tech industry's response to the changes.\n\"One of the most abused visa systems is the H1-B non-immigrant visa programme. This is supposed to allow highly skilled labourers who work in fields that Americans don't work in to come into the United States of America. What this proclamation will do is raise the fee that companies pay to sponsor H-1B applicants to $100,000.\"\n\"We need workers, we need great workers and this pretty much ensure that that's going to happen,\" Trump said.", "Narrative day 2": "Donald Trump has reiterated his administration's commitment to imp
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.69s/it]

Summary: Donald Trump has reiterated his administration's commitment to the $100,000 fee on H-1B visas, emphasizing its role in curbing program abuse and promoting the hiring of American workers. This fee is positioned as a one-time charge for new applications, which has caused confusion among tech companies. Trump believes that the fee will incentivize companies to prioritize American talent over foreign workers, despite concerns about its potential negative impact on industries reliant on skilled foreign labor. The administration continues to frame this move as a necessary step to address systemic abuses of the H-1B program.
Key points: "In the US, the tech industry is contending with a sharp rise in H-1B visa fees. US President Donald Trump called for a sweeping overhaul of the H-1B visa program, including a $100,000 application fee, affecting tech companies that have long depended on the program to recruit global talent."
"President Trump recently announced that he is raising the annual fee for H-1B visa applicants from $215 to $100,000 - potentially dealing a major blow to some US industries that rely on skilled foreign workers."
"As President Donald Trump's H-1B visa fee plan rattles corporate America, Baird has data that can give clues on which technology and services sector companies could be hit the hardest."
"It is therefore necessary to impose higher costs on companies seeking to use the H-1B program in order to address the abuse of that program while still permitting companies to hire the best of the best temporary foreign workers," Mr. Trump said in his order.
"Netflix's Reed Hastings surprisingly backs Trump's $100,000 H-1B visa fee, a move that sharply contrasts with the widespread Silicon Valley opposition."
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries with bullet points based on some daily quotes about 'Donald Trump' coming from news articles.
You are also given cumulative narrative summaries from recent past days about 'Donald Trump'. These summaries were generated by previous iterations of this same prompt and represent the historical context.
The content of the summaries and the bullet points must only be related to the theme 'Introduction of a high fee on H-1B visas'. If some part of the information does not relate to 'Introduction of a high fee on H-1B visas', do not include it in the summary or in the bullet points.

You will receive:
    - Historical narrative summaries from recent past days about 'Donald Trump'
    - Multiple sentences from news articles

Please adhere strictly to the following guidelines:

1. **Task**:
    - Your task is to analyze today's quotes about 'Donald Trump' against the historical narrative t
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Narrative day 1": "Donald Trump expressed optimism about the tech industry's reaction to the introduction of a high fee on H-1B visas, which is aimed at ensuring that only highly skilled workers are brought into the U.S. The new fee of $100,000 is intended to discourage the replacement of American workers and promote the hiring of domestic talent.\n\"I think they're going to be very happy,\" Trump said, anticipating the tech industry's response to the changes.\n\"One of the most abused visa systems is the H1-B non-immigrant visa programme. This is supposed to allow highly skilled labourers who work in fields that Americans don't work in to come into the United States of America. What this proclamation will do is raise the fee that companies pay to sponsor H-1B applicants to $100,000.\"\n\"We need workers, we need great workers and this pretty much ensure that that's going to happen,\" Trump said.", "Narrative day 2": "Donald Trump has reiterated his administration's commitment to imp
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.72s/it]

Summary: Donald Trump has reiterated his administration's commitment to the $100,000 fee on H-1B visas, emphasizing its role in curbing program abuse and promoting the hiring of American workers. This fee is positioned as a one-time charge for new applications, which has caused confusion among tech companies. Trump believes that the fee will incentivize companies to prioritize American talent over foreign workers, despite concerns about its potential negative impact on industries reliant on skilled foreign labor. Analysts and company leaders have expressed concern about potential downsizing and workforce disruption, indicating that some companies might circumvent the fee by hiring talent in countries like India. This reflects a growing apprehension about the implications of the fee on the tech industry and the future of H-1B visa holders.
Key points: Trump claims companies will prefer to avoid paying the new fee, and hiring Americans would allow them to do so. "So there's an incentive to hire Americans," he said.
H-1B visas have been a traditional funnel for Indian and Chinese talent into the US tech industry. After Donald Trump said visas for highly skilled workers would cost $100,000, prospective applicants are reconsidering.
Despite President Trump's statement that companies would be "very happy" about the order, analysts and company leaders expressed concern about potential downsizing and workforce disruption.
Some companies might work around the H-1B visa fee by hiring talent in countries like India, where Big Tech is already building innovation hubs, experts told Reuters.
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries with bullet points based on some daily quotes about 'Donald Trump' coming from news articles.
You are also given cumulative narrative summaries from recent past days about 'Donald Trump'. These summaries were generated by previous iterations of this same prompt and represent the historical context.
The content of the summaries and the bullet points must only be related to the theme 'Introduction of a high fee on H-1B visas'. If some part of the information does not relate to 'Introduction of a high fee on H-1B visas', do not include it in the summary or in the bullet points.

You will receive:
    - Historical narrative summaries from recent past days about 'Donald Trump'
    - Multiple sentences from news articles

Please adhere strictly to the following guidelines:

1. **Task**:
    - Your task is to analyze today's quotes about 'Donald Trump' against the historical narrative t
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Narrative day 1": "Donald Trump expressed optimism about the tech industry's reaction to the introduction of a high fee on H-1B visas, which is aimed at ensuring that only highly skilled workers are brought into the U.S. The new fee of $100,000 is intended to discourage the replacement of American workers and promote the hiring of domestic talent.\n\"I think they're going to be very happy,\" Trump said, anticipating the tech industry's response to the changes.\n\"One of the most abused visa systems is the H1-B non-immigrant visa programme. This is supposed to allow highly skilled labourers who work in fields that Americans don't work in to come into the United States of America. What this proclamation will do is raise the fee that companies pay to sponsor H-1B applicants to $100,000.\"\n\"We need workers, we need great workers and this pretty much ensure that that's going to happen,\" Trump said.", "Narrative day 2": "Donald Trump has reiterated his administration's commitment to imp
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.97s/it]

Summary: Donald Trump has announced a $100,000 fee for new H-1B visa applicants, reinforcing his administration's stance on curbing program abuse and promoting the hiring of American workers. This fee is intended to discourage the hiring of foreign workers and is framed as a necessary measure to protect U.S. jobs. The announcement has caused confusion among tech companies, which are concerned about the potential negative impact on their operations and may consider moving jobs overseas. Trump's assertion that the fee will encourage companies to prioritize American talent aligns with his previous statements regarding the need to address systemic abuses of the H-1B program.
Key points: On Friday, President Donald Trump's administration announced a $100,000 fee for all new recipients of H-1B visas, a type of nonimmigrant visa designed to help U.S. companies find employees with technical skills not common in the U.S.
Trump argued that the fee will encourage companies to hire American workers, instead of foreign ones.
The Trump administration's sharp increase in visa fees for H-1B workers has triggered concern among US technology companies, with many considering moving more jobs overseas.
Trump stated that 'abuse' of H-1B visas has facilitated an 'influx' of foreign labour in STEM that has undermined salaries and workplace conditions for US workers.
The fee hike sent H-1B holders into panic mode, prompting companies like Microsoft to ask employees abroad to rush back before midnight.
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries with bullet points based on some daily quotes about 'Donald Trump' coming from news articles.
You are also given cumulative narrative summaries from recent past days about 'Donald Trump'. These summaries were generated by previous iterations of this same prompt and represent the historical context.
The content of the summaries and the bullet points must only be related to the theme 'Introduction of a high fee on H-1B visas'. If some part of the information does not relate to 'Introduction of a high fee on H-1B visas', do not include it in the summary or in the bullet points.

You will receive:
    - Historical narrative summaries from recent past days about 'Donald Trump'
    - Multiple sentences from news articles

Please adhere strictly to the following guidelines:

1. **Task**:
    - Your task is to analyze today's quotes about 'Donald Trump' against the historical narrative t
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Narrative day 1": "Donald Trump expressed optimism about the tech industry's reaction to the introduction of a high fee on H-1B visas, which is aimed at ensuring that only highly skilled workers are brought into the U.S. The new fee of $100,000 is intended to discourage the replacement of American workers and promote the hiring of domestic talent.\n\"I think they're going to be very happy,\" Trump said, anticipating the tech industry's response to the changes.\n\"One of the most abused visa systems is the H1-B non-immigrant visa programme. This is supposed to allow highly skilled labourers who work in fields that Americans don't work in to come into the United States of America. What this proclamation will do is raise the fee that companies pay to sponsor H-1B applicants to $100,000.\"\n\"We need workers, we need great workers and this pretty much ensure that that's going to happen,\" Trump said.", "Narrative day 2": "Donald Trump has reiterated his administration's commitment to imp
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.17s/it]

Summary: Donald Trump has reiterated his administration's commitment to the $100,000 fee on H-1B visas, emphasizing its role in curbing program abuse and promoting the hiring of American workers. This fee is intended to discourage the hiring of foreign workers and is framed as a necessary measure to protect U.S. jobs. The announcement has caused confusion among tech companies, which are concerned about the potential negative impact on their operations and may consider moving jobs overseas. Trump's assertion that the fee will encourage companies to prioritize American talent aligns with his previous statements regarding the need to address systemic abuses of the H-1B program. Notably, Ajay Jain Bhutoria, an Indian entrepreneur, has expressed skepticism about the fee's effectiveness, suggesting it may lead to increased outsourcing and hurt startups.
Key points: Donald Trump has reiterated his administration's commitment to the $100,000 fee on H-1B visas, emphasizing its role in curbing program abuse and promoting the hiring of American workers.
Trump stated that the fee is intended to discourage the hiring of foreign workers and is framed as a necessary measure to protect U.S. jobs.
The announcement has caused confusion among tech companies, which are concerned about the potential negative impact on their operations and may consider moving jobs overseas.
Ajay Jain Bhutoria commented, "Trump's proposed $100,000 H-1B fee will fail. Lawsuits are likely, and courts may strike it down since it doesn't comply with the Administrative Procedure Act rules, which require public notice and comment in the Federal Register."

In [ ]:
#df_DT_theme_matching_citation = pd.read_csv("news_results_labeled_citation_summarized.csv")
#df_DT_theme_matching_citation.to_csv("news_results_labeled_citation_summarized.csv", index=False)

In [28]:
from src.report.html import generate_daily_recap_html
generate_daily_recap_html(df_DT_theme_matching_citation)

HTML file saved as: daily_evolution_recap.html

'daily_evolution_recap.html'

## US and India Company Position

In [29]:
narrative_dates

array(['2025-09-19', '2025-09-20', '2025-09-21', '2025-09-22',
       '2025-09-23', '2025-09-24', '2025-09-25'], dtype=object)

In [30]:
# Generalized: loop over a list of country codes, extract top 3 companies for each, and concatenate results

country_codes = ["United States", "India", "China","Canada" ]  # You can change this list as needed

# Convert the "Date" column to datetime (only once)
df["Date"] = pd.to_datetime(df["Date"])

# Dictionary: key = (country_code, company), value = dataframe of that company (over the whole date range)
top_3_companies_by_country = {}
top_3_companies_names_by_country = {}

for code in country_codes:
    # Filter by country code and narrative_dates
    df_country = df[
        (df["Country Code"] == code) &
        (df["Date"].isin(narrative_dates))
    ]
    # Get counts of all companies (Entity Type == "COMP") over the whole range
    company_counts = df_country[df_country["Entity Type"] == "COMP"]["Entity"].value_counts()
    top_3_companies = company_counts.head(3).index.tolist()
    top_3_companies_names_by_country[code] = top_3_companies

    # For each top company, save the dataframe filtered for that company (over all dates)
    for company in top_3_companies:
        top_3_companies_by_country[(code, company)] = df_country[df_country["Entity"] == company]

    # Print: the top 3 companies and their total occurrences for this country
    print(f"Top 3 companies for {code} and their total occurrences:")
    for company in top_3_companies:
        occ = len(top_3_companies_by_country[(code, company)])
        print(f"  {company}: {occ} occurrences")

# Unisci i dataframe dei top 3 per ogni country code in un unico dataframe
df_top_3_all_countries = pd.concat(
    [top_3_companies_by_country[(code, company)] 
     for code in country_codes 
     for company in top_3_companies_names_by_country[code]],
    ignore_index=True
)

Top 3 companies for United States and their total occurrences:
  Amazon.com Inc.: 493 occurrences
  Microsoft Corp.: 441 occurrences
  Alphabet Inc.: 327 occurrences
Top 3 companies for India and their total occurrences:
  Infosys Ltd.: 190 occurrences
  Wipro Ltd.: 133 occurrences
  Tata Consultancy Services Ltd.: 97 occurrences
Top 3 companies for China and their total occurrences:
  IBM Corp. Pty. Ltd.: 19 occurrences
  Dewang: 9 occurrences
  Metaview: 7 occurrences
Top 3 companies for Canada and their total occurrences:
  Thomson Reuters Corp.: 205 occurrences
  DBRS Ltd.: 8 occurrences
  Talent Fund: 2 occurrences

/tmp/ipykernel_150531/2811259160.py:16: FutureWarning:

The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.

/tmp/ipykernel_150531/2811259160.py:16: FutureWarning:

The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.

/tmp/ipykernel_150531/2811259160.py:16: FutureWarning:

The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.

/tmp/ipykernel_150531/2811259160.py:16: FutureWarning:

The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.

In [36]:
narrative_summarizer = NarrativeSummarizerFlex(llm_model="openai::gpt-4o-mini")

# Sort and initialize columns once
df_top_3_all_countries = df_top_3_all_countries.sort_values('Date')
df_top_3_all_countries["summary"] = None
df_top_3_all_countries["key_points"] = None
df_top_3_all_countries["quotes"] = None

for date in narrative_dates:
    df_temp = df_top_3_all_countries[df_top_3_all_countries["Date"] == date]
    
    # Get daily recap
    daily_recap = narrative_summarizer.get_summaries(
        main_theme="Introduction of a high fee on H-1B visas",
        df=df_temp,
        mode="companies_impact",
        additional_parameters={"main_entity": "Donald Trump"}
    )
    
    # Merge dei risultati con il dataframe originale
    for _, row in daily_recap.iterrows():
        entity = row['Entity']
        
        # Trova gli indici delle righe che matchano
        mask = (df_top_3_all_countries["Date"] == date) & (df_top_3_all_countries["Entity"] == entity)
        indices = df_top_3_all_countries[mask].index
        
        # Assegna i valori a ogni riga individualmente
        for idx in indices:
            df_top_3_all_countries.at[idx, "summary"] = row['summary']
            df_top_3_all_countries.at[idx, "key_points"] = row['key_points']  
            df_top_3_all_countries.at[idx, "quotes"] = row['quotes']

================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive company summaries, bullet points and direct quotes about the 'Introduction of a high fee on H-1B visas' introduced by 'Donald Trump'.
Your task is to analyze multiple piece of sentences coming from news for a single company about a single day.

You will receive company data including:
- Company name
- Multiple sentences from news articles

Your primary task is to synthesize this information into a comprehensive summary on how the company is positioned regarding the 'Introduction of a high fee on H-1B visas' and to extract only direct quotes coming from people of the given company.
Put a lot of attention and highlight any reposne or action or comment from the given company about the 'Introduction of a high fee on H-1B visas'.
If some part of the information does not relate to 'Introduction of a high fee on H-1B visas' or does not come from the given company, do not include it in the summary
================================================================================
DEBUG: USER PROMPTS (Total: 6)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Amazon.com Inc.", "Quote_1": "The proposal has been met with mixed reviews. Critics argue it could deter global talent and stifle innovation, while advocates believe it will protect American jobs by minimizing foreign competition. Big tech players, such as Amazon and Microsoft, who heavily depend on H-1B visas, face increased operational costs.", "Quote_2": "He said the fee would apply to new visas as well as renewals.\nSome of the top tech companies sponsoring H1-B visas include Amazon, Microsoft, Google's parent company, Alphabet, Meta, and Apple. Because companies are required to disclose to the government what they pay H1-B workers, the data has offered insights into Big Tech salaries.", "Quote_3": "Debate over the H-1B program has long simmered between Trump's conservative supporters, who argue it can depress wages, and industry leaders who emphasize its role in securing top-tier talent. The proposed fee hikes may not deter major corporations like Amazon or Microsoft,
----------------------------------------
PROMPT 2:
----------------------------------------
{"Company": "Microsoft Corp.", "Quote_1": "For companies like Google, Microsoft, Amazon, and startups across the country, this could mean a dramatic rethink of hiring practices. For foreign workers hoping to land a U.S. job, the fee makes access harder and far more exclusive.", "Quote_2": "For companies like Google, Microsoft, Amazon, and startups across the country, this could mean a dramatic rethink of hiring practices. For foreign workers hoping to land a U.S. job, the fee makes access harder and far more exclusive.", "Quote_3": "For companies like Google, Microsoft, Amazon, and startups across the country, this could mean a dramatic rethink of hiring practices. For foreign workers hoping to land a U.S. job, the fee makes access harder and far more exclusive.", "Quote_4": "Debate over the H-1B program has long simmered between Trump's conservative supporters, who argue it can depress wages, and industry leaders who emphasize its role in securing top-tier talent. The proposed fee hik
----------------------------------------
PROMPT 3:
----------------------------------------
{"Company": "IBM Corp. Pty. Ltd.", "Quote_1": "This has led to outsourcing of basic technical operations to consultancies such as Wipro, Infosys, HCL Technologies, Tata, IBM, and Cognizant, which employ foreign workers-mostly from India-contracted to American firms seeking cost savings. While critics welcome these changes, they are calling for further reforms. The AFL-CIO said the measures are \"some steps in the right direction\" but advocated for visas to be allocated based on highest wage offers rather than random selection-a proposal previously floated during Trump's first term. The increased fees could affect hiring foreign workers as it'll cost more for companies. Currently, companies pay $215 to register for the lottery and $780 for a Form I-129, the employer-sponsored petition for a non-immigrant worker.", "Quote_2": "This has led to outsourcing of basic technical operations to consultancies such as Wipro, Infosys, HCL Technologies, Tata, IBM, and Cognizant, which employ foreig
----------------------------------------
PROMPT 4:
----------------------------------------
{"Company": "Alphabet Inc.", "Quote_1": "He said the fee would apply to new visas as well as renewals.\nSome of the top tech companies sponsoring H1-B visas include Amazon, Microsoft, Google's parent company, Alphabet, Meta, and Apple. Because companies are required to disclose to the government what they pay H1-B workers, the data has offered insights into Big Tech salaries.", "Quote_2": "He said the fee would apply to new visas as well as renewals.\nSome of the top tech companies sponsoring H1-B visas include Amazon, Microsoft, Google's parent company, Alphabet, Meta, and Apple. Because companies are required to disclose to the government what they pay H1-B workers, the data has offered insights into Big Tech salaries.", "Quote_3": "For companies like Google, Microsoft, Amazon, and startups across the country, this could mean a dramatic rethink of hiring practices. For foreign workers hoping to land a U.S. job, the fee makes access harder and far more exclusive.", "Quote_4": "For com
----------------------------------------
PROMPT 5:
----------------------------------------
{"Company": "Wipro Ltd.", "Quote_1": "This has led to outsourcing of basic technical operations to consultancies such as Wipro, Infosys, HCL Technologies, Tata, IBM, and Cognizant, which employ foreign workers-mostly from India-contracted to American firms seeking cost savings. While critics welcome these changes, they are calling for further reforms. The AFL-CIO said the measures are \"some steps in the right direction\" but advocated for visas to be allocated based on highest wage offers rather than random selection-a proposal previously floated during Trump's first term. The increased fees could affect hiring foreign workers as it'll cost more for companies. Currently, companies pay $215 to register for the lottery and $780 for a Form I-129, the employer-sponsored petition for a non-immigrant worker.", "Quote_2": "This has led to outsourcing of basic technical operations to consultancies such as Wipro, Infosys, HCL Technologies, Tata, IBM, and Cognizant, which employ foreign workers
----------------------------------------
PROMPT 6:
----------------------------------------
{"Company": "Infosys Ltd.", "Quote_1": "This has led to outsourcing of basic technical operations to consultancies such as Wipro, Infosys, HCL Technologies, Tata, IBM, and Cognizant, which employ foreign workers-mostly from India-contracted to American firms seeking cost savings. While critics welcome these changes, they are calling for further reforms. The AFL-CIO said the measures are \"some steps in the right direction\" but advocated for visas to be allocated based on highest wage offers rather than random selection-a proposal previously floated during Trump's first term. The increased fees could affect hiring foreign workers as it'll cost more for companies. Currently, companies pay $215 to register for the lottery and $780 for a Form I-129, the employer-sponsored petition for a non-immigrant worker.", "Quote_2": "This has led to outsourcing of basic technical operations to consultancies such as Wipro, Infosys, HCL Technologies, Tata, IBM, and Cognizant, which employ foreign worke
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 6/6 [00:07<00:00,  1.20s/it]

================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive company summaries, bullet points and direct quotes about the 'Introduction of a high fee on H-1B visas' introduced by 'Donald Trump'.
Your task is to analyze multiple piece of sentences coming from news for a single company about a single day.

You will receive company data including:
- Company name
- Multiple sentences from news articles

Your primary task is to synthesize this information into a comprehensive summary on how the company is positioned regarding the 'Introduction of a high fee on H-1B visas' and to extract only direct quotes coming from people of the given company.
Put a lot of attention and highlight any reposne or action or comment from the given company about the 'Introduction of a high fee on H-1B visas'.
If some part of the information does not relate to 'Introduction of a high fee on H-1B visas' or does not come from the given company, do not include it in the summary
================================================================================
DEBUG: USER PROMPTS (Total: 8)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Infosys Ltd.", "Quote_1": "There was no official statement yet from either Microsoft or JPMorgan.\nPresident Trump expects the revised fee-based visa programme to generate over $100 billion for the US Treasury, designated for national debt reduction and tax cuts. Critics, however, argued that the new fee hinders talent mobility and stifles innovation.\nApproximately 71 per cent of H-1B visa holders are from India, primarily working for technology companies including Infosys, Wipro, Cognisant, and Tata Consultancy Services.", "Quote_2": "Indian IT Industry Hit Hard\nFor India, the move carries far-reaching consequences. Nearly 71% of H-1B visa holders are Indian, most employed in the technology sector. Major Indian IT companies such as Infosys, Wipro, Cognizant, and Tata Consultancy Services (TCS) have long relied on H-1B visas to place engineers and developers on US projects. With visas typically valid for three years and renewable up to six, industry leaders warn that the
----------------------------------------
PROMPT 2:
----------------------------------------
{"Company": "Wipro Ltd.", "Quote_1": "Trump's US Visa Fee Hike: The news emanating from the US never ceases to surprise India and Indians. The latest salvo being the 100k visa fee for H 1b professionals. Now, what are the problems facing? Immediately, it's going to be a cost shock for employers, companies like TCS, Wipro and others use H, 1b very substantially. And this cost jump is exceptional, and it is bound to have an impact on the delivery model entirely.", "Quote_2": "These organisations include major technology firms and large IT consulting companies, such as Amazon, Cognizant, Microsoft, Apple, TCS, Wipro, Intel, Infosys, Walmart, and many others. These companies rely heavily on Indian tech talent to fill roles in software development, AI, and data science and such a move might pivot their hiring away from international recruitment and focus more on domestic talent pipelines, drastically impacting the Indian IT talent. Industry body Nasscom said the US' move to raise the H-1B v
----------------------------------------
PROMPT 3:
----------------------------------------
{"Company": "Thomson Reuters Corp.", "Quote_1": "According to the Reuters report, U.S. Commerce Secretary Howard Lutnick was quoted in the report, urging companies to train American graduates instead of relying on foreign workers, saying, \"Train Americans. Stop bringing in people to take our jobs.\" The statement echoes long-standing criticism that the H-1B visa system has been used by companies to suppress domestic wages and sideline local talent. However, the Reuters report also cited supporters of the H-1B program, including Tesla CEO Elon Musk, who believe that the program fills critical skill gaps and keeps U.S. firms competitive in the global economy. Musk, a naturalized U.S. citizen, has held an H-1B visa in the past. The policy, if enacted, could increase costs significantly for firms, especially smaller tech companies and startups. While Reuters reported that the full administrative framework of the fee was not yet finalized, Lutnick confirmed that the figure of $100,000 per
----------------------------------------
PROMPT 4:
----------------------------------------
{"Company": "Amazon.com Inc.", "Quote_1": "President Trump has raised the H-1B visa sponsorship fee to $100,000 to prioritise American jobs and curb outsourcing. Indian professionals, who form the majority of H-1B holders, may face reduced opportunities, especially in junior roles. The change pressures companies like Amazon, Microsoft, and TCS to reconsider hiring strategies, shifting focus to highly specialised, high-wage talent and domestic graduates. United States President Donald Trump signed a proclamation on Friday introducing a steep $100,000 fee for companies sponsoring H-1B visas, the programme that allows foreign professionals to work in specialised roles in the United States. The change could reshape opportunities for foreign professionals, especially from India, across multiple sectors in the US.", "Quote_2": "Indian IT professionals are facing a new crisis after Trump's $100,000 H-1B visa fee shock. Microsoft and Amazon have warned employees on H-1B and H-4 visas to remain
----------------------------------------
PROMPT 5:
----------------------------------------
{"Company": "Alphabet Inc.", "Quote_1": "The implications for companies that rely heavily on H-1B talent - Amazon, Microsoft, Google, Meta, and the Indian IT giants - are immense. For many, this is not just a visa fee hike, but a potential disruption to revenue models, workforce planning, and innovation pipelines.", "Quote_2": "A de facto talent tax.\nEven large employers with deep pockets will feel the friction. Amazon, Microsoft, Apple, Google, and major consulting firms are among the top recipients of H-1Bs in a typical year. But the greatest pain point will be startups and mid-market firms -the engines of net job creation-whose burn rates and hiring plans cannot absorb an extra $100,000 per head per year. As Menlo Ventures partner Deedy Das warned , upping the price of world-class talent is a direct headwind to innovation. eMarketer's Jeremy Goldman called it a short-term revenue win with a long-term competitiveness loss: the U.S. may simply tax away its innovation edge .", "Quote_
----------------------------------------
PROMPT 6:
----------------------------------------
{"Company": "IBM Corp. Pty. Ltd.", "Quote_1": "The additional charge would impact employers including technology giants such as Amazon, IBM, Microsoft and Google, which have relied on the program to hire foreign workers. H-1B visas are already expensive, with the cost ranging from about $1,700 to $4,500, depending on whether the visa is expedited. The fees are typically considered a business expense for the employer.", "Quote_2": "Until now, companies seeking H-1B workers paid $215 to register for the lottery and an additional $780 for Form I-129, the employer-sponsored petition for a non-immigrant worker. Under the new rules, the cost for sponsoring a single H-1B applicant jumps to $100,000. This dramatic increase is expected to reshape how companies approach hiring foreign talent, especially for positions that have historically been outsourced to countries like India. Major firms and consultancies, including Amazon, Tata Consultancy Services, Microsoft, Apple, Google, Wipro, Infosys,
----------------------------------------
PROMPT 7:
----------------------------------------
{"Company": "Tata Consultancy Services Ltd.", "Quote_1": "There was no official statement yet from either Microsoft or JPMorgan.\nPresident Trump expects the revised fee-based visa programme to generate over $100 billion for the US Treasury, designated for national debt reduction and tax cuts. Critics, however, argued that the new fee hinders talent mobility and stifles innovation.\nApproximately 71 per cent of H-1B visa holders are from India, primarily working for technology companies including Infosys, Wipro, Cognisant, and Tata Consultancy Services.", "Quote_2": "Indian IT Industry Hit Hard\nFor India, the move carries far-reaching consequences. Nearly 71% of H-1B visa holders are Indian, most employed in the technology sector. Major Indian IT companies such as Infosys, Wipro, Cognizant, and Tata Consultancy Services (TCS) have long relied on H-1B visas to place engineers and developers on US projects. With visas typically valid for three years and renewable up to six, industry lea
----------------------------------------
PROMPT 8:
----------------------------------------
{"Company": "Microsoft Corp.", "Quote_1": "US President Donald Trump has imposed a $100,000 annual fee on companies hiring H-1B workers, arguing the visa program undermines American wages and jobs. The move is expected to hit Indian IT firms hard while favouring big corporations like Google, Microsoft, and Tesla that can afford the steep fee. TOI's US correspondent Chidanand Rajghatta explains how this order not only disrupts outsourcing but also risks shutting out young talent who later drive innovation. He points out that leaders like Satya Nadella, Sundar Pichai, and Elon Musk all began their journeys as students and H-1B visa holders. Critics call Trump's plan \"a poppycock theory.\"", "Quote_2": "Indian IT professionals are facing a new crisis after Trump's $100,000 H-1B visa fee shock. Microsoft and Amazon have warned employees on H-1B and H-4 visas to remain in or return to the US amid confusion. Former diplomats say the move is regressive, hits Indian talent, and could harm the
----------------------------------------
================================================================================

Querying OpenAI...:  12%|█▎        | 1/8 [00:04<00:29,  4.14s/it]

KeyboardInterrupt:

In [34]:
# Crea dataframe con le informazioni estratte
df_company_summaries = df_top_3_all_countries[df_top_3_all_countries['summary'].notna()][['Entity', 'Date', 'summary', 'key_points', 'quotes',"Country Code"]].drop_duplicates(subset=['Entity', 'Date']).sort_values(['Entity', 'Date']).reset_index(drop=True)

df_company_summaries.columns = ['Entity', 'Date', 'Summary', 'Key_points', 'Quotes','Country']

df_company_summaries.to_csv("news_results_labeled_company_summaries.csv", index=False)

df_company_summaries

,Entity,Date,Summary,Key_points,Quotes,Country
0,Alphabet Inc.,2025-09-19,Alphabet Inc. is positioned to face significan...,[The introduction of a high fee on H-1B visas ...,"[For companies like Google, Microsoft, Amazon,...",United States
1,Alphabet Inc.,2025-09-20,Alphabet Inc. is positioned to face significan...,"[The $100,000 annual fee on H-1B visas is expe...","[""US tech giants like Amazon, Microsoft, Googl...",United States
2,Alphabet Inc.,2025-09-21,Alphabet Inc. is significantly impacted by the...,[Alphabet Inc. is concerned about the financia...,"[Amazon, Alphabet's Google, Microsoft and othe...",United States
3,Alphabet Inc.,2025-09-22,"Alphabet Inc., through its subsidiary Google, ...",[Alphabet Inc.'s Google employs thousands of H...,"[In response to the announcement, tech giants ...",United States
4,Alphabet Inc.,2025-09-23,Alphabet Inc. is positioned as a significant p...,[Alphabet Inc. is among the tech giants that h...,"[For Silicon Valley, the decision is disruptiv...",United States
5,Alphabet Inc.,2025-09-24,Alphabet Inc. is significantly impacted by the...,[Alphabet Inc. and other major U.S. tech compa...,[The sharp increase in fees will double hiring...,United States
6,Alphabet Inc.,2025-09-25,Alphabet Inc. is positioned as a major player ...,"[The $100,000 application fee for H-1B visas w...","[Major companies like Microsoft, Google, and A...",United States
7,Amazon.com Inc.,2025-09-19,Amazon.com Inc. is significantly impacted by t...,"[Amazon, along with other big tech companies, ...",[The proposal has been met with mixed reviews....,United States
8,Amazon.com Inc.,2025-09-20,Amazon.com Inc. is significantly impacted by t...,[Amazon has warned employees on H-1B and H-4 v...,[Amazon has warned employees on H-1B and H-4 v...,United States
9,Amazon.com Inc.,2025-09-21,Amazon.com Inc. is significantly impacted by t...,[Amazon has tens of thousands of staff in the ...,"[Following the announcement, companies such as...",United States
10,Amazon.com Inc.,2025-09-22,Amazon.com Inc. is significantly impacted by t...,[Amazon is one of the top sponsors of H-1B vis...,"[In response to the announcement, tech giants ...",United States
11,Amazon.com Inc.,2025-09-23,Amazon.com Inc. is significantly impacted by t...,[Amazon is the largest employer of H-1B visa h...,"[However, despite the high fee and layoff conc...",United States
12,Amazon.com Inc.,2025-09-24,Amazon.com Inc. is significantly impacted by t...,[Amazon heavily relies on H-1B visas to recrui...,[The sharp increase in fees will double hiring...,United States
13,Amazon.com Inc.,2025-09-25,Amazon.com Inc. is positioned to absorb the ne...,[Amazon is one of the major technology compani...,"[Major companies like Microsoft, Google, and A...",United States
14,DBRS Ltd.,2025-09-24,DBRS Ltd. has expressed significant concerns r...,[The new fee on H-1B visas may compel banks to...,[The new fee may force banks to hire more offs...,Canada
15,DBRS Ltd.,2025-09-25,DBRS Ltd. has expressed concerns regarding the...,[The new fee on H-1B visas may lead banks to h...,[The new fee may force banks to hire more offs...,Canada
16,Dewang,2025-09-21,"Dewang, represented by its Founder & CEO Dewan...",[Dewang Neralla highlighted that the proposed ...,"[Dewang Neralla, Founder & CEO of cross-border...",China
17,IBM Corp. Pty. Ltd.,2025-09-19,IBM Corp. Pty. Ltd. is positioned within a lan...,[The introduction of high fees on H-1B visas c...,[The increased fees could affect hiring foreig...,China
18,IBM Corp. Pty. Ltd.,2025-09-20,IBM Corp. Pty. Ltd. is significantly impacted ...,[IBM is among the major firms that employ a su...,[The additional charge would impact employers ...,China
19,IBM Corp. Pty. Ltd.,2025-09-21,IBM Corp. Pty. Ltd. is part of the coalition C...,"[IBM is a member of Compete America, which adv...","[Scott Corley, Executive Director of Compete A...",China
20,IBM Corp. Pty. Ltd.,2025-09-22,IBM Corp. Pty. Ltd. is actively evaluating alt...,"[IBM is assessing other visa options, includin...","[Companies are assessing other visa options, i...",China
21,IBM Corp. Pty. Ltd.,2025-09-23,IBM Corp. Pty. Ltd. is positioned among the ma...,[IBM is identified as one of the major tech fi...,[The White House has defended the move as a wa...,China
22,IBM Corp. Pty. Ltd.,2025-09-24,IBM Corp. Pty. Ltd. is positioned against the ...,[IBM acknowledges that the H-1B visa fee incre...,[Economists warn that the H-1B visa fee increa...,China
23,Infosys Ltd.,2025-09-19,Infosys Ltd. is positioned within a landscape ...,[The introduction of high fees on H-1B visas c...,[The increased fees could affect hiring foreig...,India
24,Infosys Ltd.,2025-09-20,Infosys Ltd. is significantly impacted by the ...,"[The $100,000 fee for H-1B visas is considered...",[Now what will happen is everybody will work t...,India
25,Infosys Ltd.,2025-09-21,Infosys Ltd. is significantly impacted by the ...,"[The introduction of a $100,000 annual fee for...","[""This move (the US decision to hike H-1B visa...",India
26,Infosys Ltd.,2025-09-22,Infosys Ltd. is facing significant operational...,[Infosys faces operational and financial press...,"[Companies such as Infosys, Wipro, Cognizant, ...",India
27,Infosys Ltd.,2025-09-23,Infosys Ltd. is significantly impacted by the ...,[Infosys faces an estimated $150-550 million i...,"[Top Indian IT providers such as TCS, Infosys,...",India
28,Infosys Ltd.,2025-09-24,Infosys Ltd. is significantly affected by the ...,[Infosys relies heavily on H-1B visas for hiri...,[The proposed changes to the H-1B visa program...,India
29,Infosys Ltd.,2025-09-25,Infosys Ltd. is positioned to face significant...,"[Infosys, along with TCS and Wipro, is heavily...","[The burden will fall heavily on students, sta...",India
30,Metaview,2025-09-22,"Metaview, a San Francisco-based tech company, ...",[Metaview is ready to move quickly to hire top...,[We are ready to move fast to hire top profess...,China
31,Microsoft Corp.,2025-09-19,Microsoft Corp. is positioned at the center of...,"[Microsoft, along with other big tech companie...",[The proposal has been met with mixed reviews....,United States
32,Microsoft Corp.,2025-09-20,Microsoft Corp. is significantly impacted by t...,[Microsoft has warned employees on H-1B and H-...,[Microsoft and Amazon have warned employees on...,United States
33,Microsoft Corp.,2025-09-21,Microsoft Corp. has expressed significant conc...,"[Microsoft, along with other major tech compan...",[Following the announcement on Friday that the...,United States
34,Microsoft Corp.,2025-09-22,Microsoft Corp. is significantly impacted by t...,[Microsoft and Amazon have advised employees o...,[Microsoft and Amazon have warned employees on...,United States
35,Microsoft Corp.,2025-09-23,Microsoft Corp. is significantly impacted by t...,[Microsoft relies heavily on international tal...,[The changes pose substantial new costs for ma...,United States
36,Microsoft Corp.,2025-09-24,Microsoft Corp. is significantly impacted by t...,"[The introduction of a $100,000 fee on H-1B vi...","[""The sharp increase in fees will double hirin...",United States
37,Microsoft Corp.,2025-09-25,Microsoft Corp. is significantly impacted by t...,"[Microsoft employs 5,189 H-1B visa holders, ma...","[The new $100,000 application fee will hit tec...",United States
38,Talent Fund,2025-09-22,Talent Fund's position regarding the introduct...,"[The introduction of a $100,000 fee for H-1B v...",[Ultimately to attract global talent we need t...,Canada
39,Talent Fund,2025-09-25,Talent Fund is actively responding to the impl...,[Talent Fund is advocating for the expansion o...,[The official recommended the Home Office expa...,Canada
40,Tata Consultancy Services Ltd.,2025-09-20,Tata Consultancy Services Ltd. (TCS) is signif...,"[The introduction of a $100,000 fee for H-1B v...",[President Trump has raised the H-1B visa spon...,India
41,Tata Consultancy Services Ltd.,2025-09-21,Tata Consultancy Services Ltd. (TCS) is signif...,[Tata Consultancy Services expects the high fe...,"[""This would significantly reduce access to th...",India
42,Tata Consultancy Services Ltd.,2025-09-22,Tata Consultancy Services (TCS) is facing sign...,[TCS faces operational and financial pressure ...,"[Companies such as Infosys, Wipro, Cognizant, ...",India
43,Tata Consultancy Services Ltd.,2025-09-23,Tata Consultancy Services Ltd. (TCS) is signif...,"[Tata Consultancy Services employs 5,505 worke...","[For Indian IT companies, the proclamation mea...",India
44,Tata Consultancy Services Ltd.,2025-09-24,Tata Consultancy Services Ltd. (TCS) is signif...,[Tata Consultancy Services derives over half o...,"[With the new fee regime, every fresh recruit ...",India
45,Thomson Reuters Corp.,2025-09-20,Thomson Reuters Corp. highlights the significa...,"[The proposed $100,000 annual fee for H-1B vis...",[If each overseas hire or entry/travel costs $...,Canada
46,Thomson Reuters Corp.,2025-09-21,Thomson Reuters Corp. has not provided any dir...,"[Major companies, including Microsoft, JPMorga...",[Commerce Secretary Howard Lutnick on Friday s...,Canada
47,Thomson Reuters Corp.,2025-09-22,Thomson Reuters Corp. appears to be navigating...,[Thomson Reuters Corp. is expected to become m...,[It added that it has reduced its reliance on ...,Canada
48,Thomson Reuters Corp.,2025-09-23,Thomson Reuters Corp. is closely monitoring th...,"[The $100,000 fee on H-1B visas is causing con...","[While the $100,000 levy applies only to new a...",Canada
49,Thomson Reuters Corp.,2025-09-24,Thomson Reuters Corp. has reported significant...,"[The Trump administration's $100,000 fee on H-...","[""We probably have to reduce the number of H-1...",Canada
50,Thomson Reuters Corp.,2025-09-25,Thomson Reuters Corp. is positioned to be sign...,"[The new US$100,000 fee for H-1B visas represe...",[The visa previously cost employers only a few...,Canada
51,Wipro Ltd.,2025-09-19,Wipro Ltd. is positioned within a landscape wh...,[Wipro employs a significant number of foreign...,[The increased fees could affect hiring foreig...,India
52,Wipro Ltd.,2025-09-20,Wipro Ltd. is significantly impacted by the in...,[Wipro is expected to face significant challen...,"[Now, what are the problems facing? Immediatel...",India
53,Wipro Ltd.,2025-09-21,Wipro Ltd. is facing significant challenges fo...,[Wipro's shares fell by 2% following the annou...,"[The sharp escalation in visa costs, combined ...",India
54,Wipro Ltd.,2025-09-22,Wipro Ltd. is facing significant operational a...,[Wipro faces operational and financial pressur...,"[Companies such as Infosys, Wipro, Cognizant, ...",India
55,Wipro Ltd.,2025-09-23,Wipro Ltd. is significantly impacted by the in...,[Wipro is expected to face a 1-3% reduction in...,"[According to brokerages, large-cap players su...",India
56,Wipro Ltd.,2025-09-24,Wipro Ltd. is positioned to face significant c...,"[Wipro, along with other leading IT firms, der...","[With the new fee regime, every fresh recruit ...",India
57,Wipro Ltd.,2025-09-25,Wipro Ltd. is positioned in a challenging land...,[Wipro's reliance on H-1B visas has been decre...,"[IT giants like TCS, Infosys, and Wipro, which...",India

In [35]:
narrative_summarizer = NarrativeSummarizerFlex(llm_model="openai::gpt-4o-mini")

# Sort dataframe
df_company_summaries = df_company_summaries.sort_values(['Entity', 'Date'])
df_company_summaries["enhanced_summary"] = None
df_company_summaries["enhanced_key_points"] = None

# Initialize global cumulative dictionary with "entity_date" keys
previous_narrative_dict = {}

# Get unique entities and process each entity across all its dates
for entity in df_company_summaries["Entity"].unique():
    entity_df = df_company_summaries[df_company_summaries["Entity"] == entity]
    dates = sorted(entity_df["Date"].unique())
    
    # Variables to track summaries for consolidation
    iteration_summaries = {}  # Store summary for each iteration
    consolidated_narrative = None
    
    # Process each date for this entity
    for iteration, date in enumerate(dates):
        df_temp = entity_df[entity_df["Date"] == date]
        
        print(f"Processing Entity: {entity}, Date: {date}, Iteration: {iteration}")
        
        if iteration == 0:
            # First iteration: skip, use only existing summary
            print("First iteration - skipping get_summaries, using existing summary")
            
            # Take existing summary as baseline
            existing_summary = df_temp["Summary"].iloc[0] if "Summary" in df_temp.columns else ""
            existing_key_points = df_temp["Key_points"].iloc[0] if "Key_points" in df_temp.columns else []
            
            # Ensure key_points is a list
            if not isinstance(existing_key_points, list):
                existing_key_points = [str(existing_key_points)] if existing_key_points else []
            
            # Save to dataframe (use .at to assign list to single cell)
            mask = (df_company_summaries["Date"] == date) & (df_company_summaries["Entity"] == entity)
            row_index = df_company_summaries[mask].index[0]
            df_company_summaries.at[row_index, "enhanced_summary"] = existing_summary
            df_company_summaries.at[row_index, "enhanced_key_points"] = existing_key_points
            
            # Store iteration 0 summary (convert to string for consolidation purposes)
            key_points_str = "\n".join(existing_key_points) if existing_key_points else ""
            iteration_summaries[0] = existing_summary + "\n" + key_points_str
            consolidated_narrative = iteration_summaries[0]
            
        elif iteration == 1:
            # Second iteration: only temporal analysis with previous narrative
            print("Second iteration - temporal analysis only")
            
            # Prepare previous narrative for temporal analysis
            entity_previous_narrative = {f"{entity}_{dates[0]}": consolidated_narrative}
            print("entity_previous_narrative:",entity_previous_narrative)

            daily_recap = narrative_summarizer.get_summaries(
                main_theme="Introduction of a high fee on H-1B visas",
                df=df_temp,
                mode="temporal_company_narrative_from_summaries",  
                previous_narrative=entity_previous_narrative
            )
            
            # Process results
            for _, recap_row in daily_recap.iterrows():
                entity_name = recap_row['Entity']
                summary = recap_row['summary']
                key_points = recap_row['key_points']
                
                # Ensure key_points is a list
                if not isinstance(key_points, list):
                    key_points = [str(key_points)] if key_points else []
                
                # Update dataframe (use .at to assign list to single cell)
                mask = (df_company_summaries["Date"] == date) & (df_company_summaries["Entity"] == entity_name)
                row_index = df_company_summaries[mask].index[0]
                df_company_summaries.at[row_index, "enhanced_summary"] = summary
                df_company_summaries.at[row_index, "enhanced_key_points"] = key_points
                
                # Store iteration 1 summary (convert to string for consolidation purposes)
                key_points_str = "\n".join(key_points) if key_points else ""
                iteration_summaries[1] = summary + "\n" + key_points_str
                
        else:
            # Third iteration and beyond: consolidate then do temporal analysis
            print(f"Iteration {iteration} - consolidation + temporal analysis")
            
            # Step 1: Consolidate previous summaries
            # For iteration 2: previous = iteration 0, today = iteration 1
            # For iteration 3+: previous = consolidated from previous step, today = previous iteration
            if iteration == 2:
                previous_summary_for_consolidation = iteration_summaries[0]
                today_summary_for_consolidation = iteration_summaries[1]
            else:
                previous_summary_for_consolidation = consolidated_narrative
                today_summary_for_consolidation = iteration_summaries[iteration - 1]
            
            print(f"Consolidating: previous from iteration {0 if iteration == 2 else 'consolidated'}, today from iteration {iteration - 1}")
            
            # Apply consolidation using new interface
            consolidated_narrative = narrative_summarizer.get_summaries(
                main_theme="Introduction of a high fee on H-1B visas",
                mode="company_narrative_consolidation",
                previous_summary=previous_summary_for_consolidation,
                today_summary=today_summary_for_consolidation
            )
            
            print(f"Consolidated narrative length: {len(consolidated_narrative) if consolidated_narrative else 0}")
            
            # Step 2: Apply temporal analysis with consolidated summary
            entity_previous_narrative = {f"{entity}_consolidated": consolidated_narrative}
            
            daily_recap = narrative_summarizer.get_summaries(
                main_theme="Introduction of a high fee on H-1B visas",
                df=df_temp,
                mode="temporal_company_narrative_from_summaries",  
                previous_narrative=entity_previous_narrative
            )
            
            # Process results
            for _, recap_row in daily_recap.iterrows():
                entity_name = recap_row['Entity']
                summary = recap_row['summary']
                key_points = recap_row['key_points']
                
                # Ensure key_points is a list
                if not isinstance(key_points, list):
                    key_points = [str(key_points)] if key_points else []
                
                # Update dataframe (use .at to assign list to single cell)
                mask = (df_company_summaries["Date"] == date) & (df_company_summaries["Entity"] == entity_name)
                row_index = df_company_summaries[mask].index[0]
                df_company_summaries.at[row_index, "enhanced_summary"] = summary
                df_company_summaries.at[row_index, "enhanced_key_points"] = key_points
                
                # Store current iteration summary (convert to string for consolidation purposes)
                key_points_str = "\n".join(key_points) if key_points else ""
                iteration_summaries[iteration] = summary + "\n" + key_points_str
        
        print(f"Completed Entity: {entity}, Date: {date}")
        print("-" * 50)

Processing Entity: Alphabet Inc., Date: 2025-09-19 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Alphabet Inc., Date: 2025-09-19 00:00:00
--------------------------------------------------
Processing Entity: Alphabet Inc., Date: 2025-09-20 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'Alphabet Inc._2025-09-19 00:00:00': 'Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies.\nThe introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies.\nThe fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc.\nThe fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc.'}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Alphabet Inc.", "Previous Narrative": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies.\nThe introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies.\nThe fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc.\nThe fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc.", "Today Summary": "Alphabet Inc. is positioned to face significant challenges
----------------------------------------
================================================================================

Querying OpenAI...:   0%|          | 0/1 [00:00<?, ?it/s]

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.04s/it]

Completed Entity: Alphabet Inc., Date: 2025-09-20 00:00:00
--------------------------------------------------
Processing Entity: Alphabet Inc., Date: 2025-09-21 00:00:00, Iteration: 2
Iteration 2 - consolidation + temporal analysis
Consolidating: previous from iteration 0, today from iteration 1
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies.\nThe introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies.\nThe fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc.\nThe fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc.", "Today Summary": "Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B visas, as announced by President Donald Trump. This significant fee is expected to disproportionately affect smaller companies and startups, while larger corporations like Google may be able to absorb the costs. However, there are concerns that this steep fee will lead to a reduction in the hiring of junior and mid-level talent, which is crucial for innovation in the tech sector. Industry experts warn that this could create immediate talent shortages and slow down innovation, as companies like Google heavily rely on skilled foreign workers. Additionally, the fee may push some companies to consider offshoring jobs, further impacting the U.S. labor market. Critics argue that the extraordinary fee transforms H-1B hiring into a high-stakes calculation, potentially stifling the growth of the U.S. tech industry.\nThe introduction of a $100,000 annual fee on H-1B visas is expected to hit smaller companies and startups the hardest, while larger firms like Google may manage the increased costs.\nThere is a concern that the fee will lead to a decline in hiring junior and mid-level talent, which is essential for driving innovation in the tech sector."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:04<00:00,  4.73s/it]

Consolidated narrative length: 1762
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Alphabet Inc.", "Previous Narrative": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B vis
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.38s/it]

Completed Entity: Alphabet Inc., Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: Alphabet Inc., Date: 2025-09-22 00:00:00, Iteration: 3
Iteration 3 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 2
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B visas, as announced by President Donald Trump. This significant fee is expected to disproportionately affect smaller companies and startups, while larger corporations like Google may be able to absorb the costs. However, there are concerns that this steep fee will lead to a reduction in the hiring of junior and mid-level talent, which is crucial for innovation in the tech sector. Industry experts warn that this could create immediate talent shortages and slow down innovation, as companies like Google heavily rely on skilled foreign workers. Additionally, the fee may push some companies to consider offshoring jobs, further impacting the U.S. labor market. Critics argue that the extraordinary fee transforms H-1B hiring into a high-stakes calculation, potentially stifling the growth of the U.S. tech industry.", "Today Summary": "Alphabet Inc. is facing significant financial implications due to the proposed $100,000 annual fee on H-1B visas, which could result in hundreds of millions of dollars in additional costs. The company has advised its H-1B visa employees to avoid international travel and return to the U.S. promptly to mitigate potential re-entry difficulties. This response highlights Alphabet's concerns about the broader impact on the tech industry, particularly regarding the ability to fill critical positions and maintain a competitive advantage. Additionally, Alphabet, along with other major tech firms, is expected to scale back visa hires due to the high costs associated with the new fee, which could lead to project delays and increased operational costs.\nAlphabet Inc. is concerned about the financial implications of the proposed $100,000 annual fee on H-1B visas, which could lead to hundreds of millions of dollars in additional costs.\nThe company has advised its H-1B visa employees to avoid international travel and return to the U.S. to mitigate potential re-entry difficulties."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.16s/it]

Consolidated narrative length: 2513
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Alphabet Inc.", "Previous Narrative": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B vis
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.94s/it]

Completed Entity: Alphabet Inc., Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Alphabet Inc., Date: 2025-09-23 00:00:00, Iteration: 4
Iteration 4 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 3
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B visas, as announced by President Donald Trump. This significant fee is expected to disproportionately affect smaller companies and startups, while larger corporations like Google may be able to absorb the costs. However, there are concerns that this steep fee will lead to a reduction in the hiring of junior and mid-level talent, which is crucial for innovation in the tech sector. Industry experts warn that this could create immediate talent shortages and slow down innovation, as companies like Google heavily rely on skilled foreign workers. Additionally, the fee may push some companies to consider offshoring jobs, further impacting the U.S. labor market. Critics argue that the extraordinary fee transforms H-1B hiring into a high-stakes calculation, potentially stifling the growth of the U.S. tech industry. Alphabet Inc. is facing significant financial implications due to the proposed $100,000 annual fee on H-1B visas, which could result in hundreds of millions of dollars in additional costs. The company has advised its H-1B visa employees to avoid international travel and return to the U.S. promptly to mitigate potential re-entry difficulties. This response highlights Alphabet's concerns about the broader impact on the tech industry, particularly regarding the ability to fill critical positions and maintain a competitive advantage. Additionally, Alphabet, along with other major tech firms, is expected to scale back visa hires due to the high costs associated with the new fee, which could lead to project delays and increased operational costs.", "Today Summary": "Alphabet Inc., through its subsidiary Google, is facing significant challenges due to the introduction of a high fee on H-1B visas, particularly as it employs thousands of H-1B visa holders. The new $100,000 fee is expected to lead to a reevaluation of hiring practices, with a potential shift towards offshore capability centers, especially impacting startups and smaller firms that cannot absorb such costs. Industry experts have raised concerns that this policy may stifle innovation and weaken the U.S. position as a global tech hub, pushing skilled talent to other countries like Canada, Europe, or back to Asia. In response to the announcement, Google and other tech giants have advised their H-1B visa employees to remain in the U.S. and avoid international travel until the new rules take effect, highlighting the urgency and disruption caused by this regulatory change.\nAlphabet Inc. employs thousands of H-1B visa holders, making it significantly affected by the new $100,000 fee for H-1B applications.\nThe introduction of the high fee is expected to pressure hiring practices, potentially leading to a shift towards offshore capability centers instead of hiring in the U.S."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:10<00:00, 10.41s/it]

Consolidated narrative length: 3320
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Alphabet Inc.", "Previous Narrative": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B vis
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.95s/it]

Completed Entity: Alphabet Inc., Date: 2025-09-23 00:00:00
--------------------------------------------------
Processing Entity: Alphabet Inc., Date: 2025-09-24 00:00:00, Iteration: 5
Iteration 5 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 4
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B visas, as announced by President Donald Trump. This significant fee is expected to disproportionately affect smaller companies and startups, while larger corporations like Google may be able to absorb the costs. However, there are concerns that this steep fee will lead to a reduction in the hiring of junior and mid-level talent, which is crucial for innovation in the tech sector. Industry experts warn that this could create immediate talent shortages and slow down innovation, as companies like Google heavily rely on skilled foreign workers. Additionally, the fee may push some companies to consider offshoring jobs, further impacting the U.S. labor market. Critics argue that the extraordinary fee transforms H-1B hiring into a high-stakes calculation, potentially stifling the growth of the U.S. tech industry. Alphabet Inc. is facing significant financial implications due to the proposed $100,000 annual fee on H-1B visas, which could result in hundreds of millions of dollars in additional costs. The company has advised its H-1B visa employees to avoid international travel and return to the U.S. promptly to mitigate potential re-entry difficulties. This response highlights Alphabet's concerns about the broader impact on the tech industry, particularly regarding the ability to fill critical positions and maintain a competitive advantage. Additionally, Alphabet, along with other major tech firms, is expected to scale back visa hires due to the high costs associated with the new fee, which could lead to project delays and increased operational costs. Alphabet Inc., through its subsidiary Google, employs thousands of H-1B visa holders, making it significantly affected by the new $100,000 fee for H-1B applications. The introduction of the high fee is expected to pressure hiring practices, potentially leading to a shift towards offshore capability centers instead of hiring in the U.S. Industry experts have raised concerns that this policy may stifle innovation and weaken the U.S. position as a global tech hub, pushing skilled talent to other countries like Canada, Europe, or back to Asia. In response to the announcement, Google and other tech giants have advised their H-1B visa employees to remain in the U.S. and avoid international travel until the new rules take effect, highlighting the urgency and disruption caused by this regulatory change.", "Today Summary": "New information indicates that Alphabet Inc. has historically relied on H-1B visas to recruit skilled foreign workers, particularly from India and China. The introduction of the $100,000 fee is expected to be manageable for large companies like Google, but it poses a significant challenge for startups and smaller firms that depend on specialized talent for growth. The policy is viewed as disruptive, potentially hampering American startups in the competitive landscape of artificial intelligence and technology innovation. There is a growing concern that the high fees will deter access to essential talent and alter recruitment strategies across the industry, particularly disadvantaging smaller companies that cannot absorb the additional costs.\nAlphabet Inc. has historically relied on H-1B visas to recruit skilled foreign workers from countries like India and China.\nThe new $100,000 fee is expected to be manageable for large companies like Google but crippling for startups that rely on foreign specialists."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:11<00:00, 11.16s/it]

Consolidated narrative length: 4071
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Alphabet Inc.", "Previous Narrative": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B vis
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Completed Entity: Alphabet Inc., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: Alphabet Inc., Date: 2025-09-25 00:00:00, Iteration: 6
Iteration 6 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 5
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B visas, as announced by President Donald Trump. This significant fee is expected to disproportionately affect smaller companies and startups, while larger corporations like Google may be able to absorb the costs. However, there are concerns that this steep fee will lead to a reduction in the hiring of junior and mid-level talent, which is crucial for innovation in the tech sector. Industry experts warn that this could create immediate talent shortages and slow down innovation, as companies like Google heavily rely on skilled foreign workers. Additionally, the fee may push some companies to consider offshoring jobs, further impacting the U.S. labor market. Critics argue that the extraordinary fee transforms H-1B hiring into a high-stakes calculation, potentially stifling the growth of the U.S. tech industry. Alphabet Inc. is facing significant financial implications due to the proposed $100,000 annual fee on H-1B visas, which could result in hundreds of millions of dollars in additional costs. The company has advised its H-1B visa employees to avoid international travel and return to the U.S. promptly to mitigate potential re-entry difficulties. This response highlights Alphabet's concerns about the broader impact on the tech industry, particularly regarding the ability to fill critical positions and maintain a competitive advantage. Additionally, Alphabet, along with other major tech firms, is expected to scale back visa hires due to the high costs associated with the new fee, which could lead to project delays and increased operational costs. Alphabet Inc., through its subsidiary Google, employs thousands of H-1B visa holders, making it significantly affected by the new $100,000 fee for H-1B applications. The introduction of the high fee is expected to pressure hiring practices, potentially leading to a shift towards offshore capability centers instead of hiring in the U.S. Industry experts have raised concerns that this policy may stifle innovation and weaken the U.S. position as a global tech hub, pushing skilled talent to other countries like Canada, Europe, or back to Asia. In response to the announcement, Google and other tech giants have advised their H-1B visa employees to remain in the U.S. and avoid international travel until the new rules take effect, highlighting the urgency and disruption caused by this regulatory change. New information indicates that Alphabet Inc. has historically relied on H-1B visas to recruit skilled foreign workers, particularly from India and China. The introduction of the $100,000 fee is expected to be manageable for large companies like Google, but it poses a significant challenge for startups and smaller firms that depend on specialized talent for growth. The policy is viewed as disruptive, potentially hampering American startups in the competitive landscape of artificial intelligence and technology innovation. There is a growing concern that the high fees will deter access to essential talent and alter recruitment strategies across the industry, particularly disadvantaging smaller companies that cannot absorb the additional costs.", "Today Summary": "New information indicates that the introduction of a high fee on H-1B visas is expected to double hiring costs for Alphabet Inc., prompting a significant reassessment of human resources strategies. This increase in costs may lead to a reduction in applicant numbers and a greater reliance on overseas development centers, which could slow innovation and delay product launches in critical sectors such as artificial intelligence and cloud computing. While large firms like Alphabet can manage these costs, the fee is seen as crippling for startups that depend on a few foreign specialists, potentially altering hiring strategies and reducing diversity in leadership teams. The overall competitiveness of these companies may be compromised, negatively impacting their stock prices.\nThe new fee on H-1B visas is expected to double hiring costs for Alphabet Inc., leading to a reassessment of human resources strategies.\nThe policy is particularly disruptive for startups in Silicon Valley, as the high costs may be manageable for large firms like Alphabet but crippling for those that rely on a few foreign specialists."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:13<00:00, 13.26s/it]

Consolidated narrative length: 4821
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Alphabet Inc.", "Previous Narrative": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies. The introduction of a high fee on H-1B visas could lead to a dramatic rethink of hiring practices for Alphabet Inc. and other major tech companies. The fee makes access to U.S. jobs harder and far more exclusive for foreign workers hoping to land positions at Alphabet Inc. The fee will apply to both new H-1B visa applications and renewals, affecting the hiring strategy of Alphabet Inc. Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B vis
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Completed Entity: Alphabet Inc., Date: 2025-09-25 00:00:00
--------------------------------------------------
Processing Entity: Amazon.com Inc., Date: 2025-09-19 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Amazon.com Inc., Date: 2025-09-19 00:00:00
--------------------------------------------------
Processing Entity: Amazon.com Inc., Date: 2025-09-20 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'Amazon.com Inc._2025-09-19 00:00:00': 'Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on smaller startups.\nThe proposed fee could lead to a dramatic rethink of hiring practices for Amazon and other tech companies, making access to U.S. jobs harder for foreign workers.'}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Amazon.com Inc.", "Previous Narrative": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:12<00:00, 12.59s/it]

Completed Entity: Amazon.com Inc., Date: 2025-09-20 00:00:00
--------------------------------------------------
Processing Entity: Amazon.com Inc., Date: 2025-09-21 00:00:00, Iteration: 2
Iteration 2 - consolidation + temporal analysis
Consolidating: previous from iteration 0, today from iteration 1
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on smaller startups.\nThe proposed fee could lead to a dramatic rethink of hiring practices for Amazon and other tech companies, making access to U.S. jobs harder for foreign workers.", "Today Summary": "Amazon.com Inc. is facing significant challenges due to the recent introduction of a $100,000 fee for H-1B visas, as announced by President Trump. The company has advised its employees holding H-1B and H-4 visas to either remain in the U.S. or return promptly to avoid complications stemming from the new fee structure. This policy is particularly problematic for Indian IT professionals, who constitute a large segment of H-1B visa holders, and is expected to lead to a decrease in job opportunities, especially for junior roles. The increased costs associated with the new fee may compel Amazon to rethink its hiring strategies, placing greater emphasis on attracting high-wage, specialized talent and domestic graduates. This shift could disrupt the hiring process and slow down collaborations between the U.S. and India in the tech sector.\nAmazon has warned employees on H-1B and H-4 visas to remain in or return to the U.S. amid confusion over the new $100,000 fee.\nThe introduction of the high fee is expected to reduce opportunities for Indian IT professionals, particularly in junior roles."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.64s/it]

Consolidated narrative length: 1967
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Amazon.com Inc.", "Previous Narrative": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:09<00:00,  9.30s/it]

Completed Entity: Amazon.com Inc., Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: Amazon.com Inc., Date: 2025-09-22 00:00:00, Iteration: 3
Iteration 3 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 2
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on smaller startups.\nThe proposed fee could lead to a dramatic rethink of hiring practices for Amazon and other tech companies, making access to U.S. jobs harder for foreign workers.\nAmazon.com Inc. is facing significant challenges due to the recent introduction of a $100,000 fee for H-1B visas, as announced by President Trump. The company has advised its employees holding H-1B and H-4 visas to either remain in the U.S. or return promptly to avoid complications stemming from the new fee structure. This policy is particularly problematic for Indian IT professionals, who constitute a large segment of H-1B visa holders, and is expected to lead to a decrease in job opportunities, especially for junior roles. The increased costs associated with the new fee may compel Amazon to rethink its hiring strategies, placing greater emphasis on attracting high-wage, specialized talent and domestic graduates. This shift could disrupt the hiring process and slow down collaborations between the U.S. and India in the tech sector.", "Today Summary": "Amazon.com Inc. continues to face significant challenges due to the recently introduced $100,000 annual fee for H-1B visa applications. The company has tens of thousands of employees on H-1B visas, and the new fee could result in hundreds of millions of dollars in additional costs. In response to the fee's implications, Amazon has advised its H-1B and H-4 visa employees to return to the U.S. and avoid international travel, highlighting the urgency of the situation. There is growing concern among industry leaders that this fee will lead to a substantial reduction in visa sponsorships, which could severely impact Amazon's ability to hire foreign talent. Furthermore, the introduction of this fee is expected to disrupt long-term projects that depend on highly skilled workers, potentially slowing down innovation within the tech sector.\nAmazon has tens of thousands of staff in the U.S. on H-1B visas, and the new $100,000 fee could add up to hundreds of millions of dollars in costs.\nThe company has advised its H-1B and H-4 visa employees to return to the U.S. and avoid international travel due to the new fee's implications."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:12<00:00, 12.97s/it]

Consolidated narrative length: 2810
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Amazon.com Inc.", "Previous Narrative": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:09<00:00,  9.89s/it]

Completed Entity: Amazon.com Inc., Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Amazon.com Inc., Date: 2025-09-23 00:00:00, Iteration: 4
Iteration 4 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 3
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on smaller startups.\nThe proposed fee could lead to a dramatic rethink of hiring practices for Amazon and other tech companies, making access to U.S. jobs harder for foreign workers.\nAmazon.com Inc. is facing significant challenges due to the recent introduction of a $100,000 fee for H-1B visas, as announced by President Trump. The company has advised its employees holding H-1B and H-4 visas to either remain in the U.S. or return promptly to avoid complications stemming from the new fee structure. This policy is particularly problematic for Indian IT professionals, who constitute a large segment of H-1B visa holders, and is expected to lead to a decrease in job opportunities, especially for junior roles. The increased costs associated with the new fee may compel Amazon to rethink its hiring strategies, placing greater emphasis on attracting high-wage, specialized talent and domestic graduates. This shift could disrupt the hiring process and slow down collaborations between the U.S. and India in the tech sector.\nAmazon.com Inc. continues to face significant challenges due to the recently introduced $100,000 annual fee for H-1B visa applications. The company has tens of thousands of employees on H-1B visas, and the new fee could result in hundreds of millions of dollars in additional costs. In response to the fee's implications, Amazon has advised its H-1B and H-4 visa employees to return to the U.S. and avoid international travel, highlighting the urgency of the situation. There is growing concern among industry leaders that this fee will lead to a substantial reduction in visa sponsorships, which could severely impact Amazon's ability to hire foreign talent. Furthermore, the introduction of this fee is expected to disrupt long-term projects that depend on highly skilled workers, potentially slowing down innovation within the tech sector.", "Today Summary": "Amazon.com Inc. continues to grapple with the implications of the newly introduced $100,000 fee on H-1B visas, which is expected to significantly impact its staffing and operational costs. The company is one of the top sponsors of H-1B visas, employing over 14,000 visa holders by mid-2025. Analysts have raised concerns that the fee could lead to a more selective hiring process, limiting access to skilled foreign workers and potentially stifling innovation within the tech sector. In light of the new regulations, Amazon has advised its employees on H-1B visas to remain in the U.S. or return quickly if they are abroad, emphasizing the urgency of the situation. The overall sentiment within the company and the industry reflects significant concern regarding the long-term implications for talent acquisition and project timelines. Additionally, Amazon reportedly has the highest number of workers on H-1B visas among major tech firms, which positions it to face the steepest cost burden from the new fee.\nAmazon is one of the top sponsors of H-1B visas, employing over 14,000 visa holders by mid-2025, indicating a significant reliance on foreign talent.\nAnalysts predict that the new $100,000 fee could lead to a more selective hiring process, limiting access to skilled foreign workers and potentially stifling innovation within the tech sector."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:14<00:00, 14.39s/it]

Consolidated narrative length: 3820
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Amazon.com Inc.", "Previous Narrative": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.04s/it]

Completed Entity: Amazon.com Inc., Date: 2025-09-23 00:00:00
--------------------------------------------------
Processing Entity: Amazon.com Inc., Date: 2025-09-24 00:00:00, Iteration: 5
Iteration 5 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 4
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on smaller startups.\nThe proposed fee could lead to a dramatic rethink of hiring practices for Amazon and other tech companies, making access to U.S. jobs harder for foreign workers.\nAmazon.com Inc. is facing significant challenges due to the recent introduction of a $100,000 fee for H-1B visas, as announced by President Trump. The company has advised its employees holding H-1B and H-4 visas to either remain in the U.S. or return promptly to avoid complications stemming from the new fee structure. This policy is particularly problematic for Indian IT professionals, who constitute a large segment of H-1B visa holders, and is expected to lead to a decrease in job opportunities, especially for junior roles. The increased costs associated with the new fee may compel Amazon to rethink its hiring strategies, placing greater emphasis on attracting high-wage, specialized talent and domestic graduates. This shift could disrupt the hiring process and slow down collaborations between the U.S. and India in the tech sector.\nAmazon.com Inc. continues to face significant challenges due to the recently introduced $100,000 annual fee for H-1B visa applications. The company has tens of thousands of employees on H-1B visas, and the new fee could result in hundreds of millions of dollars in additional costs. In response to the fee's implications, Amazon has advised its H-1B and H-4 visa employees to return to the U.S. and avoid international travel, highlighting the urgency of the situation. There is growing concern among industry leaders that this fee will lead to a substantial reduction in visa sponsorships, which could severely impact Amazon's ability to hire foreign talent. Furthermore, the introduction of this fee is expected to disrupt long-term projects that depend on highly skilled workers, potentially slowing down innovation within the tech sector.\nAmazon.com Inc. continues to grapple with the implications of the newly introduced $100,000 fee on H-1B visas, which is expected to significantly impact its staffing and operational costs. The company is one of the top sponsors of H-1B visas, employing over 14,000 visa holders by mid-2025. Analysts have raised concerns that the fee could lead to a more selective hiring process, limiting access to skilled foreign workers and potentially stifling innovation within the tech sector. In light of the new regulations, Amazon has advised its employees on H-1B visas to remain in the U.S. or return quickly if they are abroad, emphasizing the urgency of the situation. The overall sentiment within the company and the industry reflects significant concern regarding the long-term implications for talent acquisition and project timelines. Additionally, Amazon reportedly has the highest number of workers on H-1B visas among major tech firms, which positions it to face the steepest cost burden from the new fee.", "Today Summary": "Amazon.com Inc. is facing significant challenges due to the recent introduction of a $100,000 fee on new H-1B visa applications, which is part of the Trump administration's strategy to prioritize American workers and limit foreign hiring. As the largest employer of H-1B visa holders, Amazon has been advised to instruct its employees to remain in the U.S. or return immediately to avoid complications. While experts suggest that Amazon may be able to absorb the new costs due to its financial strength, the fee is expected to be crippling for startups and smaller companies that depend on foreign talent. The fee is viewed as a disruptive change for the tech industry, which has historically relied on H-1B visas to recruit skilled workers from countries like India and China. The overall sentiment indicates that while Amazon may manage the increased costs, the broader implications could hinder innovation and collaboration within the tech sector. Additionally, the White House has clarified that the fee applies only to new applicants, not renewals, but the immediate loss of confidence in the visa system is evident, as it transforms a previously accessible opportunity into a costly barrier.\nThe $100,000 fee on new H-1B visa applications is part of a strategy by the Trump administration to prioritize American workers and limit foreign hiring.\nThe White House has clarified that the fee applies only to new applicants, not renewals, indicating a shift in the perception of the H-1B visa as a costly barrier rather than an accessible opportunity."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:12<00:00, 12.01s/it]

Consolidated narrative length: 4176
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Amazon.com Inc.", "Previous Narrative": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.85s/it]

Completed Entity: Amazon.com Inc., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: Amazon.com Inc., Date: 2025-09-25 00:00:00, Iteration: 6
Iteration 6 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 5
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on smaller startups.\nThe proposed fee could lead to a dramatic rethink of hiring practices for Amazon and other tech companies, making access to U.S. jobs harder for foreign workers.\nAmazon.com Inc. is facing significant challenges due to the recent introduction of a $100,000 fee for H-1B visas, as announced by President Trump. The company has advised its employees holding H-1B and H-4 visas to either remain in the U.S. or return promptly to avoid complications stemming from the new fee structure. This policy is particularly problematic for Indian IT professionals, who constitute a large segment of H-1B visa holders, and is expected to lead to a decrease in job opportunities, especially for junior roles. The increased costs associated with the new fee may compel Amazon to rethink its hiring strategies, placing greater emphasis on attracting high-wage, specialized talent and domestic graduates. This shift could disrupt the hiring process and slow down collaborations between the U.S. and India in the tech sector.\nAmazon.com Inc. continues to face significant challenges due to the recently introduced $100,000 annual fee for H-1B visa applications. The company has tens of thousands of employees on H-1B visas, and the new fee could result in hundreds of millions of dollars in additional costs. In response to the fee's implications, Amazon has advised its H-1B and H-4 visa employees to return to the U.S. and avoid international travel, highlighting the urgency of the situation. There is growing concern among industry leaders that this fee will lead to a substantial reduction in visa sponsorships, which could severely impact Amazon's ability to hire foreign talent. Furthermore, the introduction of this fee is expected to disrupt long-term projects that depend on highly skilled workers, potentially slowing down innovation within the tech sector.\nAmazon.com Inc. continues to grapple with the implications of the newly introduced $100,000 fee on H-1B visas, which is expected to significantly impact its staffing and operational costs. The company is one of the top sponsors of H-1B visas, employing over 14,000 visa holders by mid-2025. Analysts have raised concerns that the fee could lead to a more selective hiring process, limiting access to skilled foreign workers and potentially stifling innovation within the tech sector. In light of the new regulations, Amazon has advised its employees on H-1B visas to remain in the U.S. or return quickly if they are abroad, emphasizing the urgency of the situation. The overall sentiment within the company and the industry reflects significant concern regarding the long-term implications for talent acquisition and project timelines. Additionally, Amazon reportedly has the highest number of workers on H-1B visas among major tech firms, which positions it to face the steepest cost burden from the new fee.\nThe $100,000 fee on new H-1B visa applications is part of a strategy by the Trump administration to prioritize American workers and limit foreign hiring.\nThe White House has clarified that the fee applies only to new applicants, not renewals, indicating a shift in the perception of the H-1B visa as a costly barrier rather than an accessible opportunity.", "Today Summary": "Amazon.com Inc. is facing new challenges due to the recently introduced $100,000 fee on H-1B visas for new applicants, which is expected to double hiring costs and necessitate a reassessment of its human resources strategies. The company heavily relies on H-1B visa holders to fill critical roles in technology and innovation, and the fee increase may lead to a reduction in applicant numbers. This could result in a greater reliance on overseas development centers, potentially slowing innovation and delaying product launches in key sectors such as artificial intelligence and cloud computing. While larger companies like Amazon may be better positioned to absorb these costs, the fee is seen as particularly disruptive for startups, which may struggle to manage the increased financial burden. Experts warn that this policy could choke America's innovation pipeline and lead to a brain drain, negatively impacting productivity in the tech industry.\nThe introduction of a $100,000 fee for new H-1B visa applications is expected to double hiring costs for Amazon, prompting a reassessment of its human resources strategies.\nThe fee increase may lead to a reduction in applicant numbers and a greater reliance on overseas development centers, potentially slowing innovation and delaying product launches."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:13<00:00, 13.68s/it]

Consolidated narrative length: 4779
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Amazon.com Inc.", "Previous Narrative": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.\nAmazon, along with other big tech companies, heavily depends on H-1B visas and will face increased operational costs due to the proposed high fee.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may not deter major corporations like Amazon, but it could impose significant burdens on
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:09<00:00,  9.13s/it]

Completed Entity: Amazon.com Inc., Date: 2025-09-25 00:00:00
--------------------------------------------------
Processing Entity: DBRS Ltd., Date: 2025-09-24 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: DBRS Ltd., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: DBRS Ltd., Date: 2025-09-25 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'DBRS Ltd._2025-09-24 00:00:00': 'DBRS Ltd. has expressed significant concerns regarding the introduction of a high fee on H-1B visas, particularly its impact on hiring practices within the banking sector. The company highlights that the increased costs associated with H-1B visas may lead banks to seek more offshore workers, especially when the necessary skills are not readily available in the U.S. This shift could make it increasingly challenging to fill entry-level positions through the H-1B program, as noted by company representatives.\nThe new fee on H-1B visas may compel banks to hire more offshore workers due to difficulties in finding necessary skills in the U.S.\nDBRS Ltd. indicates that hiring for entry-level jobs using H-1B visas becomes nearly impossible under the new fee structure.'}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "DBRS Ltd.", "Previous Narrative": "DBRS Ltd. has expressed significant concerns regarding the introduction of a high fee on H-1B visas, particularly its impact on hiring practices within the banking sector. The company highlights that the increased costs associated with H-1B visas may lead banks to seek more offshore workers, especially when the necessary skills are not readily available in the U.S. This shift could make it increasingly challenging to fill entry-level positions through the H-1B program, as noted by company representatives.\nThe new fee on H-1B visas may compel banks to hire more offshore workers due to difficulties in finding necessary skills in the U.S.\nDBRS Ltd. indicates that hiring for entry-level jobs using H-1B visas becomes nearly impossible under the new fee structure.", "Today Summary": "DBRS Ltd. has expressed concerns regarding the introduction of a high fee on H-1B visas, particularly its potential impact on the banking sector. Tim O'Brien, ma
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.10s/it]

Completed Entity: DBRS Ltd., Date: 2025-09-25 00:00:00
--------------------------------------------------
Processing Entity: Dewang, Date: 2025-09-21 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Dewang, Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: IBM Corp. Pty. Ltd., Date: 2025-09-19 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: IBM Corp. Pty. Ltd., Date: 2025-09-19 00:00:00
--------------------------------------------------
Processing Entity: IBM Corp. Pty. Ltd., Date: 2025-09-20 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'IBM Corp. Pty. Ltd._2025-09-19 00:00:00': "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions.\nThe introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers.\nIBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms.\nThe AFL-CIO has indicated that while the measures are 'some steps in the right direction', they advocate for reforms in visa allocation based on wage offers rather than random selection."}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "IBM Corp. Pty. Ltd.", "Previous Narrative": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions.\nThe introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers.\nIBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American fir
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.54s/it]

Completed Entity: IBM Corp. Pty. Ltd., Date: 2025-09-20 00:00:00
--------------------------------------------------
Processing Entity: IBM Corp. Pty. Ltd., Date: 2025-09-21 00:00:00, Iteration: 2
Iteration 2 - consolidation + temporal analysis
Consolidating: previous from iteration 0, today from iteration 1
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions.\nThe introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers.\nIBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms.\nThe AFL-CIO has indicated that while the measures are 'some steps in the right direction', they advocate for reforms in visa allocation based on wage offers rather than random selection.", "Today Summary": "IBM Corp. Pty. Ltd. faces a significant challenge with the introduction of a high fee on H-1B visas, which has increased the cost of sponsoring a single applicant to $100,000. This dramatic rise in fees is expected to reshape IBM's hiring strategies, particularly as the company has historically relied on H-1B visas to employ foreign talent for outsourced roles, especially from India. The new fee structure adds to the existing costs of H-1B visas, which already range from $1,700 to $4,500, making it a substantial business expense for IBM and other major firms that depend on this program to fill critical positions. The impact of this fee increase is echoed in statements highlighting that technology giants, including IBM, will be significantly affected as they have relied heavily on the H-1B program to hire foreign workers.\nThe cost for sponsoring a single H-1B applicant has increased to $100,000, which is expected to reshape IBM's hiring practices.\nThe new fee structure adds to existing H-1B visa costs, which already range from $1,700 to $4,500, creating a substantial business expense for IBM."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.15s/it]

Consolidated narrative length: 1963
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "IBM Corp. Pty. Ltd.", "Previous Narrative": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions. The introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers. IBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  6.00s/it]

Completed Entity: IBM Corp. Pty. Ltd., Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: IBM Corp. Pty. Ltd., Date: 2025-09-22 00:00:00, Iteration: 3
Iteration 3 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 2
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions. The introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers. IBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms. The AFL-CIO has indicated that while the measures are 'some steps in the right direction', they advocate for reforms in visa allocation based on wage offers rather than random selection. IBM Corp. Pty. Ltd. faces a significant challenge with the introduction of a high fee on H-1B visas, which has increased the cost of sponsoring a single applicant to $100,000. This dramatic rise in fees is expected to reshape IBM's hiring strategies, particularly as the company has historically relied on H-1B visas to employ foreign talent for outsourced roles, especially from India. The new fee structure adds to the existing costs of H-1B visas, which already range from $1,700 to $4,500, making it a substantial business expense for IBM and other major firms that depend on this program to fill critical positions. The impact of this fee increase is echoed in statements highlighting that technology giants, including IBM, will be significantly affected as they have relied heavily on the H-1B program to hire foreign workers.", "Today Summary": "IBM Corp. Pty. Ltd. is actively involved in the coalition Compete America, which has publicly urged the US administration to reconsider the introduction of the high $100,000 fee on H-1B visas. The coalition argues that while there are exemptions for existing visa holders, the new fee structure could have detrimental effects on American job growth and economic expansion. Scott Corley, the Executive Director of Compete America, highlighted that such policies do not protect American workers but instead limit opportunities and drive investment away from the country, ultimately benefiting foreign competitors. This position adds a new dimension to IBM's stance on the H-1B visa fee increase, emphasizing the broader economic implications rather than just the operational costs for the company.\nIBM is part of the coalition Compete America, which is advocating for the reconsideration of the $100,000 fee on H-1B visas due to its potential negative impact on American job growth.\nScott Corley, Executive Director of Compete America, stated that policies increasing costs do not protect American workers but limit opportunities and drive investment away from the US."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:10<00:00, 10.73s/it]

Consolidated narrative length: 2759
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "IBM Corp. Pty. Ltd.", "Previous Narrative": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions. The introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers. IBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.19s/it]

Completed Entity: IBM Corp. Pty. Ltd., Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: IBM Corp. Pty. Ltd., Date: 2025-09-23 00:00:00, Iteration: 4
Iteration 4 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 3
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions. The introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers. IBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms. The AFL-CIO has indicated that while the measures are 'some steps in the right direction', they advocate for reforms in visa allocation based on wage offers rather than random selection. IBM Corp. Pty. Ltd. faces a significant challenge with the introduction of a high fee on H-1B visas, which has increased the cost of sponsoring a single applicant to $100,000. This dramatic rise in fees is expected to reshape IBM's hiring strategies, particularly as the company has historically relied on H-1B visas to employ foreign talent for outsourced roles, especially from India. The new fee structure adds to the existing costs of H-1B visas, which already range from $1,700 to $4,500, making it a substantial business expense for IBM and other major firms that depend on this program to fill critical positions. The impact of this fee increase is echoed in statements highlighting that technology giants, including IBM, will be significantly affected as they have relied heavily on the H-1B program to hire foreign workers. IBM Corp. Pty. Ltd. is actively involved in the coalition Compete America, which has publicly urged the US administration to reconsider the introduction of the high $100,000 fee on H-1B visas. The coalition argues that while there are exemptions for existing visa holders, the new fee structure could have detrimental effects on American job growth and economic expansion. Scott Corley, the Executive Director of Compete America, highlighted that such policies do not protect American workers but instead limit opportunities and drive investment away from the country, ultimately benefiting foreign competitors. This position adds a new dimension to IBM's stance on the H-1B visa fee increase, emphasizing the broader economic implications rather than just the operational costs for the company.", "Today Summary": "IBM Corp. Pty. Ltd. is currently evaluating alternative visa options in light of the high fee introduced on H-1B visas. The company is considering the L-1 visa route, which is designated for managers and specialized employees, but requires at least one year of overseas service. Additionally, Gary Cohn, vice-chair at IBM, has publicly defended the high fee, arguing that it is intended to ensure that H-1B visas are allocated to highly skilled individuals who are not available in the U.S. labor market. This marks a shift in IBM's approach as it explores other avenues for securing talent amidst the increased costs associated with H-1B visas.\nIBM is actively evaluating alternative visa options, including the L-1 visa route for managers and specialized employees, which requires prior overseas service.\nGary Cohn defended the high fee on H-1B visas, stating it ensures that visas are reserved for highly skilled individuals not available in the U.S. labor market."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:12<00:00, 12.10s/it]

Consolidated narrative length: 3418
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "IBM Corp. Pty. Ltd.", "Previous Narrative": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions. The introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers. IBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:04<00:00,  4.24s/it]

Completed Entity: IBM Corp. Pty. Ltd., Date: 2025-09-23 00:00:00
--------------------------------------------------
Processing Entity: IBM Corp. Pty. Ltd., Date: 2025-09-24 00:00:00, Iteration: 5
Iteration 5 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 4
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions. The introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers. IBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms. The AFL-CIO has indicated that while the measures are 'some steps in the right direction', they advocate for reforms in visa allocation based on wage offers rather than random selection. IBM Corp. Pty. Ltd. faces a significant challenge with the introduction of a high fee on H-1B visas, which has increased the cost of sponsoring a single applicant to $100,000. This dramatic rise in fees is expected to reshape IBM's hiring strategies, particularly as the company has historically relied on H-1B visas to employ foreign talent for outsourced roles, especially from India. The new fee structure adds to the existing costs of H-1B visas, which already range from $1,700 to $4,500, making it a substantial business expense for IBM and other major firms that depend on this program to fill critical positions. The impact of this fee increase is echoed in statements highlighting that technology giants, including IBM, will be significantly affected as they have relied heavily on the H-1B program to hire foreign workers. IBM Corp. Pty. Ltd. is actively involved in the coalition Compete America, which has publicly urged the US administration to reconsider the introduction of the high $100,000 fee on H-1B visas. The coalition argues that while there are exemptions for existing visa holders, the new fee structure could have detrimental effects on American job growth and economic expansion. Scott Corley, the Executive Director of Compete America, highlighted that such policies do not protect American workers but instead limit opportunities and drive investment away from the country, ultimately benefiting foreign competitors. This position adds a new dimension to IBM's stance on the H-1B visa fee increase, emphasizing the broader economic implications rather than just the operational costs for the company. Additionally, IBM Corp. Pty. Ltd. is currently evaluating alternative visa options in light of the high fee introduced on H-1B visas. The company is considering the L-1 visa route, which is designated for managers and specialized employees, but requires at least one year of overseas service. Furthermore, Gary Cohn, vice-chair at IBM, has publicly defended the high fee, arguing that it is intended to ensure that H-1B visas are allocated to highly skilled individuals who are not available in the U.S. labor market. This marks a shift in IBM's approach as it explores other avenues for securing talent amidst the increased costs associated with H-1B visas.", "Today Summary": "IBM Corp. Pty. Ltd. is now recognized as one of the major tech firms that will be significantly affected by the introduction of a high fee on H-1B visas, alongside other industry leaders such as Amazon, Microsoft, and Google. This collective group employs tens of thousands of H-1B visa holders annually. The White House has defended the new policy, framing it as a measure to address 'systemic abuse' of the H-1B program and to prioritize American workers, indicating a notable shift in the regulatory landscape that could further complicate IBM's reliance on foreign talent.\nIBM is now identified as one of the major tech firms that will feel the impact of the new high fee on H-1B visas.\nThe company is part of a collective group of tech leaders, including Amazon, Microsoft, and Google, that employ tens of thousands of H-1B visa holders each year."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.19s/it]

Consolidated narrative length: 3995
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "IBM Corp. Pty. Ltd.", "Previous Narrative": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions. The introduction of high fees on H-1B visas could increase hiring costs for companies like IBM that employ foreign workers. IBM is part of a group of consultancies that outsource basic technical operations, employing many foreign workers contracted to American firms
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:09<00:00,  9.86s/it]

Completed Entity: IBM Corp. Pty. Ltd., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: Infosys Ltd., Date: 2025-09-19 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Infosys Ltd., Date: 2025-09-19 00:00:00
--------------------------------------------------
Processing Entity: Infosys Ltd., Date: 2025-09-20 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'Infosys Ltd._2025-09-19 00:00:00': "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce.\nThe introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs.\nInfosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings.\nCurrent fees for H-1B visa applications include $215 for lottery registration and $780 for the employer-sponsored petition, which may rise under new regulations."}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Infosys Ltd.", "Previous Narrative": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce.\nThe introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs.\nInfosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings.
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:04<00:00,  4.90s/it]

Completed Entity: Infosys Ltd., Date: 2025-09-20 00:00:00
--------------------------------------------------
Processing Entity: Infosys Ltd., Date: 2025-09-21 00:00:00, Iteration: 2
Iteration 2 - consolidation + temporal analysis
Consolidating: previous from iteration 0, today from iteration 1
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce.\nThe introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs.\nInfosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings.\nCurrent fees for H-1B visa applications include $215 for lottery registration and $780 for the employer-sponsored petition, which may rise under new regulations.", "Today Summary": "Infosys Ltd. is facing significant challenges due to the introduction of a $100,000 fee on H-1B visas, as highlighted by former CFO Mohandas Pai. This steep fee is expected to discourage companies from submitting new applications for H-1B visas, potentially leading to an increase in offshoring as firms seek to minimize costs associated with hiring foreign talent. The fee applies to all H-1B positions, which means it will primarily be financially viable for high-value roles, creating difficulties for Infosys that typically relies on H-1B visas for junior and mid-level engineers. The overall sentiment suggests a shift in hiring strategies, with companies reassessing their approach to U.S. operations in light of the prohibitive costs associated with the new visa policy.\nThe $100,000 fee for H-1B visas is expected to discourage companies from filing new applications, potentially leading to increased offshoring, as stated by former Infosys CFO Mohandas Pai.\nThe fee applies to all H-1B positions, making it financially viable primarily for high-value roles, which poses challenges for Infosys that relies on H-1B visas for junior and mid-level engineers."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:04<00:00,  4.45s/it]

Consolidated narrative length: 1887
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Infosys Ltd.", "Previous Narrative": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. C
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.40s/it]

Completed Entity: Infosys Ltd., Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: Infosys Ltd., Date: 2025-09-22 00:00:00, Iteration: 3
Iteration 3 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 2
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. Current fees for H-1B visa applications include $215 for lottery registration and $780 for the employer-sponsored petition, which may rise under new regulations. Infosys Ltd. is facing significant challenges due to the introduction of a $100,000 fee on H-1B visas, as highlighted by former CFO Mohandas Pai. This steep fee is expected to discourage companies from submitting new applications for H-1B visas, potentially leading to an increase in offshoring as firms seek to minimize costs associated with hiring foreign talent. The fee applies to all H-1B positions, which means it will primarily be financially viable for high-value roles, creating difficulties for Infosys that typically relies on H-1B visas for junior and mid-level engineers. The overall sentiment suggests a shift in hiring strategies, with companies reassessing their approach to U.S. operations in light of the prohibitive costs associated with the new visa policy.", "Today Summary": "Infosys Ltd. is facing significant challenges due to the recent introduction of a $100,000 annual fee on H-1B visas, which is expected to sharply increase operational costs and reduce demand for Indian tech talent, who make up over 70% of H-1B visa holders. Analysts predict that this fee hike will lead to further adjustments in staffing strategies, including increased offshoring to India and local hiring in the U.S. The immediate impact has been a decline in Infosys's U.S.-listed shares by 4%, reflecting investor concerns about profitability and potential project disruptions. The company is already reducing its dependence on H-1B visas by shifting more work to India and hiring locally in the U.S., indicating a strategic pivot in response to the new fee structure. Industry analysts warn that the new fee could lead to a near-term freeze on new H-1B applications, further complicating the hiring landscape for Infosys and other major Indian IT firms.\nThe introduction of a $100,000 annual fee for H-1B visas is expected to sharply increase costs for Infosys and reduce demand for Indian tech talent, who constitute over 70% of H-1B visa holders.\nInfosys has begun to reduce its dependence on H-1B visas by shifting more work to India and hiring locally in the U.S., indicating a strategic response to the new fee structure."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.72s/it]

Consolidated narrative length: 2801
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Infosys Ltd.", "Previous Narrative": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. C
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.31s/it]

Completed Entity: Infosys Ltd., Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Infosys Ltd., Date: 2025-09-23 00:00:00, Iteration: 4
Iteration 4 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 3
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. Current fees for H-1B visa applications include $215 for lottery registration and $780 for the employer-sponsored petition, which may rise under new regulations. Infosys Ltd. is facing significant challenges due to the introduction of a $100,000 fee on H-1B visas, as highlighted by former CFO Mohandas Pai. This steep fee is expected to discourage companies from submitting new applications for H-1B visas, potentially leading to an increase in offshoring as firms seek to minimize costs associated with hiring foreign talent. The fee applies to all H-1B positions, which means it will primarily be financially viable for high-value roles, creating difficulties for Infosys that typically relies on H-1B visas for junior and mid-level engineers. The overall sentiment suggests a shift in hiring strategies, with companies reassessing their approach to U.S. operations in light of the prohibitive costs associated with the new visa policy. Additionally, the recent introduction of a $100,000 annual fee on H-1B visas is expected to sharply increase operational costs and reduce demand for Indian tech talent, who make up over 70% of H-1B visa holders. Analysts predict that this fee hike will lead to further adjustments in staffing strategies, including increased offshoring to India and local hiring in the U.S. The immediate impact has been a decline in Infosys's U.S.-listed shares by 4%, reflecting investor concerns about profitability and potential project disruptions. The company is already reducing its dependence on H-1B visas by shifting more work to India and hiring locally in the U.S., indicating a strategic pivot in response to the new fee structure. Industry analysts warn that the new fee could lead to a near-term freeze on new H-1B applications, further complicating the hiring landscape for Infosys and other major Indian IT firms.", "Today Summary": "Infosys Ltd. is currently grappling with significant operational and financial challenges stemming from the recent introduction of a $100,000 annual fee for H-1B visas. This fee is anticipated to drastically increase costs associated with sending engineers to the U.S. for client projects, complicating workforce planning, recruitment, and deployment strategies. In response, Infosys, along with other major Indian IT firms, is exploring alternative solutions such as remote work and client-side training in India to mitigate the impact of these increased costs. Analysts predict that the fee hike could reduce operating profits for Infosys by 7-15%, necessitating a reevaluation of pricing and hiring strategies. The overall economic advantage of sending Indian employees to the U.S. is expected to diminish, leading to a potential shift in business models and increased local hiring in the U.S. to maintain competitiveness. This represents a significant shift in strategy for Infosys as it adapts to the new fee structure, which could damage the offshore IT services model.\nThe introduction of the $100,000 annual fee for H-1B visas is expected to drastically increase costs for sending engineers to the U.S., complicating workforce planning and recruitment for Infosys.\nAnalysts estimate that the new visa fee could cut operating profits for Infosys by 7-15%, prompting a reevaluation of pricing and hiring strategies."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.55s/it]

Consolidated narrative length: 3877
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Infosys Ltd.", "Previous Narrative": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. C
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.28s/it]

Completed Entity: Infosys Ltd., Date: 2025-09-23 00:00:00
--------------------------------------------------
Processing Entity: Infosys Ltd., Date: 2025-09-24 00:00:00, Iteration: 5
Iteration 5 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 4
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. Current fees for H-1B visa applications include $215 for lottery registration and $780 for the employer-sponsored petition, which may rise under new regulations. Infosys Ltd. is facing significant challenges due to the introduction of a $100,000 fee on H-1B visas, as highlighted by former CFO Mohandas Pai. This steep fee is expected to discourage companies from submitting new applications for H-1B visas, potentially leading to an increase in offshoring as firms seek to minimize costs associated with hiring foreign talent. The fee applies to all H-1B positions, which means it will primarily be financially viable for high-value roles, creating difficulties for Infosys that typically relies on H-1B visas for junior and mid-level engineers. The overall sentiment suggests a shift in hiring strategies, with companies reassessing their approach to U.S. operations in light of the prohibitive costs associated with the new visa policy. Additionally, the recent introduction of a $100,000 annual fee on H-1B visas is expected to sharply increase operational costs and reduce demand for Indian tech talent, who make up over 70% of H-1B visa holders. Analysts predict that this fee hike will lead to further adjustments in staffing strategies, including increased offshoring to India and local hiring in the U.S. The immediate impact has been a decline in Infosys's U.S.-listed shares by 4%, reflecting investor concerns about profitability and potential project disruptions. The company is already reducing its dependence on H-1B visas by shifting more work to India and hiring locally in the U.S., indicating a strategic pivot in response to the new fee structure. Industry analysts warn that the new fee could lead to a near-term freeze on new H-1B applications, further complicating the hiring landscape for Infosys and other major Indian IT firms. Infosys Ltd. is currently grappling with significant operational and financial challenges stemming from the recent introduction of a $100,000 annual fee for H-1B visas. This fee is anticipated to drastically increase costs associated with sending engineers to the U.S. for client projects, complicating workforce planning, recruitment, and deployment strategies. In response, Infosys, along with other major Indian IT firms, is exploring alternative solutions such as remote work and client-side training in India to mitigate the impact of these increased costs. Analysts predict that the fee hike could reduce operating profits for Infosys by 7-15%, necessitating a reevaluation of pricing and hiring strategies. The overall economic advantage of sending Indian employees to the U.S. is expected to diminish, leading to a potential shift in business models and increased local hiring in the U.S. to maintain competitiveness. This represents a significant shift in strategy for Infosys as it adapts to the new fee structure, which could damage the offshore IT services model.", "Today Summary": "Today, Infosys Ltd. faces an estimated increase in annual immigration costs ranging from $150 to $550 million due to the introduction of high fees on H-1B visas. This significant rise in costs is projected to erode core operating margins by 7-15%, prompting the company to reevaluate the necessity of onsite roles and restructure contracts. To mitigate the financial impact, Infosys is expected to accelerate its offshoring and local hiring strategies. Analysts suggest that while the new policy may reduce net profit margins by 1-3%, Infosys is relatively well-positioned to adapt due to its aggressive localization strategies. However, the overall environment remains challenging, with increased operational costs and a hostile U.S. immigration stance contributing to uncertainty in the sector.\nInfosys is projected to face an increase in annual immigration costs between $150-550 million due to the new H-1B visa fee.\nThe introduction of the high fee is expected to compel Infosys to accelerate offshoring and local hiring strategies to mitigate the financial burden."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:10<00:00, 10.86s/it]

Consolidated narrative length: 4674
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Infosys Ltd.", "Previous Narrative": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. C
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.09s/it]

Completed Entity: Infosys Ltd., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: Infosys Ltd., Date: 2025-09-25 00:00:00, Iteration: 6
Iteration 6 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 5
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. Current fees for H-1B visa applications include $215 for lottery registration and $780 for the employer-sponsored petition, which may rise under new regulations. Infosys Ltd. is facing significant challenges due to the introduction of a $100,000 fee on H-1B visas, as highlighted by former CFO Mohandas Pai. This steep fee is expected to discourage companies from submitting new applications for H-1B visas, potentially leading to an increase in offshoring as firms seek to minimize costs associated with hiring foreign talent. The fee applies to all H-1B positions, which means it will primarily be financially viable for high-value roles, creating difficulties for Infosys that typically relies on H-1B visas for junior and mid-level engineers. The overall sentiment suggests a shift in hiring strategies, with companies reassessing their approach to U.S. operations in light of the prohibitive costs associated with the new visa policy. Additionally, the recent introduction of a $100,000 annual fee on H-1B visas is expected to sharply increase operational costs and reduce demand for Indian tech talent, who make up over 70% of H-1B visa holders. Analysts predict that this fee hike will lead to further adjustments in staffing strategies, including increased offshoring to India and local hiring in the U.S. The immediate impact has been a decline in Infosys's U.S.-listed shares by 4%, reflecting investor concerns about profitability and potential project disruptions. The company is already reducing its dependence on H-1B visas by shifting more work to India and hiring locally in the U.S., indicating a strategic pivot in response to the new fee structure. Industry analysts warn that the new fee could lead to a near-term freeze on new H-1B applications, further complicating the hiring landscape for Infosys and other major Indian IT firms. Infosys Ltd. is currently grappling with significant operational and financial challenges stemming from the recent introduction of a $100,000 annual fee for H-1B visas. This fee is anticipated to drastically increase costs associated with sending engineers to the U.S. for client projects, complicating workforce planning, recruitment, and deployment strategies. In response, Infosys, along with other major Indian IT firms, is exploring alternative solutions such as remote work and client-side training in India to mitigate the impact of these increased costs. Analysts predict that the fee hike could reduce operating profits for Infosys by 7-15%, necessitating a reevaluation of pricing and hiring strategies. The overall economic advantage of sending Indian employees to the U.S. is expected to diminish, leading to a potential shift in business models and increased local hiring in the U.S. to maintain competitiveness. This represents a significant shift in strategy for Infosys as it adapts to the new fee structure, which could damage the offshore IT services model. Today, Infosys Ltd. faces an estimated increase in annual immigration costs ranging from $150 to $550 million due to the introduction of high fees on H-1B visas. This significant rise in costs is projected to erode core operating margins by 7-15%, prompting the company to reevaluate the necessity of onsite roles and restructure contracts. To mitigate the financial impact, Infosys is expected to accelerate its offshoring and local hiring strategies. Analysts suggest that while the new policy may reduce net profit margins by 1-3%, Infosys is relatively well-positioned to adapt due to its aggressive localization strategies. However, the overall environment remains challenging, with increased operational costs and a hostile U.S. immigration stance contributing to uncertainty in the sector.", "Today Summary": "Today, Infosys Ltd. faces additional challenges due to the proposed introduction of a high fee on H-1B visas, which is expected to significantly increase operational costs and complicate hiring practices. Analysts have highlighted that the cost of hiring new employees under the H-1B program could equate to a full year's salary, further straining the financial landscape for Infosys and its peers. The new fee structure is anticipated to deepen existing margin pressures in an industry already dealing with tighter client budgets and technological disruptions. This situation may lead to reduced hiring or a shift of jobs back to India for Infosys and other Indian IT companies, as they navigate the financial implications of the new visa policy.\nThe cost of hiring new employees under the H-1B program could equate to a full year's salary, complicating the financial landscape for Infosys.\nThe proposed changes to the H-1B visa program may lead to reduced hiring or a shift of jobs back to India for Infosys and other Indian IT companies."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:11<00:00, 11.90s/it]

Consolidated narrative length: 5163
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Infosys Ltd.", "Previous Narrative": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce. The introduction of high fees on H-1B visas could significantly affect Infosys's ability to hire foreign workers, as it will increase operational costs. Infosys, along with other consultancies, employs a large number of foreign workers, primarily from India, to support American firms seeking cost savings. C
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.40s/it]

Completed Entity: Infosys Ltd., Date: 2025-09-25 00:00:00
--------------------------------------------------
Processing Entity: Metaview, Date: 2025-09-22 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Metaview, Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Microsoft Corp., Date: 2025-09-19 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Microsoft Corp., Date: 2025-09-19 00:00:00
--------------------------------------------------
Processing Entity: Microsoft Corp., Date: 2025-09-20 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'Microsoft Corp._2025-09-19 00:00:00': 'Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry.\nMicrosoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may lead to a dramatic rethink of hiring practices for Microsoft and other companies reliant on H-1B visas.\nThe fee makes access to U.S. jobs harder and more exclusive for foreign workers hoping to land positions in companies like Microsoft.\nWhile major corporations like Microsoft may not be deterred by the fee, smaller startups could face significant burdens.'}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Microsoft Corp.", "Previous Narrative": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry.\nMicrosoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may lead to a dramatic rethink of
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.92s/it]

Completed Entity: Microsoft Corp., Date: 2025-09-20 00:00:00
--------------------------------------------------
Processing Entity: Microsoft Corp., Date: 2025-09-21 00:00:00, Iteration: 2
Iteration 2 - consolidation + temporal analysis
Consolidating: previous from iteration 0, today from iteration 1
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry.\nMicrosoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may lead to a dramatic rethink of hiring practices for Microsoft and other companies reliant on H-1B visas.\nThe fee makes access to U.S. jobs harder and more exclusive for foreign workers hoping to land positions in companies like Microsoft.\nWhile major corporations like Microsoft may not be deterred by the fee, smaller startups could face significant burdens.", "Today Summary": "Microsoft Corp. is facing significant challenges due to the recent introduction of a $100,000 annual fee for H-1B visas, which has been described as a 'shock' to Indian IT professionals. The company, alongside Amazon, has advised its employees holding H-1B and H-4 visas to remain in or return to the United States amid confusion regarding the new policy. This fee increase is expected to disproportionately affect Indian talent, who make up a large portion of H-1B visa holders. As a result, Microsoft may need to reconsider its hiring strategies, potentially prioritizing highly specialized roles while reducing opportunities for junior and mid-level positions. There are growing concerns that this policy could stifle innovation and competitiveness in the U.S. tech sector, possibly leading to offshoring and deterring international talent from pursuing opportunities in the U.S.\nMicrosoft has warned employees on H-1B and H-4 visas to remain in or return to the U.S. amid confusion over the new $100,000 visa fee.\nThe introduction of the high fee is expected to disproportionately impact Indian IT professionals, who make up a significant portion of H-1B visa holders."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.55s/it]

Consolidated narrative length: 2155
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Microsoft Corp.", "Previous Narrative": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry.\nMicrosoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may lead to a dramatic rethink of
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.32s/it]

Completed Entity: Microsoft Corp., Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: Microsoft Corp., Date: 2025-09-22 00:00:00, Iteration: 3
Iteration 3 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 2
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry.\nMicrosoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas.\nThe introduction of the fee could deter global talent and stifle innovation, according to critics.\nThe fee may lead to a dramatic rethink of hiring practices for Microsoft and other companies reliant on H-1B visas.\nThe fee makes access to U.S. jobs harder and more exclusive for foreign workers hoping to land positions in companies like Microsoft.\nWhile major corporations like Microsoft may not be deterred by the fee, smaller startups could face significant burdens.\nMicrosoft Corp. is facing significant challenges due to the recent introduction of a $100,000 annual fee for H-1B visas, which has been described as a 'shock' to Indian IT professionals.\nThe company, alongside Amazon, has advised its employees holding H-1B and H-4 visas to remain in or return to the United States amid confusion regarding the new policy.\nThis fee increase is expected to disproportionately affect Indian talent, who make up a large portion of H-1B visa holders.\nAs a result, Microsoft may need to reconsider its hiring strategies, potentially prioritizing highly specialized roles while reducing opportunities for junior and mid-level positions.\nThere are growing concerns that this policy could stifle innovation and competitiveness in the U.S. tech sector, possibly leading to offshoring and deterring international talent from pursuing opportunities in the U.S.", "Today Summary": "Microsoft Corp. has raised significant concerns regarding the newly introduced $100,000 annual fee for H-1B visa applications, which is set to take effect imminently. The company, alongside other major tech firms, has urgently advised its H-1B employees to remain in the U.S. or return quickly if they are currently overseas, emphasizing the critical nature of the situation. Microsoft is particularly worried about the financial implications of this fee, which could lead to a reduction in H-1B sponsorships and disrupt ongoing projects that depend on skilled foreign workers. The company anticipates that the fee will force them to be more selective in their hiring of H-1B candidates, potentially hindering innovation and the influx of talent into the U.S. tech sector. Additionally, a Microsoft executive indicated that the company might consider shifting more workers to Canada due to its more favorable immigration laws, suggesting that the U.S. could lose out on tax revenue and job creation as a result of this policy.\nMicrosoft has advised its H-1B employees to remain in the U.S. or return quickly before the new fee takes effect, highlighting the urgency of the situation.\nA Microsoft executive indicated that the company may shift more workers to Canada due to friendlier immigration laws, suggesting potential job and tax revenue losses for the U.S."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.70s/it]

Consolidated narrative length: 3182
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Microsoft Corp.", "Previous Narrative": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry. Microsoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas. The introduction of the fee could deter global talent and stifle innovation, according to critics. The fee may lead to a dramatic rethink of hi
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.08s/it]

Completed Entity: Microsoft Corp., Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Microsoft Corp., Date: 2025-09-23 00:00:00, Iteration: 4
Iteration 4 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 3
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry. Microsoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas. The introduction of the fee could deter global talent and stifle innovation, according to critics. The fee may lead to a dramatic rethink of hiring practices for Microsoft and other companies reliant on H-1B visas. The fee makes access to U.S. jobs harder and more exclusive for foreign workers hoping to land positions in companies like Microsoft. While major corporations like Microsoft may not be deterred by the fee, smaller startups could face significant burdens. Microsoft Corp. is facing significant challenges due to the recent introduction of a $100,000 annual fee for H-1B visas, which has been described as a 'shock' to Indian IT professionals. The company, alongside Amazon, has advised its employees holding H-1B and H-4 visas to remain in or return to the United States amid confusion regarding the new policy. This fee increase is expected to disproportionately affect Indian talent, who make up a large portion of H-1B visa holders. As a result, Microsoft may need to reconsider its hiring strategies, potentially prioritizing highly specialized roles while reducing opportunities for junior and mid-level positions. There are growing concerns that this policy could stifle innovation and competitiveness in the U.S. tech sector, possibly leading to offshoring and deterring international talent from pursuing opportunities in the U.S. Microsoft Corp. has raised significant concerns regarding the newly introduced $100,000 annual fee for H-1B visa applications, which is set to take effect imminently. The company, alongside other major tech firms, has urgently advised its H-1B employees to remain in the U.S. or return quickly if they are currently overseas, emphasizing the critical nature of the situation. Microsoft is particularly worried about the financial implications of this fee, which could lead to a reduction in H-1B sponsorships and disrupt ongoing projects that depend on skilled foreign workers. The company anticipates that the fee will force them to be more selective in their hiring of H-1B candidates, potentially hindering innovation and the influx of talent into the U.S. tech sector. Additionally, a Microsoft executive indicated that the company might consider shifting more workers to Canada due to its more favorable immigration laws, suggesting that the U.S. could lose out on tax revenue and job creation as a result of this policy.", "Today Summary": "Microsoft Corp. continues to express significant concern regarding the newly introduced $100,000 fee on H-1B visas, which is perceived as regressive and detrimental to the American economy. The company, alongside Amazon, has reiterated its advice to employees on H-1B and H-4 visas to remain in or return to the U.S. amid ongoing confusion about the policy. This fee is expected to particularly impact Indian IT professionals, who make up a substantial portion of H-1B visa holders. The introduction of this fee may force Microsoft and other tech firms to reevaluate their hiring practices, potentially limiting access to global talent and slowing innovation. Furthermore, the policy risks disrupting India-U.S. tech collaborations and could push skilled workers towards other countries, thereby affecting the overall competitiveness of the U.S. tech industry. The new fee structure is anticipated to inflate operational costs and deter top-tier talent, which could slow critical innovation pipelines in areas such as AI, cloud computing, and cybersecurity.\nThe $100,000 fee is viewed as regressive and could harm the American economy, particularly impacting Indian talent and the tech sector's reliance on skilled workers.\nThe policy may force Microsoft and other IT firms to reconsider hiring practices, potentially limiting access to global talent and slowing innovation."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:10<00:00, 10.45s/it]

Consolidated narrative length: 4240
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Microsoft Corp.", "Previous Narrative": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry. Microsoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas. The introduction of the fee could deter global talent and stifle innovation, according to critics. The fee may lead to a dramatic rethink of hi
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:04<00:00,  4.70s/it]

Completed Entity: Microsoft Corp., Date: 2025-09-23 00:00:00
--------------------------------------------------
Processing Entity: Microsoft Corp., Date: 2025-09-24 00:00:00, Iteration: 5
Iteration 5 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 4
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry. Microsoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas. The introduction of the fee could deter global talent and stifle innovation, according to critics. The fee may lead to a dramatic rethink of hiring practices for Microsoft and other companies reliant on H-1B visas. The fee makes access to U.S. jobs harder and more exclusive for foreign workers hoping to land positions in companies like Microsoft. While major corporations like Microsoft may not be deterred by the fee, smaller startups could face significant burdens. Microsoft Corp. is facing significant challenges due to the recent introduction of a $100,000 annual fee for H-1B visas, which has been described as a 'shock' to Indian IT professionals. The company, alongside Amazon, has advised its employees holding H-1B and H-4 visas to remain in or return to the United States amid confusion regarding the new policy. This fee increase is expected to disproportionately affect Indian talent, who make up a large portion of H-1B visa holders. As a result, Microsoft may need to reconsider its hiring strategies, potentially prioritizing highly specialized roles while reducing opportunities for junior and mid-level positions. There are growing concerns that this policy could stifle innovation and competitiveness in the U.S. tech sector, possibly leading to offshoring and deterring international talent from pursuing opportunities in the U.S. Microsoft Corp. has raised significant concerns regarding the newly introduced $100,000 annual fee for H-1B visa applications, which is set to take effect imminently. The company, alongside other major tech firms, has urgently advised its H-1B employees to remain in the U.S. or return quickly if they are currently overseas, emphasizing the critical nature of the situation. Microsoft is particularly worried about the financial implications of this fee, which could lead to a reduction in H-1B sponsorships and disrupt ongoing projects that depend on skilled foreign workers. The company anticipates that the fee will force them to be more selective in their hiring of H-1B candidates, potentially hindering innovation and the influx of talent into the U.S. tech sector. Additionally, a Microsoft executive indicated that the company might consider shifting more workers to Canada due to its more favorable immigration laws, suggesting that the U.S. could lose out on tax revenue and job creation as a result of this policy. Microsoft Corp. continues to express significant concern regarding the newly introduced $100,000 fee on H-1B visas, which is perceived as regressive and detrimental to the American economy. The company, alongside Amazon, has reiterated its advice to employees on H-1B and H-4 visas to remain in or return to the U.S. amid ongoing confusion about the policy. This fee is expected to particularly impact Indian IT professionals, who make up a substantial portion of H-1B visa holders. The introduction of this fee may force Microsoft and other tech firms to reevaluate their hiring practices, potentially limiting access to global talent and slowing innovation. Furthermore, the policy risks disrupting India-U.S. tech collaborations and could push skilled workers towards other countries, thereby affecting the overall competitiveness of the U.S. tech industry. The new fee structure is anticipated to inflate operational costs and deter top-tier talent, which could slow critical innovation pipelines in areas such as AI, cloud computing, and cybersecurity.", "Today Summary": "Microsoft Corp. continues to express significant concern regarding the newly introduced $100,000 one-time fee for H-1B visa applications, which is expected to create substantial new costs for the company and other major tech employers. The fee disproportionately affects Indian technology workers, who constitute a large percentage of H-1B visa holders. Experts suggest that this fee may lead to companies considering hiring laid-off H-1B visa holders from firms like Microsoft, indicating a potential shift in hiring strategies. The overall sentiment remains that the new fee could slow down collaborations between India and the U.S. in the tech sector, further emphasizing the regressive nature of the policy and its potential harm to the American economy, which relies heavily on skilled workers, particularly from India.\nThe $100,000 one-time fee for H-1B visa applications is expected to create substantial new costs for Microsoft and other major tech employers.\nExperts suggest that the new fee could prompt companies to consider hiring laid-off H-1B visa holders from Microsoft and other tech firms."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:10<00:00, 10.26s/it]

Consolidated narrative length: 4416
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Microsoft Corp.", "Previous Narrative": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry. Microsoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas. The introduction of the fee could deter global talent and stifle innovation, according to critics. The fee may lead to a dramatic rethink of hi
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:04<00:00,  4.31s/it]

Completed Entity: Microsoft Corp., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: Microsoft Corp., Date: 2025-09-25 00:00:00, Iteration: 6
Iteration 6 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 5
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry. Microsoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas. The introduction of the fee could deter global talent and stifle innovation, according to critics. The fee may lead to a dramatic rethink of hiring practices for Microsoft and other companies reliant on H-1B visas. The fee makes access to U.S. jobs harder and more exclusive for foreign workers hoping to land positions in companies like Microsoft. While major corporations like Microsoft may not be deterred by the fee, smaller startups could face significant burdens. Microsoft Corp. is facing significant challenges due to the recent introduction of a $100,000 annual fee for H-1B visas, which has been described as a 'shock' to Indian IT professionals. The company, alongside Amazon, has advised its employees holding H-1B and H-4 visas to remain in or return to the United States amid confusion regarding the new policy. This fee increase is expected to disproportionately affect Indian talent, who make up a large portion of H-1B visa holders. As a result, Microsoft may need to reconsider its hiring strategies, potentially prioritizing highly specialized roles while reducing opportunities for junior and mid-level positions. There are growing concerns that this policy could stifle innovation and competitiveness in the U.S. tech sector, possibly leading to offshoring and deterring international talent from pursuing opportunities in the U.S. Microsoft Corp. has raised significant concerns regarding the newly introduced $100,000 annual fee for H-1B visa applications, which is set to take effect imminently. The company, alongside other major tech firms, has urgently advised its H-1B employees to remain in the U.S. or return quickly if they are currently overseas, emphasizing the critical nature of the situation. Microsoft is particularly worried about the financial implications of this fee, which could lead to a reduction in H-1B sponsorships and disrupt ongoing projects that depend on skilled foreign workers. The company anticipates that the fee will force them to be more selective in their hiring of H-1B candidates, potentially hindering innovation and the influx of talent into the U.S. tech sector. Additionally, a Microsoft executive indicated that the company might consider shifting more workers to Canada due to its more favorable immigration laws, suggesting that the U.S. could lose out on tax revenue and job creation as a result of this policy. Microsoft Corp. continues to express significant concern regarding the newly introduced $100,000 fee on H-1B visas, which is perceived as regressive and detrimental to the American economy. The company, alongside Amazon, has reiterated its advice to employees on H-1B and H-4 visas to remain in or return to the U.S. amid ongoing confusion about the policy. This fee is expected to particularly impact Indian IT professionals, who make up a substantial portion of H-1B visa holders. The introduction of this fee may force Microsoft and other tech firms to reevaluate their hiring practices, potentially limiting access to global talent and slowing innovation. Furthermore, the policy risks disrupting India-U.S. tech collaborations and could push skilled workers towards other countries, thereby affecting the overall competitiveness of the U.S. tech industry. The new fee structure is anticipated to inflate operational costs and deter top-tier talent, which could slow critical innovation pipelines in areas such as AI, cloud computing, and cybersecurity. Experts suggest that this fee may lead to companies considering hiring laid-off H-1B visa holders from firms like Microsoft, indicating a potential shift in hiring strategies.", "Today Summary": "Microsoft Corp. is facing a significant impact from the newly introduced $100,000 fee on H-1B visas, which is expected to double hiring costs and necessitate a reassessment of its human resources strategies. The company heavily relies on foreign engineers and developers to fill critical gaps in the domestic labor market, and this fee increase could lead to a reduction in applicant numbers and a greater reliance on overseas development centers. Analysts suggest that while Microsoft can absorb the costs, which represent only a small fraction of its substantial R&D budget, the policy may adversely affect smaller firms and the broader tech ecosystem, ultimately impacting competitiveness and innovation. The fee is anticipated to slow the pace of innovation and delay product launches in key sectors such as artificial intelligence and cloud computing.\nThe introduction of a $100,000 fee on H-1B visas will double hiring costs for Microsoft and prompt a reassessment of its human resources strategies.\nThe fee increase could slow the pace of innovation and delay product launches in key sectors like artificial intelligence and cloud computing."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:12<00:00, 12.10s/it]

Consolidated narrative length: 5228
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Microsoft Corp.", "Previous Narrative": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry. Microsoft, along with other big tech companies, faces increased operational costs due to the proposed high fee on H-1B visas. The introduction of the fee could deter global talent and stifle innovation, according to critics. The fee may lead to a dramatic rethink of hi
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.59s/it]

Completed Entity: Microsoft Corp., Date: 2025-09-25 00:00:00
--------------------------------------------------
Processing Entity: Talent Fund, Date: 2025-09-22 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Talent Fund, Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Talent Fund, Date: 2025-09-25 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'Talent Fund_2025-09-22 00:00:00': "Talent Fund's position regarding the introduction of a high fee on H-1B visas reflects concern over the potential impact on attracting global talent. The announcement of a significant fee increase to $100,000 by President Donald Trump has raised alarms within the tech industry, particularly as the H-1B program is crucial for skilled foreign workers, especially from India, to fill roles in technology, research, and healthcare sectors. The comments from Jamie Arrowsmith highlight the need for funding and support to ensure a smooth transition for global talent amidst these changes.\nThe introduction of a $100,000 fee for H-1B visas by President Trump has shocked the tech industry.\nThe H-1B program is essential for skilled foreign workers, particularly Indians, in the technology, research, and healthcare sectors.\nJamie Arrowsmith emphasized the need for funding and autonomy to attract global talent effectively."}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Talent Fund", "Previous Narrative": "Talent Fund's position regarding the introduction of a high fee on H-1B visas reflects concern over the potential impact on attracting global talent. The announcement of a significant fee increase to $100,000 by President Donald Trump has raised alarms within the tech industry, particularly as the H-1B program is crucial for skilled foreign workers, especially from India, to fill roles in technology, research, and healthcare sectors. The comments from Jamie Arrowsmith highlight the need for funding and support to ensure a smooth transition for global talent amidst these changes.\nThe introduction of a $100,000 fee for H-1B visas by President Trump has shocked the tech industry.\nThe H-1B program is essential for skilled foreign workers, particularly Indians, in the technology, research, and healthcare sectors.\nJamie Arrowsmith emphasized the need for funding and autonomy to attract global talent effectively.", "Today Summary": "Talent
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.25s/it]

Completed Entity: Talent Fund, Date: 2025-09-25 00:00:00
--------------------------------------------------
Processing Entity: Tata Consultancy Services Ltd., Date: 2025-09-20 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Tata Consultancy Services Ltd., Date: 2025-09-20 00:00:00
--------------------------------------------------
Processing Entity: Tata Consultancy Services Ltd., Date: 2025-09-21 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'Tata Consultancy Services Ltd._2025-09-20 00:00:00': "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations.\nThe introduction of a $100,000 fee for H-1B visa sponsorship is expected to significantly impact TCS's hiring strategies.\nTCS, along with other major firms, may need to shift focus to hiring highly specialized, high-wage talent and domestic graduates due to the increased costs of H-1B sponsorship.\nThe new fee could reduce opportunities for Indian professionals, who make up the majority of H-1B holders, particularly in junior roles.\nTCS has not yet provided a public response to the new H-1B visa fee increase."}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Tata Consultancy Services Ltd.", "Previous Narrative": "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations.\nThe introduction of a $100,000 fee for H-1B visa sponsorship is expected to signific
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.84s/it]

Completed Entity: Tata Consultancy Services Ltd., Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: Tata Consultancy Services Ltd., Date: 2025-09-22 00:00:00, Iteration: 2
Iteration 2 - consolidation + temporal analysis
Consolidating: previous from iteration 0, today from iteration 1
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations.\nThe introduction of a $100,000 fee for H-1B visa sponsorship is expected to significantly impact TCS's hiring strategies.\nTCS, along with other major firms, may need to shift focus to hiring highly specialized, high-wage talent and domestic graduates due to the increased costs of H-1B sponsorship.\nThe new fee could reduce opportunities for Indian professionals, who make up the majority of H-1B holders, particularly in junior roles.\nTCS has not yet provided a public response to the new H-1B visa fee increase.", "Today Summary": "Tata Consultancy Services Ltd. (TCS) is responding to the introduction of a high fee on H-1B visas by advising its employees on H-1B visas to either remain in the U.S. or return quickly before the new regulations take effect. This reflects a sense of urgency and concern within the company regarding the implications of the fee increase, which is expected to significantly reduce access to the H-1B program for many skilled foreign nationals. As one of the top recipients of H-1B visas, TCS anticipates facing increased operational costs that could hinder its ability to hire new talent and maintain staffing levels. The fee hike is viewed as a threat to global talent mobility, which has historically supported U.S. tech firms, and may lead to companies becoming more selective in their sponsorship of H-1B candidates, focusing on only the most critical roles.\nTCS has advised its employees on H-1B visas to stay in the U.S. or return quickly before the new regulations take effect, indicating urgency in response to the fee increase.\nThe company expects the high fee on H-1B visas to significantly reduce access to the program for many skilled foreign nationals, reshaping employer demand."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:04<00:00,  4.86s/it]

Consolidated narrative length: 1689
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Tata Consultancy Services Ltd.", "Previous Narrative": "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations. The introduction of a $100,000 fee for H-1B visa sponsorship is expected to significa
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.52s/it]

Completed Entity: Tata Consultancy Services Ltd., Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Tata Consultancy Services Ltd., Date: 2025-09-23 00:00:00, Iteration: 3
Iteration 3 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 2
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations. The introduction of a $100,000 fee for H-1B visa sponsorship is expected to significantly impact TCS's hiring strategies. TCS, along with other major firms, may need to shift focus to hiring highly specialized, high-wage talent and domestic graduates due to the increased costs of H-1B sponsorship. The new fee could reduce opportunities for Indian professionals, who make up the majority of H-1B holders, particularly in junior roles. TCS has not yet provided a public response to the new H-1B visa fee increase. TCS has advised its employees on H-1B visas to stay in the U.S. or return quickly before the new regulations take effect, indicating urgency in response to the fee increase. The company expects the high fee on H-1B visas to significantly reduce access to the program for many skilled foreign nationals, reshaping employer demand.", "Today Summary": "Tata Consultancy Services (TCS) is currently grappling with significant operational and financial challenges due to the newly introduced $100,000 annual fee on H-1B visas. This fee complicates TCS's workforce planning, recruitment, and deployment strategies, particularly as the company relies heavily on H-1B visas to send engineers to the U.S. for client projects. Analysts note that while TCS may be better positioned to absorb these costs due to its profitability and strong balance sheet, the fee increase is still expected to impact project timelines and margins. TCS is likely to explore alternative solutions, such as remote work and contract renegotiations, to alleviate the financial burden. The new fee structure is anticipated to make TCS more selective in its sponsorship of H-1B candidates, potentially reserving filings for only the most critical roles, which could further reduce access to skilled foreign workers.\nTCS is expected to explore alternative solutions such as remote work and contract renegotiations to mitigate the financial burden of the new $100,000 annual fee on H-1B visas.\nThe fee increase is anticipated to make TCS more selective in its sponsorship of H-1B candidates, potentially reserving filings for only the most business-critical roles."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.31s/it]

Consolidated narrative length: 2592
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Tata Consultancy Services Ltd.", "Previous Narrative": "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations. The introduction of a $100,000 fee for H-1B visa sponsorship is expected to significa
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.76s/it]

Completed Entity: Tata Consultancy Services Ltd., Date: 2025-09-23 00:00:00
--------------------------------------------------
Processing Entity: Tata Consultancy Services Ltd., Date: 2025-09-24 00:00:00, Iteration: 4
Iteration 4 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 3
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations. The introduction of a $100,000 fee for H-1B visa sponsorship is expected to significantly impact TCS's hiring strategies. TCS, along with other major firms, may need to shift focus to hiring highly specialized, high-wage talent and domestic graduates due to the increased costs of H-1B sponsorship. The new fee could reduce opportunities for Indian professionals, who make up the majority of H-1B holders, particularly in junior roles. TCS has not yet provided a public response to the new H-1B visa fee increase. TCS has advised its employees on H-1B visas to stay in the U.S. or return quickly before the new regulations take effect, indicating urgency in response to the fee increase. The company expects the high fee on H-1B visas to significantly reduce access to the program for many skilled foreign nationals, reshaping employer demand. TCS is currently grappling with significant operational and financial challenges due to the newly introduced $100,000 annual fee on H-1B visas. This fee complicates TCS's workforce planning, recruitment, and deployment strategies, particularly as the company relies heavily on H-1B visas to send engineers to the U.S. for client projects. Analysts note that while TCS may be better positioned to absorb these costs due to its profitability and strong balance sheet, the fee increase is still expected to impact project timelines and margins. TCS is likely to explore alternative solutions, such as remote work and contract renegotiations, to alleviate the financial burden. The new fee structure is anticipated to make TCS more selective in its sponsorship of H-1B candidates, potentially reserving filings for only the most critical roles, which could further reduce access to skilled foreign workers.", "Today Summary": "Tata Consultancy Services Ltd. (TCS) is facing significant challenges due to the introduction of a high fee on H-1B visas, which is expected to increase operating costs and compel the company to accelerate offshoring and local hiring strategies. TCS employs 5,505 workers under the H-1B visa category, making it one of the top companies affected by the new policy. Analysts predict that the new fee structure may lead to a reduction in profit margins and earnings per share, as TCS may need to replace a portion of its H-1B workforce with local hires to mitigate the financial burden. Despite these challenges, TCS is noted to be among the firms least exposed to the impacts of the new policy due to its existing localization strategies.\nTCS employs 5,505 workers using H-1B visas, making it one of the top companies affected by the new high fee policy.\nAnalysts estimate that replacing one-third of H-1B employees with local hires could reduce TCS's EBIT margins by 20-50 basis points and earnings per share by 2-4%."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Consolidated narrative length: 3461
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Tata Consultancy Services Ltd.", "Previous Narrative": "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations. The introduction of a $100,000 fee for H-1B visa sponsorship is expected to significa
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.25s/it]

Completed Entity: Tata Consultancy Services Ltd., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: Thomson Reuters Corp., Date: 2025-09-20 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Thomson Reuters Corp., Date: 2025-09-20 00:00:00
--------------------------------------------------
Processing Entity: Thomson Reuters Corp., Date: 2025-09-21 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'Thomson Reuters Corp._2025-09-20 00:00:00': "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent.\nThe proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech companies, which typically use these visas for junior and mid-level roles.\nMany companies may pull back, delay hiring, or shift roles overseas due to the increased costs associated with the new visa fee.\nThe introduction of high fees could deter global talent from coming to the U.S., reducing the country's ability to innovate and grow economically.\nThe policy may force companies to offshore high-value work, potentially harming America's competitiveness in critical areas like artificial intelligence."}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Thomson Reuters Corp.", "Previous Narrative": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent.\nThe proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech compa
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.74s/it]

Completed Entity: Thomson Reuters Corp., Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: Thomson Reuters Corp., Date: 2025-09-22 00:00:00, Iteration: 2
Iteration 2 - consolidation + temporal analysis
Consolidating: previous from iteration 0, today from iteration 1
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent.\nThe proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech companies, which typically use these visas for junior and mid-level roles.\nMany companies may pull back, delay hiring, or shift roles overseas due to the increased costs associated with the new visa fee.\nThe introduction of high fees could deter global talent from coming to the U.S., reducing the country's ability to innovate and grow economically.\nThe policy may force companies to offshore high-value work, potentially harming America's competitiveness in critical areas like artificial intelligence.", "Today Summary": "Thomson Reuters Corp. has not issued any direct comments regarding the introduction of a high fee on H-1B visas. However, the broader industry response indicates that major companies such as Microsoft, JPMorgan, and Amazon have advised their employees holding H-1B visas to remain in the United States following the announcement of the new fee. This reflects a cautious approach among firms, suggesting that the new fee may lead to increased selectivity in sponsoring H-1B candidates, which could further impact access to skilled foreign labor. Additionally, Commerce Secretary Howard Lutnick mentioned that while the fee would be paid annually, specific details are still under consideration.\nMajor companies, including Microsoft, JPMorgan, and Amazon, have advised employees holding H-1B visas to remain in the United States following the announcement of the new fee, indicating a cautious industry response.\nCommerce Secretary Howard Lutnick stated that the fee would be paid annually, but details are still being considered, highlighting ongoing discussions about the implementation of the fee."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.15s/it]

Consolidated narrative length: 1843
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Thomson Reuters Corp.", "Previous Narrative": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent.\nThe proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech compa
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:04<00:00,  4.46s/it]

Completed Entity: Thomson Reuters Corp., Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Thomson Reuters Corp., Date: 2025-09-23 00:00:00, Iteration: 3
Iteration 3 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 2
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent.\nThe proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech companies, which typically use these visas for junior and mid-level roles.\nMany companies may pull back, delay hiring, or shift roles overseas due to the increased costs associated with the new visa fee.\nThe introduction of high fees could deter global talent from coming to the U.S., reducing the country's ability to innovate and grow economically.\nThe policy may force companies to offshore high-value work, potentially harming America's competitiveness in critical areas like artificial intelligence.\nMajor companies, including Microsoft, JPMorgan, and Amazon, have advised employees holding H-1B visas to remain in the United States following the announcement of the new fee, indicating a cautious industry response.\nCommerce Secretary Howard Lutnick stated that the fee would be paid annually, but details are still being considered, highlighting ongoing discussions about the implementation of the fee.", "Today Summary": "Thomson Reuters Corp. is adapting to the newly introduced high fee on H-1B visas by becoming more selective in its sponsorship of H-1B candidates, prioritizing only the most critical roles. This strategic shift is expected to significantly limit access to the H-1B program for many skilled foreign nationals, thereby reshaping employer demand. Additionally, the company is proactively reducing its reliance on the H-1B program through increased local hiring, acquisitions, and partnerships, indicating a shift in strategy to address the challenges posed by the new fee structure. The company plans to leverage AI tools to tackle any challenges that arise from this new approach.\nThomson Reuters Corp. is expected to become more selective in H-1B sponsorship, focusing on business-critical roles due to the new high fee.\nThe company has reduced its reliance on the H-1B program through local hiring, acquisitions, and partnerships."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.29s/it]

Consolidated narrative length: 2522
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Thomson Reuters Corp.", "Previous Narrative": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent.\nThe proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech compa
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.48s/it]

Completed Entity: Thomson Reuters Corp., Date: 2025-09-23 00:00:00
--------------------------------------------------
Processing Entity: Thomson Reuters Corp., Date: 2025-09-24 00:00:00, Iteration: 4
Iteration 4 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 3
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent.\nThe proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech companies, which typically use these visas for junior and mid-level roles.\nMany companies may pull back, delay hiring, or shift roles overseas due to the increased costs associated with the new visa fee.\nThe introduction of high fees could deter global talent from coming to the U.S., reducing the country's ability to innovate and grow economically.\nThe policy may force companies to offshore high-value work, potentially harming America's competitiveness in critical areas like artificial intelligence.\nMajor companies, including Microsoft, JPMorgan, and Amazon, have advised employees holding H-1B visas to remain in the United States following the announcement of the new fee, indicating a cautious industry response.\nCommerce Secretary Howard Lutnick stated that the fee would be paid annually, but details are still being considered, highlighting ongoing discussions about the implementation of the fee.\nThomson Reuters Corp. is adapting to the newly introduced high fee on H-1B visas by becoming more selective in its sponsorship of H-1B candidates, prioritizing only the most critical roles. This strategic shift is expected to significantly limit access to the H-1B program for many skilled foreign nationals, thereby reshaping employer demand. Additionally, the company is proactively reducing its reliance on the H-1B program through increased local hiring, acquisitions, and partnerships, indicating a shift in strategy to address the challenges posed by the new fee structure. The company plans to leverage AI tools to tackle any challenges that arise from this new approach.", "Today Summary": "Thomson Reuters Corp. is actively monitoring the implications of the newly introduced $100,000 fee on H-1B visas, which is expected to significantly impact recruitment strategies within the technology sector. The fee, applicable only to new applicants, has already created confusion, prompting many companies to pause their recruitment and workforce planning. Industry experts indicate that the high cost of the H-1B visa may incentivize companies to outsource jobs to countries like India, where labor costs are lower. This shift could lead to a reduction in the number of H-1B visa workers that companies can hire, thereby affecting the overall workforce landscape in the U.S. tech industry. Additionally, the previous cost of the visa was only a few thousand dollars, making the new fee a substantial deterrent for hiring talent in the U.S. and potentially driving companies to establish innovation hubs abroad instead of maintaining back offices domestically.\nThe $100,000 fee on H-1B visas is causing confusion and leading companies to pause recruitment and workforce planning.\nExperts indicate that companies may need to reduce the number of H-1B visa workers they can hire due to the new fee."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:10<00:00, 10.20s/it]

Consolidated narrative length: 3486
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Thomson Reuters Corp.", "Previous Narrative": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent. The proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech compan
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.94s/it]

Completed Entity: Thomson Reuters Corp., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: Thomson Reuters Corp., Date: 2025-09-25 00:00:00, Iteration: 5
Iteration 5 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 4
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent. The proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech companies, which typically use these visas for junior and mid-level roles. Many companies may pull back, delay hiring, or shift roles overseas due to the increased costs associated with the new visa fee. The introduction of high fees could deter global talent from coming to the U.S., reducing the country's ability to innovate and grow economically. The policy may force companies to offshore high-value work, potentially harming America's competitiveness in critical areas like artificial intelligence. Major companies, including Microsoft, JPMorgan, and Amazon, have advised employees holding H-1B visas to remain in the United States following the announcement of the new fee, indicating a cautious industry response. Commerce Secretary Howard Lutnick stated that the fee would be paid annually, but details are still being considered, highlighting ongoing discussions about the implementation of the fee. Thomson Reuters Corp. is adapting to the newly introduced high fee on H-1B visas by becoming more selective in its sponsorship of H-1B candidates, prioritizing only the most critical roles. This strategic shift is expected to significantly limit access to the H-1B program for many skilled foreign nationals, thereby reshaping employer demand. Additionally, the company is proactively reducing its reliance on the H-1B program through increased local hiring, acquisitions, and partnerships, indicating a shift in strategy to address the challenges posed by the new fee structure. The company plans to leverage AI tools to tackle any challenges that arise from this new approach. Thomson Reuters Corp. is actively monitoring the implications of the newly introduced $100,000 fee on H-1B visas, which is expected to significantly impact recruitment strategies within the technology sector. The fee, applicable only to new applicants, has already created confusion, prompting many companies to pause their recruitment and workforce planning. Industry experts indicate that the high cost of the H-1B visa may incentivize companies to outsource jobs to countries like India, where labor costs are lower. This shift could lead to a reduction in the number of H-1B visa workers that companies can hire, thereby affecting the overall workforce landscape in the U.S. tech industry. Additionally, the previous cost of the visa was only a few thousand dollars, making the new fee a substantial deterrent for hiring talent in the U.S. and potentially driving companies to establish innovation hubs abroad instead of maintaining back offices domestically.", "Today Summary": "Thomson Reuters Corp. has expressed heightened concerns regarding the Trump administration's introduction of a $100,000 fee on H-1B visas, which marks a significant increase from the previous cost of $2,000. This drastic change is anticipated to make hiring foreign talent, especially from countries like India, more appealing due to lower wages. The company notes that this new fee is likely to disrupt hiring plans and compel firms to rethink their workforce strategies, potentially leading to a decrease in the number of H-1B visa workers they can employ. The confusion surrounding the implementation of this fee has already caused many companies to pause their recruitment efforts and adjust their budgets. Furthermore, corporate clients have described the new fee as unworkable, prompting discussions about relocating talent acquisition to other countries. Notably, Sam Liang, CEO of AI transcription start-up Otter, indicated that companies may need to reduce their H-1B workforce and consider outsourcing to countries like India to navigate the challenges posed by the new fee.\nThe Trump administration's $100,000 fee on H-1B visas is a significant increase from the previous cost of $2,000, making hiring foreign talent more attractive for companies due to lower wages.\nCorporate clients have described the new fee as unworkable, leading to discussions about relocating talent acquisition to other countries."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:10<00:00, 10.22s/it]

Consolidated narrative length: 4571
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Thomson Reuters Corp.", "Previous Narrative": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent. The proposed $100,000 annual fee for H-1B visas could significantly impact startups and mid-sized tech compan
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.39s/it]

Completed Entity: Thomson Reuters Corp., Date: 2025-09-25 00:00:00
--------------------------------------------------
Processing Entity: Wipro Ltd., Date: 2025-09-19 00:00:00, Iteration: 0
First iteration - skipping get_summaries, using existing summary
Completed Entity: Wipro Ltd., Date: 2025-09-19 00:00:00
--------------------------------------------------
Processing Entity: Wipro Ltd., Date: 2025-09-20 00:00:00, Iteration: 1
Second iteration - temporal analysis only
entity_previous_narrative: {'Wipro Ltd._2025-09-19 00:00:00': "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affect Wipro's ability to hire foreign workers due to higher costs.\nCurrent costs for companies include $215 to register for the lottery and $780 for the employer-sponsored petition for a non-immigrant worker."}
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Wipro Ltd.", "Previous Narrative": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affec
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.39s/it]

Completed Entity: Wipro Ltd., Date: 2025-09-20 00:00:00
--------------------------------------------------
Processing Entity: Wipro Ltd., Date: 2025-09-21 00:00:00, Iteration: 2
Iteration 2 - consolidation + temporal analysis
Consolidating: previous from iteration 0, today from iteration 1
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affect Wipro's ability to hire foreign workers due to higher costs.\nCurrent costs for companies include $215 to register for the lottery and $780 for the employer-sponsored petition for a non-immigrant worker.", "Today Summary": "Wipro Ltd. is facing significant challenges due to the introduction of a new $100,000 fee on H-1B visas, which is expected to reshape its hiring strategies and operational models. This fee will primarily limit the company's ability to send junior and mid-level engineers to the US, making H-1B hiring financially viable only for high-value roles that require advanced expertise. Analysts predict that this change will compel Wipro and other Indian IT firms to reassess their staffing strategies, potentially leading to a shift towards offshoring work or reducing on-site deployments. The new fee structure poses a dual challenge for Wipro, as it not only increases operational costs but also restricts the talent pool available for US projects. The introduction of this high fee is viewed as a cost shock for Wipro, which has historically relied on H-1B visas to place engineers in the US market.\nThe new $100,000 fee on H-1B visas will limit Wipro's ability to send junior and mid-level engineers to the US, making H-1B hiring financially viable only for high-value roles.\nAnalysts suggest that Wipro may need to reassess its US staffing strategies, potentially shifting work offshore or reducing on-site deployments to minimize costs."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.11s/it]

Consolidated narrative length: 2050
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Wipro Ltd.", "Previous Narrative": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affec
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.04s/it]

Completed Entity: Wipro Ltd., Date: 2025-09-21 00:00:00
--------------------------------------------------
Processing Entity: Wipro Ltd., Date: 2025-09-22 00:00:00, Iteration: 3
Iteration 3 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 2
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affect Wipro's ability to hire foreign workers due to higher costs.\nCurrent costs for companies include $215 to register for the lottery and $780 for the employer-sponsored petition for a non-immigrant worker.\nWipro Ltd. is facing significant challenges due to the introduction of a new $100,000 fee on H-1B visas, which is expected to reshape its hiring strategies and operational models. This fee will primarily limit the company's ability to send junior and mid-level engineers to the US, making H-1B hiring financially viable only for high-value roles that require advanced expertise. Analysts predict that this change will compel Wipro and other Indian IT firms to reassess their staffing strategies, potentially leading to a shift towards offshoring work or reducing on-site deployments. The new fee structure poses a dual challenge for Wipro, as it not only increases operational costs but also restricts the talent pool available for US projects. The introduction of this high fee is viewed as a cost shock for Wipro, which has historically relied on H-1B visas to place engineers in the US market.", "Today Summary": "Wipro Ltd. is experiencing significant challenges following the introduction of a high fee on H-1B visas by President Donald Trump, which has led to a 2% decline in the company's shares, reflecting investor concerns about the operational impact of increased visa costs. Analysts predict that this new fee structure will result in a near-term freeze on new H-1B applications and a shift towards offshoring work to India, as Wipro may prioritize protecting existing client contracts while increasing local hiring in the U.S. Furthermore, the high costs associated with H-1B visas could disrupt onshore projects and necessitate a reevaluation of hiring and pricing strategies, potentially leading to a loss of the U.S.'s competitive edge in innovation as global talent may seek opportunities elsewhere. This situation indicates a significant shift in the economics of deploying Indian tech talent in the U.S., with Wipro and other Indian IT firms expected to further reduce their reliance on H-1B visas.\nWipro's shares fell by 2% following the announcement of the high H-1B visa fee, indicating investor concern over the impact on the company's operations.\nAnalysts warn that the new fee structure could disrupt onshore projects and impact the revenue visibility of large IT exporters like Wipro."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:07<00:00,  7.43s/it]

Consolidated narrative length: 3344
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Wipro Ltd.", "Previous Narrative": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affec
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.12s/it]

Completed Entity: Wipro Ltd., Date: 2025-09-22 00:00:00
--------------------------------------------------
Processing Entity: Wipro Ltd., Date: 2025-09-23 00:00:00, Iteration: 4
Iteration 4 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 3
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affect Wipro's ability to hire foreign workers due to higher costs.\nCurrent costs for companies include $215 to register for the lottery and $780 for the employer-sponsored petition for a non-immigrant worker.\nWipro Ltd. is facing significant challenges due to the introduction of a new $100,000 fee on H-1B visas, which is expected to reshape its hiring strategies and operational models. This fee will primarily limit the company's ability to send junior and mid-level engineers to the US, making H-1B hiring financially viable only for high-value roles that require advanced expertise. Analysts predict that this change will compel Wipro and other Indian IT firms to reassess their staffing strategies, potentially leading to a shift towards offshoring work or reducing on-site deployments. The new fee structure poses a dual challenge for Wipro, as it not only increases operational costs but also restricts the talent pool available for US projects. The introduction of this high fee is viewed as a cost shock for Wipro, which has historically relied on H-1B visas to place engineers in the US market.\nWipro Ltd. is experiencing significant challenges following the introduction of a high fee on H-1B visas by President Donald Trump, which has led to a 2% decline in the company's shares, reflecting investor concerns about the operational impact of increased visa costs. Analysts predict that this new fee structure will result in a near-term freeze on new H-1B applications and a shift towards offshoring work to India, as Wipro may prioritize protecting existing client contracts while increasing local hiring in the U.S. Furthermore, the high costs associated with H-1B visas could disrupt onshore projects and necessitate a reevaluation of hiring and pricing strategies, potentially leading to a loss of the U.S.'s competitive edge in innovation as global talent may seek opportunities elsewhere. This situation indicates a significant shift in the economics of deploying Indian tech talent in the U.S., with Wipro and other Indian IT firms expected to further reduce their reliance on H-1B visas.\nWipro's shares fell by 2% following the announcement of the high H-1B visa fee, indicating investor concern over the impact on the company's operations.\nAnalysts warn that the new fee structure could disrupt onshore projects and impact the revenue visibility of large IT exporters like Wipro.", "Today Summary": "Wipro Ltd. is currently grappling with significant operational and financial challenges stemming from the newly introduced $100,000 annual fee for H-1B visas. This fee is expected to drastically increase the costs associated with sending engineers to the U.S. for client projects, complicating workforce planning, recruitment, and deployment strategies. In response, Wipro is exploring alternative solutions such as remote work and client-side training in India to alleviate the financial burden. Analysts have noted that while larger firms like Wipro may be able to absorb these costs more easily, mid-tier firms that rely heavily on fresh H-1B approvals will face greater difficulties. The fee hike fundamentally alters the economics of deploying Indian tech workers in the U.S., diminishing the cost advantage of sending employees overseas compared to hiring locally. This situation poses a significant threat to Wipro's profitability, with estimates suggesting a potential reduction in operating profits by 7-15% due to the new visa fees.\nWipro is exploring alternative solutions such as remote work and client-side training in India to mitigate the financial burden of the new $100,000 annual fee for H-1B visas.\nAnalysts estimate that Wipro's operating profits could be reduced by 7-15% due to the introduction of the high visa fees."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:16<00:00, 16.12s/it]

Consolidated narrative length: 4387
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Wipro Ltd.", "Previous Narrative": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affec
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.36s/it]

Completed Entity: Wipro Ltd., Date: 2025-09-23 00:00:00
--------------------------------------------------
Processing Entity: Wipro Ltd., Date: 2025-09-24 00:00:00, Iteration: 5
Iteration 5 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 4
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affect Wipro's ability to hire foreign workers due to higher costs.\nCurrent costs for companies include $215 to register for the lottery and $780 for the employer-sponsored petition for a non-immigrant worker.\nWipro Ltd. is facing significant challenges due to the introduction of a new $100,000 fee on H-1B visas, which is expected to reshape its hiring strategies and operational models. This fee will primarily limit the company's ability to send junior and mid-level engineers to the US, making H-1B hiring financially viable only for high-value roles that require advanced expertise. Analysts predict that this change will compel Wipro and other Indian IT firms to reassess their staffing strategies, potentially leading to a shift towards offshoring work or reducing on-site deployments. The new fee structure poses a dual challenge for Wipro, as it not only increases operational costs but also restricts the talent pool available for US projects. The introduction of this high fee is viewed as a cost shock for Wipro, which has historically relied on H-1B visas to place engineers in the US market.\nWipro Ltd. is experiencing significant challenges following the introduction of a high fee on H-1B visas by President Donald Trump, which has led to a 2% decline in the company's shares, reflecting investor concerns about the operational impact of increased visa costs. Analysts predict that this new fee structure will result in a near-term freeze on new H-1B applications and a shift towards offshoring work to India, as Wipro may prioritize protecting existing client contracts while increasing local hiring in the U.S. Furthermore, the high costs associated with H-1B visas could disrupt onshore projects and necessitate a reevaluation of hiring and pricing strategies, potentially leading to a loss of the U.S.'s competitive edge in innovation as global talent may seek opportunities elsewhere. This situation indicates a significant shift in the economics of deploying Indian tech talent in the U.S., with Wipro and other Indian IT firms expected to further reduce their reliance on H-1B visas.\nWipro's shares fell by 2% following the announcement of the high H-1B visa fee, indicating investor concern over the impact on the company's operations.\nAnalysts warn that the new fee structure could disrupt onshore projects and impact the revenue visibility of large IT exporters like Wipro.\nWipro Ltd. is currently grappling with significant operational and financial challenges stemming from the newly introduced $100,000 annual fee for H-1B visas. This fee is expected to drastically increase the costs associated with sending engineers to the U.S. for client projects, complicating workforce planning, recruitment, and deployment strategies. In response, Wipro is exploring alternative solutions such as remote work and client-side training in India to alleviate the financial burden. Analysts have noted that while larger firms like Wipro may be able to absorb these costs more easily, mid-tier firms that rely heavily on fresh H-1B approvals will face greater difficulties. The fee hike fundamentally alters the economics of deploying Indian tech workers in the U.S., diminishing the cost advantage of sending employees overseas compared to hiring locally. This situation poses a significant threat to Wipro's profitability, with estimates suggesting a potential reduction in operating profits by 7-15% due to the new visa fees.", "Today Summary": "Wipro Ltd. is facing a potential 1-3% reduction in net profit due to the newly introduced high fee on H-1B visas, which is expected to significantly increase the costs associated with employing foreign talent. The company, which relies heavily on rotating engineers to serve US clients, may need to rethink its onshore-offshore strategies and reduce short-term employee transfers. This shift could lead to a greater emphasis on local hiring of US citizens or green card holders. Additionally, the overall implications of the new visa policy could escalate annual immigration costs for Wipro and other top Indian IT providers by $150-550 million, further impacting core operating margins. Brokerages suggest that while larger firms like Wipro may be better positioned to absorb these changes, the financial burden remains substantial and could reshape operational strategies in the long term.\nWipro is expected to face a 1-3% reduction in net profit due to the new high fee on H-1B visas.\nThe introduction of the high fee could lead to an increase in annual immigration costs by $150-550 million for Wipro and other top Indian IT providers."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:15<00:00, 15.93s/it]

Consolidated narrative length: 5279
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Wipro Ltd.", "Previous Narrative": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affec
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:06<00:00,  6.53s/it]

Completed Entity: Wipro Ltd., Date: 2025-09-24 00:00:00
--------------------------------------------------
Processing Entity: Wipro Ltd., Date: 2025-09-25 00:00:00, Iteration: 6
Iteration 6 - consolidation + temporal analysis
Consolidating: previous from iteration consolidated, today from iteration 5
================================================================================
DEBUG: CONSOLIDATION SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in extracting and creating information from a series of info about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
Your are given summarized infomation about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about past days.
You are also given a summarized version of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles about today.

1. **Task**:
    - You must extract the new information from the new information and add it to the summary of the information about the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Analize both sources and when you create the summary, add the new information at the bottom of the summary.
    - Do not add new information if the information is already present in the previous summary.
    - The added information must be the new information that has not been mentioned in the previous summary.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not elaborate on the information, just extract the information and add it to the summary.

2. **Response Format**:
    - Output should be a JSON object with the summary.
    - Format your response as valid JSON as follows: {"summary": "<comprehensive_summary>"}.
    - Ensure all strings in the JSON are correctly formatted with proper quotes
    - IMPORTANT: Your response must be valid JSON format only

================================================================================
DEBUG: CONSOLIDATION USER PROMPT
================================================================================
{"Previous Summary": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affect Wipro's ability to hire foreign workers due to higher costs.\nCurrent costs for companies include $215 to register for the lottery and $780 for the employer-sponsored petition for a non-immigrant worker.\nWipro Ltd. is facing significant challenges due to the introduction of a new $100,000 fee on H-1B visas, which is expected to reshape its hiring strategies and operational models. This fee will primarily limit the company's ability to send junior and mid-level engineers to the US, making H-1B hiring financially viable only for high-value roles that require advanced expertise. Analysts predict that this change will compel Wipro and other Indian IT firms to reassess their staffing strategies, potentially leading to a shift towards offshoring work or reducing on-site deployments. The new fee structure poses a dual challenge for Wipro, as it not only increases operational costs but also restricts the talent pool available for US projects. The introduction of this high fee is viewed as a cost shock for Wipro, which has historically relied on H-1B visas to place engineers in the US market.\nWipro Ltd. is experiencing significant challenges following the introduction of a high fee on H-1B visas by President Donald Trump, which has led to a 2% decline in the company's shares, reflecting investor concerns about the operational impact of increased visa costs. Analysts predict that this new fee structure will result in a near-term freeze on new H-1B applications and a shift towards offshoring work to India, as Wipro may prioritize protecting existing client contracts while increasing local hiring in the U.S. Furthermore, the high costs associated with H-1B visas could disrupt onshore projects and necessitate a reevaluation of hiring and pricing strategies, potentially leading to a loss of the U.S.'s competitive edge in innovation as global talent may seek opportunities elsewhere. This situation indicates a significant shift in the economics of deploying Indian tech talent in the U.S., with Wipro and other Indian IT firms expected to further reduce their reliance on H-1B visas.\nWipro's shares fell by 2% following the announcement of the high H-1B visa fee, indicating investor concern over the impact on the company's operations.\nAnalysts warn that the new fee structure could disrupt onshore projects and impact the revenue visibility of large IT exporters like Wipro.\nWipro Ltd. is currently grappling with significant operational and financial challenges stemming from the newly introduced $100,000 annual fee for H-1B visas. This fee is expected to drastically increase the costs associated with sending engineers to the U.S. for client projects, complicating workforce planning, recruitment, and deployment strategies. In response, Wipro is exploring alternative solutions such as remote work and client-side training in India to alleviate the financial burden. Analysts have noted that while larger firms like Wipro may be able to absorb these costs more easily, mid-tier firms that rely heavily on fresh H-1B approvals will face greater difficulties. The fee hike fundamentally alters the economics of deploying Indian tech workers in the U.S., diminishing the cost advantage of sending employees overseas compared to hiring locally. This situation poses a significant threat to Wipro's profitability, with estimates suggesting a potential reduction in operating profits by 7-15% due to the new visa fees.\nWipro Ltd. is facing a potential 1-3% reduction in net profit due to the newly introduced high fee on H-1B visas, which is expected to significantly increase the costs associated with employing foreign talent. The company, which relies heavily on rotating engineers to serve US clients, may need to rethink its onshore-offshore strategies and reduce short-term employee transfers. This shift could lead to a greater emphasis on local hiring of US citizens or green card holders. Additionally, the overall implications of the new visa policy could escalate annual immigration costs for Wipro and other top Indian IT providers by $150-550 million, further impacting core operating margins. Brokerages suggest that while larger firms like Wipro may be better positioned to absorb these changes, the financial burden remains substantial and could reshape operational strategies in the long term.", "Today Summary": "Wipro Ltd. is facing heightened challenges due to the introduction of a high fee on H-1B visas, which is anticipated to significantly increase operational costs. The company, which derives over half of its yearly revenue from the U.S. market, is particularly vulnerable to changes in the H-1B visa program. Analysts from Citi Research have indicated that the new fee regime will make each fresh recruit on an H-1B visa as costly as a year's salary, thereby increasing the cost of doing business for IT services companies and their clients in the U.S., which could adversely affect profit margins. This situation may lead to reduced hiring or a shift of jobs back to India, further complicating Wipro's operational strategies in the face of rising costs associated with employing skilled foreign workers.\nWipro derives over half of its yearly revenue from the U.S. market, making it particularly vulnerable to changes in the H-1B visa program.\nCiti Research warns that the new fee regime will make each fresh recruit on an H-1B visa as costly as a year's salary, significantly increasing the cost of doing business for IT services companies."}
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:17<00:00, 17.56s/it]

Consolidated narrative length: 5876
================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating comprehensive summaries based on some daily summaries, bullet points and quotes about the theme of 'Introduction of a high fee on H-1B visas' created from news articles.
You are also given a cumulative narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'. That summary was generated by previous iterations of this same prompt and represent the historical context that you can use to analyze and recognize the new additional information.
Your goal is to create a new summary only on the new information that has not been mentioned in the previous summaries, in order to keep track of the new information that has not been mentioned in the previous summaries.


You will receive:
    - Historical narrative summary from recent past days about 'Introduction of a high fee on H-1B visas'
    - Summaries, bullet points and quotes of the current day about the theme of 'Introduction of
================================================================================
DEBUG: USER PROMPTS (Total: 1)
================================================================================
PROMPT 1:
----------------------------------------
{"Company": "Wipro Ltd.", "Previous Narrative": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.\nWipro employs a significant number of foreign workers, mostly from India, contracted to American firms seeking cost savings.\nThe introduction of increased fees for H-1B visas could affec
----------------------------------------
================================================================================

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.30s/it]

Completed Entity: Wipro Ltd., Date: 2025-09-25 00:00:00
--------------------------------------------------

In [38]:
df_company_summaries.to_csv("news_results_labeled_company_summaries.csv", index=False)

In [32]:
df_company_summaries

,Entity,Date,Summary,Key_points,Quotes,Country,enhanced_summary,enhanced_key_points
0,Alphabet Inc.,2025-09-19,Alphabet Inc. is positioned to face significan...,['The introduction of a high fee on H-1B visas...,"['For companies like Google, Microsoft, Amazon...",United States,Alphabet Inc. is positioned to face significan...,['The introduction of a high fee on H-1B visas...
1,Alphabet Inc.,2025-09-20,Alphabet Inc. is positioned to face significan...,"['The $100,000 annual fee on H-1B visas is exp...","['""US tech giants like Amazon, Microsoft, Goog...",United States,Alphabet Inc. is now facing the introduction o...,"['The introduction of a $100,000 annual fee on..."
2,Alphabet Inc.,2025-09-21,Alphabet Inc. is significantly impacted by the...,['Alphabet Inc. is concerned about the financi...,"[""Amazon, Alphabet's Google, Microsoft and oth...",United States,Alphabet Inc. is facing significant financial ...,['Alphabet Inc. is concerned about the financi...
3,Alphabet Inc.,2025-09-22,"Alphabet Inc., through its subsidiary Google, ...","[""Alphabet Inc.'s Google employs thousands of ...","['In response to the announcement, tech giants...",United States,"Alphabet Inc., through its subsidiary Google, ...",['Alphabet Inc. employs thousands of H-1B visa...
4,Alphabet Inc.,2025-09-23,Alphabet Inc. is positioned as a significant p...,['Alphabet Inc. is among the tech giants that ...,"['For Silicon Valley, the decision is disrupti...",United States,New information indicates that Alphabet Inc. h...,['Alphabet Inc. has historically relied on H-1...
5,Alphabet Inc.,2025-09-24,Alphabet Inc. is significantly impacted by the...,['Alphabet Inc. and other major U.S. tech comp...,['The sharp increase in fees will double hirin...,United States,New information indicates that the introductio...,['The new fee on H-1B visas is expected to dou...
6,Alphabet Inc.,2025-09-25,Alphabet Inc. is positioned as a major player ...,"['The $100,000 application fee for H-1B visas ...","['Major companies like Microsoft, Google, and ...",United States,Alphabet Inc. continues to face significant ch...,"['The introduction of the $100,000 fee on H-1B..."
7,Amazon.com Inc.,2025-09-19,Amazon.com Inc. is significantly impacted by t...,"['Amazon, along with other big tech companies,...",['The proposal has been met with mixed reviews...,United States,Amazon.com Inc. is significantly impacted by t...,"['Amazon, along with other big tech companies,..."
8,Amazon.com Inc.,2025-09-20,Amazon.com Inc. is significantly impacted by t...,['Amazon has warned employees on H-1B and H-4 ...,['Amazon has warned employees on H-1B and H-4 ...,United States,Amazon.com Inc. is facing significant challeng...,['Amazon has warned employees on H-1B and H-4 ...
9,Amazon.com Inc.,2025-09-21,Amazon.com Inc. is significantly impacted by t...,['Amazon has tens of thousands of staff in the...,"['Following the announcement, companies such a...",United States,Amazon.com Inc. continues to face significant ...,['Amazon has tens of thousands of staff in the...
10,Amazon.com Inc.,2025-09-22,Amazon.com Inc. is significantly impacted by t...,['Amazon is one of the top sponsors of H-1B vi...,"['In response to the announcement, tech giants...",United States,Amazon.com Inc. continues to grapple with the ...,['Amazon is one of the top sponsors of H-1B vi...
11,Amazon.com Inc.,2025-09-23,Amazon.com Inc. is significantly impacted by t...,['Amazon is the largest employer of H-1B visa ...,"['However, despite the high fee and layoff con...",United States,Amazon.com Inc. is facing significant challeng...,"['The $100,000 fee on new H-1B visa applicatio..."
12,Amazon.com Inc.,2025-09-24,Amazon.com Inc. is significantly impacted by t...,['Amazon heavily relies on H-1B visas to recru...,['The sharp increase in fees will double hirin...,United States,Amazon.com Inc. is facing new challenges due t...,"['The introduction of a $100,000 fee for new H..."
13,Amazon.com Inc.,2025-09-25,Amazon.com Inc. is positioned to absorb the ne...,['Amazon is one of the major technology compan...,"['Major companies like Microsoft, Google, and ...",United States,Amazon.com Inc. is expected to manage the new ...,"['The new $100,000 application fee for H-1B vi..."
14,DBRS Ltd.,2025-09-24,DBRS Ltd. has expressed significant concerns r...,['The new fee on H-1B visas may compel banks t...,"[""The new fee may force banks to hire more off...",Canada,DBRS Ltd. has expressed significant concerns r...,['The new fee on H-1B visas may compel banks t...
15,DBRS Ltd.,2025-09-25,DBRS Ltd. has expressed concerns regarding the...,['The new fee on H-1B visas may lead banks to ...,"[""The new fee may force banks to hire more off...",Canada,DBRS Ltd. has reiterated its concerns about th...,"[""Tim O'Brien indicated that the new fee could..."
16,Dewang,2025-09-21,"Dewang, represented by its Founder & CEO Dewan...",['Dewang Neralla highlighted that the proposed...,"['Dewang Neralla, Founder & CEO of cross-borde...",China,"Dewang, represented by its Founder & CEO Dewan...",['Dewang Neralla highlighted that the proposed...
17,IBM Corp. Pty. Ltd.,2025-09-19,IBM Corp. Pty. Ltd. is positioned within a lan...,['The introduction of high fees on H-1B visas ...,"[""The increased fees could affect hiring forei...",China,IBM Corp. Pty. Ltd. is positioned within a lan...,['The introduction of high fees on H-1B visas ...
18,IBM Corp. Pty. Ltd.,2025-09-20,IBM Corp. Pty. Ltd. is significantly impacted ...,['IBM is among the major firms that employ a s...,['The additional charge would impact employers...,China,IBM Corp. Pty. Ltd. faces a significant challe...,"[""The cost for sponsoring a single H-1B applic..."
19,IBM Corp. Pty. Ltd.,2025-09-21,IBM Corp. Pty. Ltd. is part of the coalition C...,"['IBM is a member of Compete America, which ad...","['Scott Corley, Executive Director of Compete ...",China,IBM Corp. Pty. Ltd. is actively involved in th...,['IBM is part of the coalition Compete America...
20,IBM Corp. Pty. Ltd.,2025-09-22,IBM Corp. Pty. Ltd. is actively evaluating alt...,"['IBM is assessing other visa options, includi...","['Companies are assessing other visa options, ...",China,IBM Corp. Pty. Ltd. is currently evaluating al...,['IBM is actively evaluating alternative visa ...
21,IBM Corp. Pty. Ltd.,2025-09-23,IBM Corp. Pty. Ltd. is positioned among the ma...,['IBM is identified as one of the major tech f...,"[""The White House has defended the move as a w...",China,IBM Corp. Pty. Ltd. is now recognized as one o...,['IBM is now identified as one of the major te...
22,IBM Corp. Pty. Ltd.,2025-09-24,IBM Corp. Pty. Ltd. is positioned against the ...,"[""IBM acknowledges that the H-1B visa fee incr...","[""Economists warn that the H-1B visa fee incre...",China,IBM Corp. Pty. Ltd. has expressed strong oppos...,"[""IBM acknowledges that the H-1B visa fee incr..."
23,Infosys Ltd.,2025-09-19,Infosys Ltd. is positioned within a landscape ...,"[""The introduction of high fees on H-1B visas ...","[""The increased fees could affect hiring forei...",India,Infosys Ltd. is positioned within a landscape ...,"[""The introduction of high fees on H-1B visas ..."
24,Infosys Ltd.,2025-09-20,Infosys Ltd. is significantly impacted by the ...,"['The $100,000 fee for H-1B visas is considere...",['Now what will happen is everybody will work ...,India,Infosys Ltd. is facing significant challenges ...,"['The $100,000 fee for H-1B visas is expected ..."
25,Infosys Ltd.,2025-09-21,Infosys Ltd. is significantly impacted by the ...,"['The introduction of a $100,000 annual fee fo...","['""This move (the US decision to hike H-1B vis...",India,Infosys Ltd. is facing significant challenges ...,"['The introduction of a $100,000 annual fee fo..."
26,Infosys Ltd.,2025-09-22,Infosys Ltd. is facing significant operational...,['Infosys faces operational and financial pres...,"['Companies such as Infosys, Wipro, Cognizant,...",India,Infosys Ltd. is currently grappling with signi...,"['The introduction of the $100,000 annual fee ..."
27,Infosys Ltd.,2025-09-23,Infosys Ltd. is significantly impacted by the ...,['Infosys faces an estimated $150-550 million ...,"['Top Indian IT providers such as TCS, Infosys...",India,"Today, Infosys Ltd. faces an estimated increas...",['Infosys is projected to face an increase in ...
28,Infosys Ltd.,2025-09-24,Infosys Ltd. is significantly affected by the ...,['Infosys relies heavily on H-1B visas for hir...,['The proposed changes to the H-1B visa progra...,India,"Today, Infosys Ltd. faces additional challenge...","[""The cost of hiring new employees under the H..."
29,Infosys Ltd.,2025-09-25,Infosys Ltd. is positioned to face significant...,"['Infosys, along with TCS and Wipro, is heavil...","['The burden will fall heavily on students, st...",India,"Today, Infosys Ltd. faces new challenges due t...",['The projected increase in H-1B visa costs co...
30,Metaview,2025-09-22,"Metaview, a San Francisco-based tech company, ...",['Metaview is ready to move quickly to hire to...,['We are ready to move fast to hire top profes...,China,"Metaview, a San Francisco-based tech company, ...",['Metaview is ready to move quickly to hire to...
31,Microsoft Corp.,2025-09-19,Microsoft Corp. is positioned at the center of...,"['Microsoft, along with other big tech compani...",['The proposal has been met with mixed reviews...,United States,Microsoft Corp. is positioned at the center of...,"['Microsoft, along with other big tech compani..."
32,Microsoft Corp.,2025-09-20,Microsoft Corp. is significantly impacted by t...,['Microsoft has warned employees on H-1B and H...,['Microsoft and Amazon have warned employees o...,United States,Microsoft Corp. is facing significant challeng...,['Microsoft has warned employees on H-1B and H...
33,Microsoft Corp.,2025-09-21,Microsoft Corp. has expressed significant conc...,"['Microsoft, along with other major tech compa...",['Following the announcement on Friday that th...,United States,Microsoft Corp. has raised significant concern...,['Microsoft has advised its H-1B employees to ...
34,Microsoft Corp.,2025-09-22,Microsoft Corp. is significantly impacted by t...,['Microsoft and Amazon have advised employees ...,['Microsoft and Amazon have warned employees o...,United States,Microsoft Corp. continues to express significa...,"[""The $100,000 fee is viewed as regressive and..."
35,Microsoft Corp.,2025-09-23,Microsoft Corp. is significantly impacted by t...,['Microsoft relies heavily on international ta...,['The changes pose substantial new costs for m...,United States,Microsoft Corp. continues to express significa...,"['The $100,000 one-time fee for H-1B visa appl..."
36,Microsoft Corp.,2025-09-24,Microsoft Corp. is significantly impacted by t...,"['The introduction of a $100,000 fee on H-1B v...","['""The sharp increase in fees will double hiri...",United States,Microsoft Corp. is facing a significant impact...,"['The introduction of a $100,000 fee on H-1B v..."
37,Microsoft Corp.,2025-09-25,Microsoft Corp. is significantly impacted by t...,"['Microsoft employs 5,189 H-1B visa holders, m...","['The new $100,000 application fee will hit te...",United States,Microsoft Corp. is significantly affected by t...,"['Microsoft employs 5,189 H-1B visa holders, m..."
38,Talent Fund,2025-09-22,Talent Fund's position regarding the introduct...,"['The introduction of a $100,000 fee for H-1B ...",['Ultimately to attract global talent we need ...,Canada,Talent Fund's position regarding the introduct...,"['The introduction of a $100,000 fee for H-1B ..."
39,Talent Fund,2025-09-25,Talent Fund is actively responding to the impl...,['Talent Fund is advocating for the expansion ...,['The official recommended the Home Office exp...,Canada,Talent Fund is taking a proactive approach in ...,['Talent Fund is advocating for the expansion ...
40,Tata Consultancy Services Ltd.,2025-09-20,Tata Consultancy Services Ltd. (TCS) is signif...,"[""The introduction of a $100,000 fee for H-1B ...",['President Trump has raised the H-1B visa spo...,India,Tata Consultancy Services Ltd. (TCS) is signif...,"[""The introduction of a $100,000 fee for H-1B ..."
41,Tata Consultancy Services Ltd.,2025-09-21,Tata Consultancy Services Ltd. (TCS) is signif...,['Tata Consultancy Services expects the high f...,"['""This would significantly reduce access to t...",India,Tata Consultancy Services Ltd. (TCS) is respon...,['TCS has advised its employees on H-1B visas ...
42,Tata Consultancy Services Ltd.,2025-09-22,Tata Consultancy Services (TCS) is facing sign...,['TCS faces operational and financial pressure...,"['Companies such as Infosys, Wipro, Cognizant,...",India,Tata Consultancy Services (TCS) is currently g...,['TCS is expected to explore alternative solut...
43,Tata Consultancy Services Ltd.,2025-09-23,Tata Consultancy Services Ltd. (TCS) is signif...,"['Tata Consultancy Services employs 5,505 work...","['For Indian IT companies, the proclamation me...",India,Tata Consultancy Services Ltd. (TCS) is facing...,"['TCS employs 5,505 workers using H-1B visas, ..."
44,Tata Consultancy Services Ltd.,2025-09-24,Tata Consultancy Services Ltd. (TCS) is signif...,['Tata Consultancy Services derives over half ...,"[""With the new fee regime, every fresh recruit...",India,Tata Consultancy Services Ltd. (TCS) faces hei...,"[""The new H-1B visa fee could equate to the co..."
45,Thomson Reuters Corp.,2025-09-20,Thomson Reuters Corp. highlights the significa...,"['The proposed $100,000 annual fee for H-1B vi...",['If each overseas hire or entry/travel costs ...,Canada,Thomson Reuters Corp. highlights the significa...,"['The proposed $100,000 annual fee for H-1B vi..."
46,Thomson Reuters Corp.,2025-09-21,Thomson Reuters Corp. has not provided any dir...,"['Major companies, including Microsoft, JPMorg...",['Commerce Secretary Howard Lutnick on Friday ...,Canada,Thomson Reuters Corp. has not issued any direc...,"['Major companies, including Microsoft, JPMorg..."
47,Thomson Reuters Corp.,2025-09-22,Thomson Reuters Corp. appears to be navigating...,['Thomson Reuters Corp. is expected to become ...,['It added that it has reduced its reliance on...,Canada,Thomson Reuters Corp. is adapting to the newly...,['Thomson Reuters Corp. is expected to become ...
48,Thomson Reuters Corp.,2025-09-23,Thomson Reuters Corp. is closely monitoring th...,"['The $100,000 fee on H-1B visas is causing co...","['While the $100,000 levy applies only to new ...",Canada,Thomson Reuters Corp. is actively monitoring t...,"['The $100,000 fee on H-1B visas is causing co..."
49,Thomson Reuters Corp.,2025-09-24,Thomson Reuters Corp. has reported significant...,"[""The Trump administration's $100,000 fee on H...","['""We probably have to reduce the number of H-...",Canada,Thomson Reuters Corp. has expressed heightened...,"[""The Trump administration's $100,000 fee on H..."
50,Thomson Reuters Corp.,2025-09-25,Thomson Reuters Corp. is positioned to be sign...,"['The new US$100,000 fee for H-1B visas repres...",['The visa previously cost employers only a fe...,Canada,Thomson Reuters Corp. continues to express con...,"['The new US$100,000 fee for H-1B visas is exp..."
51,Wipro Ltd.,2025-09-19,Wipro Ltd. is positioned within a landscape wh...,['Wipro employs a significant number of foreig...,"[""The increased fees could affect hiring forei...",India,Wipro Ltd. is positioned within a landscape wh...,['Wipro employs a significant number of foreig...
52,Wipro Ltd.,2025-09-20,Wipro Ltd. is significantly impacted by the in...,['Wipro is expected to face significant challe...,"[""Now, what are the problems facing? Immediate...",India,Wipro Ltd. is facing significant challenges du...,"[""The new $100,000 fee on H-1B visas will limi..."
53,Wipro Ltd.,2025-09-21,Wipro Ltd. is facing significant challenges fo...,"[""Wipro's shares fell by 2% following the anno...","['The sharp escalation in visa costs, combined...",India,Wipro Ltd. is experiencing significant challen...,"[""Wipro's shares fell by 2% following the anno..."
54,Wipro Ltd.,2025-09-22,Wipro Ltd. is facing significant operational a...,['Wipro faces operational and financial pressu...,"['Companies such as Infosys, Wipro, Cognizant,...",India,Wipro Ltd. is currently grappling with signifi...,['Wipro is exploring alternative solutions suc...
55,Wipro Ltd.,2025-09-23,Wipro Ltd. is significantly impacted by the in...,['Wipro is expected to face a 1-3% reduction i...,"['According to brokerages, large-cap players s...",India,Wipro Ltd. is facing a potential 1-3% reductio...,['Wipro is expected to face a 1-3% reduction i...
56,Wipro Ltd.,2025-09-24,Wipro Ltd. is positioned to face significant c...,"['Wipro, along with other leading IT firms, de...","[""With the new fee regime, every fresh recruit...",India,Wipro Ltd. is facing heightened challenges due...,['Wipro derives over half of its yearly revenu...
57,Wipro Ltd.,2025-09-25,Wipro Ltd. is positioned in a challenging land...,"[""Wipro's reliance on H-1B visas has been decr...","['IT giants like TCS, Infosys, and Wipro, whic...",India,Wipro Ltd. is adapting to a challenging enviro...,"[""Wipro's number of Indian employees on H-1B v..."

In [33]:
from src.report.html import generate_company_comparison_html

generate_company_comparison_html(df_company_summaries)

Company comparison HTML file saved as: company_comparison_report.html

'company_comparison_report.html'

## Generate Final Narrative for each of the Actors

In [34]:
df_temp_summaries = df_company_summaries.copy()

In [35]:
df_summaries_companies = df_company_summaries[["Entity", "Date", "enhanced_summary", "enhanced_key_points"]]
df_summaries_companies = df_summaries_companies.rename(columns={"enhanced_summary": "Summary", "enhanced_key_points": "Key Points"})
df_summaries_trump = df_DT_theme_matching_citation[["Entity", "Date", "daily summary", "daily bullet points"]]
df_summaries_trump = df_summaries_trump.drop_duplicates(subset=["Date"])
df_summaries_trump = df_summaries_trump.rename(columns={"daily summary": "Summary", "daily bullet points": "Key Points"})
df_summaries_entities = pd.concat([df_summaries_companies, df_summaries_trump], ignore_index=True)

In [ ]:
#df_summaries_entities.to_csv("df_summaries_entities.csv", index=False)

In [93]:
df_summaries_entities["Key Points"].iloc[63]

"On Friday, President Donald Trump's administration announced a $100,000 fee for all new recipients of H-1B visas, a type of nonimmigrant visa designed to help U.S. companies find employees with technical skills not common in the U.S.\nTrump argued that the fee will encourage companies to hire American workers, instead of foreign ones.\nThe Trump administration's sharp increase in visa fees for H-1B workers has triggered concern among US technology companies, with many considering moving more jobs overseas.\nTrump stated that 'abuse' of H-1B visas has facilitated an 'influx' of foreign labour in STEM that has undermined salaries and workplace conditions for US workers.\nThe fee hike sent H-1B holders into panic mode, prompting companies like Microsoft to ask employees abroad to rush back before midnight."

In [39]:
df_summaries_entities['Date'] = pd.to_datetime(df_summaries_entities['Date']).dt.strftime('%Y-%m-%d')

ValueError: time data "2025-09-19" doesn't match format "%Y-%m-%d %H:%M:%S", at position 58. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [53]:
import importlib
import sys

# Remove the module from cache if it exists
if 'src.labeler.narrative_labeler' in sys.modules:
    del sys.modules['src.labeler.narrative_labeler']

# Force reimport
from src.labeler.narrative_labeler import NarrativeLabeler, NarrativeSummarizerFlex
importlib.reload(sys.modules['src.labeler.narrative_labeler'])

import importlib
from src.prompts import labeler
importlib.reload(labeler)
from src.prompts.labeler import get_narrative_system_prompt
from src.prompts import labeler
from src.labeler.narrative_labeler import NarrativeLabeler, NarrativeSummarizerFlex

In [63]:
narrative_summarizer = NarrativeSummarizerFlex(llm_model="openai::gpt-4o")

# Sort and initialize columns once
df_summaries_entities = df_summaries_entities.sort_values('Date')

    
# Get final recap
entities_final_summary = narrative_summarizer.get_summaries(
    main_theme="Introduction of a high fee on H-1B visas",
    df=df_summaries_entities,
    mode="final_summary_from_daily_summaries",
)

================================================================================
DEBUG: SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating a comprehensive final recap summary from daily summaries focused on the theme of 'Introduction of a high fee on H-1B visas'. Each daily summary is compiled from news articles that reference specific companies or individuals based on their strategic positioning, actions taken, or relationship to the main theme.
You have to create a final narrative summary that captures the most significant developments and insights from the daily summaries.

You are given:
    - Name of the company or individual
    - A series of dates and daily summaries

1. **Task**:
    - You must create a final narrative summary that captures the most significant developments and insights from the daily summaries.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas' coming from news articles.
    - Do not add any information from your own knowledge or from any other sourc
================================================================================
DEBUG: USER PROMPTS (Total: 13)
================================================================================
PROMPT 1:
----------------------------------------
{"Company or Person": "Alphabet Inc.", "Summary 2025-09-19": "Alphabet Inc. is positioned to face significant challenges due to the introduction of a high fee on H-1B visas. The company, along with other major tech firms like Google, Microsoft, and Amazon, may need to rethink their hiring practices as the new fee could make it more difficult for foreign workers to access U.S. job opportunities. This change is expected to impact not only new visa applications but also renewals, potentially limiting the talent pool for these companies.", "Summary 2025-09-20": "Alphabet Inc. is now facing the introduction of a $100,000 annual fee on H-1B visas, as announced by President Donald Trump. This significant fee is expected to disproportionately affect smaller companies and startups, while larger corporations like Google may be able to absorb the costs. However, there are concerns that this steep fee will lead to a reduction in the hiring of junior and mid-level talent, which is crucial for innov
----------------------------------------
PROMPT 2:
----------------------------------------
{"Company or Person": "Donald Trump", "Summary 2025-09-19": "Donald Trump expressed optimism about the tech industry's reaction to the introduction of a high fee on H-1B visas, which is aimed at ensuring that only highly skilled workers are brought into the U.S. The new fee of $100,000 is intended to discourage the replacement of American workers and promote the hiring of domestic talent.", "Summary 2025-09-20": "Donald Trump has reiterated his administration's commitment to imposing a high fee on H-1B visas, raising it from $215 to $100,000 annually. This significant increase is aimed at discouraging the hiring of foreign workers in favor of American talent. Trump believes that this move will ensure that companies prioritize hiring skilled American workers. He has claimed that the new fee will be beneficial for the U.S. workforce, despite concerns from tech companies about the potential negative impact on their operations. The administration has framed this fee increase as a response
----------------------------------------
PROMPT 3:
----------------------------------------
{"Company or Person": "Wipro Ltd.", "Summary 2025-09-19": "Wipro Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. As a consultancy that employs a substantial number of foreign workers, primarily from India, Wipro is likely to face increased costs associated with hiring these employees due to the proposed fee hikes. The company is part of a broader industry that relies on outsourcing technical operations to manage costs for American firms. The AFL-CIO has noted that while the changes are seen as steps in the right direction, they advocate for reforms that prioritize visa allocation based on wage offers rather than random selection, indicating a need for further adjustments in the visa system that could affect companies like Wipro.", "Summary 2025-09-20": "Wipro Ltd. is facing significant challenges due to the introduction of a new $100,000 fee on H-1B visas, which is expected to reshape its hiring strategi
----------------------------------------
PROMPT 4:
----------------------------------------
{"Company or Person": "Amazon.com Inc.", "Summary 2025-09-19": "Amazon.com Inc. is significantly impacted by the proposed high fee on H-1B visas, which has sparked a mixed response from the industry. While some view the fee as a necessary measure to protect American jobs, critics argue it could deter global talent and hinder innovation. As a major player that relies heavily on H-1B visas, Amazon faces increased operational costs due to the proposal. The fee is expected to lead to a reevaluation of hiring practices not only for Amazon but also for other tech giants and startups, making it more challenging for foreign workers to secure employment in the U.S.", "Summary 2025-09-20": "Amazon.com Inc. is facing significant challenges due to the recent introduction of a $100,000 fee for H-1B visas, as announced by President Trump. The company has advised its employees holding H-1B and H-4 visas to either remain in the U.S. or return promptly to avoid complications stemming from the new fee s
----------------------------------------
PROMPT 5:
----------------------------------------
{"Company or Person": "Microsoft Corp.", "Summary 2025-09-19": "Microsoft Corp. is positioned at the center of the debate surrounding the introduction of a high fee on H-1B visas. The company, along with other major tech players, is likely to face increased operational costs due to the proposed fee, which critics argue could deter global talent and stifle innovation. This situation may compel Microsoft to rethink its hiring practices, particularly in relation to foreign workers, as the fee could make access to U.S. jobs more challenging and exclusive. While larger corporations like Microsoft may absorb these costs, smaller startups could experience significant burdens, highlighting the disparity in impact across the tech industry.", "Summary 2025-09-20": "Microsoft Corp. is facing significant challenges due to the recent introduction of a $100,000 annual fee for H-1B visas, which has been described as a 'shock' to Indian IT professionals. The company, alongside Amazon, has advised its
----------------------------------------
PROMPT 6:
----------------------------------------
{"Company or Person": "Infosys Ltd.", "Summary 2025-09-19": "Infosys Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company, along with other consultancies, relies heavily on foreign workers, particularly from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visa applications are expected to raise the cost of hiring foreign talent, which could deter companies from employing these workers. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for firms like Infosys that depend on a skilled foreign workforce.", "Summary 2025-09-20": "Infosys Ltd. is facing significant challenges due to the introduction of a $100,000 fee on H-1B visas, as highlighted by former CFO Mohandas Pai. This steep fee is expected to discourage companies from submitting new applications for H-1B visas, potentially leading to an i
----------------------------------------
PROMPT 7:
----------------------------------------
{"Company or Person": "IBM Corp. Pty. Ltd.", "Summary 2025-09-19": "IBM Corp. Pty. Ltd. is positioned within a landscape where the introduction of high fees on H-1B visas could significantly impact its operations. The company is part of a group of consultancies that employ a substantial number of foreign workers, primarily from India, to fulfill technical roles for American firms. The increased fees associated with H-1B visas are expected to raise the cost of hiring foreign workers, which could lead to further outsourcing of technical operations. While there are calls for reforms in the visa allocation process, the current fee structure poses a challenge for companies like IBM that rely on foreign talent for cost-effective solutions.", "Summary 2025-09-20": "IBM Corp. Pty. Ltd. faces a significant challenge with the introduction of a high fee on H-1B visas, which has increased the cost of sponsoring a single applicant to $100,000. This dramatic rise in fees is expected to reshape IBM's
----------------------------------------
PROMPT 8:
----------------------------------------
{"Company or Person": "Thomson Reuters Corp.", "Summary 2025-09-20": "Thomson Reuters Corp. highlights the significant impact that the proposed high fee on H-1B visas could have on startups and mid-sized tech companies, which often rely on these visas for junior and mid-level roles. The analysis suggests that the introduction of a $100,000 annual fee could lead many of these companies to reconsider their hiring strategies, potentially delaying or shifting roles overseas. The proposed fee is seen as a deterrent to attracting global talent, which could ultimately affect the U.S. economy's competitiveness, particularly in high-stakes sectors like artificial intelligence. The company underscores that the new policy could reshape how firms recruit skilled labor and may drive them to offshore high-value work, further complicating the landscape for U.S. tech firms that depend on foreign talent.", "Summary 2025-09-21": "Thomson Reuters Corp. has not issued any direct comments regarding the int
----------------------------------------
PROMPT 9:
----------------------------------------
{"Company or Person": "Tata Consultancy Services Ltd.", "Summary 2025-09-20": "Tata Consultancy Services Ltd. (TCS) is significantly impacted by the recent introduction of a $100,000 fee for H-1B visa sponsorship, as announced by President Trump. This steep increase is expected to reshape the hiring landscape for foreign professionals, particularly affecting Indian workers who constitute a large portion of H-1B visa holders. The new fee pressures TCS and similar companies to reconsider their hiring strategies, potentially shifting focus towards highly specialized, high-wage talent and domestic graduates. The company, along with other major firms, may face challenges in maintaining their workforce in the U.S. due to the increased costs associated with sponsoring H-1B applicants. As of now, TCS has not publicly commented on the changes, leaving uncertainty regarding their specific response to the new regulations.", "Summary 2025-09-21": "Tata Consultancy Services Ltd. (TCS) is responding
----------------------------------------
PROMPT 10:
----------------------------------------
{"Company or Person": "Dewang", "Summary 2025-09-21": "Dewang, represented by its Founder & CEO Dewang Neralla, has expressed significant concern regarding the proposed USD 100,000 annual fee for new H-1B visa petitions. Neralla emphasized that this fee reflects a troubling trend where global talent is becoming increasingly expensive and less mobile. The implications of this fee are particularly pronounced in sectors such as Information Technology and other US-facing industries, which may need to reconsider their workforce deployment strategies in response to the financial burden imposed by the new fee structure."}
----------------------------------------
PROMPT 11:
----------------------------------------
{"Company or Person": "Talent Fund", "Summary 2025-09-22": "Talent Fund's position regarding the introduction of a high fee on H-1B visas reflects concern over the potential impact on attracting global talent. The announcement of a significant fee increase to $100,000 by President Donald Trump has raised alarms within the tech industry, particularly as the H-1B program is crucial for skilled foreign workers, especially from India, to fill roles in technology, research, and healthcare sectors. The comments from Jamie Arrowsmith highlight the need for funding and support to ensure a smooth transition for global talent amidst these changes.", "Summary 2025-09-25": "Talent Fund is taking a proactive approach in response to the high fee on H-1B visas introduced by Donald Trump. They are advocating for the UK government to enhance its Global Talent Fund to better support engineering and founding professionals impacted by U.S. visa policies. Additionally, Talent Fund is urging the government
----------------------------------------
PROMPT 12:
----------------------------------------
{"Company or Person": "Metaview", "Summary 2025-09-22": "Metaview, a San Francisco-based tech company, is actively responding to the challenges posed by the recent introduction of a high fee on H-1B visas. Shahriar Tajbakhsh, the co-founder and CTO, has indicated that the firm is prepared to accelerate its hiring of top professionals despite the increased costs associated with the H-1B visa changes. He expressed confidence in the value that each team member brings, viewing the $100,000 fee as a minor concern in comparison. This proactive stance highlights Metaview's commitment to attracting and retaining skilled talent in a competitive landscape where other countries may seek to benefit from the fee hike."}
----------------------------------------
PROMPT 13:
----------------------------------------
{"Company or Person": "DBRS Ltd.", "Summary 2025-09-24": "DBRS Ltd. has expressed significant concerns regarding the introduction of a high fee on H-1B visas, particularly its impact on hiring practices within the banking sector. The company highlights that the increased costs associated with H-1B visas may lead banks to seek more offshore workers, especially when the necessary skills are not readily available in the U.S. This shift could make it increasingly challenging to fill entry-level positions through the H-1B program, as noted by company representatives.", "Summary 2025-09-25": "DBRS Ltd. has reiterated its concerns about the introduction of a high fee on H-1B visas, emphasizing its potential repercussions on the banking sector. Tim O'Brien, managing director at Morningstar DBRS, pointed out that the new fee could lead banks to increasingly hire offshore workers when necessary skills are not available in the U.S. Additionally, he warned of an unintended consequence where global
----------------------------------------
================================================================================

Querying OpenAI...:   0%|          | 0/13 [00:00<?, ?it/s]

Querying OpenAI...: 100%|██████████| 13/13 [00:07<00:00,  1.71it/s]

In [65]:
entities_final_summary.to_csv("final_summary_per_entity.csv", index=False)

In [135]:
entities_final_summary = pd.read_csv("final_summary_per_entity.csv")

In [41]:
# Versione più elegante con pandas groupby
countries_dict = df_company_summaries.groupby('Country')['Entity'].apply(list).to_dict()

# Rimuovi eventuali duplicati (se ci sono)
for country in countries_dict:
    countries_dict[country] = list(set(countries_dict[country]))

In [69]:
df_highlights = pd.DataFrame()
for country, companies in countries_dict.items():
    print("Processing companies:", companies)
    daily_highlights = narrative_summarizer.get_summaries(
        main_theme="Introduction of a high fee on H-1B visas",
        df=df_summaries_entities,
        mode="companies_daily_highlights_from_daily_key_points",
        additional_parameters={"companies": companies}
    )
    df_highlights = pd.concat([df_highlights, daily_highlights], ignore_index=True)

Processing companies: ['Thomson Reuters Corp.', 'DBRS Ltd.', 'Talent Fund']

Querying OpenAI...:   0%|          | 0/1 [00:00<?, ?it/s]

Querying OpenAI...: 100%|██████████| 1/1 [00:03<00:00,  3.22s/it]

Processing companies: ['IBM Corp. Pty. Ltd.', 'Metaview', 'Dewang']

Querying OpenAI...: 100%|██████████| 1/1 [00:02<00:00,  2.89s/it]

Processing companies: ['Tata Consultancy Services Ltd.', 'Infosys Ltd.', 'Wipro Ltd.']

Querying OpenAI...: 100%|██████████| 1/1 [00:09<00:00,  9.26s/it]

Processing companies: ['Amazon.com Inc.', 'Alphabet Inc.', 'Microsoft Corp.']

Querying OpenAI...: 100%|██████████| 1/1 [00:05<00:00,  5.19s/it]

In [70]:
df_highlights.to_csv("df_highlights.csv", index=False)

In [42]:
df_highlights = pd.read_csv("df_highlights.csv")

# CREATE VISUALIZATIONS

In [43]:
narrative_dates

array(['2025-09-19', '2025-09-20', '2025-09-21', '2025-09-22',
       '2025-09-23', '2025-09-24', '2025-09-25'], dtype=object)

In [147]:
df_company_summaries.head()

,Entity,Date,Summary,Key_points,Quotes,Country,enhanced_summary,enhanced_key_points
0,Alphabet Inc.,2025-09-19,Alphabet Inc. is positioned to face significan...,['The introduction of a high fee on H-1B visas...,"['For companies like Google, Microsoft, Amazon...",United States,Alphabet Inc. is positioned to face significan...,['The introduction of a high fee on H-1B visas...
1,Alphabet Inc.,2025-09-20,Alphabet Inc. is positioned to face significan...,"['The $100,000 annual fee on H-1B visas is exp...","['""US tech giants like Amazon, Microsoft, Goog...",United States,Alphabet Inc. is now facing the introduction o...,"['The introduction of a $100,000 annual fee on..."
2,Alphabet Inc.,2025-09-21,Alphabet Inc. is significantly impacted by the...,['Alphabet Inc. is concerned about the financi...,"[""Amazon, Alphabet's Google, Microsoft and oth...",United States,Alphabet Inc. is facing significant financial ...,['Alphabet Inc. is concerned about the financi...
3,Alphabet Inc.,2025-09-22,"Alphabet Inc., through its subsidiary Google, ...","[""Alphabet Inc.'s Google employs thousands of ...","['In response to the announcement, tech giants...",United States,"Alphabet Inc., through its subsidiary Google, ...",['Alphabet Inc. employs thousands of H-1B visa...
4,Alphabet Inc.,2025-09-23,Alphabet Inc. is positioned as a significant p...,['Alphabet Inc. is among the tech giants that ...,"['For Silicon Valley, the decision is disrupti...",United States,New information indicates that Alphabet Inc. h...,['Alphabet Inc. has historically relied on H-1...

In [149]:
import importlib
import sys

# Force reload of the plots module
if 'src.report.plots' in sys.modules:
    importlib.reload(sys.modules['src.report.plots'])

# Import the function
from src.report.plots import create_enhanced_interactive_chart

# Create enhanced chart
fig_enhanced = create_enhanced_interactive_chart(
    df_DT_theme_matching_narrative, 
    df_DT_theme_matching_citation, 
    df_top_3_all_countries, 
    df_company_summaries, 
    narrative_dates
)

# Show the enhanced plot
fig_enhanced.show()

# Save with better name
fig_enhanced.write_html("h1b_narrative_dashboard_enhanced.html")
print("Enhanced interactive dashboard saved as 'h1b_narrative_dashboard_enhanced.html'")

Enhanced interactive dashboard saved as 'h1b_narrative_dashboard_enhanced.html'

In [94]:

# Forza reload
import importlib
import sys
if 'src.report.html' in sys.modules:
    importlib.reload(sys.modules['src.report.html'])
from src.report import html

html.generate_interactive_timeline_dashboard_html(
    df_highlights=df_highlights,
    countries_dict=countries_dict,
    df_company_summaries=df_company_summaries,
    plotly_fig=fig_enhanced,
    output_file="simple_interactive_timeline.html"
    # Nessun parametro follow_trend!
)

Interactive timeline dashboard generated: simple_interactive_timeline.html

'simple_interactive_timeline.html'

Interactive timeline dashboard generated: full_dashboard.html

'full_dashboard.html'

In [55]:
countries_dict

{'Canada': ['Thomson Reuters Corp.', 'DBRS Ltd.', 'Talent Fund'],
 'China': ['Metaview', 'IBM Corp. Pty. Ltd.', 'Dewang'],
 'India': ['Tata Consultancy Services Ltd.', 'Infosys Ltd.', 'Wipro Ltd.'],
 'United States': ['Microsoft Corp.', 'Amazon.com Inc.', 'Alphabet Inc.']}

In [50]:
df_sentences_related.columns

Index(['Time Period', 'Date', 'Document ID', 'Sentence ID', 'Headline',
       'Chunk Text', 'Motivation', 'Label', 'Entity', 'Country Code',
       'Entity Type', 'Theme Matching Label', 'Theme Matching Motivation'],
      dtype='object')

In [52]:
unique_documents_count = df_sentences_related['Document ID'].nunique()
unique_documents_count

1372

In [76]:
unique_sentences_count = df_sentences_related['Sentence ID'].nunique()
unique_sentences_count

2175

In [74]:
# Extract all companies from countries_dict
all_companies = []
for country, companies in countries_dict.items():
    all_companies.extend(companies)

# Calculate overall totals for each company first
overall_totals = {}
for company in all_companies:
    company_rows = df_sentences_related[df_sentences_related['Entity'] == company]
    overall_totals[company] = {
        'Overall_Total_Sentences': len(company_rows),
        'Overall_Unique_Documents': company_rows['Document ID'].nunique()
    }

# Get unique dates
unique_dates = df_sentences_related['Date'].unique()

# Calculate statistics for each company and date
company_data = []
for date in unique_dates:
    # Filter data for this specific date
    date_data = df_sentences_related[df_sentences_related['Date'] == date]
    total_unique_docs_date = date_data['Document ID'].nunique()
    
    for company in all_companies:
        company_rows = date_data[date_data['Entity'] == company]
        total_sentences = len(company_rows)
        unique_docs = company_rows['Document ID'].nunique()
        
        # Calculate overall percentage
        overall_percentage = round((overall_totals[company]['Overall_Unique_Documents'] / unique_documents_count * 100) if unique_documents_count > 0 else 0, 2)
        
        company_data.append({
            'Date': date,
            'Company': company,
            'Total_Sentences': total_sentences,
            'Unique_Documents': unique_docs,
            'Total_Unique_Documents': total_unique_docs_date,
            'Percentage_Documents': round((unique_docs / total_unique_docs_date * 100) if total_unique_docs_date > 0 else 0, 2),
            'Overall_Total_Sentences': overall_totals[company]['Overall_Total_Sentences'],
            'Overall_Unique_Documents': overall_totals[company]['Overall_Unique_Documents'],
            'Overall_Percentage_Documents': overall_percentage
        })

# Create final dataframe
company_stats = pd.DataFrame(company_data)
company_stats = company_stats.sort_values(['Date', 'Total_Sentences'], ascending=[True, False])

In [91]:
company_stats

,Date,Company,Total_Sentences,Unique_Documents,Total_Unique_Documents,Percentage_Documents,Overall_Total_Sentences,Overall_Unique_Documents,Overall_Percentage_Documents
9,2025-09-19,Microsoft Corp.,9,4,29,13.79,441,165,12.03
10,2025-09-19,Amazon.com Inc.,9,4,29,13.79,493,169,12.32
11,2025-09-19,Alphabet Inc.,7,2,29,6.90,327,98,7.14
4,2025-09-19,IBM Corp. Pty. Ltd.,4,1,29,3.45,19,10,0.73
7,2025-09-19,Infosys Ltd.,4,1,29,3.45,190,79,5.76
...,...,...,...,...,...,...,...,...,...
74,2025-09-25,Talent Fund,1,1,63,1.59,2,2,0.15
75,2025-09-25,Metaview,0,0,63,0.00,7,1,0.07
76,2025-09-25,IBM Corp. Pty. Ltd.,0,0,63,0.00,19,10,0.73
77,2025-09-25,Dewang,0,0,63,0.00,9,2,0.15
78,2025-09-25,Tata Consultancy Services Ltd.,0,0,63,0.00,97,38,2.77

In [70]:
# Force reload if needed
import importlib
import sys
if 'src.report.plots' in sys.modules:
    importlib.reload(sys.modules['src.report.plots'])

# Import the new function
from src.report.plots import create_company_document_coverage_chart

# Use it
fig_document_coverage = create_company_document_coverage_chart(company_stats)
fig_document_coverage.show()

In [71]:
fig2 = create_company_document_coverage_chart(company_stats, relative_overall=True)
fig2.show()

In [ ]:
df_summaries_entities.columns
df_summaries_trump.columns

Index(['Entity', 'Date', 'Summary', 'Key Points'], dtype='object')

In [112]:
df_company_summaries.columns

Index(['Entity', 'Date', 'Summary', 'Key_points', 'Quotes', 'Country',
       'enhanced_summary', 'enhanced_key_points'],
      dtype='object')

In [100]:
import importlib
import sys
if 'src.report.html' in sys.modules:
    importlib.reload(sys.modules['src.report.html'])
from src.report import html
from src.report.html import generate_interactive_timeline_dashboard_html

generate_interactive_timeline_dashboard_html(
    df_highlights=df_highlights,
    df_company_summaries=df_company_summaries,
    plotly_fig=fig_enhanced,
    countries_dict=countries_dict,
    df_entities_final_summary=entities_final_summary,
    company_stats=company_stats,  # ← NEW!
    unique_sentences_count=unique_sentences_count,  # ← NEW!
    output_file="full_dashboard.html"
)

Interactive timeline dashboard generated: full_dashboard.html

'full_dashboard.html'

In [ ]:
df_summaries_entities

In [150]:
# Force reload
import importlib
import sys
if 'src.report.html' in sys.modules:
    importlib.reload(sys.modules['src.report.html'])

from src.report.html import generate_interactive_timeline_dashboard_html

# Convert Date column handling mixed formats
df_summaries_entities["Date"] = pd.to_datetime(df_summaries_entities["Date"], format='mixed')

# Generate dashboard with People Mode using df_summaries_entities
generate_interactive_timeline_dashboard_html(
    df_highlights=df_highlights,
    df_company_summaries=df_company_summaries,
    plotly_fig=fig_enhanced,
    countries_dict=countries_dict,
    df_entities_final_summary=entities_final_summary,
    company_stats=company_stats,
    unique_sentences_count=unique_sentences_count,
    df_summaries_entities=df_summaries_entities,
    output_file="full_dashboard_with_people.html"
)

Interactive timeline dashboard generated: full_dashboard_with_people.html

'full_dashboard_with_people.html'

# Generate unique final Summary

In [127]:
narrative_dates

array(['2025-09-19', '2025-09-20', '2025-09-21', '2025-09-22',
       '2025-09-23', '2025-09-24', '2025-09-25'], dtype=object)

In [136]:
import importlib
import sys

# Remove the module from cache if it exists
if 'src.labeler.narrative_labeler' in sys.modules:
    del sys.modules['src.labeler.narrative_labeler']

# Force reimport
from src.labeler.narrative_labeler import NarrativeLabeler, NarrativeSummarizerFlex
importlib.reload(sys.modules['src.labeler.narrative_labeler'])

import importlib
from src.prompts import labeler
importlib.reload(labeler)
from src.prompts.labeler import get_narrative_system_prompt
from src.prompts import labeler
from src.labeler.narrative_labeler import NarrativeLabeler, NarrativeSummarizerFlex

narrative_summarizer = NarrativeSummarizerFlex(llm_model="openai::gpt-4o")

# Sort and initialize columns once
    
# Get final recap
final_summary = narrative_summarizer.get_summaries(
    main_theme="Introduction of a high fee on H-1B visas",
    df=entities_final_summary,
    mode="final_summary_general_report",
)

================================================================================
DEBUG: FINAL SUMMARY GENERAL REPORT SYSTEM PROMPT
================================================================================

Forget all previous prompts.
You are assisting a professional analyst in creating a comprehensive final recap summary from summaries focused on the theme of 'Introduction of a high fee on H-1B visas'. Each daily summary is compiled from news articles that reference specific companies or individuals based on their strategic positioning, actions taken, or relationship to the main theme.
You have to create a final narrative summary that captures the most significant developments and insights from the summaries.

You are given a series of the following::
    - Name of the company or individual
    - Summaries about the theme of 'Introduction of a high fee on H-1B visas' about the company or the individual

1. **Task**:
    - You must create a final narrative summary that captures the most significant developments and insights from the summaries.
    - Do not include any information that is not related to the theme of 'Introduction of a high fee on H-1B visas'.
    - Do not add any inform
================================================================================
DEBUG: FINAL SUMMARY GENERAL REPORT USER PROMPT
================================================================================
{
  "Alphabet Inc.": "The introduction of a high fee on H-1B visas, specifically a $100,000 annual fee, has posed significant challenges for Alphabet Inc. and the broader tech industry. Alphabet, along with other major tech firms like Google, Microsoft, and Amazon, is expected to face increased operational costs and potential talent shortages as a result of this policy. The fee is anticipated to impact not only new visa applications but also renewals, limiting the talent pool available to these companies. While larger corporations like Alphabet may be able to absorb the costs, the fee is seen as particularly burdensome for startups and smaller firms, which could lead to a reduction in hiring of junior and mid-level talent crucial for innovation. Industry experts warn that this could slow down innovation and push companies to consider offshoring jobs, affecting the U.S. labor market. Alphabet has advised its H-1B visa employees to avoid international travel to mitigate potential re-entr
================================================================================

Querying OpenAI...:   0%|          | 0/1 [00:00<?, ?it/s]

Querying OpenAI...: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

In [137]:
final_summary

'{"summary": "The introduction of a $100,000 annual fee on H-1B visas has significantly impacted various sectors, particularly the tech industry, which heavily relies on foreign talent. Major companies like Alphabet Inc., Amazon.com Inc., Microsoft Corp., and IBM Corp. Pty. Ltd. are facing increased operational costs and potential talent shortages. This fee is expected to double hiring costs, prompting these companies to reassess their human resources strategies, potentially slowing innovation and delaying projects in critical areas such as artificial intelligence and cloud computing. The policy, introduced by Donald Trump, aims to curb perceived abuses of the H-1B program and protect American jobs, but it has led to confusion and apprehension among tech companies, with fears of workforce disruption and potential downsizing.\\n\\nIndian IT firms like Wipro Ltd., Infosys Ltd., and Tata Consultancy Services Ltd. are particularly affected, as they rely heavily on H-1B visas for their operations in the U.S. These companies are exploring alternative solutions such as offshoring work, increasing local hiring in the U.S., and utilizing remote work to mitigate the financial burden. The fee is expected to erode operating margins and increase annual immigration costs significantly, prompting a strategic shift in business models and hiring practices.\\n\\nSmaller firms and startups are disproportionately affected, as the fee poses a significant financial burden, potentially stifling innovation and collaboration within the tech sector. Companies like Metaview and Talent Fund are taking proactive measures to adapt, with Metaview focusing on attracting top talent despite the higher costs, and Talent Fund advocating for enhanced global talent acquisition strategies.\\n\\nThe banking sector, as noted by DBRS Ltd., may also see a shift towards hiring offshore workers due to the increased costs, potentially leading to a relocation of global experts to more favorable jurisdictions like Canada. Overall, the high fee on H-1B visas is reshaping the operational landscape for many companies, necessitating strategic pivots to adapt to the evolving immigration policy environment."}'

In [128]:
entities_final_summary.columns

Index(['Entity', 'summary', 'key_points', 'quotes', 'country', 'quote_count'], dtype='object')

In [126]:
entities_final_summary

,Entity,summary,key_points,quotes,country,quote_count
0,Alphabet Inc.,"The introduction of a high fee on H-1B visas, ...",[],[],NaN,7
1,Donald Trump,"In September 2025, Donald Trump announced a si...",[],[],NaN,7
2,Wipro Ltd.,Wipro Ltd. is navigating significant challenge...,[],[],NaN,7
3,Amazon.com Inc.,Amazon.com Inc. is significantly impacted by t...,[],[],NaN,7
4,Microsoft Corp.,"The introduction of a $100,000 fee on H-1B vis...",[],[],NaN,7
5,Infosys Ltd.,Infosys Ltd. is navigating significant challen...,[],[],NaN,7
6,IBM Corp. Pty. Ltd.,IBM Corp. Pty. Ltd. is navigating a challengin...,[],[],NaN,6
7,Thomson Reuters Corp.,"The introduction of a $100,000 annual fee on H...",[],[],NaN,6
8,Tata Consultancy Services Ltd.,Tata Consultancy Services Ltd. (TCS) is signif...,[],[],NaN,5
9,Dewang,"Dewang, led by Founder & CEO Dewang Neralla, h...",[],[],NaN,1
10,Talent Fund,The introduction of a high fee on H-1B visas b...,[],[],NaN,2
11,Metaview,"Metaview, a tech company based in San Francisc...",[],[],NaN,1
12,DBRS Ltd.,DBRS Ltd. has raised significant concerns abou...,[],[],NaN,2

In [151]:
import importlib
import sys

# Rimuovi completamente il modulo dalla cache
if 'src.report.html' in sys.modules:
    del sys.modules['src.report.html']

# Reimporta da zero
from src.report.html import generate_interactive_timeline_dashboard_html


generate_interactive_timeline_dashboard_html(
    df_highlights=df_highlights,
    df_company_summaries=df_company_summaries,
    plotly_fig=fig_enhanced,
    countries_dict=countries_dict,
    df_entities_final_summary=entities_final_summary,
    company_stats=company_stats,
    unique_sentences_count=unique_sentences_count,
    df_summaries_entities=df_summaries_entities,
    final_summary=final_summary,  # ← PRENDI SOLO IL VALORE
    output_file="full_dashboard_with_people_and_summary.html"
)

Interactive timeline dashboard generated: full_dashboard_with_people_and_summary.html

'full_dashboard_with_people_and_summary.html'