# Large-Scale Portfolio Briefs Generation V2

This notebook runs Brief V2 batches for a portfolio of `RP_ENTITY_ID` values, monitors each batch to completion, retrieves generated bullets, previews the first 10 entities, and exports all bullet results to Excel.

## Step 1: Load Company Identifiers from CSV File

Read the portfolio CSV, locate the `RP_ENTITY_ID` column, remove empty or duplicate identifiers, and prepare the entity list used by the V2 batch APIs.

In [1]:
from __future__ import annotations

import json
import os
import time
import traceback
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd
import requests
from IPython.display import Markdown, display

JsonDict = dict[str, Any]

CSV_PATH = Path("static/data/US_100.csv")
df = pd.read_csv(CSV_PATH, dtype=str)

entity_id_column = next((c for c in df.columns if c.strip().upper() == "RP_ENTITY_ID"), None)
if entity_id_column is None:
    raise ValueError(f"RP_ENTITY_ID column not found in {CSV_PATH}")

ids: list[str] = (
    df[entity_id_column]
    .astype(str)
    .str.strip()
    .replace({"": None})
    .dropna()
    .drop_duplicates()
    .tolist()
)

print(f"Loaded {len(ids)} unique RP_ENTITY_ID values from {CSV_PATH}")

Loaded 107 unique RP_ENTITY_ID values from static/data/US_100.csv

## Step 2: Configure Brief V2 Batch Processing

Configure the V2 API endpoints, batch size, and report window. The V2 workflow uses the selected `2026-02-01T00:00:00` to `2026-03-30T23:59:59` window.

In [2]:
# Batch size follows the V1 notebook's production-oriented default.
BATCH_SIZE: int = 50
companies: list[str] = ids

API_BASE_URL: str = "http://localhost:8000"
RUN_PARALLEL_URL: str = f"{API_BASE_URL}/api/v1/batch/run-parallel"
BULLETS_URL: str = f"{API_BASE_URL}/api/v1/batch/bullets"


FORCE_WINDOW_START: str = "2026-02-01T00:00:00"
FORCE_WINDOW_END: str = "2026-03-30T23:59:59"

POLL_INTERVAL_SECONDS: int = 30
BATCH_TIMEOUT_SECONDS: int = 3600

# Optional token support, retained from the V1 workflow if the local service requires it.
token = os.environ.get("API_TOKEN") or os.environ.get("TOKEN") or os.environ.get("API_KEY")
params: dict[str, str] = {"token": token} if token else {}

print(f"Using {len(companies)} companies")
print(f"Batch size: {BATCH_SIZE}")
print(f"Report window: {FORCE_WINDOW_START} to {FORCE_WINDOW_END}")

Using 107 companies
Batch size: 50
Report window: 2026-02-01T00:00:00 to 2026-03-30T23:59:59

## Step 3: Set Output Folder and File Names

All V2 artifacts are written under `output/` with V2-specific file names so they do not overwrite V1 outputs.

In [17]:
OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

BRIEF_V2_BATCH_SUMMARY_FILE = OUTPUT_DIR / "brief_v2_batch_summaries.json"
BRIEF_V2_FIRST5_BULLETS_FILE = OUTPUT_DIR / "brief_v2_first5_bullets.json"
BRIEF_V2_ALL_BULLETS_FILE = OUTPUT_DIR / "brief_v2_all_bullets.json"
OUT_XLSX = OUTPUT_DIR / "portfolio_briefs_generation_v2.xlsx"

## Step 4: Define API and Formatting Helpers

These helpers keep the V2 API calls, polling logic, JSON persistence, and citation formatting reusable across the notebook.

In [4]:
def chunk_entities(entity_ids: list[str], batch_size: int) -> list[list[str]]:
    """Split entity identifiers into fixed-size batches."""
    return [entity_ids[start : start + batch_size] for start in range(0, len(entity_ids), batch_size)]


def request_json(method: str, url: str, *, timeout: int = 60, **kwargs: Any) -> JsonDict:
    """Call the local Brief V2 API and return parsed JSON with useful HTTP error context."""
    response = requests.request(method, url, params=params, timeout=timeout, **kwargs)
    try:
        response.raise_for_status()
    except requests.HTTPError as exc:
        message = f"{method} {url} failed with {response.status_code}: {response.text}"
        raise requests.HTTPError(message) from exc
    return response.json()


def status_url_for(batch_id: str) -> str:
    """Build the V2 batch status endpoint for a submitted batch."""
    return f"{API_BASE_URL}/api/v1/batch/parallel/{batch_id}/status"


def is_batch_complete(status_payload: JsonDict) -> bool:
    """Return True when all entities in a V2 batch have either succeeded or failed."""
    total = int(status_payload.get("total") or 0)
    succeeded = int(status_payload.get("succeeded") or 0)
    failed = int(status_payload.get("failed") or 0)
    running = int(status_payload.get("running") or 0)
    not_started = int(status_payload.get("not_started") or 0)

    if total > 0:
        return succeeded + failed >= total
    return running == 0 and not_started == 0 and succeeded + failed > 0


def status_summary(status_payload: JsonDict) -> str:
    """Format a compact status line for notebook progress output."""
    return (
        f"succeeded={status_payload.get('succeeded', 0)}, "
        f"failed={status_payload.get('failed', 0)}, "
        f"running={status_payload.get('running', 0)}, "
        f"not_started={status_payload.get('not_started', 0)}, "
        f"total={status_payload.get('total', 0)}"
    )


def save_json(path: Path, payload: Any) -> None:
    """Persist payload as indented UTF-8 JSON."""
    with path.open("w", encoding="utf-8") as file_handle:
        json.dump(payload, file_handle, ensure_ascii=False, indent=2)


def fetch_bullets_for_entities(entity_ids: list[str]) -> JsonDict:
    """Retrieve saved V2 bullets for a list of entities."""
    if not entity_ids:
        return {"results": [], "total_entities": 0, "total_bullets": 0}
    return request_json("POST", BULLETS_URL, json={"entity_ids": entity_ids}, timeout=180)

## Step 5: Run Brief V2 Batches Sequentially

Submit one `run-parallel` batch at a time, poll its status until every entity has either succeeded or failed, then move to the next batch. This matches the requested flow: once a batch is complete, start the next batch.

In [5]:
batch_summaries: list[JsonDict] = []
entity_batches = chunk_entities(companies, BATCH_SIZE)

print(f"Batch starting date and time: {datetime.now()}")

for batch_number, batch in enumerate(entity_batches, start=1):
    batch_start = (batch_number - 1) * BATCH_SIZE + 1
    batch_end = batch_start + len(batch) - 1
    payload_batch: JsonDict = {
        "entity_ids": batch,
        "force_window_start": FORCE_WINDOW_START,
        "force_window_end": FORCE_WINDOW_END,
    }

    summary: JsonDict = {
        "batch_number": batch_number,
        "batch_start": batch_start,
        "batch_end": batch_end,
        "entity_count": len(batch),
        "entity_ids": batch,
        "payload": payload_batch,
        "status": "submitted",
        "submitted_at_local": datetime.now().isoformat(),
    }

    try:
        print(f"Submitting batch {batch_start}-{batch_end} ({len(batch)} entities)...")
        submit_response = request_json("POST", RUN_PARALLEL_URL, json=payload_batch, timeout=180)
        summary["submission_response"] = submit_response
    except requests.RequestException as exc:
        print(f"Batch {batch_start}-{batch_end} submission failed: {exc}")
        traceback.print_exc()
        summary["status"] = "submit_failed"
        summary["error"] = str(exc)
        batch_summaries.append(summary)
        continue

    batch_id = str(submit_response.get("batch_id") or "").strip()
    if not batch_id:
        print(f"Batch {batch_start}-{batch_end} did not return a batch_id; skipping status polling.")
        summary["status"] = "missing_batch_id"
        batch_summaries.append(summary)
        continue

    summary["batch_id"] = batch_id
    summary["submitted_at"] = submit_response.get("submitted_at")
    summary["total"] = submit_response.get("total")

    final_status_response: JsonDict | None = None
    waited_seconds = 0

    while waited_seconds <= BATCH_TIMEOUT_SECONDS:
        try:
            status_response = request_json("GET", status_url_for(batch_id), timeout=60)
            final_status_response = status_response
            print(f"Batch {batch_start}-{batch_end} status: {status_summary(status_response)}")

            if is_batch_complete(status_response):
                failed = int(status_response.get("failed") or 0)
                summary["status"] = "completed_with_failures" if failed else "completed"
                break
        except requests.RequestException as exc:
            print(f"Status check error for batch {batch_id}: {exc}")
            summary.setdefault("status_errors", []).append(str(exc))

        time.sleep(POLL_INTERVAL_SECONDS)
        waited_seconds += POLL_INTERVAL_SECONDS

    if final_status_response is None:
        summary["status"] = "status_unavailable"
    elif not is_batch_complete(final_status_response):
        summary["status"] = "timeout"

    summary["waited_seconds"] = waited_seconds
    summary["completed_at_local"] = datetime.now().isoformat()
    summary["final_status_response"] = final_status_response
    batch_summaries.append(summary)

    print(f"Batch {batch_start}-{batch_end} finished with status: {summary['status']}")

save_json(BRIEF_V2_BATCH_SUMMARY_FILE, batch_summaries)

print(f"Saved {len(batch_summaries)} batch summaries to {BRIEF_V2_BATCH_SUMMARY_FILE}")
print(f"Batch completion date and time: {datetime.now()}")

Batch starting date and time: 2026-04-25 17:09:48.060164
Submitting batch 1-50 (50 entities)...
Batch 1-50 status: succeeded=0, failed=0, running=0, not_started=50, total=50
Batch 1-50 status: succeeded=0, failed=0, running=10, not_started=40, total=50
Batch 1-50 status: succeeded=0, failed=0, running=10, not_started=40, total=50
Batch 1-50 status: succeeded=2, failed=0, running=8, not_started=40, total=50
Batch 1-50 status: succeeded=6, failed=0, running=6, not_started=38, total=50
Batch 1-50 status: succeeded=9, failed=0, running=6, not_started=35, total=50
Batch 1-50 status: succeeded=11, failed=0, running=6, not_started=33, total=50
Batch 1-50 status: succeeded=12, failed=0, running=7, not_started=31, total=50
Batch 1-50 status: succeeded=15, failed=0, running=6, not_started=29, total=50
Batch 1-50 status: succeeded=18, failed=0, running=4, not_started=28, total=50
Batch 1-50 status: succeeded=21, failed=0, running=4, not_started=25, total=50
Batch 1-50 status: succeeded=21, failed=0, running=6, not_started=23, total=50
Batch 1-50 status: succeeded=23, failed=0, running=6, not_started=21, total=50
Batch 1-50 status: succeeded=25, failed=0, running=6, not_started=19, total=50
Batch 1-50 status: succeeded=26, failed=0, running=5, not_started=19, total=50
Batch 1-50 status: succeeded=29, failed=0, running=4, not_started=17, total=50
Batch 1-50 status: succeeded=30, failed=0, running=4, not_started=16, total=50
Batch 1-50 status: succeeded=32, failed=0, running=3, not_started=15, total=50
Batch 1-50 status: succeeded=33, failed=0, running=4, not_started=13, total=50
Batch 1-50 status: succeeded=35, failed=0, running=4, not_started=11, total=50
Batch 1-50 status: succeeded=36, failed=0, running=4, not_started=10, total=50
Batch 1-50 status: succeeded=37, failed=0, running=5, not_started=8, total=50
Batch 1-50 status: succeeded=39, failed=0, running=4, not_started=7, total=50
Batch 1-50 status: succeeded=41, failed=0, running=2, not_started=7, total=50
Batch 1-50 status: succeeded=41, failed=0, running=4, not_started=5, total=50
Batch 1-50 status: succeeded=43, failed=0, running=4, not_started=3, total=50
Batch 1-50 status: succeeded=45, failed=0, running=2, not_started=3, total=50
Batch 1-50 status: succeeded=46, failed=0, running=3, not_started=1, total=50
Batch 1-50 status: succeeded=47, failed=0, running=3, not_started=0, total=50
Batch 1-50 status: succeeded=49, failed=0, running=1, not_started=0, total=50
Batch 1-50 status: succeeded=49, failed=0, running=1, not_started=0, total=50
Batch 1-50 status: succeeded=50, failed=0, running=0, not_started=0, total=50
Batch 1-50 finished with status: completed
Submitting batch 51-100 (50 entities)...
Batch 51-100 status: succeeded=0, failed=0, running=0, not_started=50, total=50
Batch 51-100 status: succeeded=0, failed=0, running=10, not_started=40, total=50
Batch 51-100 status: succeeded=0, failed=0, running=10, not_started=40, total=50
Batch 51-100 status: succeeded=4, failed=0, running=6, not_started=40, total=50
Batch 51-100 status: succeeded=10, failed=0, running=2, not_started=38, total=50
Batch 51-100 status: succeeded=10, failed=0, running=7, not_started=33, total=50
Batch 51-100 status: succeeded=10, failed=0, running=10, not_started=30, total=50
Batch 51-100 status: succeeded=14, failed=0, running=6, not_started=30, total=50
Batch 51-100 status: succeeded=17, failed=0, running=3, not_started=30, total=50
Batch 51-100 status: succeeded=20, failed=0, running=3, not_started=27, total=50
Batch 51-100 status: succeeded=20, failed=0, running=5, not_started=25, total=50
Batch 51-100 status: succeeded=21, failed=0, running=6, not_started=23, total=50
Batch 51-100 status: succeeded=25, failed=0, running=5, not_started=20, total=50
Batch 51-100 status: succeeded=26, failed=0, running=4, not_started=20, total=50
Batch 51-100 status: succeeded=29, failed=0, running=2, not_started=19, total=50
Batch 51-100 status: succeeded=30, failed=0, running=3, not_started=17, total=50
Batch 51-100 status: succeeded=31, failed=0, running=4, not_started=15, total=50
Batch 51-100 status: succeeded=31, failed=0, running=6, not_started=13, total=50
Batch 51-100 status: succeeded=33, failed=0, running=6, not_started=11, total=50
Batch 51-100 status: succeeded=36, failed=0, running=4, not_started=10, total=50
Batch 51-100 status: succeeded=39, failed=0, running=2, not_started=9, total=50
Batch 51-100 status: succeeded=40, failed=0, running=1, not_started=9, total=50
Batch 51-100 status: succeeded=40, failed=0, running=3, not_started=7, total=50
Batch 51-100 status: succeeded=41, failed=0, running=4, not_started=5, total=50
Batch 51-100 status: succeeded=42, failed=0, running=5, not_started=3, total=50
Batch 51-100 status: succeeded=44, failed=0, running=5, not_started=1, total=50
Batch 51-100 status: succeeded=44, failed=0, running=6, not_started=0, total=50
Batch 51-100 status: succeeded=49, failed=0, running=1, not_started=0, total=50
Batch 51-100 status: succeeded=49, failed=0, running=1, not_started=0, total=50
Batch 51-100 status: succeeded=50, failed=0, running=0, not_started=0, total=50
Batch 51-100 finished with status: completed
Submitting batch 101-107 (7 entities)...
Batch 101-107 status: succeeded=0, failed=0, running=0, not_started=7, total=7
Batch 101-107 status: succeeded=0, failed=0, running=7, not_started=0, total=7
Batch 101-107 status: succeeded=1, failed=0, running=6, not_started=0, total=7
Batch 101-107 status: succeeded=6, failed=0, running=1, not_started=0, total=7
Batch 101-107 status: succeeded=7, failed=0, running=0, not_started=0, total=7
Batch 101-107 finished with status: completed
Saved 3 batch summaries to output/brief_v2_batch_summaries.json
Batch completion date and time: 2026-04-25 17:41:50.579663

## Step 6: Retrieve Bullets for the First 5 Entities

After batches complete, fetch bullets for the first 5 entities and save the raw response for inspection.

In [18]:
preview_entity_ids: list[str] = companies[:5]
first5_bullets_response = fetch_bullets_for_entities(preview_entity_ids)
save_json(BRIEF_V2_FIRST5_BULLETS_FILE, first5_bullets_response)

first5_results: list[JsonDict] = first5_bullets_response.get("results", []) or []

print(
    f"Retrieved bullets for {len(first5_results)} preview entities "
    f"with {first5_bullets_response.get('total_bullets', 0)} total bullets."
)
print(f"Saved preview bullets to {BRIEF_V2_FIRST5_BULLETS_FILE}")

Retrieved bullets for 5 preview entities with 26 total bullets.
Saved preview bullets to output/brief_v2_first5_bullets.json

## Step 7: Display First 5 Entity Bullet Results

Render the first 5 V2 bullet results in a notebook-friendly analyst view, including run metadata, bullet text, citations, and discard summaries.

In [21]:
def source_names_from_citation(citation: JsonDict) -> list[str]:
    """Extract citation source names from V2 source_references metadata."""
    source_references = citation.get("source_references") or []
    source_names: list[str] = []

    if isinstance(source_references, list):
        for source_reference in source_references:
            if not isinstance(source_reference, dict):
                continue
            source_name = str(source_reference.get("source_name") or "").strip()
            if source_name and source_name not in source_names:
                source_names.append(source_name)

    fallback_source_name = str(citation.get("source_name") or "").strip()
    if fallback_source_name and fallback_source_name not in source_names:
        source_names.append(fallback_source_name)

    return source_names


def citations_table(citations: list[JsonDict]) -> pd.DataFrame:
    """Build a readable citation table for notebook preview output."""
    rows: list[JsonDict] = []

    for citation_number, citation in enumerate(citations, start=1):
        source_names = source_names_from_citation(citation)
        rows.append({
            "#": citation_number,
            "source": ", ".join(source_names),
            "headline": str(citation.get("headline") or "").strip(),
            "citation_id": str(citation.get("id") or "").strip(),
        })

    return pd.DataFrame(rows, columns=["#", "source", "headline", "citation_id"])


def count_items(value: Any) -> int:
    """Count list-like discard buckets from the V2 response."""
    return len(value) if isinstance(value, list) else 0


def render_v2_entity_result(entity_result: JsonDict, *, top_n: int | None = None) -> None:
    """Display one V2 entity result with runs, bullets, citations, and discard counts."""
    entity_id = entity_result.get("entity_id", "N/A")
    entity_name = entity_result.get("entity_name") or "Unknown"
    found = entity_result.get("found")
    total_runs = entity_result.get("total_runs", 0)
    total_bullets = entity_result.get("total_bullets", 0)

    display(Markdown(
        f"## {entity_name}\n"
        f"**RP_ENTITY_ID:** `{entity_id}`  |  **Found:** {found}  |  "
        f"**Runs:** {total_runs}  |  **Bullets:** {total_bullets}"
    ))

    runs = entity_result.get("runs", []) or []
    if not runs:
        display(Markdown("_No runs found for this entity._"))
        return

    for run_index, run in enumerate(runs, start=1):
        bullets = run.get("bullets", []) or []
        display(Markdown(
            f"### Run {run_index}: `{run.get('run_id', 'N/A')}`\n"
            f"**Window:** {run.get('report_window_start', 'N/A')} to {run.get('report_window_end', 'N/A')}  |  "
            f"**Created:** {run.get('run_created_at', 'N/A')}  |  "
            f"**Saved:** {run.get('bullets_saved', len(bullets))}  |  "
            f"**Discarded:** {run.get('bullets_discarded', 0)}"
        ))

        discard_summary = (
            f"**Discarded by relevance:** {count_items(run.get('discarded_by_relevance'))}  |  "
            f"**Discarded by grounding:** {count_items(run.get('discarded_by_grounding'))}  |  "
            f"**Discarded by novelty:** {count_items(run.get('discarded_by_novelty'))}"
        )
        display(Markdown(discard_summary))

        if not bullets:
            display(Markdown("_No bullet points found for this run._"))
            continue

        limit = top_n if top_n is not None else len(bullets)
        table_rows: list[JsonDict] = []

        for bullet_number, bullet in enumerate(bullets[:limit], start=1):
            text = str(bullet.get("text") or "").strip()
            citations = bullet.get("citations", []) or []
            citation_df = citations_table(citations)
            decision_line = (
                f"embedding_decision={bullet.get('embedding_decision', '')}, "
                f"search_action={bullet.get('search_action', '')}, "
                f"not_fully_novel={bullet.get('not_fully_novel', '')}"
            )

            display(Markdown(f"{bullet_number}. {text}\n\n**Decisions:** `{decision_line}`"))
            display(Markdown("**Citations:**"))
            if citation_df.empty:
                display(Markdown("_No citations found for this bullet._"))
            else:
                display(citation_df)

            table_rows.append({
                "trace_id": bullet.get("trace_id", ""),
                "bullet": text,
                "citation_count": len(citations),
                "citation_ids": "; ".join(str(citation.get("id") or "") for citation in citations),
                "embedding_decision": bullet.get("embedding_decision", ""),
                "search_action": bullet.get("search_action", ""),
                "not_fully_novel": bullet.get("not_fully_novel", ""),
            })

        display(Markdown("**Raw table (for copy/export):**"))
        display(pd.DataFrame(table_rows))


for preview_result in first5_results:
    render_v2_entity_result(preview_result)

## Costco Wholesale Corp.
**RP_ENTITY_ID:** `B8EF97`  |  **Found:** True  |  **Runs:** 1  |  **Bullets:** 5

### Run 1: `3e5d177b-931c-481e-88b2-f8887cf9f491`
**Window:** 2026-02-01T00:00:00 to 2026-03-30T23:59:59  |  **Created:** 2026-04-25T21:11:32.236752  |  **Saved:** 5  |  **Discarded:** 19

**Discarded by relevance:** 3  |  **Discarded by grounding:** 3  |  **Discarded by novelty:** 13

1. Costco Wholesale Corp. reported fiscal Q2 2026 earnings per share of $4.58, up 13.9% from $4.02 a year earlier, beating analyst consensus estimates.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Costco Wholesale Q2 EPS $4.58 Beats $4.57 Esti...,CQS:B896293465F647C1D49FADE6E563860B-1
1,2,,Costco Wholesale Corporation - Costco Wholesal...,CQS:A15F37BE95D40607275F7A6189118FDD-3
2,3,,"Costco Wholesale Fiscal Q2 Earnings, Revenue Rise",CQS:6838F43DD9F164B9C0B4EE1D54DCDEB9-1
3,4,,Costco Wholesale Corp. Q2 Reported EPS USD 4.5...,CQS:B8D4A89E7BE56C19835F67CEE0FD0BD2-1

2. Costco Wholesale Corp. posted Q2 2026 net profit of $2.03 billion, exceeding consensus estimates and rising from $1.79 billion in the prior year period.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Costco Wholesale Corp. Reports Q2 Net Profit R...,CQS:59E907E6750460A40A88EF94875D6199-1
1,2,,Costco Wholesale Corp. Q2 Net Profit Reported ...,CQS:19C47E8EA5C084B1FCA378D4FC81BFC1-1
2,3,,Costco Wholesale Corp. Q2 Net Profit USD 2.04B...,CQS:DAB4B2D976847B4910F2D8FEBB65D600-1
3,4,,GLOBAL BRIEFING: US action to cut pressure on ...,CQS:1BF1CF1FB13B910F573E8FF9AB6F1A94-19
4,5,,"SA BRIEFING: Top 40 futures up, but risk-off s...",CQS:EB7D7EF2DEEC919151255D4D98ADB744-17

3. Costco Wholesale Corp., which told analysts that the timing of any tariff refunds was unclear, has disclosed that any refunds would be used to lower prices and enhance value for customers rather than to directly reimburse those who paid higher prices during the tariff period.

**Decisions:** `embedding_decision=keep, search_action=rewrite, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Costco Faces Class Action Over Tariff Refunds ...,CQS:0574BEC5102B920154320AF4EF9C6F85-2
1,2,,New lawsuit says Costco raised its prices in r...,CQS:50FC67C56C32EF75335785685A2FA5E0-2
2,3,,Costco Quarterly Results Top Street Views; Say...,CQS:233334664A36AE1CD08C2E2CF3875236-5
3,4,,"Costco sued over claims it raised prices, then...",CQS:1B77AB121FD9F8DB147F6A1CA60383A2-2
4,5,,Costco Considers Using Potential Tariff Refund...,CQS:F14CE3745926A8F1203D5A36731D8490-1

4. Costco Wholesale Corp. is leveraging its Kirkland private label to enter the energy drink market, directly competing with established brands like Celsius and Monster Beverage, with early strong consumer interest reported for the new Kirkland-branded energy drink.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Costco Tests Private-Label Entry in Energy Dri...,CQS:0F7720D811DC1336ACF5AE903868CD2B-1

5. Costco Wholesale Corp. continues to monitor the impact of Middle East instability on its supply chain, particularly regarding fuel costs and shipping schedules, though no disruptions have been reported as of the latest update.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,EXTRA: Costco details warehouse growth plans a...,CQS:B977CFD2A5F96001A2C4C329C47560A2-14
1,2,,EXTRA: Costco details warehouse growth plans a...,CQS:B977CFD2A5F96001A2C4C329C47560A2-15

**Raw table (for copy/export):**

,trace_id,bullet,citation_count,citation_ids,embedding_decision,search_action,not_fully_novel
0,00f1efa9-7cd9-4b14-9fda-866ecf94b09d,Costco Wholesale Corp. reported fiscal Q2 2026...,4,CQS:B896293465F647C1D49FADE6E563860B-1; CQS:A1...,keep,keep,False
1,b54e4393-e03c-4426-a399-cd46f3370ccf,Costco Wholesale Corp. posted Q2 2026 net prof...,5,CQS:59E907E6750460A40A88EF94875D6199-1; CQS:19...,keep,keep,False
2,f8c76606-d04f-43bc-8963-64629d706247,"Costco Wholesale Corp., which told analysts th...",5,CQS:0574BEC5102B920154320AF4EF9C6F85-2; CQS:50...,keep,rewrite,False
3,c12033d0-b57b-40d1-8777-24fdcfc595e1,Costco Wholesale Corp. is leveraging its Kirkl...,1,CQS:0F7720D811DC1336ACF5AE903868CD2B-1,keep,keep,False
4,74056eaa-bbb5-41a3-bab6-92b77d7a3863,Costco Wholesale Corp. continues to monitor th...,2,CQS:B977CFD2A5F96001A2C4C329C47560A2-14; CQS:B...,keep,keep,False

## Amphenol Corp.
**RP_ENTITY_ID:** `BB07E4`  |  **Found:** True  |  **Runs:** 1  |  **Bullets:** 3

### Run 1: `b582e108-6ee6-4e16-b771-314b3c34685c`
**Window:** 2026-02-01T00:00:00 to 2026-03-30T23:59:59  |  **Created:** 2026-04-25T21:10:59.953560  |  **Saved:** 3  |  **Discarded:** 7

**Discarded by relevance:** 1  |  **Discarded by grounding:** 1  |  **Discarded by novelty:** 5

1. Amphenol Corporation's Board of Directors approved a first quarter 2026 dividend of $0.25 per share, payable on April 14, 2026 to shareholders of record as of March 23, 2026.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Amphenol Announces First Quarter 2026 Dividend,CQS:C1DBA628A2FFCB09F677A784C7BAD7F6-1
1,2,,Amphenol Announces First Quarter 2026 Dividend,CQS:CB751163A8EA168E05DD8AF2762D0E36-1
2,3,,Reminder - Amphenol (APH) Goes Ex-Dividend Soon,CQS:E559A6D34780343E23CAF421BB50C48B-1

2. Amphenol Corporation introduced the Fiber Systems VITA 87 high-density circular MT connectors, supporting up to 192 fibers in a compact size-15 shell, targeting mission-critical military and aerospace applications with both physical contact and expanded beam MT ferrule configurations.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Interstate Connecting Components (ICC) Announc...,CQS:E8D341043BE47E274D19EE7B8A423576-1
1,2,,Interstate Connecting Components (ICC) Announc...,CQS:E8D341043BE47E274D19EE7B8A423576-2

3. Amphenol Corporation's presence at DesignCon 2026 showcased its high-speed interconnect solutions directly to engineers and customers driving AI data infrastructure projects, reinforcing its positioning in the fast-growing AI-led datacom market.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Should Amphenol's Record-Beating Q4 and Higher...,CQS:1B0F63C6A71ABBA1CB81F01B9EE52534-5

**Raw table (for copy/export):**

,trace_id,bullet,citation_count,citation_ids,embedding_decision,search_action,not_fully_novel
0,259c4d10-de00-461f-8b08-da4ec85df3a6,Amphenol Corporation's Board of Directors appr...,3,CQS:C1DBA628A2FFCB09F677A784C7BAD7F6-1; CQS:CB...,keep,keep,False
1,735474de-2d5d-4d94-b56f-66eff29509e7,Amphenol Corporation introduced the Fiber Syst...,2,CQS:E8D341043BE47E274D19EE7B8A423576-1; CQS:E8...,keep,keep,False
2,93e2acec-6282-464b-82fa-b0b1e8f01ac3,Amphenol Corporation's presence at DesignCon 2...,1,CQS:1B0F63C6A71ABBA1CB81F01B9EE52534-5,keep,keep,False

## Moody's Corp.
**RP_ENTITY_ID:** `3461CF`  |  **Found:** True  |  **Runs:** 1  |  **Bullets:** 6

### Run 1: `15b68730-5e07-4498-869e-3c8d04852628`
**Window:** 2026-02-01T00:00:00 to 2026-03-30T23:59:59  |  **Created:** 2026-04-25T21:11:26.946631  |  **Saved:** 6  |  **Discarded:** 12

**Discarded by relevance:** 5  |  **Discarded by grounding:** 2  |  **Discarded by novelty:** 5

1. Moody's Corp. communicated that its 2026 operating expenses are projected to increase in the mid-single-digit percent range, remaining below the expected rate of revenue growth and reflecting operating leverage.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Moody's sees FY26 operating expenses up mid-si...,CQS:433931301B7F521C84C43A412EB4FF56-1

2. Moody's Corp. noted that the analytics segment sustained 9% revenue growth in 2025 and that management guidance indicates this organic growth momentum should continue, supported by proprietary data assets, privacy law protections, and high customer retention rates.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Research Alert: CFRA Upgrades Opinion On Share...,CQS:D7075412DA8424BDDECF185E45D3D92F-3

3. Moody's Corp. stated that the overall long-term outlook remains favorable for continued growth across both reportable segments, driven by trends such as the enablement of generative AI, the health of major economies, and expansion of integrated data and analytics solutions.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Moody's Corporation - 2025 Annual Report,CQS:E7388E43A21CFAD3A47D570DE98FD3EA-120
1,2,,Moody's Corporation - Fourth Quarter 2025 Fina...,CQS:FEC1FADD6A0D508FFCC66DA6C288619D-69

4. Moody's Corporation announced a strategic partnership with Quantexa to integrate Quantexa's graph technology with Moody's data, enabling financial institutions to access updated views of people, companies, and relationships through advanced contextual analytics embedded directly into customer workflows.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Quantexa Showcases How Decision Intelligence P...,CQS:7357C0386D5670B89ABCBFB7042B12D0-5

5. Moody's Corporation launched its network-agnostic Token Integration Engine, becoming the first credit rating agency to ingest analytical data and share credit insights on-chain, and began operating a node on the Canton Network to enable secure, compliant, and efficient dissemination of ratings across blockchain platforms.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Moody's Ratings Becomes First Credit Rating Ag...,CQS:C37ED8BE5C021A80EC43A2230D284C76-1
1,2,,Moody's Corporation - Moody's Ratings Becomes ...,CQS:2E50E57285CB1D7D904D98F7D772C06C-1

6. Moody's Corporation reported repurchasing 0.9 million shares during the fourth quarter of 2025 at an average cost of $485.55 per share, with $4.0 billion of share repurchase authority remaining as of December 31, 2025, and no expiration date set for this authorization.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Moody's Corporation - 4Q 2025 Earnings Press R...,CQS:F3CAFF08C3F9F2A75694112D3A5DEF76-16

**Raw table (for copy/export):**

,trace_id,bullet,citation_count,citation_ids,embedding_decision,search_action,not_fully_novel
0,369eb030-1b24-4b2b-ab69-2c291fc658b6,Moody's Corp. communicated that its 2026 opera...,1,CQS:433931301B7F521C84C43A412EB4FF56-1,keep,keep,False
1,dba0d0af-18c8-461c-98c4-63becf46ac75,Moody's Corp. noted that the analytics segment...,1,CQS:D7075412DA8424BDDECF185E45D3D92F-3,keep,keep,False
2,f3b11a79-b761-4715-94d9-6cb02320f6c5,Moody's Corp. stated that the overall long-ter...,2,CQS:E7388E43A21CFAD3A47D570DE98FD3EA-120; CQS:...,keep,keep,False
3,e85ad8cc-4311-4eae-91af-b922eb5a5426,Moody's Corporation announced a strategic part...,1,CQS:7357C0386D5670B89ABCBFB7042B12D0-5,keep,keep,False
4,a37eba13-1de7-4615-aeba-b90556cdfbab,Moody's Corporation launched its network-agnos...,2,CQS:C37ED8BE5C021A80EC43A2230D284C76-1; CQS:2E...,keep,keep,False
5,2f6c336f-3b85-4f7d-9449-87b55b28d323,Moody's Corporation reported repurchasing 0.9 ...,1,CQS:F3CAFF08C3F9F2A75694112D3A5DEF76-16,keep,keep,False

## Arista Networks Inc.
**RP_ENTITY_ID:** `3DC887`  |  **Found:** True  |  **Runs:** 1  |  **Bullets:** 6

### Run 1: `6050aef0-3f16-4a3d-b3e2-612b3f81882d`
**Window:** 2026-02-01T00:00:00 to 2026-03-30T23:59:59  |  **Created:** 2026-04-25T21:11:24.995213  |  **Saved:** 6  |  **Discarded:** 18

**Discarded by relevance:** 8  |  **Discarded by grounding:** 3  |  **Discarded by novelty:** 7

1. Arista Networks Inc. delivered fourth-quarter revenue of $2.49 billion, surpassing analyst expectations of $2.38 billion and marking a 29% year-over-year increase from $1.93 billion.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,"Advance Auto Parts, Arista Networks And 3 Stoc...",CQS:D8E2CC439E88A42280E924539E8F79A1-4
1,2,,"Update: Arista Networks Q4 Non-GAAP Earnings, ...",CQS:179C40B91F847ED943DE06EDDD714407-2
2,3,,Arista Networks Q4 Adj. EPS $0.82 Beats $0.76 ...,CQS:6A86740A5B65BF6749773CAC58A3477A-1
3,4,,"Coinbase, Apple, Applied Materials, Arista Net...",CQS:09D9E44D406EF7CD9916FD0EA9CBA0A7-7
4,5,,"Arista Networks reports Q4 EPS 82c, consensus 76c",CQS:434F1D6A0877EA38753DECC3496CA8DE-1
5,6,,"Arista Stock Surges After Q4 Beat, Q1 Sales Ou...",CQS:ED4E799D35A70B52AAA6F42D58C2AFE0-2
6,7,,"Arista Networks Q4 Non-GAAP Earnings, Revenue ...",CQS:2C2E0C2B3FAE52223DCA5EE06AD4AB86-2
7,8,,Research Alert: Arista Networks Revenue Surges...,CQS:0A8DFF577BB13F029B964507BCF0FEEF-2
8,9,,Arista Networks Stock Climbs After Strong Q4 R...,CQS:F69EEAAF3F6F1706632555B39C487CB5-3
9,10,,Arista Networks Analysts Raise Price Targets O...,CQS:55C34D4A5627E440ED495C88B1D267D0-2

2. Arista Networks Inc. surpassed $1 billion in quarterly net income for the first time in the fourth quarter of 2025.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Research Alert: Arista Networks Revenue Surges...,CQS:0A8DFF577BB13F029B964507BCF0FEEF-2
1,2,,"Arista Stock Surges After Q4 Beat, Q1 Sales Ou...",CQS:ED4E799D35A70B52AAA6F42D58C2AFE0-3

3. Arista Networks Inc. announced the formation of a multi-source agreement for the XPO high-density liquid cooled pluggable optics module, delivering 12.8 Tbps per module and achieving 204.8 Tbps per open compute rack unit, a fourfold improvement over previous 1600G-OSFP optics.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Arista Announces XPO High Density Liquid Coole...,CQS:4C4C19172363B6F99CCF963F1B16284A-1
1,2,,Arista Networks Inc. - Arista Announces XPO Hi...,CQS:4A2FB743CFA047CE57EB5E2F1B2C904C-1
2,3,,Arista Announces XPO High Density Liquid Coole...,CQS:4C4C19172363B6F99CCF963F1B16284A-2
3,4,,Arista Networks Inc. - Arista Announces XPO Hi...,CQS:4A2FB743CFA047CE57EB5E2F1B2C904C-2
4,5,,Arista Networks Announces XPO Multi-Source Agr...,CQS:A9E4F421B2BCA094CAF813DD4A8A5E3F-1
5,6,,Arista Announces XPO High Density Liquid Coole...,CQS:A0D71672A96BDAF867BD6E45132613FA-2

4. Arista Networks Inc. will debut the XPO module with live demonstrations at OFC 2026 in Los Angeles, showcasing the technology at booth 1571 and through partner exhibits.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Arista Announces XPO High Density Liquid Coole...,CQS:4C4C19172363B6F99CCF963F1B16284A-5
1,2,,Arista Networks Inc. - Arista Announces XPO Hi...,CQS:4A2FB743CFA047CE57EB5E2F1B2C904C-5

5. Arista Networks Inc. highlighted that the XPO module supports all major industry optics standards and features an integrated cold plate capable of cooling up to 400W per module, addressing the bandwidth and thermal demands of AI data centers.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Arista Announces XPO High Density Liquid Coole...,CQS:4C4C19172363B6F99CCF963F1B16284A-2
1,2,,Arista Networks Inc. - Arista Announces XPO Hi...,CQS:4A2FB743CFA047CE57EB5E2F1B2C904C-2
2,3,,Arista Announces XPO High Density Liquid Coole...,CQS:A0D71672A96BDAF867BD6E45132613FA-2

6. Arista Networks Inc. organized and led the formation of the XPO Multi-Source Agreement, bringing together industry partners such as Marvell Technology Inc., Lightmatter, and Foxconn Interconnect Technology Ltd. to define a new high-density, liquid-cooled optical transceiver standard for AI-scale data centers.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,Arista Announces XPO High Density Liquid Coole...,CQS:4C4C19172363B6F99CCF963F1B16284A-1
1,2,,Arista Networks Inc. - Arista Announces XPO Hi...,CQS:4A2FB743CFA047CE57EB5E2F1B2C904C-1
2,3,,Marvell Technology Inc. - Marvell Joins XPO MS...,CQS:BCF751F7847AA62AB83B9463EF76EF1E-2
3,4,,Lightmatter Joins XPO MSA as Founding Member t...,CQS:3ABEF1C30D167B71924134B8EEE2F453-1
4,5,,Arista's Liquid-Cooled AI Optics Push Might Ch...,CQS:DEB9F84427176078FBF885725F54700F-1
5,6,,Arista Announces XPO High Density Liquid Coole...,CQS:7EBE5B61D5B72BCD466A2B678C87FAB2-1
6,7,,Can Arista's Latest XPO Optical Modules for AI...,CQS:A0DBC0FE8FBD5E4FB1BDE35783BC6AE3-1
7,8,,Arista XPO Optics Push AI Data Center Role And...,CQS:3A49FC4805C7B3218A54BD9CE76E1916-1
8,9,,Foxconn Interconnect Technology Ltd. - FIT Set...,CQS:C87A96B29B5DD9017D2FACF71915C210-2

**Raw table (for copy/export):**

,trace_id,bullet,citation_count,citation_ids,embedding_decision,search_action,not_fully_novel
0,eb0146d4-e50b-4aa1-aac3-160fd8d13e19,Arista Networks Inc. delivered fourth-quarter ...,10,CQS:D8E2CC439E88A42280E924539E8F79A1-4; CQS:17...,keep,keep,False
1,b1424208-838d-4bdb-a9cd-0a38b548d5e2,Arista Networks Inc. surpassed $1 billion in q...,2,CQS:0A8DFF577BB13F029B964507BCF0FEEF-2; CQS:ED...,keep,keep,False
2,ab11340a-b3b0-4f07-87c5-e016f6aab091,Arista Networks Inc. announced the formation o...,6,CQS:4C4C19172363B6F99CCF963F1B16284A-1; CQS:4A...,keep,keep,False
3,6b446ebd-eef7-4962-860e-0cda87566249,Arista Networks Inc. will debut the XPO module...,2,CQS:4C4C19172363B6F99CCF963F1B16284A-5; CQS:4A...,keep,keep,False
4,b68ed226-2969-48a8-8e0f-a74b67c28402,Arista Networks Inc. highlighted that the XPO ...,3,CQS:4C4C19172363B6F99CCF963F1B16284A-2; CQS:4A...,keep,keep,False
5,35257140-2e62-4b01-a575-e78b27155b79,Arista Networks Inc. organized and led the for...,9,CQS:4C4C19172363B6F99CCF963F1B16284A-1; CQS:4A...,keep,keep,False

## U.S. Bancorp Co.
**RP_ENTITY_ID:** `6166D1`  |  **Found:** True  |  **Runs:** 1  |  **Bullets:** 6

### Run 1: `11b28eef-42f4-446e-8cb2-538a10916659`
**Window:** 2026-02-01T00:00:00 to 2026-03-30T23:59:59  |  **Created:** 2026-04-25T21:11:06.270821  |  **Saved:** 6  |  **Discarded:** 5

**Discarded by relevance:** 2  |  **Discarded by grounding:** 0  |  **Discarded by novelty:** 3

1. U.S. Bancorp Co. announced that Toby Clements will become senior executive vice president and chief operations officer effective April 13, succeeding Souheil Badran who is retiring.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,U.S. Bancorp Announces Leadership Changes in I...,CQS:C276C0AAD052B7E8E70AEFA7A3763667-1
1,2,,U.S. Bancorp appoints Toby Clements as COO,CQS:DA54557ED0DDCDDA26B99D67A4381D1A-1
2,3,,U.S. Bancorp Names Toby Clements COO,CQS:D5572358BC35AF70034E399788F8EE63-1
3,4,,U.S. Bancorp Appoints Toby Clements Operations...,CQS:6C9D5D2DB5CD8582F576CE1201C19FFC-1
4,5,,U.S. Bank names next COO,CQS:18165A0B596340FD81F4D42E04BC5715-1
5,6,,Truist Keeps Buy on U.S. Bancorp (USB) Despite...,CQS:5310D72CDD677B97675C3AE340F80C1D-1

2. U.S. Bancorp Co. appointed Alan Flanagan as head of Global Investment Services, placing him in charge of global fund services and corporate trust operations.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,U.S. Bancorp - Alan Flanagan joins U.S. Bank a...,CQS:153021EE2799DC167732FD18DB58D910-1
1,2,,U.S. Bancorp - Alan Flanagan joins U.S. Bank a...,CQS:153021EE2799DC167732FD18DB58D910-3
2,3,,U.S. Bancorp - Alan Flanagan joins U.S. Bank a...,CQS:153021EE2799DC167732FD18DB58D910-5
3,4,,U.S. Bancorp Taps Alan Flanagan To Shape Globa...,CQS:EEF517A7788B319021761DE590DEBA13-1
4,5,,U.S. Bancorp Taps Alan Flanagan To Shape Globa...,CQS:4FC356F7C3C8AC37A5647E7BB19EC8F4-1
5,6,,U.S. Bancorp Taps Alan Flanagan To Shape Globa...,CQS:EEF517A7788B319021761DE590DEBA13-2
6,7,,U.S. Bancorp Taps Alan Flanagan To Shape Globa...,CQS:4FC356F7C3C8AC37A5647E7BB19EC8F4-2
7,8,,U.S. Bancorp Taps Alan Flanagan To Shape Globa...,CQS:EEF517A7788B319021761DE590DEBA13-5

3. U.S. Bancorp Co. named Ryan K. Nelson as President of Emerging Affluent Wealth Management to lead strategy and teams focused on beginning investors.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,U.S. Bancorp - U.S. Bancorp Advisors Launches ...,CQS:1BEAE60F29A6C3070FC7602F017AF061-3
1,2,,U.S. Bancorp - U.S. Bancorp Advisors Launches ...,CQS:1BEAE60F29A6C3070FC7602F017AF061-4

4. U.S. Bancorp Co. introduced new six- and seven-year loan options on its Avvance platform for larger home improvement projects, further enhancing its embedded lending capabilities.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,How U.S. Bank's Avvance Expansion At U.S. Banc...,CQS:4ECE55827431EB356403E91864A1228D-1

5. U.S. Bancorp Co. launched a suite of wealth management offerings targeting new and emerging investors, including a team-based advisory service for clients with at least $25,000, an enhanced self-directed brokerage platform with no minimum investment, and a next-generation investing platform that integrates banking and investing in a single app.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,U.S. Bancorp - U.S. Bancorp Advisors Launches ...,CQS:1BEAE60F29A6C3070FC7602F017AF061-1
1,2,,U.S. Bancorp - U.S. Bancorp Advisors Launches ...,CQS:1BEAE60F29A6C3070FC7602F017AF061-2
2,3,,U.S. Bancorp - U.S. Bancorp Advisors Launches ...,CQS:1BEAE60F29A6C3070FC7602F017AF061-5
3,4,,U.S. Bancorp - U.S. Bancorp Advisors Launches ...,CQS:1BEAE60F29A6C3070FC7602F017AF061-6
4,5,,U.S. Bancorp - U.S. Bancorp Advisors Launches ...,CQS:1BEAE60F29A6C3070FC7602F017AF061-7
5,6,,U.S. Bancorp Advisors Launches Suite of Offeri...,CQS:AC9DD942602F7504819C95A9A04ACBAC-1

6. U.S. Bancorp Co. rolled out a connected wealth model for emerging affluent investors, combining hybrid human advice, self-directed investing, and integrated banking data to simplify the investing experience and provide flexible engagement options.

**Decisions:** `embedding_decision=keep, search_action=keep, not_fully_novel=False`

**Citations:**

,#,source,headline,citation_id
0,1,,US Bancorp Advisors targets emerging affluent ...,CQS:B454294FAE97EFC8256000DC21D4918D-1
1,2,,US Bancorp Advisors targets emerging affluent ...,CQS:B454294FAE97EFC8256000DC21D4918D-2
2,3,,US Bancorp Advisors targets emerging affluent ...,CQS:B454294FAE97EFC8256000DC21D4918D-3

**Raw table (for copy/export):**

,trace_id,bullet,citation_count,citation_ids,embedding_decision,search_action,not_fully_novel
0,c9acf465-33e2-4522-b86e-3331845fc6fe,U.S. Bancorp Co. announced that Toby Clements ...,6,CQS:C276C0AAD052B7E8E70AEFA7A3763667-1; CQS:DA...,keep,keep,False
1,58fa47df-e32b-444d-b54e-5a90cdc7f070,U.S. Bancorp Co. appointed Alan Flanagan as he...,8,CQS:153021EE2799DC167732FD18DB58D910-1; CQS:15...,keep,keep,False
2,b9c7b49d-8859-47d4-b031-d87ece464e8b,U.S. Bancorp Co. named Ryan K. Nelson as Presi...,2,CQS:1BEAE60F29A6C3070FC7602F017AF061-3; CQS:1B...,keep,keep,False
3,e8b6bf1a-f60e-4e22-ba0e-a3aa39eff7bf,U.S. Bancorp Co. introduced new six- and seven...,1,CQS:4ECE55827431EB356403E91864A1228D-1,keep,keep,False
4,3b58a896-2318-44d6-948a-366d6cafb779,U.S. Bancorp Co. launched a suite of wealth ma...,6,CQS:1BEAE60F29A6C3070FC7602F017AF061-1; CQS:1B...,keep,keep,False
5,1cc84fd7-2785-4354-ad9f-e49dfbc28fb9,U.S. Bancorp Co. rolled out a connected wealth...,3,CQS:B454294FAE97EFC8256000DC21D4918D-1; CQS:B4...,keep,keep,False

## Step 8: Retrieve All Bullets and Export to Excel

Fetch saved bullets for all entities in the same `BATCH_SIZE` chunks, persist the raw combined V2 response, flatten runs/bullets/citations, and export the results to Excel.

In [20]:
def source_names_from_citation_for_export(citation: JsonDict) -> list[str]:
    """Extract citation source names from V2 source_references metadata."""
    source_references = citation.get("source_references") or []
    source_names: list[str] = []

    if isinstance(source_references, list):
        for source_reference in source_references:
            if not isinstance(source_reference, dict):
                continue
            source_name = str(source_reference.get("source_name") or "").strip()
            if source_name and source_name not in source_names:
                source_names.append(source_name)

    fallback_source_name = str(citation.get("source_name") or "").strip()
    if fallback_source_name and fallback_source_name not in source_names:
        source_names.append(fallback_source_name)

    return source_names


def citation_fields(citations: list[JsonDict]) -> JsonDict:
    """Flatten citation objects into semicolon-delimited Excel fields."""
    return {
        "citation_ids": "; ".join(str(citation.get("id") or "") for citation in citations),
        "citation_headlines": "; ".join(str(citation.get("headline") or "") for citation in citations),
        "citation_sources": "; ".join(
            ", ".join(source_names_from_citation_for_export(citation)) for citation in citations
        ),
        "citation_texts": "\n---\n".join(str(citation.get("text") or "") for citation in citations),
    }


def entity_run_base_row(entity_result: JsonDict, run: JsonDict | None = None) -> JsonDict:
    """Build common export columns for an entity/run pair."""
    run_payload = run or {}
    return {
        "rp_entity_id": entity_result.get("entity_id", ""),
        "entity_name": entity_result.get("entity_name", ""),
        "found": entity_result.get("found", ""),
        "total_runs": entity_result.get("total_runs", 0),
        "total_bullets": entity_result.get("total_bullets", 0),
        "run_id": run_payload.get("run_id", ""),
        "report_window_start": run_payload.get("report_window_start", ""),
        "report_window_end": run_payload.get("report_window_end", ""),
        "run_created_at": run_payload.get("run_created_at", ""),
        "run_bullet_count": run_payload.get("bullet_count", 0),
        "bullets_saved": run_payload.get("bullets_saved", 0),
        "bullets_discarded": run_payload.get("bullets_discarded", 0),
        "discarded_by_relevance_count": count_items(run_payload.get("discarded_by_relevance")),
        "discarded_by_grounding_count": count_items(run_payload.get("discarded_by_grounding")),
        "discarded_by_novelty_count": count_items(run_payload.get("discarded_by_novelty")),
    }


def flatten_v2_results(results: list[JsonDict]) -> pd.DataFrame:
    """Flatten V2 bullet results into one Excel-friendly row per bullet."""
    rows: list[JsonDict] = []

    for entity_result in results:
        runs = entity_result.get("runs", []) or []
        if not runs:
            rows.append({
                **entity_run_base_row(entity_result),
                "bullet_number": "",
                "trace_id": "",
                "bullet_text": "",
                "embedding_decision": "",
                "search_action": "",
                "not_fully_novel": "",
                "citation_count": 0,
                **citation_fields([]),
            })
            continue

        for run in runs:
            bullets = run.get("bullets", []) or []
            if not bullets:
                rows.append({
                    **entity_run_base_row(entity_result, run),
                    "bullet_number": "",
                    "trace_id": "",
                    "bullet_text": "",
                    "embedding_decision": "",
                    "search_action": "",
                    "not_fully_novel": "",
                    "citation_count": 0,
                    **citation_fields([]),
                })
                continue

            for bullet_number, bullet in enumerate(bullets, start=1):
                citations = bullet.get("citations", []) or []
                rows.append({
                    **entity_run_base_row(entity_result, run),
                    "bullet_number": bullet_number,
                    "trace_id": bullet.get("trace_id", ""),
                    "bullet_text": str(bullet.get("text") or "").strip(),
                    "embedding_decision": bullet.get("embedding_decision", ""),
                    "search_action": bullet.get("search_action", ""),
                    "not_fully_novel": bullet.get("not_fully_novel", ""),
                    "citation_count": len(citations),
                    **citation_fields(citations),
                })

    return pd.DataFrame(rows)


all_bullets_results: list[JsonDict] = []
all_bullets_responses: list[JsonDict] = []

for batch_number, batch in enumerate(chunk_entities(companies, BATCH_SIZE), start=1):
    batch_start = (batch_number - 1) * BATCH_SIZE + 1
    batch_end = batch_start + len(batch) - 1
    print(f"Retrieving bullets for entities {batch_start}-{batch_end}...")

    try:
        bullets_response = fetch_bullets_for_entities(batch)
    except requests.RequestException as exc:
        print(f"Bullet retrieval failed for entities {batch_start}-{batch_end}: {exc}")
        traceback.print_exc()
        all_bullets_responses.append({
            "batch_number": batch_number,
            "batch_start": batch_start,
            "batch_end": batch_end,
            "entity_ids": batch,
            "status": "failed",
            "error": str(exc),
        })
        continue

    batch_results = bullets_response.get("results", []) or []
    all_bullets_results.extend(batch_results)
    all_bullets_responses.append({
        "batch_number": batch_number,
        "batch_start": batch_start,
        "batch_end": batch_end,
        "entity_ids": batch,
        "status": "completed",
        "total_entities": bullets_response.get("total_entities", len(batch_results)),
        "total_bullets": bullets_response.get("total_bullets", 0),
        "response": bullets_response,
    })
    print(f"Retrieved {len(batch_results)} entities and {bullets_response.get('total_bullets', 0)} bullets.")

all_bullets_payload: JsonDict = {
    "retrieved_at_local": datetime.now().isoformat(),
    "batch_size": BATCH_SIZE,
    "total_entities": len(all_bullets_results),
    "total_bullets": sum(int(result.get("total_bullets") or 0) for result in all_bullets_results),
    "results": all_bullets_results,
    "batch_responses": all_bullets_responses,
}

save_json(BRIEF_V2_ALL_BULLETS_FILE, all_bullets_payload)

df_out = flatten_v2_results(all_bullets_results)

with pd.ExcelWriter(OUT_XLSX, engine="xlsxwriter") as writer:
    df_out.to_excel(writer, index=False, sheet_name="Briefs V2")
    worksheet = writer.sheets["Briefs V2"]
    worksheet.freeze_panes(1, 0)
    worksheet.autofilter(0, 0, max(len(df_out), 1), max(len(df_out.columns) - 1, 0))

    for column_index, column_name in enumerate(df_out.columns):
        max_width = max(len(str(column_name)), 12)
        if not df_out.empty:
            sample_width = df_out[column_name].astype(str).str.slice(0, 80).map(len).max()
            max_width = max(max_width, int(sample_width))
        worksheet.set_column(column_index, column_index, min(max_width + 2, 80))

print(f"Saved raw V2 bullet payload to {BRIEF_V2_ALL_BULLETS_FILE}")
print(f"Written {len(df_out)} rows to {OUT_XLSX}")
display(df_out.head(20))

Retrieving bullets for entities 1-50...
Retrieved 50 entities and 301 bullets.
Retrieving bullets for entities 51-100...
Retrieved 50 entities and 290 bullets.
Retrieving bullets for entities 101-107...
Retrieved 7 entities and 40 bullets.
Saved raw V2 bullet payload to output/brief_v2_all_bullets.json
Written 632 rows to output/portfolio_briefs_generation_v2.xlsx

,rp_entity_id,entity_name,found,total_runs,total_bullets,run_id,report_window_start,report_window_end,run_created_at,run_bullet_count,...,trace_id,bullet_text,embedding_decision,search_action,not_fully_novel,citation_count,citation_ids,citation_headlines,citation_sources,citation_texts
0,B8EF97,Costco Wholesale Corp.,True,1,5,3e5d177b-931c-481e-88b2-f8887cf9f491,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:32.236752,5,...,00f1efa9-7cd9-4b14-9fda-866ecf94b09d,Costco Wholesale Corp. reported fiscal Q2 2026...,keep,keep,False,4,CQS:B896293465F647C1D49FADE6E563860B-1; CQS:A1...,Costco Wholesale Q2 EPS $4.58 Beats $4.57 Esti...,; ; ;,Costco Wholesale (NASDAQ:COST) reported quarte...
1,B8EF97,Costco Wholesale Corp.,True,1,5,3e5d177b-931c-481e-88b2-f8887cf9f491,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:32.236752,5,...,b54e4393-e03c-4426-a399-cd46f3370ccf,Costco Wholesale Corp. posted Q2 2026 net prof...,keep,keep,False,5,CQS:59E907E6750460A40A88EF94875D6199-1; CQS:19...,Costco Wholesale Corp. Reports Q2 Net Profit R...,; ; ; ;,Costco Wholesale Corp. Reports Q2 Net Profit R...
2,B8EF97,Costco Wholesale Corp.,True,1,5,3e5d177b-931c-481e-88b2-f8887cf9f491,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:32.236752,5,...,f8c76606-d04f-43bc-8963-64629d706247,"Costco Wholesale Corp., which told analysts th...",keep,rewrite,False,5,CQS:0574BEC5102B920154320AF4EF9C6F85-2; CQS:50...,Costco Faces Class Action Over Tariff Refunds ...,; ; ; ;,The complaint alleges the lawsuit aims to stop...
3,B8EF97,Costco Wholesale Corp.,True,1,5,3e5d177b-931c-481e-88b2-f8887cf9f491,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:32.236752,5,...,c12033d0-b57b-40d1-8777-24fdcfc595e1,Costco Wholesale Corp. is leveraging its Kirkl...,keep,keep,False,1,CQS:0F7720D811DC1336ACF5AE903868CD2B-1,Costco Tests Private-Label Entry in Energy Dri...,,This article first appeared on GuruFocus.\nCos...
4,B8EF97,Costco Wholesale Corp.,True,1,5,3e5d177b-931c-481e-88b2-f8887cf9f491,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:32.236752,5,...,74056eaa-bbb5-41a3-bab6-92b77d7a3863,Costco Wholesale Corp. continues to monitor th...,keep,keep,False,2,CQS:B977CFD2A5F96001A2C4C329C47560A2-14; CQS:B...,EXTRA: Costco details warehouse growth plans a...,;,"In the warehouses, Vachris said Costco is achi..."
5,BB07E4,Amphenol Corp.,True,1,3,b582e108-6ee6-4e16-b771-314b3c34685c,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:10:59.953560,3,...,259c4d10-de00-461f-8b08-da4ec85df3a6,Amphenol Corporation's Board of Directors appr...,keep,keep,False,3,CQS:C1DBA628A2FFCB09F677A784C7BAD7F6-1; CQS:CB...,Amphenol Announces First Quarter 2026 Dividend...,; ;,Amphenol Corporation (NYSE:APH) announced toda...
6,BB07E4,Amphenol Corp.,True,1,3,b582e108-6ee6-4e16-b771-314b3c34685c,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:10:59.953560,3,...,735474de-2d5d-4d94-b56f-66eff29509e7,Amphenol Corporation introduced the Fiber Syst...,keep,keep,False,2,CQS:E8D341043BE47E274D19EE7B8A423576-1; CQS:E8...,Interstate Connecting Components (ICC) Announc...,;,"LUMBERTON, N.J., March 19, 2026 (GLOBE NEWSWIR..."
7,BB07E4,Amphenol Corp.,True,1,3,b582e108-6ee6-4e16-b771-314b3c34685c,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:10:59.953560,3,...,93e2acec-6282-464b-82fa-b0b1e8f01ac3,Amphenol Corporation's presence at DesignCon 2...,keep,keep,False,1,CQS:1B0F63C6A71ABBA1CB81F01B9EE52534-5,Should Amphenol's Record-Beating Q4 and Higher...,,"In this context, Amphenol's presence at Design..."
8,3461CF,Moody's Corp.,True,1,6,15b68730-5e07-4498-869e-3c8d04852628,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:26.946631,6,...,369eb030-1b24-4b2b-ab69-2c291fc658b6,Moody's Corp. communicated that its 2026 opera...,keep,keep,False,1,CQS:433931301B7F521C84C43A412EB4FF56-1,Moody's sees FY26 operating expenses up mid-si...,,"The company said, ""Operating expenses projecte..."
9,3461CF,Moody's Corp.,True,1,6,15b68730-5e07-4498-869e-3c8d04852628,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:26.946631,6,...,dba0d0af-18c8-461c-98c4-63becf46ac75,Moody's Corp. noted that the analytics segment...,keep,keep,False,1,CQS:D7075412DA8424BDDECF185E45D3D92F-3,Research Alert: CFRA Upgrades Opinion On Share...,,The MA analytics segment sustained 9% revenue ...
10,3461CF,Moody's Corp.,True,1,6,15b68730-5e07-4498-869e-3c8d04852628,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:26.946631,6,...,f3b11a79-b761-4715-94d9-6cb02320f6c5,Moody's Corp. stated that the overall long-ter...,keep,keep,False,2,CQS:E7388E43A21CFAD3A47D570DE98FD3EA-120; CQS:...,Moody's Corporation - 2025 Annual Report; Mood...,;,PROSPECTS FOR GROWTH\nMoody's believes that th...
11,3461CF,Moody's Corp.,True,1,6,15b68730-5e07-4498-869e-3c8d04852628,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:26.946631,6,...,e85ad8cc-4311-4eae-91af-b922eb5a5426,Moody's Corporation announced a strategic part...,keep,keep,False,1,CQS:7357C0386D5670B89ABCBFB7042B12D0-5,Quantexa Showcases How Decision Intelligence P...,,Strategic Partnership with Moody's \n \nQuante...
12,3461CF,Moody's Corp.,True,1,6,15b68730-5e07-4498-869e-3c8d04852628,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:26.946631,6,...,a37eba13-1de7-4615-aeba-b90556cdfbab,Moody's Corporation launched its network-agnos...,keep,keep,False,2,CQS:C37ED8BE5C021A80EC43A2230D284C76-1; CQS:2E...,Moody's Ratings Becomes First Credit Rating Ag...,;,Moody's Corporation (NYSE:MCO) today announced...
13,3461CF,Moody's Corp.,True,1,6,15b68730-5e07-4498-869e-3c8d04852628,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:26.946631,6,...,2f6c336f-3b85-4f7d-9449-87b55b28d323,Moody's Corporation reported repurchasing 0.9 ...,keep,keep,False,1,CQS:F3CAFF08C3F9F2A75694112D3A5DEF76-16,Moody's Corporation - 4Q 2025 Earnings Press R...,,Dividends\n2024\n2025\n- Cash flow from operat...
14,3DC887,Arista Networks Inc.,True,1,6,6050aef0-3f16-4a3d-b3e2-612b3f81882d,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:24.995213,6,...,eb0146d4-e50b-4aa1-aac3-160fd8d13e19,Arista Networks Inc. delivered fourth-quarter ...,keep,keep,False,10,CQS:D8E2CC439E88A42280E924539E8F79A1-4; CQS:17...,"Advance Auto Parts, Arista Networks And 3 Stoc...",; ; ; ; ; ; ; ; ;,Arista Networks Inc. (NYSE:ANET) posted upbeat...
15,3DC887,Arista Networks Inc.,True,1,6,6050aef0-3f16-4a3d-b3e2-612b3f81882d,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:24.995213,6,...,b1424208-838d-4bdb-a9cd-0a38b548d5e2,Arista Networks Inc. surpassed $1 billion in q...,keep,keep,False,2,CQS:0A8DFF577BB13F029B964507BCF0FEEF-2; CQS:ED...,Research Alert: Arista Networks Revenue Surges...,;,Arista delivered strong Q4 2025 results with r...
16,3DC887,Arista Networks Inc.,True,1,6,6050aef0-3f16-4a3d-b3e2-612b3f81882d,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:24.995213,6,...,ab11340a-b3b0-4f07-87c5-e016f6aab091,Arista Networks Inc. announced the formation o...,keep,keep,False,6,CQS:4C4C19172363B6F99CCF963F1B16284A-1; CQS:4A...,Arista Announces XPO High Density Liquid Coole...,; ; ; ; ;,Multi-source Agreement for 64-channel XPO modu...
17,3DC887,Arista Networks Inc.,True,1,6,6050aef0-3f16-4a3d-b3e2-612b3f81882d,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:24.995213,6,...,6b446ebd-eef7-4962-860e-0cda87566249,Arista Networks Inc. will debut the XPO module...,keep,keep,False,2,CQS:4C4C19172363B6F99CCF963F1B16284A-5; CQS:4A...,Arista Announces XPO High Density Liquid Coole...,;,The XPO MSA will debut at OFC 2026 in Los Ange...
18,3DC887,Arista Networks Inc.,True,1,6,6050aef0-3f16-4a3d-b3e2-612b3f81882d,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:24.995213,6,...,b68ed226-2969-48a8-8e0f-a74b67c28402,Arista Networks Inc. highlighted that the XPO ...,keep,keep,False,3,CQS:4C4C19172363B6F99CCF963F1B16284A-2; CQS:4A...,Arista Announces XPO High Density Liquid Coole...,; ;,Record-Breaking Throughput: Delivers 12.8 Tbps...
19,3DC887,Arista Networks Inc.,True,1,6,6050aef0-3f16-4a3d-b3e2-612b3f81882d,2026-02-01T00:00:00,2026-03-30T23:59:59,2026-04-25T21:11:24.995213,6,...,35257140-2e62-4b01-a575-e78b27155b79,Arista Networks Inc. organized and led the for...,keep,keep,False,9,CQS:4C4C19172363B6F99CCF963F1B16284A-1; CQS:4A...,Arista Announces XPO High Density Liquid Coole...,; ; ; ; ; ; ; ;,Multi-source Agreement for 64-channel XPO modu...